{
  "hash": "ed016c397d3a25116c811fcdf23902f9",
  "result": {
    "markdown": "---\ntitle: \"Social Networks__Final Project\"\nauthor: \"Niharika Pola\"\ndescription: \"Social Networks__Final Project\"\ndate: \"05/01/2022\"\nformat: html\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n#loading required packages\nlibrary(readr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ ggplot2   3.4.2     ✔ tibble    3.2.1\n✔ lubridate 1.9.2     ✔ tidyr     1.3.0\n✔ purrr     1.0.1     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'psych'\n\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n:::\n\n```{.r .cell-code}\nlibrary(igraph)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'igraph'\n\nThe following objects are masked from 'package:lubridate':\n\n    %--%, union\n\nThe following objects are masked from 'package:purrr':\n\n    compose, simplify\n\nThe following object is masked from 'package:tidyr':\n\n    crossing\n\nThe following object is masked from 'package:tibble':\n\n    as_data_frame\n\nThe following objects are masked from 'package:dplyr':\n\n    as_data_frame, groups, union\n\nThe following objects are masked from 'package:stats':\n\n    decompose, spectrum\n\nThe following object is masked from 'package:base':\n\n    union\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#reading the raw data\ndata_2022 <- read.csv(\"DataFolder_NiharikaPola/kaggle_survey_2022_responses.csv\")\ndim(data_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 23998   296\n```\n:::\n:::\n\n\n## Social Network analysis of the Master's Degree Kagglers 2022\n\n### Introduction\n\nMaster's degrees have gained significant prominence worldwide, particularly in the field of AI and data science. According to recent statistics, the number of students pursuing master's degrees has been steadily increasing, with a global growth rate of around 6% per year. In the realm of AI and data science, master's programs have seen exponential growth, with a substantial rise in enrollment over the past decade. This surge is attributed to the rising demand for skilled professionals in the field and the recognition of the specialized knowledge and practical skills that a master's degree provides. The prominence of master's degrees in AI and data science is reflected in the industry, where employers actively seek graduates with this level of education to meet the growing need for experts in handling and extracting insights from vast amounts of data using advanced AI techniques.\n\nIn this project, I aim to analyze the network of Master's community by using 2022 Kaggle Machine Learning & Data Science Survey. I focused on socio-demographic distribution of the master's community along with few of the questions that are based on machine learning skills and methods of the community world-wide. This code book highlights the preparation of the data, socio-demographic analysis, network analysis and visualization, network statistics and hypothesis testing in the form of answers to the questions that are requested in the course.\n\n#### 1. About the Data\n\nThe original data set is from 2022 Kaggle Machine Learning & Data Science Survey. The truly comprehensive view of the state of data science and machine learning. The survey was live from 09/16/2022 to 10/16/2022, and after cleaning the data we finished with 23,997 responses!\n\nThe raw data consists of 23998 rows and 296 columns with various socio-demographic questions (Age, Gender, Country, Occupation, Salary etc) and rest are focused on understanding various machine learning, AI and data science skills, methods, platforms used by the kaggle community. All the inferences that are stated in this codebook can describe only Kaggle users and should not be extrapolated to the broader population of data analysts.\n\nAs mentioned above, my study aims to understand the socio-demographic distribution of the Master's community from this survey data and using network analysis to find out the machine learning skills distribution of this community using network analysis.\n\nThe following are the columns that are considered for analysis.\n\nQ2: What is your age (# years)?\n\nQ3: What is your gender?\n\nQ4: In which country do you currently reside?\n\nQ5: Are you currently a student? (high school, university, or graduate)\n\nQ8: What is the highest level of formal education that you have attained or plan to attain within the next 2 years?\n\nQ11: For how many years have you been writing code and/or programming?\n\nQ29: What is your current yearly compensation (approximate \\$USD)?\n\nQ23: Select the title most similar to your current role\n\nQ18: Which of the following ML algorithms do you use on a regular basis?\n\nQ17: Which of the following machine learning frameworks do you use on a regular basis?\n\nQ20: Which of the following natural language processing (NLP) methods do you use on a regular basis?\n\nQ37: Do you use any of the following managed machine learning products on a regular basis?\n\nEach of the columns 17, 18, 20, & 37 have more than one parts to it based on the number of options given in the survey respectively.\n\n##### Hypothesis/Research Questions:\n\n1.  Does countries with highest number of Master's degrees show strong ML skill related environment network?\n2.  Which job role is popular among the ML & Data Science Master's Community?\n3.  How is the distribution of gender in the Master's community?\n\n##### Data Preparation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create subsets of variables dedicated to machine learning skills/methods.\n\nalgo <- c(\"Q18_1\", \"Q18_2\",\t\"Q18_3\",\t\"Q18_4\",\t\"Q18_5\",\t\"Q18_6\",\t\"Q18_7\",\t\"Q18_8\",\t\"Q18_9\",\t\"Q18_10\")\nnlp <- c(\"Q20_1\", \"Q20_2\", \"Q20_3\", \"Q20_4\", \"Q20_5\", \"Q20_6\")\nml_frameworks <- c(\"Q17_1\", \"Q17_2\", \"Q17_3\", \"Q17_4\", \"Q17_5\", \"Q17_6\", \"Q17_7\", \"Q17_8\", \"Q17_9\", \"Q17_10\")\nml_products <- c(\"Q37_1\", \"Q37_2\", \"Q37_3\", \"Q37_4\", \"Q37_5\", \"Q37_6\", \"Q37_7\", \"Q37_8\", \"Q37_9\", \"Q37_10\")\n\n# Get a separate dataframe with skills-related questions and convert to binary\nskills_questions <- c(algo, nlp, ml_frameworks, ml_products)\ndf_skills <- data_2022[, skills_questions]\ndf_skills <- data.frame(df_skills)\n\n\n# Create final dataframe with socio-demographic parameters and skills\ndf_socdem <- data_2022[, c('Q2', 'Q3', 'Q4', 'Q5', 'Q8', 'Q11', 'Q29', 'Q23' )]\ndf_fin <- merge(df_socdem, df_skills, by = 0)\n\n# Change names of countries\ndf_fin$Q4 <- ifelse(df_fin$Q4 == \"Iran, Islamic Republic of...\", \"Iran\",\n                    ifelse(df_fin$Q4 == \"Republic of Korea\", \"South Korea\",\n                           ifelse(df_fin$Q4 == \"United Kingdom of Great Britain and Northern Ireland\", \"United Kingdom\",\n                                  ifelse(df_fin$Q4 == \"United States of America\", \"USA\", df_fin$Q4))))\n\n# Drop respondents who didn't indicate their country\ndf_fin <- df_fin[!is.na(df_fin$Q4), ]\n\n# Master's or not Master's\ndf_fin$Q8_ms <- ifelse(df_fin$Q8 == \"Master’s degree\", \"Master's\", \"not Master's\")\ndf_fin$Q8_ms <- as.factor(df_fin$Q8_ms)\n\n\n# Salary to ordinal\ndf_fin$Q29 <- factor(df_fin$Q29, ordered = TRUE, levels = c(\"$0-999\", \"1,000-1,999\", \"2,000-2,999\", \"3,000-3,999\", \"4,000-4,999\",\n                                                          \"5,000-7,499\", \"7,500-9,999\", \"10,000-14,999\", \"15,000-19,999\",\n                                                          \"20,000-24,999\", \"25,000-29,999\", \"30,000-39,999\", \"40,000-49,999\",\n                                                          \"50,000-59,999\", \"60,000-69,999\", \"70,000-79,999\", \"80,000-89,999\",\n                                                          \"90,000-99,999\", \"100,000-124,999\", \"125,000-149,999\", \"150,000-199,999\",\n                                                          \"200,000-249,999\", \"250,000-299,999\", \"300,000-500,000\", \"> $500,000\"))\n\n# Experience to ordinal\ndf_fin$Q11 <- factor(df_fin$Q11, ordered = TRUE, levels = c(\"< 1 years\", \"1-2 years\", \"3-5 years\", \"5-10 years\", \"10-20 years\", \"20+ years\"))\n\n# Age to ordinal\ndf_fin$Q2 <- factor(df_fin$Q2, ordered = TRUE, levels = c(\"18-21\", \"22-24\", \"25-29\", \"30-34\", \"35-39\", \"40-44\", \"45-49\", \"50-54\", \"55-59\", \"60-69\", \"70+\"))\n\n# Variable with Top 20 countries\ntop_countries <- names(sort(table(df_fin$Q4), decreasing = TRUE))[1:21]\ntop_countries <- top_countries[top_countries != \"Other\"]\ndf_fin$Q4_top <- ifelse(df_fin$Q4 %in% top_countries, df_fin$Q4, NA)\n\ndf_fin <- df_fin[-1, ]\n```\n:::\n\n\nEach of the ML based questions are categorized in to four columns and a dataframe called df_skills. The socio-demo graphic columns are grouped into df_socdem dataframe and these two are merged into the final data set df_fin.\n\nA filter is applied to the Q8 column of df_fin for Master's degree community.\n\nAs the Experience-Q11 & Age-Q2 have range values in their cells, they are converted to ordinal type.\n\nGoing further, the network graph is created between countries and skills distribution. Hence the Countries are the nodes and Skills are the edges.\n\n### 2. Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df_fin)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t23997 obs. of  47 variables:\n $ Row.names: 'AsIs' chr  \"10\" \"100\" \"1000\" \"10000\" ...\n $ Q2       : Ord.factor w/ 11 levels \"18-21\"<\"22-24\"<..: 11 2 4 2 4 6 3 9 7 2 ...\n $ Q3       : chr  \"Man\" \"Man\" \"Man\" \"Man\" ...\n $ Q4       : chr  \"Australia\" \"India\" \"China\" \"Taiwan\" ...\n $ Q5       : chr  \"No\" \"No\" \"No\" \"Yes\" ...\n $ Q8       : chr  \"Doctoral degree\" \"Master’s degree\" \"Doctoral degree\" \"Master’s degree\" ...\n $ Q11      : Ord.factor w/ 6 levels \"< 1 years\"<\"1-2 years\"<..: 6 4 5 NA 1 NA 3 1 NA NA ...\n $ Q29      : Ord.factor w/ 25 levels \"$0-999\"<\"1,000-1,999\"<..: 19 9 15 NA NA NA NA NA NA NA ...\n $ Q23      : chr  \"Research Scientist\" \"Software Engineer\" \"Software Engineer\" \"\" ...\n $ Q18_1    : chr  \"Linear or Logistic Regression\" \"Linear or Logistic Regression\" \"Linear or Logistic Regression\" \"Linear or Logistic Regression\" ...\n $ Q18_2    : chr  \"Decision Trees or Random Forests\" \"Decision Trees or Random Forests\" \"\" \"Decision Trees or Random Forests\" ...\n $ Q18_3    : chr  \"\" \"\" \"\" \"Gradient Boosting Machines (xgboost, lightgbm, etc)\" ...\n $ Q18_4    : chr  \"\" \"\" \"\" \"Bayesian Approaches\" ...\n $ Q18_5    : chr  \"\" \"\" \"\" \"\" ...\n $ Q18_6    : chr  \"\" \"Dense Neural Networks (MLPs, etc)\" \"Dense Neural Networks (MLPs, etc)\" \"\" ...\n $ Q18_7    : chr  \"\" \"Convolutional Neural Networks\" \"Convolutional Neural Networks\" \"\" ...\n $ Q18_8    : chr  \"\" \"\" \"Generative Adversarial Networks\" \"\" ...\n $ Q18_9    : chr  \"\" \"\" \"\" \"\" ...\n $ Q18_10   : chr  \"\" \"\" \"Transformer Networks (BERT, gpt-3, etc)\" \"\" ...\n $ Q20_1    : chr  \"\" \"\" \"Word embeddings/vectors (GLoVe, fastText, word2vec)\" \"\" ...\n $ Q20_2    : chr  \"nan\" \"nan\" \"Encoder-decoder models (seq2seq, vanilla transformers)\" \"nan\" ...\n $ Q20_3    : chr  \"\" \"\" \"\" \"\" ...\n $ Q20_4    : chr  \"\" \"\" \"Transformer language models (GPT-3, BERT, XLnet, etc)\" \"\" ...\n $ Q20_5    : chr  \"\" \"\" \"\" \"\" ...\n $ Q20_6    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_1    : chr  \"\" \"  Scikit-learn \" \"  Scikit-learn \" \"  Scikit-learn \" ...\n $ Q17_2    : chr  \"\" \"  TensorFlow \" \"  TensorFlow \" \"\" ...\n $ Q17_3    : chr  \" Keras \" \"\" \" Keras \" \"\" ...\n $ Q17_4    : chr  \"\" \"\" \" PyTorch \" \"\" ...\n $ Q17_5    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_6    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_7    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_8    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_9    : chr  \"\" \"\" \"\" \"\" ...\n $ Q17_10   : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_1    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_2    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_3    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_4    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_5    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_6    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_7    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_8    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_9    : chr  \"\" \"\" \"\" \"\" ...\n $ Q37_10   : chr  \"\" \"\" \"\" \"\" ...\n $ Q8_ms    : Factor w/ 2 levels \"Master's\",\"not Master's\": 2 1 2 1 2 1 1 1 2 2 ...\n $ Q4_top   : chr  NA \"India\" \"China\" \"Taiwan\" ...\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnet <- select(df_fin,\"Q4_top\", \"Q18_1\", \"Q18_2\",  \"Q18_3\",  \"Q18_4\", \"Q18_5\", \"Q18_6\", \"Q18_7\", \"Q18_8\", \"Q18_9\", \"Q18_10\", \"Q20_1\", \"Q20_2\", \"Q20_3\", \"Q20_4\", \"Q20_5\", \"Q17_1\", \"Q17_2\", \"Q17_3\", \"Q17_4\", \"Q17_5\", \"Q17_6\", \"Q17_7\", \"Q17_8\", \"Q17_9\", \"Q17_10\", \"Q37_1\")\n\n# Convert the data to an igraph object\ng <- graph.data.frame(net)\n\n# Number of Components\nnum_components <- components(g)$no\ncat(\"Number of Components:\", num_components, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of Components: 1 \n```\n:::\n\n```{.r .cell-code}\n# Proportion of Nodes in Giant Component and Proportion of Unconnected Nodes/Singletons\ngiant_component <- max(components(g)$csize)\nproportion_giant_component <- giant_component / vcount(g)\nproportion_singletons <- sum(components(g)$csize == 1) / vcount(g)\ncat(\"Proportion of Nodes in Giant Component:\", proportion_giant_component, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProportion of Nodes in Giant Component: 1 \n```\n:::\n\n```{.r .cell-code}\ncat(\"Proportion of Unconnected Nodes/Singletons:\", proportion_singletons, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nProportion of Unconnected Nodes/Singletons: 0 \n```\n:::\n\n```{.r .cell-code}\n# Check if the graph is fully connected\nif (num_components == 1) {\n  # Network Diameter\n  network_diameter <- diameter(g)\n  cat(\"Network Diameter:\", network_diameter, \"\\n\")\n\n  # Distribution of Network Geodesics\n  geodesics <- distances(g, mode = \"all\")\n  cat(\"Distribution of Network Geodesics:\\n\")\n  hist(geodesics, main = \"Distribution of Network Geodesics\", xlab = \"Geodesic Length\", ylab = \"Frequency\")\n} else {\n  cat(\"The graph is not fully connected.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNetwork Diameter: 1 \nDistribution of Network Geodesics:\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Graph Density\ngraph_density <- edge_density(g)\ncat(\"Graph Density:\", graph_density, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGraph Density: 47.4249 \n```\n:::\n\n```{.r .cell-code}\n# Average Node Degree\naverage_degree <- mean(degree(g))\ncat(\"Average Node Degree:\", average_degree, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAverage Node Degree: 2086.696 \n```\n:::\n\n```{.r .cell-code}\n# Degree Distribution\ndegree_dist <- degree_distribution(g)\ncat(\"Degree Distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDegree Distribution:\n```\n:::\n\n```{.r .cell-code}\nplot(degree_dist, main = \"Degree Distribution\", xlab = \"Degree\", ylab = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\n-   There is only one component in the network, indicating that all nodes are connected in a single connected structure.\n\n-   The entire network consists of a single giant component, meaning that all nodes are part of the largest connected component.\n\n-   There are no unconnected nodes or singletons in the network, implying that all nodes have at least one connection to other nodes.\n\n-   The network diameter is 1, suggesting that the maximum shortest path between any two nodes in the network is only one. This indicates a highly connected and compact network structure.\n\n-   The specific details of the distribution of network geodesics are not provided, so further interpretation regarding the network's path lengths and connectivity patterns cannot be determined.\n\n-   The graph density is given as 47.4249. Graph density measures the proportion of possible edges that are present in the network. A density of 1 would indicate a complete graph, while a density of 0 would represent a completely sparse or disconnected graph.\n\n-   The average node degree is reported as 2086.696. This indicates that, on average, each node in the network is connected to approximately 2086.696 other nodes. A higher average node degree suggests a denser and more interconnected network.\n\n-   The degree distribution is not provided, so the specific distribution shape (e.g., power-law, normal, etc.) and additional information about the connectivity patterns of individual nodes in the network cannot be determined.\n\nOverall, the provided descriptive statistics suggest a highly connected network with a single giant component, where all nodes are connected and there are no unconnected nodes or singletons. The network has a small diameter, indicating short path lengths between nodes. The graph density and average node degree values suggest a relatively dense and interconnected network structure.\n\n### General Socio-Demographic portrait of a Masters degree Kagglers\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create dataframe for visualization of Q8\ndf_ms_viz <- df_fin[df_fin$Q8_ms == \"Master's\", ]\ndf_ms_viz_country <- as.data.frame(table(df_ms_viz$Q4_top))\ndf_ms_viz_country <- df_ms_viz_country[order(-df_ms_viz_country$Freq), ]\ndf_ms_viz_country_grey <- df_ms_viz_country\ndf_ms_viz_country_grey$Freq <- c(rep(0, 4), df_ms_viz_country_grey$Freq[5:nrow(df_ms_viz_country_grey)])\n\n\n# Create dataframe for visualization of Q23\ndf_ms_viz_role <- as.data.frame(table(df_ms_viz$Q23))\ndf_ms_viz_role <- df_ms_viz_role[complete.cases(df_ms_viz_role), ]\ndf_ms_viz_role <- df_ms_viz_role[order(-df_ms_viz_role$Freq), ]\ndf_ms_viz_role_grey <- df_ms_viz_role\ndf_ms_viz_role_grey$Freq <- c(rep(0, 4), df_ms_viz_role_grey$Freq[5:nrow(df_ms_viz_role_grey)])\n\n# Create dataframe for visualization of Q3\ndf_ms_viz_gender <- as.data.frame(table(df_ms_viz$Q3))\ndf_ms_viz_gender <- df_ms_viz_gender[order(-df_ms_viz_gender$Freq), ]\ndf_ms_viz_gender_grey <- df_ms_viz_gender\ndf_ms_viz_gender_grey$Freq <- c(rep(0, 4), df_ms_viz_gender_grey$Freq[5:nrow(df_ms_viz_gender_grey)])\n\n# Create plots\npar(mfrow = c(1, 3), mar = c(5, 4, 2, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Country distribution for Q8\nplot_country <- ggplot(data = df_ms_viz_country, aes(x = Var1, y = Freq, fill = Var1)) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  geom_text(aes(label = Freq), vjust = -0, size = 3.5, color = \"black\") +\n  coord_flip() +\n  labs(title = \"Plot-1: Country distribution\", x = NULL, y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.text.x = element_text(angle = 1, hjust = 0.5, vjust = 0.5, size = 12),\n        axis.text.y = element_text(size = 10),\n        legend.position = \"none\")\nplot_country\n```\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nPlot-1 visualizes the number of Masters degree holders or students who are currently pursuing Master's in the top-20 countries of the survey data.\n\nIn absolute terms, India tangibly outperforms other countries by the amount Master's degree released. or going to be released. The second place is occupied by USA, followed by Brazil, Nigeria and Pakistan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Job title distribution for Q23\nplot_job_title <- ggplot(data = df_ms_viz_role, aes(x = Var1, y = Freq, fill = Var1)) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  geom_text(aes(label = Freq), vjust = -0, size = 3.5, color = \"black\") +\n  coord_flip() +\n  labs(title = \"Plot-2: Job title distribution\", x = NULL, y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5, size = 10),\n        axis.text.y = element_text(size = 8),\n        legend.position = \"none\")\nplot_job_title\n```\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nPlot-2 visualizes the current roles of the Master's degree kaggler's in the field of ML & Data Science.\n\nThe empty cells indicate either they are current students or they didn't answer this particular question.\n\nHowever, if you don't consider the empty cell, the most popular job role in the Master's degree field is the Data Scientist followed by Data Analyst.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Gender distribution for Q3\nplot_gender <- ggplot(data = df_ms_viz_gender, aes(x = Var1, y = Freq, fill = Var1)) +\n  geom_bar(stat = \"identity\", color = \"black\") +\n  geom_text(aes(label = Freq), vjust = -0, size = 3.5, color = \"black\") +\n  coord_flip() +\n  labs(title = \"Plot-3: Gender distribution\", x = NULL, y = \"Frequency\") +\n  theme_minimal() +\n  theme(plot.title = element_text(size = 16, face = \"bold\"),\n        axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5, size = 12),\n        axis.text.y = element_text(size = 10),\n        legend.position = \"none\")\n\nplot_gender\n```\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nPlot-3 above show that the number of males with Master's degree is roughly 3 times as high as women, meaning that even a highly academic environment retains this drastically pronounced gender-related disproportion.\n\n#### 3. Network Graph: How does the ML skill-related environment of Kaggle Master's degree community differ between nations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# Calculate the Jaccard similarity index for every pair of countries\nsimilarity_matrix <- matrix(nrow = length(top_countries), ncol = length(top_countries))\n\nfor (i in 1:length(top_countries)) {\n    for (j in 1:length(top_countries)) {\n        df_i <- df_fin[df_fin$Q4_top == top_countries[i], c(\"Q18_1\", \"Q18_2\",  \"Q18_3\",  \"Q18_4\", \"Q18_5\", \"Q18_6\", \"Q18_7\", \"Q18_8\", \"Q18_9\", \"Q18_10\", \"Q20_1\", \"Q20_2\", \"Q20_3\", \"Q20_4\", \"Q20_5\", \"Q17_1\", \"Q17_2\", \"Q17_3\", \"Q17_4\", \"Q17_5\", \"Q17_6\", \"Q17_7\", \"Q17_8\", \"Q17_9\", \"Q17_10\", \"Q37_1\")]\n        df_j <- df_fin[df_fin$Q4_top == top_countries[j], c(\"Q18_1\", \"Q18_2\",  \"Q18_3\",  \"Q18_4\", \"Q18_5\", \"Q18_6\", \"Q18_7\", \"Q18_8\", \"Q18_9\", \"Q18_10\", \"Q20_1\", \"Q20_2\", \"Q20_3\", \"Q20_4\", \"Q20_5\", \"Q17_1\", \"Q17_2\", \"Q17_3\", \"Q17_4\", \"Q17_5\", \"Q17_6\", \"Q17_7\", \"Q17_8\", \"Q17_9\", \"Q17_10\", \"Q37_1\")]\n similarity_matrix[i,j] <- length(intersect(df_i, df_j))/length(union(df_i, df_j))\n\n    }\n}\n\n# Create the graph from the adjacency matrix\ngraph <- graph.adjacency(similarity_matrix, mode = \"undirected\", weighted = TRUE, diag = FALSE)\nV(graph)$name <- top_countries\n\n# Remove edges with weight 0\ngraph <- delete_edges(graph, E(graph)[weight == 0])\n\n\n# Plot the graph\nplot(graph, vertex.size=10, vertex.label.cex=0.8, main = \"Network of Countries\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_NiharikaPola_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nAccording to the network graph here, the Machine Learning skill related environment doesn't differ much between the top-20 countries.\n\nHowever, considering India, USA, Brazil, Nigeria and Pakistan being the largest producers of Master's degree holders, one can assume that their skill range to be vast.\n\nBut, this can be derived from the graph that the countries, India, Brazil, United Kingdom, France, Egypt and Columbia are closely knitted together and also strongly connected with all other countries. This means that these countries share a strong ML skill related environment amongst the Master's Community.\n\nShockingly, USA is not in this list despite being the second highest in the Master's degree production.\n\nThis answers our first research question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the degree of each node (the number of edges incident to each node)\nnode_degrees <- degree(graph)\n\n# Calculate the average path length (the average shortest path between all pairs of nodes)\navg_path_length <- average.path.length(graph)\n\n# Calculate the diameter of the graph (the longest shortest path between any pair of nodes)\ndiameter_graph <- diameter(graph)\n\n# Calculate the graph's density (the proportion of potential edges that are actual edges)\ngraph_density <- edge_density(graph)\n\n# Calculate the graph's transitivity (the proportion of triangles to triplets in the graph)\ngraph_transitivity <- transitivity(graph, type=\"global\")\n\n# Calculate betweenness centrality for each node (a measure of centrality based on shortest paths)\nbetweenness_centrality <- betweenness(graph)\n\n# Print network statistics\nprint(paste(\"Average path length: \", avg_path_length))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Average path length:  0.5\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"Diameter of the graph: \", diameter_graph))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Diameter of the graph:  0.5\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"Graph density: \", graph_density))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Graph density:  1\"\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"Global transitivity: \", graph_transitivity))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Global transitivity:  1\"\n```\n:::\n\n```{.r .cell-code}\n# Convert centrality measures to data frames for easier viewing\nnode_degrees <- as.data.frame(node_degrees)\ncolnames(node_degrees) <- c(\"Node Degree\")\nprint(node_degrees)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Node Degree\nIndia                   19\nUSA                     19\nBrazil                  19\nNigeria                 19\nPakistan                19\nJapan                   19\nChina                   19\nEgypt                   19\nMexico                  19\nIndonesia               19\nTurkey                  19\nRussia                  19\nSouth Korea             19\nFrance                  19\nUnited Kingdom          19\nCanada                  19\nSpain                   19\nColombia                19\nBangladesh              19\nTaiwan                  19\n```\n:::\n\n```{.r .cell-code}\nbetweenness_centrality <- as.data.frame(betweenness_centrality)\ncolnames(betweenness_centrality) <- c(\"Betweenness Centrality\")\nprint(betweenness_centrality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Betweenness Centrality\nIndia                               0\nUSA                                 0\nBrazil                              0\nNigeria                             0\nPakistan                            0\nJapan                               0\nChina                               0\nEgypt                               0\nMexico                              0\nIndonesia                           0\nTurkey                              0\nRussia                              0\nSouth Korea                         0\nFrance                              0\nUnited Kingdom                      0\nCanada                              0\nSpain                               0\nColombia                            0\nBangladesh                          0\nTaiwan                              0\n```\n:::\n:::\n\n\n-   Average path length: 0.5\n\nThe average path length is a measure of how \"far\" nodes are from each other in a graph. In this case, the average path length of 0.5 indicates that, on average, it takes 0.5 steps to reach any other node in the graph. A lower average path length generally suggests a more connected or compact graph.\n\n-   Diameter of the graph: 0.5\n\nThe diameter of a graph is the longest shortest path between any pair of nodes. In this case, the diameter of 0.5 suggests that the longest shortest path in the graph is 0.5 units. A smaller diameter indicates that the graph is relatively small or well-connected.\n\n-   Graph density: 1\n\nGraph density is a measure of how many edges are present in the graph compared to the total possible number of edges. A density of 1 indicates that the graph is complete, meaning that every pair of nodes is connected by an edge. In a complete graph, the density is at its maximum.\n\n-   Global transitivity: 1\n\nGlobal transitivity, also known as the clustering coefficient, measures the degree to which nodes in a graph tend to cluster together. A value of 1 suggests that every node in the graph is fully connected to its neighbors, forming closed triangles. It indicates a high level of clustering or transitivity in the graph.\n\nIn summary, the provided graph has a relatively low average path length and diameter, indicating good connectivity. The graph is also complete with a density of 1, meaning that all possible edges are present. Furthermore, the graph exhibits a high level of clustering or transitivity with a global transitivity of 1.\n\n#### 4. Network Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# Function to calculate different measures and identify prominent nodes\nidentifyProminentNodes <- function(df, G) {\n  # Measure of popularity/status\n  # In-degree centrality\n  in_degree <- degree(G, mode = \"in\")\n  max_in_degree <- max(in_degree)\n  min_in_degree <- min(in_degree)\n  high_in_degree_nodes <- V(G)[in_degree == max_in_degree]\n  low_in_degree_nodes <- V(G)[in_degree == min_in_degree]\n  \n  # Out-degree centrality\n  out_degree <- degree(G, mode = \"out\")\n  max_out_degree <- max(out_degree)\n  min_out_degree <- min(out_degree)\n  high_out_degree_nodes <- V(G)[out_degree == max_out_degree]\n  low_out_degree_nodes <- V(G)[out_degree == min_out_degree]\n  \n  # Bonachich power\n  bonachich_power <- bonpow(G)\n  max_bonachich_power <- max(bonachich_power)\n  min_bonachich_power <- min(bonachich_power)\n  high_bonachich_power_nodes <- V(G)[bonachich_power == max_bonachich_power]\n  low_bonachich_power_nodes <- V(G)[bonachich_power == min_bonachich_power]\n  \n  # Eigenvector centrality\n  eigenvector_centrality <- eigen_centrality(G)$vector\n  max_eigenvector_centrality <- max(eigenvector_centrality)\n  min_eigenvector_centrality <- min(eigenvector_centrality)\n  high_eigenvector_centrality_nodes <- V(G)[eigenvector_centrality == max_eigenvector_centrality]\n  low_eigenvector_centrality_nodes <- V(G)[eigenvector_centrality == min_eigenvector_centrality]\n  \n  # Derived/reflected centrality\n  derived_centrality <- (in_degree + out_degree) / 2\n  max_derived_centrality <- max(derived_centrality)\n  min_derived_centrality <- min(derived_centrality)\n  high_derived_centrality_nodes <- V(G)[derived_centrality == max_derived_centrality]\n  low_derived_centrality_nodes <- V(G)[derived_centrality == min_derived_centrality]\n  \n  # Measure of role/power\n  # Constraint\n  constraint <- constraint(G)\n  max_constraint <- max(constraint)\n  min_constraint <- min(constraint)\n  high_constraint_nodes <- V(G)[constraint == max_constraint]\n  low_constraint_nodes <- V(G)[constraint == min_constraint]\n  \n  # Betweenness centrality\n  betweenness_centrality <- betweenness(G)\n  max_betweenness_centrality <- max(betweenness_centrality)\n  min_betweenness_centrality <- min(betweenness_centrality)\n  high_betweenness_centrality_nodes <- V(G)[betweenness_centrality == max_betweenness_centrality]\n  low_betweenness_centrality_nodes <- V(G)[betweenness_centrality == min_betweenness_centrality]\n  \n  # Edge betweenness (brokerage)\n  edge_betweenness <- edge_betweenness(G)\n  max_edge_betweenness <- max(edge_betweenness)\n  min_edge_betweenness <- min(edge_betweenness)\n  high_brokerage_nodes <- ends(G, E(G)[edge_betweenness == max_edge_betweenness])\n  low_brokerage_nodes <- ends(G, E(G)[edge_betweenness == min_edge_betweenness])\n  \n  # Create a list of results\n  results <- list(\n    in_degree = list(max = max_in_degree, min = min_in_degree, high_nodes = high_in_degree_nodes, low_nodes = low_in_degree_nodes),\n    out_degree = list(max = max_out_degree, min = min_out_degree, high_nodes = high_out_degree_nodes, low_nodes = low_out_degree_nodes),\n    bonachich_power = list(max = max_bonachich_power, min = min_bonachich_power, high_nodes = high_bonachich_power_nodes, low_nodes = low_bonachich_power_nodes),\n    eigenvector_centrality = list(max = max_eigenvector_centrality, min = min_eigenvector_centrality, high_nodes = high_eigenvector_centrality_nodes, low_nodes = low_eigenvector_centrality_nodes),\n    derived_centrality = list(max = max_derived_centrality, min = min_derived_centrality, high_nodes = high_derived_centrality_nodes, low_nodes = low_derived_centrality_nodes),\n    constraint = list(max = max_constraint, min = min_constraint, high_nodes = high_constraint_nodes, low_nodes = low_constraint_nodes),\n    betweenness_centrality = list(max = max_betweenness_centrality, min = min_betweenness_centrality, high_nodes = high_betweenness_centrality_nodes, low_nodes = low_betweenness_centrality_nodes),\n    brokerage = list(max = max_edge_betweenness, min = min_edge_betweenness, high_nodes = high_brokerage_nodes, low_nodes = low_brokerage_nodes)\n  )\n  \n  return(results)\n}\n\nresults <- identifyProminentNodes(net, g)\n\n# Print the results\nprint(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$in_degree\n$in_degree$max\n[1] 12659\n\n$in_degree$min\n[1] 0\n\n$in_degree$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] \n\n$in_degree$low_nodes\n+ 21/23 vertices, named, from a5bd026:\n [1] NA             India          China          Taiwan         Brazil        \n [6] USA            Mexico         Indonesia      Pakistan       United Kingdom\n[11] South Korea    France         Turkey         Egypt          Nigeria       \n[16] Spain          Bangladesh     Japan          Colombia       Russia        \n[21] Canada        \n\n\n$out_degree\n$out_degree$max\n[1] 8792\n\n$out_degree$min\n[1] 0\n\n$out_degree$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] India\n\n$out_degree$low_nodes\n+ 2/23 vertices, named, from a5bd026:\n[1] Linear or Logistic Regression                              \n\n\n$bonachich_power\n$bonachich_power$max\n[1] 3.914278\n\n$bonachich_power$min\n[1] 0\n\n$bonachich_power$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] India\n\n$bonachich_power$low_nodes\n+ 2/23 vertices, named, from a5bd026:\n[1] Linear or Logistic Regression                              \n\n\n$eigenvector_centrality\n$eigenvector_centrality$max\n[1] 1\n\n$eigenvector_centrality$min\n[1] 0.02743026\n\n$eigenvector_centrality$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] India\n\n$eigenvector_centrality$low_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] Taiwan\n\n\n$derived_centrality\n$derived_centrality$max\n[1] 6329.5\n\n$derived_centrality$min\n[1] 121\n\n$derived_centrality$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] \n\n$derived_centrality$low_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] Taiwan\n\n\n$constraint\n$constraint$max\n[1] 0.5489773\n\n$constraint$min\n[1] 0.201266\n\n$constraint$high_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] France\n\n$constraint$low_nodes\n+ 1/23 vertex, named, from a5bd026:\n[1] Linear or Logistic Regression\n\n\n$betweenness_centrality\n$betweenness_centrality$max\n[1] 0\n\n$betweenness_centrality$min\n[1] 0\n\n$betweenness_centrality$high_nodes\n+ 23/23 vertices, named, from a5bd026:\n [1] NA                            India                        \n [3] China                         Taiwan                       \n [5] Brazil                        USA                          \n [7] Mexico                        Indonesia                    \n [9] Pakistan                      United Kingdom               \n[11] South Korea                   France                       \n[13] Turkey                        Egypt                        \n[15] Nigeria                       Spain                        \n[17] Bangladesh                    Japan                        \n[19] Colombia                      Russia                       \n+ ... omitted several vertices\n\n$betweenness_centrality$low_nodes\n+ 23/23 vertices, named, from a5bd026:\n [1] NA                            India                        \n [3] China                         Taiwan                       \n [5] Brazil                        USA                          \n [7] Mexico                        Indonesia                    \n [9] Pakistan                      United Kingdom               \n[11] South Korea                   France                       \n[13] Turkey                        Egypt                        \n[15] Nigeria                       Spain                        \n[17] Bangladesh                    Japan                        \n[19] Colombia                      Russia                       \n+ ... omitted several vertices\n\n\n$brokerage\n$brokerage$max\n[1] 0.01111111\n\n$brokerage$min\n[1] 0.0002127207\n\n$brokerage$high_nodes\n      [,1]     [,2]\n [1,] \"France\" \"\"  \n [2,] \"France\" \"\"  \n [3,] \"France\" \"\"  \n [4,] \"France\" \"\"  \n [5,] \"France\" \"\"  \n [6,] \"France\" \"\"  \n [7,] \"France\" \"\"  \n [8,] \"France\" \"\"  \n [9,] \"France\" \"\"  \n[10,] \"France\" \"\"  \n[11,] \"France\" \"\"  \n[12,] \"France\" \"\"  \n[13,] \"France\" \"\"  \n[14,] \"France\" \"\"  \n[15,] \"France\" \"\"  \n[16,] \"France\" \"\"  \n[17,] \"France\" \"\"  \n[18,] \"France\" \"\"  \n[19,] \"France\" \"\"  \n[20,] \"France\" \"\"  \n[21,] \"France\" \"\"  \n[22,] \"France\" \"\"  \n[23,] \"France\" \"\"  \n[24,] \"France\" \"\"  \n[25,] \"France\" \"\"  \n[26,] \"France\" \"\"  \n[27,] \"France\" \"\"  \n[28,] \"France\" \"\"  \n[29,] \"France\" \"\"  \n[30,] \"France\" \"\"  \n[31,] \"France\" \"\"  \n[32,] \"France\" \"\"  \n[33,] \"France\" \"\"  \n[34,] \"France\" \"\"  \n[35,] \"France\" \"\"  \n[36,] \"France\" \"\"  \n[37,] \"France\" \"\"  \n[38,] \"France\" \"\"  \n[39,] \"France\" \"\"  \n[40,] \"France\" \"\"  \n[41,] \"France\" \"\"  \n[42,] \"France\" \"\"  \n[43,] \"France\" \"\"  \n[44,] \"France\" \"\"  \n[45,] \"France\" \"\"  \n[46,] \"France\" \"\"  \n[47,] \"France\" \"\"  \n[48,] \"France\" \"\"  \n[49,] \"France\" \"\"  \n[50,] \"France\" \"\"  \n[51,] \"France\" \"\"  \n[52,] \"France\" \"\"  \n[53,] \"France\" \"\"  \n[54,] \"France\" \"\"  \n[55,] \"France\" \"\"  \n[56,] \"France\" \"\"  \n[57,] \"France\" \"\"  \n[58,] \"France\" \"\"  \n[59,] \"France\" \"\"  \n[60,] \"France\" \"\"  \n[61,] \"France\" \"\"  \n[62,] \"France\" \"\"  \n[63,] \"France\" \"\"  \n[64,] \"France\" \"\"  \n[65,] \"France\" \"\"  \n[66,] \"France\" \"\"  \n[67,] \"France\" \"\"  \n[68,] \"France\" \"\"  \n[69,] \"France\" \"\"  \n[70,] \"France\" \"\"  \n[71,] \"France\" \"\"  \n[72,] \"France\" \"\"  \n[73,] \"France\" \"\"  \n[74,] \"France\" \"\"  \n[75,] \"France\" \"\"  \n[76,] \"France\" \"\"  \n[77,] \"France\" \"\"  \n[78,] \"France\" \"\"  \n[79,] \"France\" \"\"  \n[80,] \"France\" \"\"  \n[81,] \"France\" \"\"  \n[82,] \"France\" \"\"  \n[83,] \"France\" \"\"  \n[84,] \"France\" \"\"  \n[85,] \"France\" \"\"  \n[86,] \"France\" \"\"  \n[87,] \"France\" \"\"  \n[88,] \"France\" \"\"  \n[89,] \"France\" \"\"  \n[90,] \"France\" \"\"  \n\n$brokerage$low_nodes\n        [,1]    [,2]\n   [1,] \"India\" \"\"  \n   [2,] \"India\" \"\"  \n   [3,] \"India\" \"\"  \n   [4,] \"India\" \"\"  \n   [5,] \"India\" \"\"  \n   [6,] \"India\" \"\"  \n   [7,] \"India\" \"\"  \n   [8,] \"India\" \"\"  \n   [9,] \"India\" \"\"  \n  [10,] \"India\" \"\"  \n  [11,] \"India\" \"\"  \n  [12,] \"India\" \"\"  \n  [13,] \"India\" \"\"  \n  [14,] \"India\" \"\"  \n  [15,] \"India\" \"\"  \n  [16,] \"India\" \"\"  \n  [17,] \"India\" \"\"  \n  [18,] \"India\" \"\"  \n  [19,] \"India\" \"\"  \n  [20,] \"India\" \"\"  \n  [21,] \"India\" \"\"  \n  [22,] \"India\" \"\"  \n  [23,] \"India\" \"\"  \n  [24,] \"India\" \"\"  \n  [25,] \"India\" \"\"  \n  [26,] \"India\" \"\"  \n  [27,] \"India\" \"\"  \n  [28,] \"India\" \"\"  \n  [29,] \"India\" \"\"  \n  [30,] \"India\" \"\"  \n  [31,] \"India\" \"\"  \n  [32,] \"India\" \"\"  \n  [33,] \"India\" \"\"  \n  [34,] \"India\" \"\"  \n  [35,] \"India\" \"\"  \n  [36,] \"India\" \"\"  \n  [37,] \"India\" \"\"  \n  [38,] \"India\" \"\"  \n  [39,] \"India\" \"\"  \n  [40,] \"India\" \"\"  \n  [41,] \"India\" \"\"  \n  [42,] \"India\" \"\"  \n  [43,] \"India\" \"\"  \n  [44,] \"India\" \"\"  \n  [45,] \"India\" \"\"  \n  [46,] \"India\" \"\"  \n  [47,] \"India\" \"\"  \n  [48,] \"India\" \"\"  \n  [49,] \"India\" \"\"  \n  [50,] \"India\" \"\"  \n  [51,] \"India\" \"\"  \n  [52,] \"India\" \"\"  \n  [53,] \"India\" \"\"  \n  [54,] \"India\" \"\"  \n  [55,] \"India\" \"\"  \n  [56,] \"India\" \"\"  \n  [57,] \"India\" \"\"  \n  [58,] \"India\" \"\"  \n  [59,] \"India\" \"\"  \n  [60,] \"India\" \"\"  \n  [61,] \"India\" \"\"  \n  [62,] \"India\" \"\"  \n  [63,] \"India\" \"\"  \n  [64,] \"India\" \"\"  \n  [65,] \"India\" \"\"  \n  [66,] \"India\" \"\"  \n  [67,] \"India\" \"\"  \n  [68,] \"India\" \"\"  \n  [69,] \"India\" \"\"  \n  [70,] \"India\" \"\"  \n  [71,] \"India\" \"\"  \n  [72,] \"India\" \"\"  \n  [73,] \"India\" \"\"  \n  [74,] \"India\" \"\"  \n  [75,] \"India\" \"\"  \n  [76,] \"India\" \"\"  \n  [77,] \"India\" \"\"  \n  [78,] \"India\" \"\"  \n  [79,] \"India\" \"\"  \n  [80,] \"India\" \"\"  \n  [81,] \"India\" \"\"  \n  [82,] \"India\" \"\"  \n  [83,] \"India\" \"\"  \n  [84,] \"India\" \"\"  \n  [85,] \"India\" \"\"  \n  [86,] \"India\" \"\"  \n  [87,] \"India\" \"\"  \n  [88,] \"India\" \"\"  \n  [89,] \"India\" \"\"  \n  [90,] \"India\" \"\"  \n  [91,] \"India\" \"\"  \n  [92,] \"India\" \"\"  \n  [93,] \"India\" \"\"  \n  [94,] \"India\" \"\"  \n  [95,] \"India\" \"\"  \n  [96,] \"India\" \"\"  \n  [97,] \"India\" \"\"  \n  [98,] \"India\" \"\"  \n  [99,] \"India\" \"\"  \n [100,] \"India\" \"\"  \n [101,] \"India\" \"\"  \n [102,] \"India\" \"\"  \n [103,] \"India\" \"\"  \n [104,] \"India\" \"\"  \n [105,] \"India\" \"\"  \n [106,] \"India\" \"\"  \n [107,] \"India\" \"\"  \n [108,] \"India\" \"\"  \n [109,] \"India\" \"\"  \n [110,] \"India\" \"\"  \n [111,] \"India\" \"\"  \n [112,] \"India\" \"\"  \n [113,] \"India\" \"\"  \n [114,] \"India\" \"\"  \n [115,] \"India\" \"\"  \n [116,] \"India\" \"\"  \n [117,] \"India\" \"\"  \n [118,] \"India\" \"\"  \n [119,] \"India\" \"\"  \n [120,] \"India\" \"\"  \n [121,] \"India\" \"\"  \n [122,] \"India\" \"\"  \n [123,] \"India\" \"\"  \n [124,] \"India\" \"\"  \n [125,] \"India\" \"\"  \n [126,] \"India\" \"\"  \n [127,] \"India\" \"\"  \n [128,] \"India\" \"\"  \n [129,] \"India\" \"\"  \n [130,] \"India\" \"\"  \n [131,] \"India\" \"\"  \n [132,] \"India\" \"\"  \n [133,] \"India\" \"\"  \n [134,] \"India\" \"\"  \n [135,] \"India\" \"\"  \n [136,] \"India\" \"\"  \n [137,] \"India\" \"\"  \n [138,] \"India\" \"\"  \n [139,] \"India\" \"\"  \n [140,] \"India\" \"\"  \n [141,] \"India\" \"\"  \n [142,] \"India\" \"\"  \n [143,] \"India\" \"\"  \n [144,] \"India\" \"\"  \n [145,] \"India\" \"\"  \n [146,] \"India\" \"\"  \n [147,] \"India\" \"\"  \n [148,] \"India\" \"\"  \n [149,] \"India\" \"\"  \n [150,] \"India\" \"\"  \n [151,] \"India\" \"\"  \n [152,] \"India\" \"\"  \n [153,] \"India\" \"\"  \n [154,] \"India\" \"\"  \n [155,] \"India\" \"\"  \n [156,] \"India\" \"\"  \n [157,] \"India\" \"\"  \n [158,] \"India\" \"\"  \n [159,] \"India\" \"\"  \n [160,] \"India\" \"\"  \n [161,] \"India\" \"\"  \n [162,] \"India\" \"\"  \n [163,] \"India\" \"\"  \n [164,] \"India\" \"\"  \n [165,] \"India\" \"\"  \n [166,] \"India\" \"\"  \n [167,] \"India\" \"\"  \n [168,] \"India\" \"\"  \n [169,] \"India\" \"\"  \n [170,] \"India\" \"\"  \n [171,] \"India\" \"\"  \n [172,] \"India\" \"\"  \n [173,] \"India\" \"\"  \n [174,] \"India\" \"\"  \n [175,] \"India\" \"\"  \n [176,] \"India\" \"\"  \n [177,] \"India\" \"\"  \n [178,] \"India\" \"\"  \n [179,] \"India\" \"\"  \n [180,] \"India\" \"\"  \n [181,] \"India\" \"\"  \n [182,] \"India\" \"\"  \n [183,] \"India\" \"\"  \n [184,] \"India\" \"\"  \n [185,] \"India\" \"\"  \n [186,] \"India\" \"\"  \n [187,] \"India\" \"\"  \n [188,] \"India\" \"\"  \n [189,] \"India\" \"\"  \n [190,] \"India\" \"\"  \n [191,] \"India\" \"\"  \n [192,] \"India\" \"\"  \n [193,] \"India\" \"\"  \n [194,] \"India\" \"\"  \n [195,] \"India\" \"\"  \n [196,] \"India\" \"\"  \n [197,] \"India\" \"\"  \n [198,] \"India\" \"\"  \n [199,] \"India\" \"\"  \n [200,] \"India\" \"\"  \n [201,] \"India\" \"\"  \n [202,] \"India\" \"\"  \n [203,] \"India\" \"\"  \n [204,] \"India\" \"\"  \n [205,] \"India\" \"\"  \n [206,] \"India\" \"\"  \n [207,] \"India\" \"\"  \n [208,] \"India\" \"\"  \n [209,] \"India\" \"\"  \n [210,] \"India\" \"\"  \n [211,] \"India\" \"\"  \n [212,] \"India\" \"\"  \n [213,] \"India\" \"\"  \n [214,] \"India\" \"\"  \n [215,] \"India\" \"\"  \n [216,] \"India\" \"\"  \n [217,] \"India\" \"\"  \n [218,] \"India\" \"\"  \n [219,] \"India\" \"\"  \n [220,] \"India\" \"\"  \n [221,] \"India\" \"\"  \n [222,] \"India\" \"\"  \n [223,] \"India\" \"\"  \n [224,] \"India\" \"\"  \n [225,] \"India\" \"\"  \n [226,] \"India\" \"\"  \n [227,] \"India\" \"\"  \n [228,] \"India\" \"\"  \n [229,] \"India\" \"\"  \n [230,] \"India\" \"\"  \n [231,] \"India\" \"\"  \n [232,] \"India\" \"\"  \n [233,] \"India\" \"\"  \n [234,] \"India\" \"\"  \n [235,] \"India\" \"\"  \n [236,] \"India\" \"\"  \n [237,] \"India\" \"\"  \n [238,] \"India\" \"\"  \n [239,] \"India\" \"\"  \n [240,] \"India\" \"\"  \n [241,] \"India\" \"\"  \n [242,] \"India\" \"\"  \n [243,] \"India\" \"\"  \n [244,] \"India\" \"\"  \n [245,] \"India\" \"\"  \n [246,] \"India\" \"\"  \n [247,] \"India\" \"\"  \n [248,] \"India\" \"\"  \n [249,] \"India\" \"\"  \n [250,] \"India\" \"\"  \n [251,] \"India\" \"\"  \n [252,] \"India\" \"\"  \n [253,] \"India\" \"\"  \n [254,] \"India\" \"\"  \n [255,] \"India\" \"\"  \n [256,] \"India\" \"\"  \n [257,] \"India\" \"\"  \n [258,] \"India\" \"\"  \n [259,] \"India\" \"\"  \n [260,] \"India\" \"\"  \n [261,] \"India\" \"\"  \n [262,] \"India\" \"\"  \n [263,] \"India\" \"\"  \n [264,] \"India\" \"\"  \n [265,] \"India\" \"\"  \n [266,] \"India\" \"\"  \n [267,] \"India\" \"\"  \n [268,] \"India\" \"\"  \n [269,] \"India\" \"\"  \n [270,] \"India\" \"\"  \n [271,] \"India\" \"\"  \n [272,] \"India\" \"\"  \n [273,] \"India\" \"\"  \n [274,] \"India\" \"\"  \n [275,] \"India\" \"\"  \n [276,] \"India\" \"\"  \n [277,] \"India\" \"\"  \n [278,] \"India\" \"\"  \n [279,] \"India\" \"\"  \n [280,] \"India\" \"\"  \n [281,] \"India\" \"\"  \n [282,] \"India\" \"\"  \n [283,] \"India\" \"\"  \n [284,] \"India\" \"\"  \n [285,] \"India\" \"\"  \n [286,] \"India\" \"\"  \n [287,] \"India\" \"\"  \n [288,] \"India\" \"\"  \n [289,] \"India\" \"\"  \n [290,] \"India\" \"\"  \n [291,] \"India\" \"\"  \n [292,] \"India\" \"\"  \n [293,] \"India\" \"\"  \n [294,] \"India\" \"\"  \n [295,] \"India\" \"\"  \n [296,] \"India\" \"\"  \n [297,] \"India\" \"\"  \n [298,] \"India\" \"\"  \n [299,] \"India\" \"\"  \n [300,] \"India\" \"\"  \n [301,] \"India\" \"\"  \n [302,] \"India\" \"\"  \n [303,] \"India\" \"\"  \n [304,] \"India\" \"\"  \n [305,] \"India\" \"\"  \n [306,] \"India\" \"\"  \n [307,] \"India\" \"\"  \n [308,] \"India\" \"\"  \n [309,] \"India\" \"\"  \n [310,] \"India\" \"\"  \n [311,] \"India\" \"\"  \n [312,] \"India\" \"\"  \n [313,] \"India\" \"\"  \n [314,] \"India\" \"\"  \n [315,] \"India\" \"\"  \n [316,] \"India\" \"\"  \n [317,] \"India\" \"\"  \n [318,] \"India\" \"\"  \n [319,] \"India\" \"\"  \n [320,] \"India\" \"\"  \n [321,] \"India\" \"\"  \n [322,] \"India\" \"\"  \n [323,] \"India\" \"\"  \n [324,] \"India\" \"\"  \n [325,] \"India\" \"\"  \n [326,] \"India\" \"\"  \n [327,] \"India\" \"\"  \n [328,] \"India\" \"\"  \n [329,] \"India\" \"\"  \n [330,] \"India\" \"\"  \n [331,] \"India\" \"\"  \n [332,] \"India\" \"\"  \n [333,] \"India\" \"\"  \n [334,] \"India\" \"\"  \n [335,] \"India\" \"\"  \n [336,] \"India\" \"\"  \n [337,] \"India\" \"\"  \n [338,] \"India\" \"\"  \n [339,] \"India\" \"\"  \n [340,] \"India\" \"\"  \n [341,] \"India\" \"\"  \n [342,] \"India\" \"\"  \n [343,] \"India\" \"\"  \n [344,] \"India\" \"\"  \n [345,] \"India\" \"\"  \n [346,] \"India\" \"\"  \n [347,] \"India\" \"\"  \n [348,] \"India\" \"\"  \n [349,] \"India\" \"\"  \n [350,] \"India\" \"\"  \n [351,] \"India\" \"\"  \n [352,] \"India\" \"\"  \n [353,] \"India\" \"\"  \n [354,] \"India\" \"\"  \n [355,] \"India\" \"\"  \n [356,] \"India\" \"\"  \n [357,] \"India\" \"\"  \n [358,] \"India\" \"\"  \n [359,] \"India\" \"\"  \n [360,] \"India\" \"\"  \n [361,] \"India\" \"\"  \n [362,] \"India\" \"\"  \n [363,] \"India\" \"\"  \n [364,] \"India\" \"\"  \n [365,] \"India\" \"\"  \n [366,] \"India\" \"\"  \n [367,] \"India\" \"\"  \n [368,] \"India\" \"\"  \n [369,] \"India\" \"\"  \n [370,] \"India\" \"\"  \n [371,] \"India\" \"\"  \n [372,] \"India\" \"\"  \n [373,] \"India\" \"\"  \n [374,] \"India\" \"\"  \n [375,] \"India\" \"\"  \n [376,] \"India\" \"\"  \n [377,] \"India\" \"\"  \n [378,] \"India\" \"\"  \n [379,] \"India\" \"\"  \n [380,] \"India\" \"\"  \n [381,] \"India\" \"\"  \n [382,] \"India\" \"\"  \n [383,] \"India\" \"\"  \n [384,] \"India\" \"\"  \n [385,] \"India\" \"\"  \n [386,] \"India\" \"\"  \n [387,] \"India\" \"\"  \n [388,] \"India\" \"\"  \n [389,] \"India\" \"\"  \n [390,] \"India\" \"\"  \n [391,] \"India\" \"\"  \n [392,] \"India\" \"\"  \n [393,] \"India\" \"\"  \n [394,] \"India\" \"\"  \n [395,] \"India\" \"\"  \n [396,] \"India\" \"\"  \n [397,] \"India\" \"\"  \n [398,] \"India\" \"\"  \n [399,] \"India\" \"\"  \n [400,] \"India\" \"\"  \n [401,] \"India\" \"\"  \n [402,] \"India\" \"\"  \n [403,] \"India\" \"\"  \n [404,] \"India\" \"\"  \n [405,] \"India\" \"\"  \n [406,] \"India\" \"\"  \n [407,] \"India\" \"\"  \n [408,] \"India\" \"\"  \n [409,] \"India\" \"\"  \n [410,] \"India\" \"\"  \n [411,] \"India\" \"\"  \n [412,] \"India\" \"\"  \n [413,] \"India\" \"\"  \n [414,] \"India\" \"\"  \n [415,] \"India\" \"\"  \n [416,] \"India\" \"\"  \n [417,] \"India\" \"\"  \n [418,] \"India\" \"\"  \n [419,] \"India\" \"\"  \n [420,] \"India\" \"\"  \n [421,] \"India\" \"\"  \n [422,] \"India\" \"\"  \n [423,] \"India\" \"\"  \n [424,] \"India\" \"\"  \n [425,] \"India\" \"\"  \n [426,] \"India\" \"\"  \n [427,] \"India\" \"\"  \n [428,] \"India\" \"\"  \n [429,] \"India\" \"\"  \n [430,] \"India\" \"\"  \n [431,] \"India\" \"\"  \n [432,] \"India\" \"\"  \n [433,] \"India\" \"\"  \n [434,] \"India\" \"\"  \n [435,] \"India\" \"\"  \n [436,] \"India\" \"\"  \n [437,] \"India\" \"\"  \n [438,] \"India\" \"\"  \n [439,] \"India\" \"\"  \n [440,] \"India\" \"\"  \n [441,] \"India\" \"\"  \n [442,] \"India\" \"\"  \n [443,] \"India\" \"\"  \n [444,] \"India\" \"\"  \n [445,] \"India\" \"\"  \n [446,] \"India\" \"\"  \n [447,] \"India\" \"\"  \n [448,] \"India\" \"\"  \n [449,] \"India\" \"\"  \n [450,] \"India\" \"\"  \n [451,] \"India\" \"\"  \n [452,] \"India\" \"\"  \n [453,] \"India\" \"\"  \n [454,] \"India\" \"\"  \n [455,] \"India\" \"\"  \n [456,] \"India\" \"\"  \n [457,] \"India\" \"\"  \n [458,] \"India\" \"\"  \n [459,] \"India\" \"\"  \n [460,] \"India\" \"\"  \n [461,] \"India\" \"\"  \n [462,] \"India\" \"\"  \n [463,] \"India\" \"\"  \n [464,] \"India\" \"\"  \n [465,] \"India\" \"\"  \n [466,] \"India\" \"\"  \n [467,] \"India\" \"\"  \n [468,] \"India\" \"\"  \n [469,] \"India\" \"\"  \n [470,] \"India\" \"\"  \n [471,] \"India\" \"\"  \n [472,] \"India\" \"\"  \n [473,] \"India\" \"\"  \n [474,] \"India\" \"\"  \n [475,] \"India\" \"\"  \n [476,] \"India\" \"\"  \n [477,] \"India\" \"\"  \n [478,] \"India\" \"\"  \n [479,] \"India\" \"\"  \n [480,] \"India\" \"\"  \n [481,] \"India\" \"\"  \n [482,] \"India\" \"\"  \n [483,] \"India\" \"\"  \n [484,] \"India\" \"\"  \n [485,] \"India\" \"\"  \n [486,] \"India\" \"\"  \n [487,] \"India\" \"\"  \n [488,] \"India\" \"\"  \n [489,] \"India\" \"\"  \n [490,] \"India\" \"\"  \n [491,] \"India\" \"\"  \n [492,] \"India\" \"\"  \n [493,] \"India\" \"\"  \n [494,] \"India\" \"\"  \n [495,] \"India\" \"\"  \n [496,] \"India\" \"\"  \n [497,] \"India\" \"\"  \n [498,] \"India\" \"\"  \n [499,] \"India\" \"\"  \n [500,] \"India\" \"\"  \n [501,] \"India\" \"\"  \n [502,] \"India\" \"\"  \n [503,] \"India\" \"\"  \n [504,] \"India\" \"\"  \n [505,] \"India\" \"\"  \n [506,] \"India\" \"\"  \n [507,] \"India\" \"\"  \n [508,] \"India\" \"\"  \n [509,] \"India\" \"\"  \n [510,] \"India\" \"\"  \n [511,] \"India\" \"\"  \n [512,] \"India\" \"\"  \n [513,] \"India\" \"\"  \n [514,] \"India\" \"\"  \n [515,] \"India\" \"\"  \n [516,] \"India\" \"\"  \n [517,] \"India\" \"\"  \n [518,] \"India\" \"\"  \n [519,] \"India\" \"\"  \n [520,] \"India\" \"\"  \n [521,] \"India\" \"\"  \n [522,] \"India\" \"\"  \n [523,] \"India\" \"\"  \n [524,] \"India\" \"\"  \n [525,] \"India\" \"\"  \n [526,] \"India\" \"\"  \n [527,] \"India\" \"\"  \n [528,] \"India\" \"\"  \n [529,] \"India\" \"\"  \n [530,] \"India\" \"\"  \n [531,] \"India\" \"\"  \n [532,] \"India\" \"\"  \n [533,] \"India\" \"\"  \n [534,] \"India\" \"\"  \n [535,] \"India\" \"\"  \n [536,] \"India\" \"\"  \n [537,] \"India\" \"\"  \n [538,] \"India\" \"\"  \n [539,] \"India\" \"\"  \n [540,] \"India\" \"\"  \n [541,] \"India\" \"\"  \n [542,] \"India\" \"\"  \n [543,] \"India\" \"\"  \n [544,] \"India\" \"\"  \n [545,] \"India\" \"\"  \n [546,] \"India\" \"\"  \n [547,] \"India\" \"\"  \n [548,] \"India\" \"\"  \n [549,] \"India\" \"\"  \n [550,] \"India\" \"\"  \n [551,] \"India\" \"\"  \n [552,] \"India\" \"\"  \n [553,] \"India\" \"\"  \n [554,] \"India\" \"\"  \n [555,] \"India\" \"\"  \n [556,] \"India\" \"\"  \n [557,] \"India\" \"\"  \n [558,] \"India\" \"\"  \n [559,] \"India\" \"\"  \n [560,] \"India\" \"\"  \n [561,] \"India\" \"\"  \n [562,] \"India\" \"\"  \n [563,] \"India\" \"\"  \n [564,] \"India\" \"\"  \n [565,] \"India\" \"\"  \n [566,] \"India\" \"\"  \n [567,] \"India\" \"\"  \n [568,] \"India\" \"\"  \n [569,] \"India\" \"\"  \n [570,] \"India\" \"\"  \n [571,] \"India\" \"\"  \n [572,] \"India\" \"\"  \n [573,] \"India\" \"\"  \n [574,] \"India\" \"\"  \n [575,] \"India\" \"\"  \n [576,] \"India\" \"\"  \n [577,] \"India\" \"\"  \n [578,] \"India\" \"\"  \n [579,] \"India\" \"\"  \n [580,] \"India\" \"\"  \n [581,] \"India\" \"\"  \n [582,] \"India\" \"\"  \n [583,] \"India\" \"\"  \n [584,] \"India\" \"\"  \n [585,] \"India\" \"\"  \n [586,] \"India\" \"\"  \n [587,] \"India\" \"\"  \n [588,] \"India\" \"\"  \n [589,] \"India\" \"\"  \n [590,] \"India\" \"\"  \n [591,] \"India\" \"\"  \n [592,] \"India\" \"\"  \n [593,] \"India\" \"\"  \n [594,] \"India\" \"\"  \n [595,] \"India\" \"\"  \n [596,] \"India\" \"\"  \n [597,] \"India\" \"\"  \n [598,] \"India\" \"\"  \n [599,] \"India\" \"\"  \n [600,] \"India\" \"\"  \n [601,] \"India\" \"\"  \n [602,] \"India\" \"\"  \n [603,] \"India\" \"\"  \n [604,] \"India\" \"\"  \n [605,] \"India\" \"\"  \n [606,] \"India\" \"\"  \n [607,] \"India\" \"\"  \n [608,] \"India\" \"\"  \n [609,] \"India\" \"\"  \n [610,] \"India\" \"\"  \n [611,] \"India\" \"\"  \n [612,] \"India\" \"\"  \n [613,] \"India\" \"\"  \n [614,] \"India\" \"\"  \n [615,] \"India\" \"\"  \n [616,] \"India\" \"\"  \n [617,] \"India\" \"\"  \n [618,] \"India\" \"\"  \n [619,] \"India\" \"\"  \n [620,] \"India\" \"\"  \n [621,] \"India\" \"\"  \n [622,] \"India\" \"\"  \n [623,] \"India\" \"\"  \n [624,] \"India\" \"\"  \n [625,] \"India\" \"\"  \n [626,] \"India\" \"\"  \n [627,] \"India\" \"\"  \n [628,] \"India\" \"\"  \n [629,] \"India\" \"\"  \n [630,] \"India\" \"\"  \n [631,] \"India\" \"\"  \n [632,] \"India\" \"\"  \n [633,] \"India\" \"\"  \n [634,] \"India\" \"\"  \n [635,] \"India\" \"\"  \n [636,] \"India\" \"\"  \n [637,] \"India\" \"\"  \n [638,] \"India\" \"\"  \n [639,] \"India\" \"\"  \n [640,] \"India\" \"\"  \n [641,] \"India\" \"\"  \n [642,] \"India\" \"\"  \n [643,] \"India\" \"\"  \n [644,] \"India\" \"\"  \n [645,] \"India\" \"\"  \n [646,] \"India\" \"\"  \n [647,] \"India\" \"\"  \n [648,] \"India\" \"\"  \n [649,] \"India\" \"\"  \n [650,] \"India\" \"\"  \n [651,] \"India\" \"\"  \n [652,] \"India\" \"\"  \n [653,] \"India\" \"\"  \n [654,] \"India\" \"\"  \n [655,] \"India\" \"\"  \n [656,] \"India\" \"\"  \n [657,] \"India\" \"\"  \n [658,] \"India\" \"\"  \n [659,] \"India\" \"\"  \n [660,] \"India\" \"\"  \n [661,] \"India\" \"\"  \n [662,] \"India\" \"\"  \n [663,] \"India\" \"\"  \n [664,] \"India\" \"\"  \n [665,] \"India\" \"\"  \n [666,] \"India\" \"\"  \n [667,] \"India\" \"\"  \n [668,] \"India\" \"\"  \n [669,] \"India\" \"\"  \n [670,] \"India\" \"\"  \n [671,] \"India\" \"\"  \n [672,] \"India\" \"\"  \n [673,] \"India\" \"\"  \n [674,] \"India\" \"\"  \n [675,] \"India\" \"\"  \n [676,] \"India\" \"\"  \n [677,] \"India\" \"\"  \n [678,] \"India\" \"\"  \n [679,] \"India\" \"\"  \n [680,] \"India\" \"\"  \n [681,] \"India\" \"\"  \n [682,] \"India\" \"\"  \n [683,] \"India\" \"\"  \n [684,] \"India\" \"\"  \n [685,] \"India\" \"\"  \n [686,] \"India\" \"\"  \n [687,] \"India\" \"\"  \n [688,] \"India\" \"\"  \n [689,] \"India\" \"\"  \n [690,] \"India\" \"\"  \n [691,] \"India\" \"\"  \n [692,] \"India\" \"\"  \n [693,] \"India\" \"\"  \n [694,] \"India\" \"\"  \n [695,] \"India\" \"\"  \n [696,] \"India\" \"\"  \n [697,] \"India\" \"\"  \n [698,] \"India\" \"\"  \n [699,] \"India\" \"\"  \n [700,] \"India\" \"\"  \n [701,] \"India\" \"\"  \n [702,] \"India\" \"\"  \n [703,] \"India\" \"\"  \n [704,] \"India\" \"\"  \n [705,] \"India\" \"\"  \n [706,] \"India\" \"\"  \n [707,] \"India\" \"\"  \n [708,] \"India\" \"\"  \n [709,] \"India\" \"\"  \n [710,] \"India\" \"\"  \n [711,] \"India\" \"\"  \n [712,] \"India\" \"\"  \n [713,] \"India\" \"\"  \n [714,] \"India\" \"\"  \n [715,] \"India\" \"\"  \n [716,] \"India\" \"\"  \n [717,] \"India\" \"\"  \n [718,] \"India\" \"\"  \n [719,] \"India\" \"\"  \n [720,] \"India\" \"\"  \n [721,] \"India\" \"\"  \n [722,] \"India\" \"\"  \n [723,] \"India\" \"\"  \n [724,] \"India\" \"\"  \n [725,] \"India\" \"\"  \n [726,] \"India\" \"\"  \n [727,] \"India\" \"\"  \n [728,] \"India\" \"\"  \n [729,] \"India\" \"\"  \n [730,] \"India\" \"\"  \n [731,] \"India\" \"\"  \n [732,] \"India\" \"\"  \n [733,] \"India\" \"\"  \n [734,] \"India\" \"\"  \n [735,] \"India\" \"\"  \n [736,] \"India\" \"\"  \n [737,] \"India\" \"\"  \n [738,] \"India\" \"\"  \n [739,] \"India\" \"\"  \n [740,] \"India\" \"\"  \n [741,] \"India\" \"\"  \n [742,] \"India\" \"\"  \n [743,] \"India\" \"\"  \n [744,] \"India\" \"\"  \n [745,] \"India\" \"\"  \n [746,] \"India\" \"\"  \n [747,] \"India\" \"\"  \n [748,] \"India\" \"\"  \n [749,] \"India\" \"\"  \n [750,] \"India\" \"\"  \n [751,] \"India\" \"\"  \n [752,] \"India\" \"\"  \n [753,] \"India\" \"\"  \n [754,] \"India\" \"\"  \n [755,] \"India\" \"\"  \n [756,] \"India\" \"\"  \n [757,] \"India\" \"\"  \n [758,] \"India\" \"\"  \n [759,] \"India\" \"\"  \n [760,] \"India\" \"\"  \n [761,] \"India\" \"\"  \n [762,] \"India\" \"\"  \n [763,] \"India\" \"\"  \n [764,] \"India\" \"\"  \n [765,] \"India\" \"\"  \n [766,] \"India\" \"\"  \n [767,] \"India\" \"\"  \n [768,] \"India\" \"\"  \n [769,] \"India\" \"\"  \n [770,] \"India\" \"\"  \n [771,] \"India\" \"\"  \n [772,] \"India\" \"\"  \n [773,] \"India\" \"\"  \n [774,] \"India\" \"\"  \n [775,] \"India\" \"\"  \n [776,] \"India\" \"\"  \n [777,] \"India\" \"\"  \n [778,] \"India\" \"\"  \n [779,] \"India\" \"\"  \n [780,] \"India\" \"\"  \n [781,] \"India\" \"\"  \n [782,] \"India\" \"\"  \n [783,] \"India\" \"\"  \n [784,] \"India\" \"\"  \n [785,] \"India\" \"\"  \n [786,] \"India\" \"\"  \n [787,] \"India\" \"\"  \n [788,] \"India\" \"\"  \n [789,] \"India\" \"\"  \n [790,] \"India\" \"\"  \n [791,] \"India\" \"\"  \n [792,] \"India\" \"\"  \n [793,] \"India\" \"\"  \n [794,] \"India\" \"\"  \n [795,] \"India\" \"\"  \n [796,] \"India\" \"\"  \n [797,] \"India\" \"\"  \n [798,] \"India\" \"\"  \n [799,] \"India\" \"\"  \n [800,] \"India\" \"\"  \n [801,] \"India\" \"\"  \n [802,] \"India\" \"\"  \n [803,] \"India\" \"\"  \n [804,] \"India\" \"\"  \n [805,] \"India\" \"\"  \n [806,] \"India\" \"\"  \n [807,] \"India\" \"\"  \n [808,] \"India\" \"\"  \n [809,] \"India\" \"\"  \n [810,] \"India\" \"\"  \n [811,] \"India\" \"\"  \n [812,] \"India\" \"\"  \n [813,] \"India\" \"\"  \n [814,] \"India\" \"\"  \n [815,] \"India\" \"\"  \n [816,] \"India\" \"\"  \n [817,] \"India\" \"\"  \n [818,] \"India\" \"\"  \n [819,] \"India\" \"\"  \n [820,] \"India\" \"\"  \n [821,] \"India\" \"\"  \n [822,] \"India\" \"\"  \n [823,] \"India\" \"\"  \n [824,] \"India\" \"\"  \n [825,] \"India\" \"\"  \n [826,] \"India\" \"\"  \n [827,] \"India\" \"\"  \n [828,] \"India\" \"\"  \n [829,] \"India\" \"\"  \n [830,] \"India\" \"\"  \n [831,] \"India\" \"\"  \n [832,] \"India\" \"\"  \n [833,] \"India\" \"\"  \n [834,] \"India\" \"\"  \n [835,] \"India\" \"\"  \n [836,] \"India\" \"\"  \n [837,] \"India\" \"\"  \n [838,] \"India\" \"\"  \n [839,] \"India\" \"\"  \n [840,] \"India\" \"\"  \n [841,] \"India\" \"\"  \n [842,] \"India\" \"\"  \n [843,] \"India\" \"\"  \n [844,] \"India\" \"\"  \n [845,] \"India\" \"\"  \n [846,] \"India\" \"\"  \n [847,] \"India\" \"\"  \n [848,] \"India\" \"\"  \n [849,] \"India\" \"\"  \n [850,] \"India\" \"\"  \n [851,] \"India\" \"\"  \n [852,] \"India\" \"\"  \n [853,] \"India\" \"\"  \n [854,] \"India\" \"\"  \n [855,] \"India\" \"\"  \n [856,] \"India\" \"\"  \n [857,] \"India\" \"\"  \n [858,] \"India\" \"\"  \n [859,] \"India\" \"\"  \n [860,] \"India\" \"\"  \n [861,] \"India\" \"\"  \n [862,] \"India\" \"\"  \n [863,] \"India\" \"\"  \n [864,] \"India\" \"\"  \n [865,] \"India\" \"\"  \n [866,] \"India\" \"\"  \n [867,] \"India\" \"\"  \n [868,] \"India\" \"\"  \n [869,] \"India\" \"\"  \n [870,] \"India\" \"\"  \n [871,] \"India\" \"\"  \n [872,] \"India\" \"\"  \n [873,] \"India\" \"\"  \n [874,] \"India\" \"\"  \n [875,] \"India\" \"\"  \n [876,] \"India\" \"\"  \n [877,] \"India\" \"\"  \n [878,] \"India\" \"\"  \n [879,] \"India\" \"\"  \n [880,] \"India\" \"\"  \n [881,] \"India\" \"\"  \n [882,] \"India\" \"\"  \n [883,] \"India\" \"\"  \n [884,] \"India\" \"\"  \n [885,] \"India\" \"\"  \n [886,] \"India\" \"\"  \n [887,] \"India\" \"\"  \n [888,] \"India\" \"\"  \n [889,] \"India\" \"\"  \n [890,] \"India\" \"\"  \n [891,] \"India\" \"\"  \n [892,] \"India\" \"\"  \n [893,] \"India\" \"\"  \n [894,] \"India\" \"\"  \n [895,] \"India\" \"\"  \n [896,] \"India\" \"\"  \n [897,] \"India\" \"\"  \n [898,] \"India\" \"\"  \n [899,] \"India\" \"\"  \n [900,] \"India\" \"\"  \n [901,] \"India\" \"\"  \n [902,] \"India\" \"\"  \n [903,] \"India\" \"\"  \n [904,] \"India\" \"\"  \n [905,] \"India\" \"\"  \n [906,] \"India\" \"\"  \n [907,] \"India\" \"\"  \n [908,] \"India\" \"\"  \n [909,] \"India\" \"\"  \n [910,] \"India\" \"\"  \n [911,] \"India\" \"\"  \n [912,] \"India\" \"\"  \n [913,] \"India\" \"\"  \n [914,] \"India\" \"\"  \n [915,] \"India\" \"\"  \n [916,] \"India\" \"\"  \n [917,] \"India\" \"\"  \n [918,] \"India\" \"\"  \n [919,] \"India\" \"\"  \n [920,] \"India\" \"\"  \n [921,] \"India\" \"\"  \n [922,] \"India\" \"\"  \n [923,] \"India\" \"\"  \n [924,] \"India\" \"\"  \n [925,] \"India\" \"\"  \n [926,] \"India\" \"\"  \n [927,] \"India\" \"\"  \n [928,] \"India\" \"\"  \n [929,] \"India\" \"\"  \n [930,] \"India\" \"\"  \n [931,] \"India\" \"\"  \n [932,] \"India\" \"\"  \n [933,] \"India\" \"\"  \n [934,] \"India\" \"\"  \n [935,] \"India\" \"\"  \n [936,] \"India\" \"\"  \n [937,] \"India\" \"\"  \n [938,] \"India\" \"\"  \n [939,] \"India\" \"\"  \n [940,] \"India\" \"\"  \n [941,] \"India\" \"\"  \n [942,] \"India\" \"\"  \n [943,] \"India\" \"\"  \n [944,] \"India\" \"\"  \n [945,] \"India\" \"\"  \n [946,] \"India\" \"\"  \n [947,] \"India\" \"\"  \n [948,] \"India\" \"\"  \n [949,] \"India\" \"\"  \n [950,] \"India\" \"\"  \n [951,] \"India\" \"\"  \n [952,] \"India\" \"\"  \n [953,] \"India\" \"\"  \n [954,] \"India\" \"\"  \n [955,] \"India\" \"\"  \n [956,] \"India\" \"\"  \n [957,] \"India\" \"\"  \n [958,] \"India\" \"\"  \n [959,] \"India\" \"\"  \n [960,] \"India\" \"\"  \n [961,] \"India\" \"\"  \n [962,] \"India\" \"\"  \n [963,] \"India\" \"\"  \n [964,] \"India\" \"\"  \n [965,] \"India\" \"\"  \n [966,] \"India\" \"\"  \n [967,] \"India\" \"\"  \n [968,] \"India\" \"\"  \n [969,] \"India\" \"\"  \n [970,] \"India\" \"\"  \n [971,] \"India\" \"\"  \n [972,] \"India\" \"\"  \n [973,] \"India\" \"\"  \n [974,] \"India\" \"\"  \n [975,] \"India\" \"\"  \n [976,] \"India\" \"\"  \n [977,] \"India\" \"\"  \n [978,] \"India\" \"\"  \n [979,] \"India\" \"\"  \n [980,] \"India\" \"\"  \n [981,] \"India\" \"\"  \n [982,] \"India\" \"\"  \n [983,] \"India\" \"\"  \n [984,] \"India\" \"\"  \n [985,] \"India\" \"\"  \n [986,] \"India\" \"\"  \n [987,] \"India\" \"\"  \n [988,] \"India\" \"\"  \n [989,] \"India\" \"\"  \n [990,] \"India\" \"\"  \n [991,] \"India\" \"\"  \n [992,] \"India\" \"\"  \n [993,] \"India\" \"\"  \n [994,] \"India\" \"\"  \n [995,] \"India\" \"\"  \n [996,] \"India\" \"\"  \n [997,] \"India\" \"\"  \n [998,] \"India\" \"\"  \n [999,] \"India\" \"\"  \n[1000,] \"India\" \"\"  \n[1001,] \"India\" \"\"  \n[1002,] \"India\" \"\"  \n[1003,] \"India\" \"\"  \n[1004,] \"India\" \"\"  \n[1005,] \"India\" \"\"  \n[1006,] \"India\" \"\"  \n[1007,] \"India\" \"\"  \n[1008,] \"India\" \"\"  \n[1009,] \"India\" \"\"  \n[1010,] \"India\" \"\"  \n[1011,] \"India\" \"\"  \n[1012,] \"India\" \"\"  \n[1013,] \"India\" \"\"  \n[1014,] \"India\" \"\"  \n[1015,] \"India\" \"\"  \n[1016,] \"India\" \"\"  \n[1017,] \"India\" \"\"  \n[1018,] \"India\" \"\"  \n[1019,] \"India\" \"\"  \n[1020,] \"India\" \"\"  \n[1021,] \"India\" \"\"  \n[1022,] \"India\" \"\"  \n[1023,] \"India\" \"\"  \n[1024,] \"India\" \"\"  \n[1025,] \"India\" \"\"  \n[1026,] \"India\" \"\"  \n[1027,] \"India\" \"\"  \n[1028,] \"India\" \"\"  \n[1029,] \"India\" \"\"  \n[1030,] \"India\" \"\"  \n[1031,] \"India\" \"\"  \n[1032,] \"India\" \"\"  \n[1033,] \"India\" \"\"  \n[1034,] \"India\" \"\"  \n[1035,] \"India\" \"\"  \n[1036,] \"India\" \"\"  \n[1037,] \"India\" \"\"  \n[1038,] \"India\" \"\"  \n[1039,] \"India\" \"\"  \n[1040,] \"India\" \"\"  \n[1041,] \"India\" \"\"  \n[1042,] \"India\" \"\"  \n[1043,] \"India\" \"\"  \n[1044,] \"India\" \"\"  \n[1045,] \"India\" \"\"  \n[1046,] \"India\" \"\"  \n[1047,] \"India\" \"\"  \n[1048,] \"India\" \"\"  \n[1049,] \"India\" \"\"  \n[1050,] \"India\" \"\"  \n[1051,] \"India\" \"\"  \n[1052,] \"India\" \"\"  \n[1053,] \"India\" \"\"  \n[1054,] \"India\" \"\"  \n[1055,] \"India\" \"\"  \n[1056,] \"India\" \"\"  \n[1057,] \"India\" \"\"  \n[1058,] \"India\" \"\"  \n[1059,] \"India\" \"\"  \n[1060,] \"India\" \"\"  \n[1061,] \"India\" \"\"  \n[1062,] \"India\" \"\"  \n[1063,] \"India\" \"\"  \n[1064,] \"India\" \"\"  \n[1065,] \"India\" \"\"  \n[1066,] \"India\" \"\"  \n[1067,] \"India\" \"\"  \n[1068,] \"India\" \"\"  \n[1069,] \"India\" \"\"  \n[1070,] \"India\" \"\"  \n[1071,] \"India\" \"\"  \n[1072,] \"India\" \"\"  \n[1073,] \"India\" \"\"  \n[1074,] \"India\" \"\"  \n[1075,] \"India\" \"\"  \n[1076,] \"India\" \"\"  \n[1077,] \"India\" \"\"  \n[1078,] \"India\" \"\"  \n[1079,] \"India\" \"\"  \n[1080,] \"India\" \"\"  \n[1081,] \"India\" \"\"  \n[1082,] \"India\" \"\"  \n[1083,] \"India\" \"\"  \n[1084,] \"India\" \"\"  \n[1085,] \"India\" \"\"  \n[1086,] \"India\" \"\"  \n[1087,] \"India\" \"\"  \n[1088,] \"India\" \"\"  \n[1089,] \"India\" \"\"  \n[1090,] \"India\" \"\"  \n[1091,] \"India\" \"\"  \n[1092,] \"India\" \"\"  \n[1093,] \"India\" \"\"  \n[1094,] \"India\" \"\"  \n[1095,] \"India\" \"\"  \n[1096,] \"India\" \"\"  \n[1097,] \"India\" \"\"  \n[1098,] \"India\" \"\"  \n[1099,] \"India\" \"\"  \n[1100,] \"India\" \"\"  \n[1101,] \"India\" \"\"  \n[1102,] \"India\" \"\"  \n[1103,] \"India\" \"\"  \n[1104,] \"India\" \"\"  \n[1105,] \"India\" \"\"  \n[1106,] \"India\" \"\"  \n[1107,] \"India\" \"\"  \n[1108,] \"India\" \"\"  \n[1109,] \"India\" \"\"  \n[1110,] \"India\" \"\"  \n[1111,] \"India\" \"\"  \n[1112,] \"India\" \"\"  \n[1113,] \"India\" \"\"  \n[1114,] \"India\" \"\"  \n[1115,] \"India\" \"\"  \n[1116,] \"India\" \"\"  \n[1117,] \"India\" \"\"  \n[1118,] \"India\" \"\"  \n[1119,] \"India\" \"\"  \n[1120,] \"India\" \"\"  \n[1121,] \"India\" \"\"  \n[1122,] \"India\" \"\"  \n[1123,] \"India\" \"\"  \n[1124,] \"India\" \"\"  \n[1125,] \"India\" \"\"  \n[1126,] \"India\" \"\"  \n[1127,] \"India\" \"\"  \n[1128,] \"India\" \"\"  \n[1129,] \"India\" \"\"  \n[1130,] \"India\" \"\"  \n[1131,] \"India\" \"\"  \n[1132,] \"India\" \"\"  \n[1133,] \"India\" \"\"  \n[1134,] \"India\" \"\"  \n[1135,] \"India\" \"\"  \n[1136,] \"India\" \"\"  \n[1137,] \"India\" \"\"  \n[1138,] \"India\" \"\"  \n[1139,] \"India\" \"\"  \n[1140,] \"India\" \"\"  \n[1141,] \"India\" \"\"  \n[1142,] \"India\" \"\"  \n[1143,] \"India\" \"\"  \n[1144,] \"India\" \"\"  \n[1145,] \"India\" \"\"  \n[1146,] \"India\" \"\"  \n[1147,] \"India\" \"\"  \n[1148,] \"India\" \"\"  \n[1149,] \"India\" \"\"  \n[1150,] \"India\" \"\"  \n[1151,] \"India\" \"\"  \n[1152,] \"India\" \"\"  \n[1153,] \"India\" \"\"  \n[1154,] \"India\" \"\"  \n[1155,] \"India\" \"\"  \n[1156,] \"India\" \"\"  \n[1157,] \"India\" \"\"  \n[1158,] \"India\" \"\"  \n[1159,] \"India\" \"\"  \n[1160,] \"India\" \"\"  \n[1161,] \"India\" \"\"  \n[1162,] \"India\" \"\"  \n[1163,] \"India\" \"\"  \n[1164,] \"India\" \"\"  \n[1165,] \"India\" \"\"  \n[1166,] \"India\" \"\"  \n[1167,] \"India\" \"\"  \n[1168,] \"India\" \"\"  \n[1169,] \"India\" \"\"  \n[1170,] \"India\" \"\"  \n[1171,] \"India\" \"\"  \n[1172,] \"India\" \"\"  \n[1173,] \"India\" \"\"  \n[1174,] \"India\" \"\"  \n[1175,] \"India\" \"\"  \n[1176,] \"India\" \"\"  \n[1177,] \"India\" \"\"  \n[1178,] \"India\" \"\"  \n[1179,] \"India\" \"\"  \n[1180,] \"India\" \"\"  \n[1181,] \"India\" \"\"  \n[1182,] \"India\" \"\"  \n[1183,] \"India\" \"\"  \n[1184,] \"India\" \"\"  \n[1185,] \"India\" \"\"  \n[1186,] \"India\" \"\"  \n[1187,] \"India\" \"\"  \n[1188,] \"India\" \"\"  \n[1189,] \"India\" \"\"  \n[1190,] \"India\" \"\"  \n[1191,] \"India\" \"\"  \n[1192,] \"India\" \"\"  \n[1193,] \"India\" \"\"  \n[1194,] \"India\" \"\"  \n[1195,] \"India\" \"\"  \n[1196,] \"India\" \"\"  \n[1197,] \"India\" \"\"  \n[1198,] \"India\" \"\"  \n[1199,] \"India\" \"\"  \n[1200,] \"India\" \"\"  \n[1201,] \"India\" \"\"  \n[1202,] \"India\" \"\"  \n[1203,] \"India\" \"\"  \n[1204,] \"India\" \"\"  \n[1205,] \"India\" \"\"  \n[1206,] \"India\" \"\"  \n[1207,] \"India\" \"\"  \n[1208,] \"India\" \"\"  \n[1209,] \"India\" \"\"  \n[1210,] \"India\" \"\"  \n[1211,] \"India\" \"\"  \n[1212,] \"India\" \"\"  \n[1213,] \"India\" \"\"  \n[1214,] \"India\" \"\"  \n[1215,] \"India\" \"\"  \n[1216,] \"India\" \"\"  \n[1217,] \"India\" \"\"  \n[1218,] \"India\" \"\"  \n[1219,] \"India\" \"\"  \n[1220,] \"India\" \"\"  \n[1221,] \"India\" \"\"  \n[1222,] \"India\" \"\"  \n[1223,] \"India\" \"\"  \n[1224,] \"India\" \"\"  \n[1225,] \"India\" \"\"  \n[1226,] \"India\" \"\"  \n[1227,] \"India\" \"\"  \n[1228,] \"India\" \"\"  \n[1229,] \"India\" \"\"  \n[1230,] \"India\" \"\"  \n[1231,] \"India\" \"\"  \n[1232,] \"India\" \"\"  \n[1233,] \"India\" \"\"  \n[1234,] \"India\" \"\"  \n[1235,] \"India\" \"\"  \n[1236,] \"India\" \"\"  \n[1237,] \"India\" \"\"  \n[1238,] \"India\" \"\"  \n[1239,] \"India\" \"\"  \n[1240,] \"India\" \"\"  \n[1241,] \"India\" \"\"  \n[1242,] \"India\" \"\"  \n[1243,] \"India\" \"\"  \n[1244,] \"India\" \"\"  \n[1245,] \"India\" \"\"  \n[1246,] \"India\" \"\"  \n[1247,] \"India\" \"\"  \n[1248,] \"India\" \"\"  \n[1249,] \"India\" \"\"  \n[1250,] \"India\" \"\"  \n[1251,] \"India\" \"\"  \n[1252,] \"India\" \"\"  \n[1253,] \"India\" \"\"  \n[1254,] \"India\" \"\"  \n[1255,] \"India\" \"\"  \n[1256,] \"India\" \"\"  \n[1257,] \"India\" \"\"  \n[1258,] \"India\" \"\"  \n[1259,] \"India\" \"\"  \n[1260,] \"India\" \"\"  \n[1261,] \"India\" \"\"  \n[1262,] \"India\" \"\"  \n[1263,] \"India\" \"\"  \n[1264,] \"India\" \"\"  \n[1265,] \"India\" \"\"  \n[1266,] \"India\" \"\"  \n[1267,] \"India\" \"\"  \n[1268,] \"India\" \"\"  \n[1269,] \"India\" \"\"  \n[1270,] \"India\" \"\"  \n[1271,] \"India\" \"\"  \n[1272,] \"India\" \"\"  \n[1273,] \"India\" \"\"  \n[1274,] \"India\" \"\"  \n[1275,] \"India\" \"\"  \n[1276,] \"India\" \"\"  \n[1277,] \"India\" \"\"  \n[1278,] \"India\" \"\"  \n[1279,] \"India\" \"\"  \n[1280,] \"India\" \"\"  \n[1281,] \"India\" \"\"  \n[1282,] \"India\" \"\"  \n[1283,] \"India\" \"\"  \n[1284,] \"India\" \"\"  \n[1285,] \"India\" \"\"  \n[1286,] \"India\" \"\"  \n[1287,] \"India\" \"\"  \n[1288,] \"India\" \"\"  \n[1289,] \"India\" \"\"  \n[1290,] \"India\" \"\"  \n[1291,] \"India\" \"\"  \n[1292,] \"India\" \"\"  \n[1293,] \"India\" \"\"  \n[1294,] \"India\" \"\"  \n[1295,] \"India\" \"\"  \n[1296,] \"India\" \"\"  \n[1297,] \"India\" \"\"  \n[1298,] \"India\" \"\"  \n[1299,] \"India\" \"\"  \n[1300,] \"India\" \"\"  \n[1301,] \"India\" \"\"  \n[1302,] \"India\" \"\"  \n[1303,] \"India\" \"\"  \n[1304,] \"India\" \"\"  \n[1305,] \"India\" \"\"  \n[1306,] \"India\" \"\"  \n[1307,] \"India\" \"\"  \n[1308,] \"India\" \"\"  \n[1309,] \"India\" \"\"  \n[1310,] \"India\" \"\"  \n[1311,] \"India\" \"\"  \n[1312,] \"India\" \"\"  \n[1313,] \"India\" \"\"  \n[1314,] \"India\" \"\"  \n[1315,] \"India\" \"\"  \n[1316,] \"India\" \"\"  \n[1317,] \"India\" \"\"  \n[1318,] \"India\" \"\"  \n[1319,] \"India\" \"\"  \n[1320,] \"India\" \"\"  \n[1321,] \"India\" \"\"  \n[1322,] \"India\" \"\"  \n[1323,] \"India\" \"\"  \n[1324,] \"India\" \"\"  \n[1325,] \"India\" \"\"  \n[1326,] \"India\" \"\"  \n[1327,] \"India\" \"\"  \n[1328,] \"India\" \"\"  \n[1329,] \"India\" \"\"  \n[1330,] \"India\" \"\"  \n[1331,] \"India\" \"\"  \n[1332,] \"India\" \"\"  \n[1333,] \"India\" \"\"  \n[1334,] \"India\" \"\"  \n[1335,] \"India\" \"\"  \n[1336,] \"India\" \"\"  \n[1337,] \"India\" \"\"  \n[1338,] \"India\" \"\"  \n[1339,] \"India\" \"\"  \n[1340,] \"India\" \"\"  \n[1341,] \"India\" \"\"  \n[1342,] \"India\" \"\"  \n[1343,] \"India\" \"\"  \n[1344,] \"India\" \"\"  \n[1345,] \"India\" \"\"  \n[1346,] \"India\" \"\"  \n[1347,] \"India\" \"\"  \n[1348,] \"India\" \"\"  \n[1349,] \"India\" \"\"  \n[1350,] \"India\" \"\"  \n[1351,] \"India\" \"\"  \n[1352,] \"India\" \"\"  \n[1353,] \"India\" \"\"  \n[1354,] \"India\" \"\"  \n[1355,] \"India\" \"\"  \n[1356,] \"India\" \"\"  \n[1357,] \"India\" \"\"  \n[1358,] \"India\" \"\"  \n[1359,] \"India\" \"\"  \n[1360,] \"India\" \"\"  \n[1361,] \"India\" \"\"  \n[1362,] \"India\" \"\"  \n[1363,] \"India\" \"\"  \n[1364,] \"India\" \"\"  \n[1365,] \"India\" \"\"  \n[1366,] \"India\" \"\"  \n[1367,] \"India\" \"\"  \n[1368,] \"India\" \"\"  \n[1369,] \"India\" \"\"  \n[1370,] \"India\" \"\"  \n[1371,] \"India\" \"\"  \n[1372,] \"India\" \"\"  \n[1373,] \"India\" \"\"  \n[1374,] \"India\" \"\"  \n[1375,] \"India\" \"\"  \n[1376,] \"India\" \"\"  \n[1377,] \"India\" \"\"  \n[1378,] \"India\" \"\"  \n[1379,] \"India\" \"\"  \n[1380,] \"India\" \"\"  \n[1381,] \"India\" \"\"  \n[1382,] \"India\" \"\"  \n[1383,] \"India\" \"\"  \n[1384,] \"India\" \"\"  \n[1385,] \"India\" \"\"  \n[1386,] \"India\" \"\"  \n[1387,] \"India\" \"\"  \n[1388,] \"India\" \"\"  \n[1389,] \"India\" \"\"  \n[1390,] \"India\" \"\"  \n[1391,] \"India\" \"\"  \n[1392,] \"India\" \"\"  \n[1393,] \"India\" \"\"  \n[1394,] \"India\" \"\"  \n[1395,] \"India\" \"\"  \n[1396,] \"India\" \"\"  \n[1397,] \"India\" \"\"  \n[1398,] \"India\" \"\"  \n[1399,] \"India\" \"\"  \n[1400,] \"India\" \"\"  \n[1401,] \"India\" \"\"  \n[1402,] \"India\" \"\"  \n[1403,] \"India\" \"\"  \n[1404,] \"India\" \"\"  \n[1405,] \"India\" \"\"  \n[1406,] \"India\" \"\"  \n[1407,] \"India\" \"\"  \n[1408,] \"India\" \"\"  \n[1409,] \"India\" \"\"  \n[1410,] \"India\" \"\"  \n[1411,] \"India\" \"\"  \n[1412,] \"India\" \"\"  \n[1413,] \"India\" \"\"  \n[1414,] \"India\" \"\"  \n[1415,] \"India\" \"\"  \n[1416,] \"India\" \"\"  \n[1417,] \"India\" \"\"  \n[1418,] \"India\" \"\"  \n[1419,] \"India\" \"\"  \n[1420,] \"India\" \"\"  \n[1421,] \"India\" \"\"  \n[1422,] \"India\" \"\"  \n[1423,] \"India\" \"\"  \n[1424,] \"India\" \"\"  \n[1425,] \"India\" \"\"  \n[1426,] \"India\" \"\"  \n[1427,] \"India\" \"\"  \n[1428,] \"India\" \"\"  \n[1429,] \"India\" \"\"  \n[1430,] \"India\" \"\"  \n[1431,] \"India\" \"\"  \n[1432,] \"India\" \"\"  \n[1433,] \"India\" \"\"  \n[1434,] \"India\" \"\"  \n[1435,] \"India\" \"\"  \n[1436,] \"India\" \"\"  \n[1437,] \"India\" \"\"  \n[1438,] \"India\" \"\"  \n[1439,] \"India\" \"\"  \n[1440,] \"India\" \"\"  \n[1441,] \"India\" \"\"  \n[1442,] \"India\" \"\"  \n[1443,] \"India\" \"\"  \n[1444,] \"India\" \"\"  \n[1445,] \"India\" \"\"  \n[1446,] \"India\" \"\"  \n[1447,] \"India\" \"\"  \n[1448,] \"India\" \"\"  \n[1449,] \"India\" \"\"  \n[1450,] \"India\" \"\"  \n[1451,] \"India\" \"\"  \n[1452,] \"India\" \"\"  \n[1453,] \"India\" \"\"  \n[1454,] \"India\" \"\"  \n[1455,] \"India\" \"\"  \n[1456,] \"India\" \"\"  \n[1457,] \"India\" \"\"  \n[1458,] \"India\" \"\"  \n[1459,] \"India\" \"\"  \n[1460,] \"India\" \"\"  \n[1461,] \"India\" \"\"  \n[1462,] \"India\" \"\"  \n[1463,] \"India\" \"\"  \n[1464,] \"India\" \"\"  \n[1465,] \"India\" \"\"  \n[1466,] \"India\" \"\"  \n[1467,] \"India\" \"\"  \n[1468,] \"India\" \"\"  \n[1469,] \"India\" \"\"  \n[1470,] \"India\" \"\"  \n[1471,] \"India\" \"\"  \n[1472,] \"India\" \"\"  \n[1473,] \"India\" \"\"  \n[1474,] \"India\" \"\"  \n[1475,] \"India\" \"\"  \n[1476,] \"India\" \"\"  \n[1477,] \"India\" \"\"  \n[1478,] \"India\" \"\"  \n[1479,] \"India\" \"\"  \n[1480,] \"India\" \"\"  \n[1481,] \"India\" \"\"  \n[1482,] \"India\" \"\"  \n[1483,] \"India\" \"\"  \n[1484,] \"India\" \"\"  \n[1485,] \"India\" \"\"  \n[1486,] \"India\" \"\"  \n[1487,] \"India\" \"\"  \n[1488,] \"India\" \"\"  \n[1489,] \"India\" \"\"  \n[1490,] \"India\" \"\"  \n[1491,] \"India\" \"\"  \n[1492,] \"India\" \"\"  \n[1493,] \"India\" \"\"  \n[1494,] \"India\" \"\"  \n[1495,] \"India\" \"\"  \n[1496,] \"India\" \"\"  \n[1497,] \"India\" \"\"  \n[1498,] \"India\" \"\"  \n[1499,] \"India\" \"\"  \n[1500,] \"India\" \"\"  \n[1501,] \"India\" \"\"  \n[1502,] \"India\" \"\"  \n[1503,] \"India\" \"\"  \n[1504,] \"India\" \"\"  \n[1505,] \"India\" \"\"  \n[1506,] \"India\" \"\"  \n[1507,] \"India\" \"\"  \n[1508,] \"India\" \"\"  \n[1509,] \"India\" \"\"  \n[1510,] \"India\" \"\"  \n[1511,] \"India\" \"\"  \n[1512,] \"India\" \"\"  \n[1513,] \"India\" \"\"  \n[1514,] \"India\" \"\"  \n[1515,] \"India\" \"\"  \n[1516,] \"India\" \"\"  \n[1517,] \"India\" \"\"  \n[1518,] \"India\" \"\"  \n[1519,] \"India\" \"\"  \n[1520,] \"India\" \"\"  \n[1521,] \"India\" \"\"  \n[1522,] \"India\" \"\"  \n[1523,] \"India\" \"\"  \n[1524,] \"India\" \"\"  \n[1525,] \"India\" \"\"  \n[1526,] \"India\" \"\"  \n[1527,] \"India\" \"\"  \n[1528,] \"India\" \"\"  \n[1529,] \"India\" \"\"  \n[1530,] \"India\" \"\"  \n[1531,] \"India\" \"\"  \n[1532,] \"India\" \"\"  \n[1533,] \"India\" \"\"  \n[1534,] \"India\" \"\"  \n[1535,] \"India\" \"\"  \n[1536,] \"India\" \"\"  \n[1537,] \"India\" \"\"  \n[1538,] \"India\" \"\"  \n[1539,] \"India\" \"\"  \n[1540,] \"India\" \"\"  \n[1541,] \"India\" \"\"  \n[1542,] \"India\" \"\"  \n[1543,] \"India\" \"\"  \n[1544,] \"India\" \"\"  \n[1545,] \"India\" \"\"  \n[1546,] \"India\" \"\"  \n[1547,] \"India\" \"\"  \n[1548,] \"India\" \"\"  \n[1549,] \"India\" \"\"  \n[1550,] \"India\" \"\"  \n[1551,] \"India\" \"\"  \n[1552,] \"India\" \"\"  \n[1553,] \"India\" \"\"  \n[1554,] \"India\" \"\"  \n[1555,] \"India\" \"\"  \n[1556,] \"India\" \"\"  \n[1557,] \"India\" \"\"  \n[1558,] \"India\" \"\"  \n[1559,] \"India\" \"\"  \n[1560,] \"India\" \"\"  \n[1561,] \"India\" \"\"  \n[1562,] \"India\" \"\"  \n[1563,] \"India\" \"\"  \n[1564,] \"India\" \"\"  \n[1565,] \"India\" \"\"  \n[1566,] \"India\" \"\"  \n[1567,] \"India\" \"\"  \n[1568,] \"India\" \"\"  \n[1569,] \"India\" \"\"  \n[1570,] \"India\" \"\"  \n[1571,] \"India\" \"\"  \n[1572,] \"India\" \"\"  \n[1573,] \"India\" \"\"  \n[1574,] \"India\" \"\"  \n[1575,] \"India\" \"\"  \n[1576,] \"India\" \"\"  \n[1577,] \"India\" \"\"  \n[1578,] \"India\" \"\"  \n[1579,] \"India\" \"\"  \n[1580,] \"India\" \"\"  \n[1581,] \"India\" \"\"  \n[1582,] \"India\" \"\"  \n[1583,] \"India\" \"\"  \n[1584,] \"India\" \"\"  \n[1585,] \"India\" \"\"  \n[1586,] \"India\" \"\"  \n[1587,] \"India\" \"\"  \n[1588,] \"India\" \"\"  \n[1589,] \"India\" \"\"  \n[1590,] \"India\" \"\"  \n[1591,] \"India\" \"\"  \n[1592,] \"India\" \"\"  \n[1593,] \"India\" \"\"  \n[1594,] \"India\" \"\"  \n[1595,] \"India\" \"\"  \n[1596,] \"India\" \"\"  \n[1597,] \"India\" \"\"  \n[1598,] \"India\" \"\"  \n[1599,] \"India\" \"\"  \n[1600,] \"India\" \"\"  \n[1601,] \"India\" \"\"  \n[1602,] \"India\" \"\"  \n[1603,] \"India\" \"\"  \n[1604,] \"India\" \"\"  \n[1605,] \"India\" \"\"  \n[1606,] \"India\" \"\"  \n[1607,] \"India\" \"\"  \n[1608,] \"India\" \"\"  \n[1609,] \"India\" \"\"  \n[1610,] \"India\" \"\"  \n[1611,] \"India\" \"\"  \n[1612,] \"India\" \"\"  \n[1613,] \"India\" \"\"  \n[1614,] \"India\" \"\"  \n[1615,] \"India\" \"\"  \n[1616,] \"India\" \"\"  \n[1617,] \"India\" \"\"  \n[1618,] \"India\" \"\"  \n[1619,] \"India\" \"\"  \n[1620,] \"India\" \"\"  \n[1621,] \"India\" \"\"  \n[1622,] \"India\" \"\"  \n[1623,] \"India\" \"\"  \n[1624,] \"India\" \"\"  \n[1625,] \"India\" \"\"  \n[1626,] \"India\" \"\"  \n[1627,] \"India\" \"\"  \n[1628,] \"India\" \"\"  \n[1629,] \"India\" \"\"  \n[1630,] \"India\" \"\"  \n[1631,] \"India\" \"\"  \n[1632,] \"India\" \"\"  \n[1633,] \"India\" \"\"  \n[1634,] \"India\" \"\"  \n[1635,] \"India\" \"\"  \n[1636,] \"India\" \"\"  \n[1637,] \"India\" \"\"  \n[1638,] \"India\" \"\"  \n[1639,] \"India\" \"\"  \n[1640,] \"India\" \"\"  \n[1641,] \"India\" \"\"  \n[1642,] \"India\" \"\"  \n[1643,] \"India\" \"\"  \n[1644,] \"India\" \"\"  \n[1645,] \"India\" \"\"  \n[1646,] \"India\" \"\"  \n[1647,] \"India\" \"\"  \n[1648,] \"India\" \"\"  \n[1649,] \"India\" \"\"  \n[1650,] \"India\" \"\"  \n[1651,] \"India\" \"\"  \n[1652,] \"India\" \"\"  \n[1653,] \"India\" \"\"  \n[1654,] \"India\" \"\"  \n[1655,] \"India\" \"\"  \n[1656,] \"India\" \"\"  \n[1657,] \"India\" \"\"  \n[1658,] \"India\" \"\"  \n[1659,] \"India\" \"\"  \n[1660,] \"India\" \"\"  \n[1661,] \"India\" \"\"  \n[1662,] \"India\" \"\"  \n[1663,] \"India\" \"\"  \n[1664,] \"India\" \"\"  \n[1665,] \"India\" \"\"  \n[1666,] \"India\" \"\"  \n[1667,] \"India\" \"\"  \n[1668,] \"India\" \"\"  \n[1669,] \"India\" \"\"  \n[1670,] \"India\" \"\"  \n[1671,] \"India\" \"\"  \n[1672,] \"India\" \"\"  \n[1673,] \"India\" \"\"  \n[1674,] \"India\" \"\"  \n[1675,] \"India\" \"\"  \n[1676,] \"India\" \"\"  \n[1677,] \"India\" \"\"  \n[1678,] \"India\" \"\"  \n[1679,] \"India\" \"\"  \n[1680,] \"India\" \"\"  \n[1681,] \"India\" \"\"  \n[1682,] \"India\" \"\"  \n[1683,] \"India\" \"\"  \n[1684,] \"India\" \"\"  \n[1685,] \"India\" \"\"  \n[1686,] \"India\" \"\"  \n[1687,] \"India\" \"\"  \n[1688,] \"India\" \"\"  \n[1689,] \"India\" \"\"  \n[1690,] \"India\" \"\"  \n[1691,] \"India\" \"\"  \n[1692,] \"India\" \"\"  \n[1693,] \"India\" \"\"  \n[1694,] \"India\" \"\"  \n[1695,] \"India\" \"\"  \n[1696,] \"India\" \"\"  \n[1697,] \"India\" \"\"  \n[1698,] \"India\" \"\"  \n[1699,] \"India\" \"\"  \n[1700,] \"India\" \"\"  \n[1701,] \"India\" \"\"  \n[1702,] \"India\" \"\"  \n[1703,] \"India\" \"\"  \n[1704,] \"India\" \"\"  \n[1705,] \"India\" \"\"  \n[1706,] \"India\" \"\"  \n[1707,] \"India\" \"\"  \n[1708,] \"India\" \"\"  \n[1709,] \"India\" \"\"  \n[1710,] \"India\" \"\"  \n[1711,] \"India\" \"\"  \n[1712,] \"India\" \"\"  \n[1713,] \"India\" \"\"  \n[1714,] \"India\" \"\"  \n[1715,] \"India\" \"\"  \n[1716,] \"India\" \"\"  \n[1717,] \"India\" \"\"  \n[1718,] \"India\" \"\"  \n[1719,] \"India\" \"\"  \n[1720,] \"India\" \"\"  \n[1721,] \"India\" \"\"  \n[1722,] \"India\" \"\"  \n[1723,] \"India\" \"\"  \n[1724,] \"India\" \"\"  \n[1725,] \"India\" \"\"  \n[1726,] \"India\" \"\"  \n[1727,] \"India\" \"\"  \n[1728,] \"India\" \"\"  \n[1729,] \"India\" \"\"  \n[1730,] \"India\" \"\"  \n[1731,] \"India\" \"\"  \n[1732,] \"India\" \"\"  \n[1733,] \"India\" \"\"  \n[1734,] \"India\" \"\"  \n[1735,] \"India\" \"\"  \n[1736,] \"India\" \"\"  \n[1737,] \"India\" \"\"  \n[1738,] \"India\" \"\"  \n[1739,] \"India\" \"\"  \n[1740,] \"India\" \"\"  \n[1741,] \"India\" \"\"  \n[1742,] \"India\" \"\"  \n[1743,] \"India\" \"\"  \n[1744,] \"India\" \"\"  \n[1745,] \"India\" \"\"  \n[1746,] \"India\" \"\"  \n[1747,] \"India\" \"\"  \n[1748,] \"India\" \"\"  \n[1749,] \"India\" \"\"  \n[1750,] \"India\" \"\"  \n[1751,] \"India\" \"\"  \n[1752,] \"India\" \"\"  \n[1753,] \"India\" \"\"  \n[1754,] \"India\" \"\"  \n[1755,] \"India\" \"\"  \n[1756,] \"India\" \"\"  \n[1757,] \"India\" \"\"  \n[1758,] \"India\" \"\"  \n[1759,] \"India\" \"\"  \n[1760,] \"India\" \"\"  \n[1761,] \"India\" \"\"  \n[1762,] \"India\" \"\"  \n[1763,] \"India\" \"\"  \n[1764,] \"India\" \"\"  \n[1765,] \"India\" \"\"  \n[1766,] \"India\" \"\"  \n[1767,] \"India\" \"\"  \n[1768,] \"India\" \"\"  \n[1769,] \"India\" \"\"  \n[1770,] \"India\" \"\"  \n[1771,] \"India\" \"\"  \n[1772,] \"India\" \"\"  \n[1773,] \"India\" \"\"  \n[1774,] \"India\" \"\"  \n[1775,] \"India\" \"\"  \n[1776,] \"India\" \"\"  \n[1777,] \"India\" \"\"  \n[1778,] \"India\" \"\"  \n[1779,] \"India\" \"\"  \n[1780,] \"India\" \"\"  \n[1781,] \"India\" \"\"  \n[1782,] \"India\" \"\"  \n[1783,] \"India\" \"\"  \n[1784,] \"India\" \"\"  \n[1785,] \"India\" \"\"  \n[1786,] \"India\" \"\"  \n[1787,] \"India\" \"\"  \n[1788,] \"India\" \"\"  \n[1789,] \"India\" \"\"  \n[1790,] \"India\" \"\"  \n[1791,] \"India\" \"\"  \n[1792,] \"India\" \"\"  \n[1793,] \"India\" \"\"  \n[1794,] \"India\" \"\"  \n[1795,] \"India\" \"\"  \n[1796,] \"India\" \"\"  \n[1797,] \"India\" \"\"  \n[1798,] \"India\" \"\"  \n[1799,] \"India\" \"\"  \n[1800,] \"India\" \"\"  \n[1801,] \"India\" \"\"  \n[1802,] \"India\" \"\"  \n[1803,] \"India\" \"\"  \n[1804,] \"India\" \"\"  \n[1805,] \"India\" \"\"  \n[1806,] \"India\" \"\"  \n[1807,] \"India\" \"\"  \n[1808,] \"India\" \"\"  \n[1809,] \"India\" \"\"  \n[1810,] \"India\" \"\"  \n[1811,] \"India\" \"\"  \n[1812,] \"India\" \"\"  \n[1813,] \"India\" \"\"  \n[1814,] \"India\" \"\"  \n[1815,] \"India\" \"\"  \n[1816,] \"India\" \"\"  \n[1817,] \"India\" \"\"  \n[1818,] \"India\" \"\"  \n[1819,] \"India\" \"\"  \n[1820,] \"India\" \"\"  \n[1821,] \"India\" \"\"  \n[1822,] \"India\" \"\"  \n[1823,] \"India\" \"\"  \n[1824,] \"India\" \"\"  \n[1825,] \"India\" \"\"  \n[1826,] \"India\" \"\"  \n[1827,] \"India\" \"\"  \n[1828,] \"India\" \"\"  \n[1829,] \"India\" \"\"  \n[1830,] \"India\" \"\"  \n[1831,] \"India\" \"\"  \n[1832,] \"India\" \"\"  \n[1833,] \"India\" \"\"  \n[1834,] \"India\" \"\"  \n[1835,] \"India\" \"\"  \n[1836,] \"India\" \"\"  \n[1837,] \"India\" \"\"  \n[1838,] \"India\" \"\"  \n[1839,] \"India\" \"\"  \n[1840,] \"India\" \"\"  \n[1841,] \"India\" \"\"  \n[1842,] \"India\" \"\"  \n[1843,] \"India\" \"\"  \n[1844,] \"India\" \"\"  \n[1845,] \"India\" \"\"  \n[1846,] \"India\" \"\"  \n[1847,] \"India\" \"\"  \n[1848,] \"India\" \"\"  \n[1849,] \"India\" \"\"  \n[1850,] \"India\" \"\"  \n[1851,] \"India\" \"\"  \n[1852,] \"India\" \"\"  \n[1853,] \"India\" \"\"  \n[1854,] \"India\" \"\"  \n[1855,] \"India\" \"\"  \n[1856,] \"India\" \"\"  \n[1857,] \"India\" \"\"  \n[1858,] \"India\" \"\"  \n[1859,] \"India\" \"\"  \n[1860,] \"India\" \"\"  \n[1861,] \"India\" \"\"  \n[1862,] \"India\" \"\"  \n[1863,] \"India\" \"\"  \n[1864,] \"India\" \"\"  \n[1865,] \"India\" \"\"  \n[1866,] \"India\" \"\"  \n[1867,] \"India\" \"\"  \n[1868,] \"India\" \"\"  \n[1869,] \"India\" \"\"  \n[1870,] \"India\" \"\"  \n[1871,] \"India\" \"\"  \n[1872,] \"India\" \"\"  \n[1873,] \"India\" \"\"  \n[1874,] \"India\" \"\"  \n[1875,] \"India\" \"\"  \n[1876,] \"India\" \"\"  \n[1877,] \"India\" \"\"  \n[1878,] \"India\" \"\"  \n[1879,] \"India\" \"\"  \n[1880,] \"India\" \"\"  \n[1881,] \"India\" \"\"  \n[1882,] \"India\" \"\"  \n[1883,] \"India\" \"\"  \n[1884,] \"India\" \"\"  \n[1885,] \"India\" \"\"  \n[1886,] \"India\" \"\"  \n[1887,] \"India\" \"\"  \n[1888,] \"India\" \"\"  \n[1889,] \"India\" \"\"  \n[1890,] \"India\" \"\"  \n[1891,] \"India\" \"\"  \n[1892,] \"India\" \"\"  \n[1893,] \"India\" \"\"  \n[1894,] \"India\" \"\"  \n[1895,] \"India\" \"\"  \n[1896,] \"India\" \"\"  \n[1897,] \"India\" \"\"  \n[1898,] \"India\" \"\"  \n[1899,] \"India\" \"\"  \n[1900,] \"India\" \"\"  \n[1901,] \"India\" \"\"  \n[1902,] \"India\" \"\"  \n[1903,] \"India\" \"\"  \n[1904,] \"India\" \"\"  \n[1905,] \"India\" \"\"  \n[1906,] \"India\" \"\"  \n[1907,] \"India\" \"\"  \n[1908,] \"India\" \"\"  \n[1909,] \"India\" \"\"  \n[1910,] \"India\" \"\"  \n[1911,] \"India\" \"\"  \n[1912,] \"India\" \"\"  \n[1913,] \"India\" \"\"  \n[1914,] \"India\" \"\"  \n[1915,] \"India\" \"\"  \n[1916,] \"India\" \"\"  \n[1917,] \"India\" \"\"  \n[1918,] \"India\" \"\"  \n[1919,] \"India\" \"\"  \n[1920,] \"India\" \"\"  \n[1921,] \"India\" \"\"  \n[1922,] \"India\" \"\"  \n[1923,] \"India\" \"\"  \n[1924,] \"India\" \"\"  \n[1925,] \"India\" \"\"  \n[1926,] \"India\" \"\"  \n[1927,] \"India\" \"\"  \n[1928,] \"India\" \"\"  \n[1929,] \"India\" \"\"  \n[1930,] \"India\" \"\"  \n[1931,] \"India\" \"\"  \n[1932,] \"India\" \"\"  \n[1933,] \"India\" \"\"  \n[1934,] \"India\" \"\"  \n[1935,] \"India\" \"\"  \n[1936,] \"India\" \"\"  \n[1937,] \"India\" \"\"  \n[1938,] \"India\" \"\"  \n[1939,] \"India\" \"\"  \n[1940,] \"India\" \"\"  \n[1941,] \"India\" \"\"  \n[1942,] \"India\" \"\"  \n[1943,] \"India\" \"\"  \n[1944,] \"India\" \"\"  \n[1945,] \"India\" \"\"  \n[1946,] \"India\" \"\"  \n[1947,] \"India\" \"\"  \n[1948,] \"India\" \"\"  \n[1949,] \"India\" \"\"  \n[1950,] \"India\" \"\"  \n[1951,] \"India\" \"\"  \n[1952,] \"India\" \"\"  \n[1953,] \"India\" \"\"  \n[1954,] \"India\" \"\"  \n[1955,] \"India\" \"\"  \n[1956,] \"India\" \"\"  \n[1957,] \"India\" \"\"  \n[1958,] \"India\" \"\"  \n[1959,] \"India\" \"\"  \n[1960,] \"India\" \"\"  \n[1961,] \"India\" \"\"  \n[1962,] \"India\" \"\"  \n[1963,] \"India\" \"\"  \n[1964,] \"India\" \"\"  \n[1965,] \"India\" \"\"  \n[1966,] \"India\" \"\"  \n[1967,] \"India\" \"\"  \n[1968,] \"India\" \"\"  \n[1969,] \"India\" \"\"  \n[1970,] \"India\" \"\"  \n[1971,] \"India\" \"\"  \n[1972,] \"India\" \"\"  \n[1973,] \"India\" \"\"  \n[1974,] \"India\" \"\"  \n[1975,] \"India\" \"\"  \n[1976,] \"India\" \"\"  \n[1977,] \"India\" \"\"  \n[1978,] \"India\" \"\"  \n[1979,] \"India\" \"\"  \n[1980,] \"India\" \"\"  \n[1981,] \"India\" \"\"  \n[1982,] \"India\" \"\"  \n[1983,] \"India\" \"\"  \n[1984,] \"India\" \"\"  \n[1985,] \"India\" \"\"  \n[1986,] \"India\" \"\"  \n[1987,] \"India\" \"\"  \n[1988,] \"India\" \"\"  \n[1989,] \"India\" \"\"  \n[1990,] \"India\" \"\"  \n[1991,] \"India\" \"\"  \n[1992,] \"India\" \"\"  \n[1993,] \"India\" \"\"  \n[1994,] \"India\" \"\"  \n[1995,] \"India\" \"\"  \n[1996,] \"India\" \"\"  \n[1997,] \"India\" \"\"  \n[1998,] \"India\" \"\"  \n[1999,] \"India\" \"\"  \n[2000,] \"India\" \"\"  \n[2001,] \"India\" \"\"  \n[2002,] \"India\" \"\"  \n[2003,] \"India\" \"\"  \n[2004,] \"India\" \"\"  \n[2005,] \"India\" \"\"  \n[2006,] \"India\" \"\"  \n[2007,] \"India\" \"\"  \n[2008,] \"India\" \"\"  \n[2009,] \"India\" \"\"  \n[2010,] \"India\" \"\"  \n[2011,] \"India\" \"\"  \n[2012,] \"India\" \"\"  \n[2013,] \"India\" \"\"  \n[2014,] \"India\" \"\"  \n[2015,] \"India\" \"\"  \n[2016,] \"India\" \"\"  \n[2017,] \"India\" \"\"  \n[2018,] \"India\" \"\"  \n[2019,] \"India\" \"\"  \n[2020,] \"India\" \"\"  \n[2021,] \"India\" \"\"  \n[2022,] \"India\" \"\"  \n[2023,] \"India\" \"\"  \n[2024,] \"India\" \"\"  \n[2025,] \"India\" \"\"  \n[2026,] \"India\" \"\"  \n[2027,] \"India\" \"\"  \n[2028,] \"India\" \"\"  \n[2029,] \"India\" \"\"  \n[2030,] \"India\" \"\"  \n[2031,] \"India\" \"\"  \n[2032,] \"India\" \"\"  \n[2033,] \"India\" \"\"  \n[2034,] \"India\" \"\"  \n[2035,] \"India\" \"\"  \n[2036,] \"India\" \"\"  \n[2037,] \"India\" \"\"  \n[2038,] \"India\" \"\"  \n[2039,] \"India\" \"\"  \n[2040,] \"India\" \"\"  \n[2041,] \"India\" \"\"  \n[2042,] \"India\" \"\"  \n[2043,] \"India\" \"\"  \n[2044,] \"India\" \"\"  \n[2045,] \"India\" \"\"  \n[2046,] \"India\" \"\"  \n[2047,] \"India\" \"\"  \n[2048,] \"India\" \"\"  \n[2049,] \"India\" \"\"  \n[2050,] \"India\" \"\"  \n[2051,] \"India\" \"\"  \n[2052,] \"India\" \"\"  \n[2053,] \"India\" \"\"  \n[2054,] \"India\" \"\"  \n[2055,] \"India\" \"\"  \n[2056,] \"India\" \"\"  \n[2057,] \"India\" \"\"  \n[2058,] \"India\" \"\"  \n[2059,] \"India\" \"\"  \n[2060,] \"India\" \"\"  \n[2061,] \"India\" \"\"  \n[2062,] \"India\" \"\"  \n[2063,] \"India\" \"\"  \n[2064,] \"India\" \"\"  \n[2065,] \"India\" \"\"  \n[2066,] \"India\" \"\"  \n[2067,] \"India\" \"\"  \n[2068,] \"India\" \"\"  \n[2069,] \"India\" \"\"  \n[2070,] \"India\" \"\"  \n[2071,] \"India\" \"\"  \n[2072,] \"India\" \"\"  \n[2073,] \"India\" \"\"  \n[2074,] \"India\" \"\"  \n[2075,] \"India\" \"\"  \n[2076,] \"India\" \"\"  \n[2077,] \"India\" \"\"  \n[2078,] \"India\" \"\"  \n[2079,] \"India\" \"\"  \n[2080,] \"India\" \"\"  \n[2081,] \"India\" \"\"  \n[2082,] \"India\" \"\"  \n[2083,] \"India\" \"\"  \n[2084,] \"India\" \"\"  \n[2085,] \"India\" \"\"  \n[2086,] \"India\" \"\"  \n[2087,] \"India\" \"\"  \n[2088,] \"India\" \"\"  \n[2089,] \"India\" \"\"  \n[2090,] \"India\" \"\"  \n[2091,] \"India\" \"\"  \n[2092,] \"India\" \"\"  \n[2093,] \"India\" \"\"  \n[2094,] \"India\" \"\"  \n[2095,] \"India\" \"\"  \n[2096,] \"India\" \"\"  \n[2097,] \"India\" \"\"  \n[2098,] \"India\" \"\"  \n[2099,] \"India\" \"\"  \n[2100,] \"India\" \"\"  \n[2101,] \"India\" \"\"  \n[2102,] \"India\" \"\"  \n[2103,] \"India\" \"\"  \n[2104,] \"India\" \"\"  \n[2105,] \"India\" \"\"  \n[2106,] \"India\" \"\"  \n[2107,] \"India\" \"\"  \n[2108,] \"India\" \"\"  \n[2109,] \"India\" \"\"  \n[2110,] \"India\" \"\"  \n[2111,] \"India\" \"\"  \n[2112,] \"India\" \"\"  \n[2113,] \"India\" \"\"  \n[2114,] \"India\" \"\"  \n[2115,] \"India\" \"\"  \n[2116,] \"India\" \"\"  \n[2117,] \"India\" \"\"  \n[2118,] \"India\" \"\"  \n[2119,] \"India\" \"\"  \n[2120,] \"India\" \"\"  \n[2121,] \"India\" \"\"  \n[2122,] \"India\" \"\"  \n[2123,] \"India\" \"\"  \n[2124,] \"India\" \"\"  \n[2125,] \"India\" \"\"  \n[2126,] \"India\" \"\"  \n[2127,] \"India\" \"\"  \n[2128,] \"India\" \"\"  \n[2129,] \"India\" \"\"  \n[2130,] \"India\" \"\"  \n[2131,] \"India\" \"\"  \n[2132,] \"India\" \"\"  \n[2133,] \"India\" \"\"  \n[2134,] \"India\" \"\"  \n[2135,] \"India\" \"\"  \n[2136,] \"India\" \"\"  \n[2137,] \"India\" \"\"  \n[2138,] \"India\" \"\"  \n[2139,] \"India\" \"\"  \n[2140,] \"India\" \"\"  \n[2141,] \"India\" \"\"  \n[2142,] \"India\" \"\"  \n[2143,] \"India\" \"\"  \n[2144,] \"India\" \"\"  \n[2145,] \"India\" \"\"  \n[2146,] \"India\" \"\"  \n[2147,] \"India\" \"\"  \n[2148,] \"India\" \"\"  \n[2149,] \"India\" \"\"  \n[2150,] \"India\" \"\"  \n[2151,] \"India\" \"\"  \n[2152,] \"India\" \"\"  \n[2153,] \"India\" \"\"  \n[2154,] \"India\" \"\"  \n[2155,] \"India\" \"\"  \n[2156,] \"India\" \"\"  \n[2157,] \"India\" \"\"  \n[2158,] \"India\" \"\"  \n[2159,] \"India\" \"\"  \n[2160,] \"India\" \"\"  \n[2161,] \"India\" \"\"  \n[2162,] \"India\" \"\"  \n[2163,] \"India\" \"\"  \n[2164,] \"India\" \"\"  \n[2165,] \"India\" \"\"  \n[2166,] \"India\" \"\"  \n[2167,] \"India\" \"\"  \n[2168,] \"India\" \"\"  \n[2169,] \"India\" \"\"  \n[2170,] \"India\" \"\"  \n[2171,] \"India\" \"\"  \n[2172,] \"India\" \"\"  \n[2173,] \"India\" \"\"  \n[2174,] \"India\" \"\"  \n[2175,] \"India\" \"\"  \n[2176,] \"India\" \"\"  \n[2177,] \"India\" \"\"  \n[2178,] \"India\" \"\"  \n[2179,] \"India\" \"\"  \n[2180,] \"India\" \"\"  \n[2181,] \"India\" \"\"  \n[2182,] \"India\" \"\"  \n[2183,] \"India\" \"\"  \n[2184,] \"India\" \"\"  \n[2185,] \"India\" \"\"  \n[2186,] \"India\" \"\"  \n[2187,] \"India\" \"\"  \n[2188,] \"India\" \"\"  \n[2189,] \"India\" \"\"  \n[2190,] \"India\" \"\"  \n[2191,] \"India\" \"\"  \n[2192,] \"India\" \"\"  \n[2193,] \"India\" \"\"  \n[2194,] \"India\" \"\"  \n[2195,] \"India\" \"\"  \n[2196,] \"India\" \"\"  \n[2197,] \"India\" \"\"  \n[2198,] \"India\" \"\"  \n[2199,] \"India\" \"\"  \n[2200,] \"India\" \"\"  \n[2201,] \"India\" \"\"  \n[2202,] \"India\" \"\"  \n[2203,] \"India\" \"\"  \n[2204,] \"India\" \"\"  \n[2205,] \"India\" \"\"  \n[2206,] \"India\" \"\"  \n[2207,] \"India\" \"\"  \n[2208,] \"India\" \"\"  \n[2209,] \"India\" \"\"  \n[2210,] \"India\" \"\"  \n[2211,] \"India\" \"\"  \n[2212,] \"India\" \"\"  \n[2213,] \"India\" \"\"  \n[2214,] \"India\" \"\"  \n[2215,] \"India\" \"\"  \n[2216,] \"India\" \"\"  \n[2217,] \"India\" \"\"  \n[2218,] \"India\" \"\"  \n[2219,] \"India\" \"\"  \n[2220,] \"India\" \"\"  \n[2221,] \"India\" \"\"  \n[2222,] \"India\" \"\"  \n[2223,] \"India\" \"\"  \n[2224,] \"India\" \"\"  \n[2225,] \"India\" \"\"  \n[2226,] \"India\" \"\"  \n[2227,] \"India\" \"\"  \n[2228,] \"India\" \"\"  \n[2229,] \"India\" \"\"  \n[2230,] \"India\" \"\"  \n[2231,] \"India\" \"\"  \n[2232,] \"India\" \"\"  \n[2233,] \"India\" \"\"  \n[2234,] \"India\" \"\"  \n[2235,] \"India\" \"\"  \n[2236,] \"India\" \"\"  \n[2237,] \"India\" \"\"  \n[2238,] \"India\" \"\"  \n[2239,] \"India\" \"\"  \n[2240,] \"India\" \"\"  \n[2241,] \"India\" \"\"  \n[2242,] \"India\" \"\"  \n[2243,] \"India\" \"\"  \n[2244,] \"India\" \"\"  \n[2245,] \"India\" \"\"  \n[2246,] \"India\" \"\"  \n[2247,] \"India\" \"\"  \n[2248,] \"India\" \"\"  \n[2249,] \"India\" \"\"  \n[2250,] \"India\" \"\"  \n[2251,] \"India\" \"\"  \n[2252,] \"India\" \"\"  \n[2253,] \"India\" \"\"  \n[2254,] \"India\" \"\"  \n[2255,] \"India\" \"\"  \n[2256,] \"India\" \"\"  \n[2257,] \"India\" \"\"  \n[2258,] \"India\" \"\"  \n[2259,] \"India\" \"\"  \n[2260,] \"India\" \"\"  \n[2261,] \"India\" \"\"  \n[2262,] \"India\" \"\"  \n[2263,] \"India\" \"\"  \n[2264,] \"India\" \"\"  \n[2265,] \"India\" \"\"  \n[2266,] \"India\" \"\"  \n[2267,] \"India\" \"\"  \n[2268,] \"India\" \"\"  \n[2269,] \"India\" \"\"  \n[2270,] \"India\" \"\"  \n[2271,] \"India\" \"\"  \n[2272,] \"India\" \"\"  \n[2273,] \"India\" \"\"  \n[2274,] \"India\" \"\"  \n[2275,] \"India\" \"\"  \n[2276,] \"India\" \"\"  \n[2277,] \"India\" \"\"  \n[2278,] \"India\" \"\"  \n[2279,] \"India\" \"\"  \n[2280,] \"India\" \"\"  \n[2281,] \"India\" \"\"  \n[2282,] \"India\" \"\"  \n[2283,] \"India\" \"\"  \n[2284,] \"India\" \"\"  \n[2285,] \"India\" \"\"  \n[2286,] \"India\" \"\"  \n[2287,] \"India\" \"\"  \n[2288,] \"India\" \"\"  \n[2289,] \"India\" \"\"  \n[2290,] \"India\" \"\"  \n[2291,] \"India\" \"\"  \n[2292,] \"India\" \"\"  \n[2293,] \"India\" \"\"  \n[2294,] \"India\" \"\"  \n[2295,] \"India\" \"\"  \n[2296,] \"India\" \"\"  \n[2297,] \"India\" \"\"  \n[2298,] \"India\" \"\"  \n[2299,] \"India\" \"\"  \n[2300,] \"India\" \"\"  \n[2301,] \"India\" \"\"  \n[2302,] \"India\" \"\"  \n[2303,] \"India\" \"\"  \n[2304,] \"India\" \"\"  \n[2305,] \"India\" \"\"  \n[2306,] \"India\" \"\"  \n[2307,] \"India\" \"\"  \n[2308,] \"India\" \"\"  \n[2309,] \"India\" \"\"  \n[2310,] \"India\" \"\"  \n[2311,] \"India\" \"\"  \n[2312,] \"India\" \"\"  \n[2313,] \"India\" \"\"  \n[2314,] \"India\" \"\"  \n[2315,] \"India\" \"\"  \n[2316,] \"India\" \"\"  \n[2317,] \"India\" \"\"  \n[2318,] \"India\" \"\"  \n[2319,] \"India\" \"\"  \n[2320,] \"India\" \"\"  \n[2321,] \"India\" \"\"  \n[2322,] \"India\" \"\"  \n[2323,] \"India\" \"\"  \n[2324,] \"India\" \"\"  \n[2325,] \"India\" \"\"  \n[2326,] \"India\" \"\"  \n[2327,] \"India\" \"\"  \n[2328,] \"India\" \"\"  \n[2329,] \"India\" \"\"  \n[2330,] \"India\" \"\"  \n[2331,] \"India\" \"\"  \n[2332,] \"India\" \"\"  \n[2333,] \"India\" \"\"  \n[2334,] \"India\" \"\"  \n[2335,] \"India\" \"\"  \n[2336,] \"India\" \"\"  \n[2337,] \"India\" \"\"  \n[2338,] \"India\" \"\"  \n[2339,] \"India\" \"\"  \n[2340,] \"India\" \"\"  \n[2341,] \"India\" \"\"  \n[2342,] \"India\" \"\"  \n[2343,] \"India\" \"\"  \n[2344,] \"India\" \"\"  \n[2345,] \"India\" \"\"  \n[2346,] \"India\" \"\"  \n[2347,] \"India\" \"\"  \n[2348,] \"India\" \"\"  \n[2349,] \"India\" \"\"  \n[2350,] \"India\" \"\"  \n[2351,] \"India\" \"\"  \n[2352,] \"India\" \"\"  \n[2353,] \"India\" \"\"  \n[2354,] \"India\" \"\"  \n[2355,] \"India\" \"\"  \n[2356,] \"India\" \"\"  \n[2357,] \"India\" \"\"  \n[2358,] \"India\" \"\"  \n[2359,] \"India\" \"\"  \n[2360,] \"India\" \"\"  \n[2361,] \"India\" \"\"  \n[2362,] \"India\" \"\"  \n[2363,] \"India\" \"\"  \n[2364,] \"India\" \"\"  \n[2365,] \"India\" \"\"  \n[2366,] \"India\" \"\"  \n[2367,] \"India\" \"\"  \n[2368,] \"India\" \"\"  \n[2369,] \"India\" \"\"  \n[2370,] \"India\" \"\"  \n[2371,] \"India\" \"\"  \n[2372,] \"India\" \"\"  \n[2373,] \"India\" \"\"  \n[2374,] \"India\" \"\"  \n[2375,] \"India\" \"\"  \n[2376,] \"India\" \"\"  \n[2377,] \"India\" \"\"  \n[2378,] \"India\" \"\"  \n[2379,] \"India\" \"\"  \n[2380,] \"India\" \"\"  \n[2381,] \"India\" \"\"  \n[2382,] \"India\" \"\"  \n[2383,] \"India\" \"\"  \n[2384,] \"India\" \"\"  \n[2385,] \"India\" \"\"  \n[2386,] \"India\" \"\"  \n[2387,] \"India\" \"\"  \n[2388,] \"India\" \"\"  \n[2389,] \"India\" \"\"  \n[2390,] \"India\" \"\"  \n[2391,] \"India\" \"\"  \n[2392,] \"India\" \"\"  \n[2393,] \"India\" \"\"  \n[2394,] \"India\" \"\"  \n[2395,] \"India\" \"\"  \n[2396,] \"India\" \"\"  \n[2397,] \"India\" \"\"  \n[2398,] \"India\" \"\"  \n[2399,] \"India\" \"\"  \n[2400,] \"India\" \"\"  \n[2401,] \"India\" \"\"  \n[2402,] \"India\" \"\"  \n[2403,] \"India\" \"\"  \n[2404,] \"India\" \"\"  \n[2405,] \"India\" \"\"  \n[2406,] \"India\" \"\"  \n[2407,] \"India\" \"\"  \n[2408,] \"India\" \"\"  \n[2409,] \"India\" \"\"  \n[2410,] \"India\" \"\"  \n[2411,] \"India\" \"\"  \n[2412,] \"India\" \"\"  \n[2413,] \"India\" \"\"  \n[2414,] \"India\" \"\"  \n[2415,] \"India\" \"\"  \n[2416,] \"India\" \"\"  \n[2417,] \"India\" \"\"  \n[2418,] \"India\" \"\"  \n[2419,] \"India\" \"\"  \n[2420,] \"India\" \"\"  \n[2421,] \"India\" \"\"  \n[2422,] \"India\" \"\"  \n[2423,] \"India\" \"\"  \n[2424,] \"India\" \"\"  \n[2425,] \"India\" \"\"  \n[2426,] \"India\" \"\"  \n[2427,] \"India\" \"\"  \n[2428,] \"India\" \"\"  \n[2429,] \"India\" \"\"  \n[2430,] \"India\" \"\"  \n[2431,] \"India\" \"\"  \n[2432,] \"India\" \"\"  \n[2433,] \"India\" \"\"  \n[2434,] \"India\" \"\"  \n[2435,] \"India\" \"\"  \n[2436,] \"India\" \"\"  \n[2437,] \"India\" \"\"  \n[2438,] \"India\" \"\"  \n[2439,] \"India\" \"\"  \n[2440,] \"India\" \"\"  \n[2441,] \"India\" \"\"  \n[2442,] \"India\" \"\"  \n[2443,] \"India\" \"\"  \n[2444,] \"India\" \"\"  \n[2445,] \"India\" \"\"  \n[2446,] \"India\" \"\"  \n[2447,] \"India\" \"\"  \n[2448,] \"India\" \"\"  \n[2449,] \"India\" \"\"  \n[2450,] \"India\" \"\"  \n[2451,] \"India\" \"\"  \n[2452,] \"India\" \"\"  \n[2453,] \"India\" \"\"  \n[2454,] \"India\" \"\"  \n[2455,] \"India\" \"\"  \n[2456,] \"India\" \"\"  \n[2457,] \"India\" \"\"  \n[2458,] \"India\" \"\"  \n[2459,] \"India\" \"\"  \n[2460,] \"India\" \"\"  \n[2461,] \"India\" \"\"  \n[2462,] \"India\" \"\"  \n[2463,] \"India\" \"\"  \n[2464,] \"India\" \"\"  \n[2465,] \"India\" \"\"  \n[2466,] \"India\" \"\"  \n[2467,] \"India\" \"\"  \n[2468,] \"India\" \"\"  \n[2469,] \"India\" \"\"  \n[2470,] \"India\" \"\"  \n[2471,] \"India\" \"\"  \n[2472,] \"India\" \"\"  \n[2473,] \"India\" \"\"  \n[2474,] \"India\" \"\"  \n[2475,] \"India\" \"\"  \n[2476,] \"India\" \"\"  \n[2477,] \"India\" \"\"  \n[2478,] \"India\" \"\"  \n[2479,] \"India\" \"\"  \n[2480,] \"India\" \"\"  \n[2481,] \"India\" \"\"  \n[2482,] \"India\" \"\"  \n[2483,] \"India\" \"\"  \n[2484,] \"India\" \"\"  \n[2485,] \"India\" \"\"  \n[2486,] \"India\" \"\"  \n[2487,] \"India\" \"\"  \n[2488,] \"India\" \"\"  \n[2489,] \"India\" \"\"  \n[2490,] \"India\" \"\"  \n[2491,] \"India\" \"\"  \n[2492,] \"India\" \"\"  \n[2493,] \"India\" \"\"  \n[2494,] \"India\" \"\"  \n[2495,] \"India\" \"\"  \n[2496,] \"India\" \"\"  \n[2497,] \"India\" \"\"  \n[2498,] \"India\" \"\"  \n[2499,] \"India\" \"\"  \n[2500,] \"India\" \"\"  \n[2501,] \"India\" \"\"  \n[2502,] \"India\" \"\"  \n[2503,] \"India\" \"\"  \n[2504,] \"India\" \"\"  \n[2505,] \"India\" \"\"  \n[2506,] \"India\" \"\"  \n[2507,] \"India\" \"\"  \n[2508,] \"India\" \"\"  \n[2509,] \"India\" \"\"  \n[2510,] \"India\" \"\"  \n[2511,] \"India\" \"\"  \n[2512,] \"India\" \"\"  \n[2513,] \"India\" \"\"  \n[2514,] \"India\" \"\"  \n[2515,] \"India\" \"\"  \n[2516,] \"India\" \"\"  \n[2517,] \"India\" \"\"  \n[2518,] \"India\" \"\"  \n[2519,] \"India\" \"\"  \n[2520,] \"India\" \"\"  \n[2521,] \"India\" \"\"  \n[2522,] \"India\" \"\"  \n[2523,] \"India\" \"\"  \n[2524,] \"India\" \"\"  \n[2525,] \"India\" \"\"  \n[2526,] \"India\" \"\"  \n[2527,] \"India\" \"\"  \n[2528,] \"India\" \"\"  \n[2529,] \"India\" \"\"  \n[2530,] \"India\" \"\"  \n[2531,] \"India\" \"\"  \n[2532,] \"India\" \"\"  \n[2533,] \"India\" \"\"  \n[2534,] \"India\" \"\"  \n[2535,] \"India\" \"\"  \n[2536,] \"India\" \"\"  \n[2537,] \"India\" \"\"  \n[2538,] \"India\" \"\"  \n[2539,] \"India\" \"\"  \n[2540,] \"India\" \"\"  \n[2541,] \"India\" \"\"  \n[2542,] \"India\" \"\"  \n[2543,] \"India\" \"\"  \n[2544,] \"India\" \"\"  \n[2545,] \"India\" \"\"  \n[2546,] \"India\" \"\"  \n[2547,] \"India\" \"\"  \n[2548,] \"India\" \"\"  \n[2549,] \"India\" \"\"  \n[2550,] \"India\" \"\"  \n[2551,] \"India\" \"\"  \n[2552,] \"India\" \"\"  \n[2553,] \"India\" \"\"  \n[2554,] \"India\" \"\"  \n[2555,] \"India\" \"\"  \n[2556,] \"India\" \"\"  \n[2557,] \"India\" \"\"  \n[2558,] \"India\" \"\"  \n[2559,] \"India\" \"\"  \n[2560,] \"India\" \"\"  \n[2561,] \"India\" \"\"  \n[2562,] \"India\" \"\"  \n[2563,] \"India\" \"\"  \n[2564,] \"India\" \"\"  \n[2565,] \"India\" \"\"  \n[2566,] \"India\" \"\"  \n[2567,] \"India\" \"\"  \n[2568,] \"India\" \"\"  \n[2569,] \"India\" \"\"  \n[2570,] \"India\" \"\"  \n[2571,] \"India\" \"\"  \n[2572,] \"India\" \"\"  \n[2573,] \"India\" \"\"  \n[2574,] \"India\" \"\"  \n[2575,] \"India\" \"\"  \n[2576,] \"India\" \"\"  \n[2577,] \"India\" \"\"  \n[2578,] \"India\" \"\"  \n[2579,] \"India\" \"\"  \n[2580,] \"India\" \"\"  \n[2581,] \"India\" \"\"  \n[2582,] \"India\" \"\"  \n[2583,] \"India\" \"\"  \n[2584,] \"India\" \"\"  \n[2585,] \"India\" \"\"  \n[2586,] \"India\" \"\"  \n[2587,] \"India\" \"\"  \n[2588,] \"India\" \"\"  \n[2589,] \"India\" \"\"  \n[2590,] \"India\" \"\"  \n[2591,] \"India\" \"\"  \n[2592,] \"India\" \"\"  \n[2593,] \"India\" \"\"  \n[2594,] \"India\" \"\"  \n[2595,] \"India\" \"\"  \n[2596,] \"India\" \"\"  \n[2597,] \"India\" \"\"  \n[2598,] \"India\" \"\"  \n[2599,] \"India\" \"\"  \n[2600,] \"India\" \"\"  \n[2601,] \"India\" \"\"  \n[2602,] \"India\" \"\"  \n[2603,] \"India\" \"\"  \n[2604,] \"India\" \"\"  \n[2605,] \"India\" \"\"  \n[2606,] \"India\" \"\"  \n[2607,] \"India\" \"\"  \n[2608,] \"India\" \"\"  \n[2609,] \"India\" \"\"  \n[2610,] \"India\" \"\"  \n[2611,] \"India\" \"\"  \n[2612,] \"India\" \"\"  \n[2613,] \"India\" \"\"  \n[2614,] \"India\" \"\"  \n[2615,] \"India\" \"\"  \n[2616,] \"India\" \"\"  \n[2617,] \"India\" \"\"  \n[2618,] \"India\" \"\"  \n[2619,] \"India\" \"\"  \n[2620,] \"India\" \"\"  \n[2621,] \"India\" \"\"  \n[2622,] \"India\" \"\"  \n[2623,] \"India\" \"\"  \n[2624,] \"India\" \"\"  \n[2625,] \"India\" \"\"  \n[2626,] \"India\" \"\"  \n[2627,] \"India\" \"\"  \n[2628,] \"India\" \"\"  \n[2629,] \"India\" \"\"  \n[2630,] \"India\" \"\"  \n[2631,] \"India\" \"\"  \n[2632,] \"India\" \"\"  \n[2633,] \"India\" \"\"  \n[2634,] \"India\" \"\"  \n[2635,] \"India\" \"\"  \n[2636,] \"India\" \"\"  \n[2637,] \"India\" \"\"  \n[2638,] \"India\" \"\"  \n[2639,] \"India\" \"\"  \n[2640,] \"India\" \"\"  \n[2641,] \"India\" \"\"  \n[2642,] \"India\" \"\"  \n[2643,] \"India\" \"\"  \n[2644,] \"India\" \"\"  \n[2645,] \"India\" \"\"  \n[2646,] \"India\" \"\"  \n[2647,] \"India\" \"\"  \n[2648,] \"India\" \"\"  \n[2649,] \"India\" \"\"  \n[2650,] \"India\" \"\"  \n[2651,] \"India\" \"\"  \n[2652,] \"India\" \"\"  \n[2653,] \"India\" \"\"  \n[2654,] \"India\" \"\"  \n[2655,] \"India\" \"\"  \n[2656,] \"India\" \"\"  \n[2657,] \"India\" \"\"  \n[2658,] \"India\" \"\"  \n[2659,] \"India\" \"\"  \n[2660,] \"India\" \"\"  \n[2661,] \"India\" \"\"  \n[2662,] \"India\" \"\"  \n[2663,] \"India\" \"\"  \n[2664,] \"India\" \"\"  \n[2665,] \"India\" \"\"  \n[2666,] \"India\" \"\"  \n[2667,] \"India\" \"\"  \n[2668,] \"India\" \"\"  \n[2669,] \"India\" \"\"  \n[2670,] \"India\" \"\"  \n[2671,] \"India\" \"\"  \n[2672,] \"India\" \"\"  \n[2673,] \"India\" \"\"  \n[2674,] \"India\" \"\"  \n[2675,] \"India\" \"\"  \n[2676,] \"India\" \"\"  \n[2677,] \"India\" \"\"  \n[2678,] \"India\" \"\"  \n[2679,] \"India\" \"\"  \n[2680,] \"India\" \"\"  \n[2681,] \"India\" \"\"  \n[2682,] \"India\" \"\"  \n[2683,] \"India\" \"\"  \n[2684,] \"India\" \"\"  \n[2685,] \"India\" \"\"  \n[2686,] \"India\" \"\"  \n[2687,] \"India\" \"\"  \n[2688,] \"India\" \"\"  \n[2689,] \"India\" \"\"  \n[2690,] \"India\" \"\"  \n[2691,] \"India\" \"\"  \n[2692,] \"India\" \"\"  \n[2693,] \"India\" \"\"  \n[2694,] \"India\" \"\"  \n[2695,] \"India\" \"\"  \n[2696,] \"India\" \"\"  \n[2697,] \"India\" \"\"  \n[2698,] \"India\" \"\"  \n[2699,] \"India\" \"\"  \n[2700,] \"India\" \"\"  \n[2701,] \"India\" \"\"  \n[2702,] \"India\" \"\"  \n[2703,] \"India\" \"\"  \n[2704,] \"India\" \"\"  \n[2705,] \"India\" \"\"  \n[2706,] \"India\" \"\"  \n[2707,] \"India\" \"\"  \n[2708,] \"India\" \"\"  \n[2709,] \"India\" \"\"  \n[2710,] \"India\" \"\"  \n[2711,] \"India\" \"\"  \n[2712,] \"India\" \"\"  \n[2713,] \"India\" \"\"  \n[2714,] \"India\" \"\"  \n[2715,] \"India\" \"\"  \n[2716,] \"India\" \"\"  \n[2717,] \"India\" \"\"  \n[2718,] \"India\" \"\"  \n[2719,] \"India\" \"\"  \n[2720,] \"India\" \"\"  \n[2721,] \"India\" \"\"  \n[2722,] \"India\" \"\"  \n[2723,] \"India\" \"\"  \n[2724,] \"India\" \"\"  \n[2725,] \"India\" \"\"  \n[2726,] \"India\" \"\"  \n[2727,] \"India\" \"\"  \n[2728,] \"India\" \"\"  \n[2729,] \"India\" \"\"  \n[2730,] \"India\" \"\"  \n[2731,] \"India\" \"\"  \n[2732,] \"India\" \"\"  \n[2733,] \"India\" \"\"  \n[2734,] \"India\" \"\"  \n[2735,] \"India\" \"\"  \n[2736,] \"India\" \"\"  \n[2737,] \"India\" \"\"  \n[2738,] \"India\" \"\"  \n[2739,] \"India\" \"\"  \n[2740,] \"India\" \"\"  \n[2741,] \"India\" \"\"  \n[2742,] \"India\" \"\"  \n[2743,] \"India\" \"\"  \n[2744,] \"India\" \"\"  \n[2745,] \"India\" \"\"  \n[2746,] \"India\" \"\"  \n[2747,] \"India\" \"\"  \n[2748,] \"India\" \"\"  \n[2749,] \"India\" \"\"  \n[2750,] \"India\" \"\"  \n[2751,] \"India\" \"\"  \n[2752,] \"India\" \"\"  \n[2753,] \"India\" \"\"  \n[2754,] \"India\" \"\"  \n[2755,] \"India\" \"\"  \n[2756,] \"India\" \"\"  \n[2757,] \"India\" \"\"  \n[2758,] \"India\" \"\"  \n[2759,] \"India\" \"\"  \n[2760,] \"India\" \"\"  \n[2761,] \"India\" \"\"  \n[2762,] \"India\" \"\"  \n[2763,] \"India\" \"\"  \n[2764,] \"India\" \"\"  \n[2765,] \"India\" \"\"  \n[2766,] \"India\" \"\"  \n[2767,] \"India\" \"\"  \n[2768,] \"India\" \"\"  \n[2769,] \"India\" \"\"  \n[2770,] \"India\" \"\"  \n[2771,] \"India\" \"\"  \n[2772,] \"India\" \"\"  \n[2773,] \"India\" \"\"  \n[2774,] \"India\" \"\"  \n[2775,] \"India\" \"\"  \n[2776,] \"India\" \"\"  \n[2777,] \"India\" \"\"  \n[2778,] \"India\" \"\"  \n[2779,] \"India\" \"\"  \n[2780,] \"India\" \"\"  \n[2781,] \"India\" \"\"  \n[2782,] \"India\" \"\"  \n[2783,] \"India\" \"\"  \n[2784,] \"India\" \"\"  \n[2785,] \"India\" \"\"  \n[2786,] \"India\" \"\"  \n[2787,] \"India\" \"\"  \n[2788,] \"India\" \"\"  \n[2789,] \"India\" \"\"  \n[2790,] \"India\" \"\"  \n[2791,] \"India\" \"\"  \n[2792,] \"India\" \"\"  \n[2793,] \"India\" \"\"  \n[2794,] \"India\" \"\"  \n[2795,] \"India\" \"\"  \n[2796,] \"India\" \"\"  \n[2797,] \"India\" \"\"  \n[2798,] \"India\" \"\"  \n[2799,] \"India\" \"\"  \n[2800,] \"India\" \"\"  \n[2801,] \"India\" \"\"  \n[2802,] \"India\" \"\"  \n[2803,] \"India\" \"\"  \n[2804,] \"India\" \"\"  \n[2805,] \"India\" \"\"  \n[2806,] \"India\" \"\"  \n[2807,] \"India\" \"\"  \n[2808,] \"India\" \"\"  \n[2809,] \"India\" \"\"  \n[2810,] \"India\" \"\"  \n[2811,] \"India\" \"\"  \n[2812,] \"India\" \"\"  \n[2813,] \"India\" \"\"  \n[2814,] \"India\" \"\"  \n[2815,] \"India\" \"\"  \n[2816,] \"India\" \"\"  \n[2817,] \"India\" \"\"  \n[2818,] \"India\" \"\"  \n[2819,] \"India\" \"\"  \n[2820,] \"India\" \"\"  \n[2821,] \"India\" \"\"  \n[2822,] \"India\" \"\"  \n[2823,] \"India\" \"\"  \n[2824,] \"India\" \"\"  \n[2825,] \"India\" \"\"  \n[2826,] \"India\" \"\"  \n[2827,] \"India\" \"\"  \n[2828,] \"India\" \"\"  \n[2829,] \"India\" \"\"  \n[2830,] \"India\" \"\"  \n[2831,] \"India\" \"\"  \n[2832,] \"India\" \"\"  \n[2833,] \"India\" \"\"  \n[2834,] \"India\" \"\"  \n[2835,] \"India\" \"\"  \n[2836,] \"India\" \"\"  \n[2837,] \"India\" \"\"  \n[2838,] \"India\" \"\"  \n[2839,] \"India\" \"\"  \n[2840,] \"India\" \"\"  \n[2841,] \"India\" \"\"  \n[2842,] \"India\" \"\"  \n[2843,] \"India\" \"\"  \n[2844,] \"India\" \"\"  \n[2845,] \"India\" \"\"  \n[2846,] \"India\" \"\"  \n[2847,] \"India\" \"\"  \n[2848,] \"India\" \"\"  \n[2849,] \"India\" \"\"  \n[2850,] \"India\" \"\"  \n[2851,] \"India\" \"\"  \n[2852,] \"India\" \"\"  \n[2853,] \"India\" \"\"  \n[2854,] \"India\" \"\"  \n[2855,] \"India\" \"\"  \n[2856,] \"India\" \"\"  \n[2857,] \"India\" \"\"  \n[2858,] \"India\" \"\"  \n[2859,] \"India\" \"\"  \n[2860,] \"India\" \"\"  \n[2861,] \"India\" \"\"  \n[2862,] \"India\" \"\"  \n[2863,] \"India\" \"\"  \n[2864,] \"India\" \"\"  \n[2865,] \"India\" \"\"  \n[2866,] \"India\" \"\"  \n[2867,] \"India\" \"\"  \n[2868,] \"India\" \"\"  \n[2869,] \"India\" \"\"  \n[2870,] \"India\" \"\"  \n[2871,] \"India\" \"\"  \n[2872,] \"India\" \"\"  \n[2873,] \"India\" \"\"  \n[2874,] \"India\" \"\"  \n[2875,] \"India\" \"\"  \n[2876,] \"India\" \"\"  \n[2877,] \"India\" \"\"  \n[2878,] \"India\" \"\"  \n[2879,] \"India\" \"\"  \n[2880,] \"India\" \"\"  \n[2881,] \"India\" \"\"  \n[2882,] \"India\" \"\"  \n[2883,] \"India\" \"\"  \n[2884,] \"India\" \"\"  \n[2885,] \"India\" \"\"  \n[2886,] \"India\" \"\"  \n[2887,] \"India\" \"\"  \n[2888,] \"India\" \"\"  \n[2889,] \"India\" \"\"  \n[2890,] \"India\" \"\"  \n[2891,] \"India\" \"\"  \n[2892,] \"India\" \"\"  \n[2893,] \"India\" \"\"  \n[2894,] \"India\" \"\"  \n[2895,] \"India\" \"\"  \n[2896,] \"India\" \"\"  \n[2897,] \"India\" \"\"  \n[2898,] \"India\" \"\"  \n[2899,] \"India\" \"\"  \n[2900,] \"India\" \"\"  \n[2901,] \"India\" \"\"  \n[2902,] \"India\" \"\"  \n[2903,] \"India\" \"\"  \n[2904,] \"India\" \"\"  \n[2905,] \"India\" \"\"  \n[2906,] \"India\" \"\"  \n[2907,] \"India\" \"\"  \n[2908,] \"India\" \"\"  \n[2909,] \"India\" \"\"  \n[2910,] \"India\" \"\"  \n[2911,] \"India\" \"\"  \n[2912,] \"India\" \"\"  \n[2913,] \"India\" \"\"  \n[2914,] \"India\" \"\"  \n[2915,] \"India\" \"\"  \n[2916,] \"India\" \"\"  \n[2917,] \"India\" \"\"  \n[2918,] \"India\" \"\"  \n[2919,] \"India\" \"\"  \n[2920,] \"India\" \"\"  \n[2921,] \"India\" \"\"  \n[2922,] \"India\" \"\"  \n[2923,] \"India\" \"\"  \n[2924,] \"India\" \"\"  \n[2925,] \"India\" \"\"  \n[2926,] \"India\" \"\"  \n[2927,] \"India\" \"\"  \n[2928,] \"India\" \"\"  \n[2929,] \"India\" \"\"  \n[2930,] \"India\" \"\"  \n[2931,] \"India\" \"\"  \n[2932,] \"India\" \"\"  \n[2933,] \"India\" \"\"  \n[2934,] \"India\" \"\"  \n[2935,] \"India\" \"\"  \n[2936,] \"India\" \"\"  \n[2937,] \"India\" \"\"  \n[2938,] \"India\" \"\"  \n[2939,] \"India\" \"\"  \n[2940,] \"India\" \"\"  \n[2941,] \"India\" \"\"  \n[2942,] \"India\" \"\"  \n[2943,] \"India\" \"\"  \n[2944,] \"India\" \"\"  \n[2945,] \"India\" \"\"  \n[2946,] \"India\" \"\"  \n[2947,] \"India\" \"\"  \n[2948,] \"India\" \"\"  \n[2949,] \"India\" \"\"  \n[2950,] \"India\" \"\"  \n[2951,] \"India\" \"\"  \n[2952,] \"India\" \"\"  \n[2953,] \"India\" \"\"  \n[2954,] \"India\" \"\"  \n[2955,] \"India\" \"\"  \n[2956,] \"India\" \"\"  \n[2957,] \"India\" \"\"  \n[2958,] \"India\" \"\"  \n[2959,] \"India\" \"\"  \n[2960,] \"India\" \"\"  \n[2961,] \"India\" \"\"  \n[2962,] \"India\" \"\"  \n[2963,] \"India\" \"\"  \n[2964,] \"India\" \"\"  \n[2965,] \"India\" \"\"  \n[2966,] \"India\" \"\"  \n[2967,] \"India\" \"\"  \n[2968,] \"India\" \"\"  \n[2969,] \"India\" \"\"  \n[2970,] \"India\" \"\"  \n[2971,] \"India\" \"\"  \n[2972,] \"India\" \"\"  \n[2973,] \"India\" \"\"  \n[2974,] \"India\" \"\"  \n[2975,] \"India\" \"\"  \n[2976,] \"India\" \"\"  \n[2977,] \"India\" \"\"  \n[2978,] \"India\" \"\"  \n[2979,] \"India\" \"\"  \n[2980,] \"India\" \"\"  \n[2981,] \"India\" \"\"  \n[2982,] \"India\" \"\"  \n[2983,] \"India\" \"\"  \n[2984,] \"India\" \"\"  \n[2985,] \"India\" \"\"  \n[2986,] \"India\" \"\"  \n[2987,] \"India\" \"\"  \n[2988,] \"India\" \"\"  \n[2989,] \"India\" \"\"  \n[2990,] \"India\" \"\"  \n[2991,] \"India\" \"\"  \n[2992,] \"India\" \"\"  \n[2993,] \"India\" \"\"  \n[2994,] \"India\" \"\"  \n[2995,] \"India\" \"\"  \n[2996,] \"India\" \"\"  \n[2997,] \"India\" \"\"  \n[2998,] \"India\" \"\"  \n[2999,] \"India\" \"\"  \n[3000,] \"India\" \"\"  \n[3001,] \"India\" \"\"  \n[3002,] \"India\" \"\"  \n[3003,] \"India\" \"\"  \n[3004,] \"India\" \"\"  \n[3005,] \"India\" \"\"  \n[3006,] \"India\" \"\"  \n[3007,] \"India\" \"\"  \n[3008,] \"India\" \"\"  \n[3009,] \"India\" \"\"  \n[3010,] \"India\" \"\"  \n[3011,] \"India\" \"\"  \n[3012,] \"India\" \"\"  \n[3013,] \"India\" \"\"  \n[3014,] \"India\" \"\"  \n[3015,] \"India\" \"\"  \n[3016,] \"India\" \"\"  \n[3017,] \"India\" \"\"  \n[3018,] \"India\" \"\"  \n[3019,] \"India\" \"\"  \n[3020,] \"India\" \"\"  \n[3021,] \"India\" \"\"  \n[3022,] \"India\" \"\"  \n[3023,] \"India\" \"\"  \n[3024,] \"India\" \"\"  \n[3025,] \"India\" \"\"  \n[3026,] \"India\" \"\"  \n[3027,] \"India\" \"\"  \n[3028,] \"India\" \"\"  \n[3029,] \"India\" \"\"  \n[3030,] \"India\" \"\"  \n[3031,] \"India\" \"\"  \n[3032,] \"India\" \"\"  \n[3033,] \"India\" \"\"  \n[3034,] \"India\" \"\"  \n[3035,] \"India\" \"\"  \n[3036,] \"India\" \"\"  \n[3037,] \"India\" \"\"  \n[3038,] \"India\" \"\"  \n[3039,] \"India\" \"\"  \n[3040,] \"India\" \"\"  \n[3041,] \"India\" \"\"  \n[3042,] \"India\" \"\"  \n[3043,] \"India\" \"\"  \n[3044,] \"India\" \"\"  \n[3045,] \"India\" \"\"  \n[3046,] \"India\" \"\"  \n[3047,] \"India\" \"\"  \n[3048,] \"India\" \"\"  \n[3049,] \"India\" \"\"  \n[3050,] \"India\" \"\"  \n[3051,] \"India\" \"\"  \n[3052,] \"India\" \"\"  \n[3053,] \"India\" \"\"  \n[3054,] \"India\" \"\"  \n[3055,] \"India\" \"\"  \n[3056,] \"India\" \"\"  \n[3057,] \"India\" \"\"  \n[3058,] \"India\" \"\"  \n[3059,] \"India\" \"\"  \n[3060,] \"India\" \"\"  \n[3061,] \"India\" \"\"  \n[3062,] \"India\" \"\"  \n[3063,] \"India\" \"\"  \n[3064,] \"India\" \"\"  \n[3065,] \"India\" \"\"  \n[3066,] \"India\" \"\"  \n[3067,] \"India\" \"\"  \n[3068,] \"India\" \"\"  \n[3069,] \"India\" \"\"  \n[3070,] \"India\" \"\"  \n[3071,] \"India\" \"\"  \n[3072,] \"India\" \"\"  \n[3073,] \"India\" \"\"  \n[3074,] \"India\" \"\"  \n[3075,] \"India\" \"\"  \n[3076,] \"India\" \"\"  \n[3077,] \"India\" \"\"  \n[3078,] \"India\" \"\"  \n[3079,] \"India\" \"\"  \n[3080,] \"India\" \"\"  \n[3081,] \"India\" \"\"  \n[3082,] \"India\" \"\"  \n[3083,] \"India\" \"\"  \n[3084,] \"India\" \"\"  \n[3085,] \"India\" \"\"  \n[3086,] \"India\" \"\"  \n[3087,] \"India\" \"\"  \n[3088,] \"India\" \"\"  \n[3089,] \"India\" \"\"  \n[3090,] \"India\" \"\"  \n[3091,] \"India\" \"\"  \n[3092,] \"India\" \"\"  \n[3093,] \"India\" \"\"  \n[3094,] \"India\" \"\"  \n[3095,] \"India\" \"\"  \n[3096,] \"India\" \"\"  \n[3097,] \"India\" \"\"  \n[3098,] \"India\" \"\"  \n[3099,] \"India\" \"\"  \n[3100,] \"India\" \"\"  \n[3101,] \"India\" \"\"  \n[3102,] \"India\" \"\"  \n[3103,] \"India\" \"\"  \n[3104,] \"India\" \"\"  \n[3105,] \"India\" \"\"  \n[3106,] \"India\" \"\"  \n[3107,] \"India\" \"\"  \n[3108,] \"India\" \"\"  \n[3109,] \"India\" \"\"  \n[3110,] \"India\" \"\"  \n[3111,] \"India\" \"\"  \n[3112,] \"India\" \"\"  \n[3113,] \"India\" \"\"  \n[3114,] \"India\" \"\"  \n[3115,] \"India\" \"\"  \n[3116,] \"India\" \"\"  \n[3117,] \"India\" \"\"  \n[3118,] \"India\" \"\"  \n[3119,] \"India\" \"\"  \n[3120,] \"India\" \"\"  \n[3121,] \"India\" \"\"  \n[3122,] \"India\" \"\"  \n[3123,] \"India\" \"\"  \n[3124,] \"India\" \"\"  \n[3125,] \"India\" \"\"  \n[3126,] \"India\" \"\"  \n[3127,] \"India\" \"\"  \n[3128,] \"India\" \"\"  \n[3129,] \"India\" \"\"  \n[3130,] \"India\" \"\"  \n[3131,] \"India\" \"\"  \n[3132,] \"India\" \"\"  \n[3133,] \"India\" \"\"  \n[3134,] \"India\" \"\"  \n[3135,] \"India\" \"\"  \n[3136,] \"India\" \"\"  \n[3137,] \"India\" \"\"  \n[3138,] \"India\" \"\"  \n[3139,] \"India\" \"\"  \n[3140,] \"India\" \"\"  \n[3141,] \"India\" \"\"  \n[3142,] \"India\" \"\"  \n[3143,] \"India\" \"\"  \n[3144,] \"India\" \"\"  \n[3145,] \"India\" \"\"  \n[3146,] \"India\" \"\"  \n[3147,] \"India\" \"\"  \n[3148,] \"India\" \"\"  \n[3149,] \"India\" \"\"  \n[3150,] \"India\" \"\"  \n[3151,] \"India\" \"\"  \n[3152,] \"India\" \"\"  \n[3153,] \"India\" \"\"  \n[3154,] \"India\" \"\"  \n[3155,] \"India\" \"\"  \n[3156,] \"India\" \"\"  \n[3157,] \"India\" \"\"  \n[3158,] \"India\" \"\"  \n[3159,] \"India\" \"\"  \n[3160,] \"India\" \"\"  \n[3161,] \"India\" \"\"  \n[3162,] \"India\" \"\"  \n[3163,] \"India\" \"\"  \n[3164,] \"India\" \"\"  \n[3165,] \"India\" \"\"  \n[3166,] \"India\" \"\"  \n[3167,] \"India\" \"\"  \n[3168,] \"India\" \"\"  \n[3169,] \"India\" \"\"  \n[3170,] \"India\" \"\"  \n[3171,] \"India\" \"\"  \n[3172,] \"India\" \"\"  \n[3173,] \"India\" \"\"  \n[3174,] \"India\" \"\"  \n[3175,] \"India\" \"\"  \n[3176,] \"India\" \"\"  \n[3177,] \"India\" \"\"  \n[3178,] \"India\" \"\"  \n[3179,] \"India\" \"\"  \n[3180,] \"India\" \"\"  \n[3181,] \"India\" \"\"  \n[3182,] \"India\" \"\"  \n[3183,] \"India\" \"\"  \n[3184,] \"India\" \"\"  \n[3185,] \"India\" \"\"  \n[3186,] \"India\" \"\"  \n[3187,] \"India\" \"\"  \n[3188,] \"India\" \"\"  \n[3189,] \"India\" \"\"  \n[3190,] \"India\" \"\"  \n[3191,] \"India\" \"\"  \n[3192,] \"India\" \"\"  \n[3193,] \"India\" \"\"  \n[3194,] \"India\" \"\"  \n[3195,] \"India\" \"\"  \n[3196,] \"India\" \"\"  \n[3197,] \"India\" \"\"  \n[3198,] \"India\" \"\"  \n[3199,] \"India\" \"\"  \n[3200,] \"India\" \"\"  \n[3201,] \"India\" \"\"  \n[3202,] \"India\" \"\"  \n[3203,] \"India\" \"\"  \n[3204,] \"India\" \"\"  \n[3205,] \"India\" \"\"  \n[3206,] \"India\" \"\"  \n[3207,] \"India\" \"\"  \n[3208,] \"India\" \"\"  \n[3209,] \"India\" \"\"  \n[3210,] \"India\" \"\"  \n[3211,] \"India\" \"\"  \n[3212,] \"India\" \"\"  \n[3213,] \"India\" \"\"  \n[3214,] \"India\" \"\"  \n[3215,] \"India\" \"\"  \n[3216,] \"India\" \"\"  \n[3217,] \"India\" \"\"  \n[3218,] \"India\" \"\"  \n[3219,] \"India\" \"\"  \n[3220,] \"India\" \"\"  \n[3221,] \"India\" \"\"  \n[3222,] \"India\" \"\"  \n[3223,] \"India\" \"\"  \n[3224,] \"India\" \"\"  \n[3225,] \"India\" \"\"  \n[3226,] \"India\" \"\"  \n[3227,] \"India\" \"\"  \n[3228,] \"India\" \"\"  \n[3229,] \"India\" \"\"  \n[3230,] \"India\" \"\"  \n[3231,] \"India\" \"\"  \n[3232,] \"India\" \"\"  \n[3233,] \"India\" \"\"  \n[3234,] \"India\" \"\"  \n[3235,] \"India\" \"\"  \n[3236,] \"India\" \"\"  \n[3237,] \"India\" \"\"  \n[3238,] \"India\" \"\"  \n[3239,] \"India\" \"\"  \n[3240,] \"India\" \"\"  \n[3241,] \"India\" \"\"  \n[3242,] \"India\" \"\"  \n[3243,] \"India\" \"\"  \n[3244,] \"India\" \"\"  \n[3245,] \"India\" \"\"  \n[3246,] \"India\" \"\"  \n[3247,] \"India\" \"\"  \n[3248,] \"India\" \"\"  \n[3249,] \"India\" \"\"  \n[3250,] \"India\" \"\"  \n[3251,] \"India\" \"\"  \n[3252,] \"India\" \"\"  \n[3253,] \"India\" \"\"  \n[3254,] \"India\" \"\"  \n[3255,] \"India\" \"\"  \n[3256,] \"India\" \"\"  \n[3257,] \"India\" \"\"  \n[3258,] \"India\" \"\"  \n[3259,] \"India\" \"\"  \n[3260,] \"India\" \"\"  \n[3261,] \"India\" \"\"  \n[3262,] \"India\" \"\"  \n[3263,] \"India\" \"\"  \n[3264,] \"India\" \"\"  \n[3265,] \"India\" \"\"  \n[3266,] \"India\" \"\"  \n[3267,] \"India\" \"\"  \n[3268,] \"India\" \"\"  \n[3269,] \"India\" \"\"  \n[3270,] \"India\" \"\"  \n[3271,] \"India\" \"\"  \n[3272,] \"India\" \"\"  \n[3273,] \"India\" \"\"  \n[3274,] \"India\" \"\"  \n[3275,] \"India\" \"\"  \n[3276,] \"India\" \"\"  \n[3277,] \"India\" \"\"  \n[3278,] \"India\" \"\"  \n[3279,] \"India\" \"\"  \n[3280,] \"India\" \"\"  \n[3281,] \"India\" \"\"  \n[3282,] \"India\" \"\"  \n[3283,] \"India\" \"\"  \n[3284,] \"India\" \"\"  \n[3285,] \"India\" \"\"  \n[3286,] \"India\" \"\"  \n[3287,] \"India\" \"\"  \n[3288,] \"India\" \"\"  \n[3289,] \"India\" \"\"  \n[3290,] \"India\" \"\"  \n[3291,] \"India\" \"\"  \n[3292,] \"India\" \"\"  \n[3293,] \"India\" \"\"  \n[3294,] \"India\" \"\"  \n[3295,] \"India\" \"\"  \n[3296,] \"India\" \"\"  \n[3297,] \"India\" \"\"  \n[3298,] \"India\" \"\"  \n[3299,] \"India\" \"\"  \n[3300,] \"India\" \"\"  \n[3301,] \"India\" \"\"  \n[3302,] \"India\" \"\"  \n[3303,] \"India\" \"\"  \n[3304,] \"India\" \"\"  \n[3305,] \"India\" \"\"  \n[3306,] \"India\" \"\"  \n[3307,] \"India\" \"\"  \n[3308,] \"India\" \"\"  \n[3309,] \"India\" \"\"  \n[3310,] \"India\" \"\"  \n[3311,] \"India\" \"\"  \n[3312,] \"India\" \"\"  \n[3313,] \"India\" \"\"  \n[3314,] \"India\" \"\"  \n[3315,] \"India\" \"\"  \n[3316,] \"India\" \"\"  \n[3317,] \"India\" \"\"  \n[3318,] \"India\" \"\"  \n[3319,] \"India\" \"\"  \n[3320,] \"India\" \"\"  \n[3321,] \"India\" \"\"  \n[3322,] \"India\" \"\"  \n[3323,] \"India\" \"\"  \n[3324,] \"India\" \"\"  \n[3325,] \"India\" \"\"  \n[3326,] \"India\" \"\"  \n[3327,] \"India\" \"\"  \n[3328,] \"India\" \"\"  \n[3329,] \"India\" \"\"  \n[3330,] \"India\" \"\"  \n[3331,] \"India\" \"\"  \n[3332,] \"India\" \"\"  \n[3333,] \"India\" \"\"  \n[3334,] \"India\" \"\"  \n[3335,] \"India\" \"\"  \n[3336,] \"India\" \"\"  \n[3337,] \"India\" \"\"  \n[3338,] \"India\" \"\"  \n[3339,] \"India\" \"\"  \n[3340,] \"India\" \"\"  \n[3341,] \"India\" \"\"  \n[3342,] \"India\" \"\"  \n[3343,] \"India\" \"\"  \n[3344,] \"India\" \"\"  \n[3345,] \"India\" \"\"  \n[3346,] \"India\" \"\"  \n[3347,] \"India\" \"\"  \n[3348,] \"India\" \"\"  \n[3349,] \"India\" \"\"  \n[3350,] \"India\" \"\"  \n[3351,] \"India\" \"\"  \n[3352,] \"India\" \"\"  \n[3353,] \"India\" \"\"  \n[3354,] \"India\" \"\"  \n[3355,] \"India\" \"\"  \n[3356,] \"India\" \"\"  \n[3357,] \"India\" \"\"  \n[3358,] \"India\" \"\"  \n[3359,] \"India\" \"\"  \n[3360,] \"India\" \"\"  \n[3361,] \"India\" \"\"  \n[3362,] \"India\" \"\"  \n[3363,] \"India\" \"\"  \n[3364,] \"India\" \"\"  \n[3365,] \"India\" \"\"  \n[3366,] \"India\" \"\"  \n[3367,] \"India\" \"\"  \n[3368,] \"India\" \"\"  \n[3369,] \"India\" \"\"  \n[3370,] \"India\" \"\"  \n[3371,] \"India\" \"\"  \n[3372,] \"India\" \"\"  \n[3373,] \"India\" \"\"  \n[3374,] \"India\" \"\"  \n[3375,] \"India\" \"\"  \n[3376,] \"India\" \"\"  \n[3377,] \"India\" \"\"  \n[3378,] \"India\" \"\"  \n[3379,] \"India\" \"\"  \n[3380,] \"India\" \"\"  \n[3381,] \"India\" \"\"  \n[3382,] \"India\" \"\"  \n[3383,] \"India\" \"\"  \n[3384,] \"India\" \"\"  \n[3385,] \"India\" \"\"  \n[3386,] \"India\" \"\"  \n[3387,] \"India\" \"\"  \n[3388,] \"India\" \"\"  \n[3389,] \"India\" \"\"  \n[3390,] \"India\" \"\"  \n[3391,] \"India\" \"\"  \n[3392,] \"India\" \"\"  \n[3393,] \"India\" \"\"  \n[3394,] \"India\" \"\"  \n[3395,] \"India\" \"\"  \n[3396,] \"India\" \"\"  \n[3397,] \"India\" \"\"  \n[3398,] \"India\" \"\"  \n[3399,] \"India\" \"\"  \n[3400,] \"India\" \"\"  \n[3401,] \"India\" \"\"  \n[3402,] \"India\" \"\"  \n[3403,] \"India\" \"\"  \n[3404,] \"India\" \"\"  \n[3405,] \"India\" \"\"  \n[3406,] \"India\" \"\"  \n[3407,] \"India\" \"\"  \n[3408,] \"India\" \"\"  \n[3409,] \"India\" \"\"  \n[3410,] \"India\" \"\"  \n[3411,] \"India\" \"\"  \n[3412,] \"India\" \"\"  \n[3413,] \"India\" \"\"  \n[3414,] \"India\" \"\"  \n[3415,] \"India\" \"\"  \n[3416,] \"India\" \"\"  \n[3417,] \"India\" \"\"  \n[3418,] \"India\" \"\"  \n[3419,] \"India\" \"\"  \n[3420,] \"India\" \"\"  \n[3421,] \"India\" \"\"  \n[3422,] \"India\" \"\"  \n[3423,] \"India\" \"\"  \n[3424,] \"India\" \"\"  \n[3425,] \"India\" \"\"  \n[3426,] \"India\" \"\"  \n[3427,] \"India\" \"\"  \n[3428,] \"India\" \"\"  \n[3429,] \"India\" \"\"  \n[3430,] \"India\" \"\"  \n[3431,] \"India\" \"\"  \n[3432,] \"India\" \"\"  \n[3433,] \"India\" \"\"  \n[3434,] \"India\" \"\"  \n[3435,] \"India\" \"\"  \n[3436,] \"India\" \"\"  \n[3437,] \"India\" \"\"  \n[3438,] \"India\" \"\"  \n[3439,] \"India\" \"\"  \n[3440,] \"India\" \"\"  \n[3441,] \"India\" \"\"  \n[3442,] \"India\" \"\"  \n[3443,] \"India\" \"\"  \n[3444,] \"India\" \"\"  \n[3445,] \"India\" \"\"  \n[3446,] \"India\" \"\"  \n[3447,] \"India\" \"\"  \n[3448,] \"India\" \"\"  \n[3449,] \"India\" \"\"  \n[3450,] \"India\" \"\"  \n[3451,] \"India\" \"\"  \n[3452,] \"India\" \"\"  \n[3453,] \"India\" \"\"  \n[3454,] \"India\" \"\"  \n[3455,] \"India\" \"\"  \n[3456,] \"India\" \"\"  \n[3457,] \"India\" \"\"  \n[3458,] \"India\" \"\"  \n[3459,] \"India\" \"\"  \n[3460,] \"India\" \"\"  \n[3461,] \"India\" \"\"  \n[3462,] \"India\" \"\"  \n[3463,] \"India\" \"\"  \n[3464,] \"India\" \"\"  \n[3465,] \"India\" \"\"  \n[3466,] \"India\" \"\"  \n[3467,] \"India\" \"\"  \n[3468,] \"India\" \"\"  \n[3469,] \"India\" \"\"  \n[3470,] \"India\" \"\"  \n[3471,] \"India\" \"\"  \n[3472,] \"India\" \"\"  \n[3473,] \"India\" \"\"  \n[3474,] \"India\" \"\"  \n[3475,] \"India\" \"\"  \n[3476,] \"India\" \"\"  \n[3477,] \"India\" \"\"  \n[3478,] \"India\" \"\"  \n[3479,] \"India\" \"\"  \n[3480,] \"India\" \"\"  \n[3481,] \"India\" \"\"  \n[3482,] \"India\" \"\"  \n[3483,] \"India\" \"\"  \n[3484,] \"India\" \"\"  \n[3485,] \"India\" \"\"  \n[3486,] \"India\" \"\"  \n[3487,] \"India\" \"\"  \n[3488,] \"India\" \"\"  \n[3489,] \"India\" \"\"  \n[3490,] \"India\" \"\"  \n[3491,] \"India\" \"\"  \n[3492,] \"India\" \"\"  \n[3493,] \"India\" \"\"  \n[3494,] \"India\" \"\"  \n[3495,] \"India\" \"\"  \n[3496,] \"India\" \"\"  \n[3497,] \"India\" \"\"  \n[3498,] \"India\" \"\"  \n[3499,] \"India\" \"\"  \n[3500,] \"India\" \"\"  \n[3501,] \"India\" \"\"  \n[3502,] \"India\" \"\"  \n[3503,] \"India\" \"\"  \n[3504,] \"India\" \"\"  \n[3505,] \"India\" \"\"  \n[3506,] \"India\" \"\"  \n[3507,] \"India\" \"\"  \n[3508,] \"India\" \"\"  \n[3509,] \"India\" \"\"  \n[3510,] \"India\" \"\"  \n[3511,] \"India\" \"\"  \n[3512,] \"India\" \"\"  \n[3513,] \"India\" \"\"  \n[3514,] \"India\" \"\"  \n[3515,] \"India\" \"\"  \n[3516,] \"India\" \"\"  \n[3517,] \"India\" \"\"  \n[3518,] \"India\" \"\"  \n[3519,] \"India\" \"\"  \n[3520,] \"India\" \"\"  \n[3521,] \"India\" \"\"  \n[3522,] \"India\" \"\"  \n[3523,] \"India\" \"\"  \n[3524,] \"India\" \"\"  \n[3525,] \"India\" \"\"  \n[3526,] \"India\" \"\"  \n[3527,] \"India\" \"\"  \n[3528,] \"India\" \"\"  \n[3529,] \"India\" \"\"  \n[3530,] \"India\" \"\"  \n[3531,] \"India\" \"\"  \n[3532,] \"India\" \"\"  \n[3533,] \"India\" \"\"  \n[3534,] \"India\" \"\"  \n[3535,] \"India\" \"\"  \n[3536,] \"India\" \"\"  \n[3537,] \"India\" \"\"  \n[3538,] \"India\" \"\"  \n[3539,] \"India\" \"\"  \n[3540,] \"India\" \"\"  \n[3541,] \"India\" \"\"  \n[3542,] \"India\" \"\"  \n[3543,] \"India\" \"\"  \n[3544,] \"India\" \"\"  \n[3545,] \"India\" \"\"  \n[3546,] \"India\" \"\"  \n[3547,] \"India\" \"\"  \n[3548,] \"India\" \"\"  \n[3549,] \"India\" \"\"  \n[3550,] \"India\" \"\"  \n[3551,] \"India\" \"\"  \n[3552,] \"India\" \"\"  \n[3553,] \"India\" \"\"  \n[3554,] \"India\" \"\"  \n[3555,] \"India\" \"\"  \n[3556,] \"India\" \"\"  \n[3557,] \"India\" \"\"  \n[3558,] \"India\" \"\"  \n[3559,] \"India\" \"\"  \n[3560,] \"India\" \"\"  \n[3561,] \"India\" \"\"  \n[3562,] \"India\" \"\"  \n[3563,] \"India\" \"\"  \n[3564,] \"India\" \"\"  \n[3565,] \"India\" \"\"  \n[3566,] \"India\" \"\"  \n[3567,] \"India\" \"\"  \n[3568,] \"India\" \"\"  \n[3569,] \"India\" \"\"  \n[3570,] \"India\" \"\"  \n[3571,] \"India\" \"\"  \n[3572,] \"India\" \"\"  \n[3573,] \"India\" \"\"  \n[3574,] \"India\" \"\"  \n[3575,] \"India\" \"\"  \n[3576,] \"India\" \"\"  \n[3577,] \"India\" \"\"  \n[3578,] \"India\" \"\"  \n[3579,] \"India\" \"\"  \n[3580,] \"India\" \"\"  \n[3581,] \"India\" \"\"  \n[3582,] \"India\" \"\"  \n[3583,] \"India\" \"\"  \n[3584,] \"India\" \"\"  \n[3585,] \"India\" \"\"  \n[3586,] \"India\" \"\"  \n[3587,] \"India\" \"\"  \n[3588,] \"India\" \"\"  \n[3589,] \"India\" \"\"  \n[3590,] \"India\" \"\"  \n[3591,] \"India\" \"\"  \n[3592,] \"India\" \"\"  \n[3593,] \"India\" \"\"  \n[3594,] \"India\" \"\"  \n[3595,] \"India\" \"\"  \n[3596,] \"India\" \"\"  \n[3597,] \"India\" \"\"  \n[3598,] \"India\" \"\"  \n[3599,] \"India\" \"\"  \n[3600,] \"India\" \"\"  \n[3601,] \"India\" \"\"  \n[3602,] \"India\" \"\"  \n[3603,] \"India\" \"\"  \n[3604,] \"India\" \"\"  \n[3605,] \"India\" \"\"  \n[3606,] \"India\" \"\"  \n[3607,] \"India\" \"\"  \n[3608,] \"India\" \"\"  \n[3609,] \"India\" \"\"  \n[3610,] \"India\" \"\"  \n[3611,] \"India\" \"\"  \n[3612,] \"India\" \"\"  \n[3613,] \"India\" \"\"  \n[3614,] \"India\" \"\"  \n[3615,] \"India\" \"\"  \n[3616,] \"India\" \"\"  \n[3617,] \"India\" \"\"  \n[3618,] \"India\" \"\"  \n[3619,] \"India\" \"\"  \n[3620,] \"India\" \"\"  \n[3621,] \"India\" \"\"  \n[3622,] \"India\" \"\"  \n[3623,] \"India\" \"\"  \n[3624,] \"India\" \"\"  \n[3625,] \"India\" \"\"  \n[3626,] \"India\" \"\"  \n[3627,] \"India\" \"\"  \n[3628,] \"India\" \"\"  \n[3629,] \"India\" \"\"  \n[3630,] \"India\" \"\"  \n[3631,] \"India\" \"\"  \n[3632,] \"India\" \"\"  \n[3633,] \"India\" \"\"  \n[3634,] \"India\" \"\"  \n[3635,] \"India\" \"\"  \n[3636,] \"India\" \"\"  \n[3637,] \"India\" \"\"  \n[3638,] \"India\" \"\"  \n[3639,] \"India\" \"\"  \n[3640,] \"India\" \"\"  \n[3641,] \"India\" \"\"  \n[3642,] \"India\" \"\"  \n[3643,] \"India\" \"\"  \n[3644,] \"India\" \"\"  \n[3645,] \"India\" \"\"  \n[3646,] \"India\" \"\"  \n[3647,] \"India\" \"\"  \n[3648,] \"India\" \"\"  \n[3649,] \"India\" \"\"  \n[3650,] \"India\" \"\"  \n[3651,] \"India\" \"\"  \n[3652,] \"India\" \"\"  \n[3653,] \"India\" \"\"  \n[3654,] \"India\" \"\"  \n[3655,] \"India\" \"\"  \n[3656,] \"India\" \"\"  \n[3657,] \"India\" \"\"  \n[3658,] \"India\" \"\"  \n[3659,] \"India\" \"\"  \n[3660,] \"India\" \"\"  \n[3661,] \"India\" \"\"  \n[3662,] \"India\" \"\"  \n[3663,] \"India\" \"\"  \n[3664,] \"India\" \"\"  \n[3665,] \"India\" \"\"  \n[3666,] \"India\" \"\"  \n[3667,] \"India\" \"\"  \n[3668,] \"India\" \"\"  \n[3669,] \"India\" \"\"  \n[3670,] \"India\" \"\"  \n[3671,] \"India\" \"\"  \n[3672,] \"India\" \"\"  \n[3673,] \"India\" \"\"  \n[3674,] \"India\" \"\"  \n[3675,] \"India\" \"\"  \n[3676,] \"India\" \"\"  \n[3677,] \"India\" \"\"  \n[3678,] \"India\" \"\"  \n[3679,] \"India\" \"\"  \n[3680,] \"India\" \"\"  \n[3681,] \"India\" \"\"  \n[3682,] \"India\" \"\"  \n[3683,] \"India\" \"\"  \n[3684,] \"India\" \"\"  \n[3685,] \"India\" \"\"  \n[3686,] \"India\" \"\"  \n[3687,] \"India\" \"\"  \n[3688,] \"India\" \"\"  \n[3689,] \"India\" \"\"  \n[3690,] \"India\" \"\"  \n[3691,] \"India\" \"\"  \n[3692,] \"India\" \"\"  \n[3693,] \"India\" \"\"  \n[3694,] \"India\" \"\"  \n[3695,] \"India\" \"\"  \n[3696,] \"India\" \"\"  \n[3697,] \"India\" \"\"  \n[3698,] \"India\" \"\"  \n[3699,] \"India\" \"\"  \n[3700,] \"India\" \"\"  \n[3701,] \"India\" \"\"  \n[3702,] \"India\" \"\"  \n[3703,] \"India\" \"\"  \n[3704,] \"India\" \"\"  \n[3705,] \"India\" \"\"  \n[3706,] \"India\" \"\"  \n[3707,] \"India\" \"\"  \n[3708,] \"India\" \"\"  \n[3709,] \"India\" \"\"  \n[3710,] \"India\" \"\"  \n[3711,] \"India\" \"\"  \n[3712,] \"India\" \"\"  \n[3713,] \"India\" \"\"  \n[3714,] \"India\" \"\"  \n[3715,] \"India\" \"\"  \n[3716,] \"India\" \"\"  \n[3717,] \"India\" \"\"  \n[3718,] \"India\" \"\"  \n[3719,] \"India\" \"\"  \n[3720,] \"India\" \"\"  \n[3721,] \"India\" \"\"  \n[3722,] \"India\" \"\"  \n[3723,] \"India\" \"\"  \n[3724,] \"India\" \"\"  \n[3725,] \"India\" \"\"  \n[3726,] \"India\" \"\"  \n[3727,] \"India\" \"\"  \n[3728,] \"India\" \"\"  \n[3729,] \"India\" \"\"  \n[3730,] \"India\" \"\"  \n[3731,] \"India\" \"\"  \n[3732,] \"India\" \"\"  \n[3733,] \"India\" \"\"  \n[3734,] \"India\" \"\"  \n[3735,] \"India\" \"\"  \n[3736,] \"India\" \"\"  \n[3737,] \"India\" \"\"  \n[3738,] \"India\" \"\"  \n[3739,] \"India\" \"\"  \n[3740,] \"India\" \"\"  \n[3741,] \"India\" \"\"  \n[3742,] \"India\" \"\"  \n[3743,] \"India\" \"\"  \n[3744,] \"India\" \"\"  \n[3745,] \"India\" \"\"  \n[3746,] \"India\" \"\"  \n[3747,] \"India\" \"\"  \n[3748,] \"India\" \"\"  \n[3749,] \"India\" \"\"  \n[3750,] \"India\" \"\"  \n[3751,] \"India\" \"\"  \n[3752,] \"India\" \"\"  \n[3753,] \"India\" \"\"  \n[3754,] \"India\" \"\"  \n[3755,] \"India\" \"\"  \n[3756,] \"India\" \"\"  \n[3757,] \"India\" \"\"  \n[3758,] \"India\" \"\"  \n[3759,] \"India\" \"\"  \n[3760,] \"India\" \"\"  \n[3761,] \"India\" \"\"  \n[3762,] \"India\" \"\"  \n[3763,] \"India\" \"\"  \n[3764,] \"India\" \"\"  \n[3765,] \"India\" \"\"  \n[3766,] \"India\" \"\"  \n[3767,] \"India\" \"\"  \n[3768,] \"India\" \"\"  \n[3769,] \"India\" \"\"  \n[3770,] \"India\" \"\"  \n[3771,] \"India\" \"\"  \n[3772,] \"India\" \"\"  \n[3773,] \"India\" \"\"  \n[3774,] \"India\" \"\"  \n[3775,] \"India\" \"\"  \n[3776,] \"India\" \"\"  \n[3777,] \"India\" \"\"  \n[3778,] \"India\" \"\"  \n[3779,] \"India\" \"\"  \n[3780,] \"India\" \"\"  \n[3781,] \"India\" \"\"  \n[3782,] \"India\" \"\"  \n[3783,] \"India\" \"\"  \n[3784,] \"India\" \"\"  \n[3785,] \"India\" \"\"  \n[3786,] \"India\" \"\"  \n[3787,] \"India\" \"\"  \n[3788,] \"India\" \"\"  \n[3789,] \"India\" \"\"  \n[3790,] \"India\" \"\"  \n[3791,] \"India\" \"\"  \n[3792,] \"India\" \"\"  \n[3793,] \"India\" \"\"  \n[3794,] \"India\" \"\"  \n[3795,] \"India\" \"\"  \n[3796,] \"India\" \"\"  \n[3797,] \"India\" \"\"  \n[3798,] \"India\" \"\"  \n[3799,] \"India\" \"\"  \n[3800,] \"India\" \"\"  \n[3801,] \"India\" \"\"  \n[3802,] \"India\" \"\"  \n[3803,] \"India\" \"\"  \n[3804,] \"India\" \"\"  \n[3805,] \"India\" \"\"  \n[3806,] \"India\" \"\"  \n[3807,] \"India\" \"\"  \n[3808,] \"India\" \"\"  \n[3809,] \"India\" \"\"  \n[3810,] \"India\" \"\"  \n[3811,] \"India\" \"\"  \n[3812,] \"India\" \"\"  \n[3813,] \"India\" \"\"  \n[3814,] \"India\" \"\"  \n[3815,] \"India\" \"\"  \n[3816,] \"India\" \"\"  \n[3817,] \"India\" \"\"  \n[3818,] \"India\" \"\"  \n[3819,] \"India\" \"\"  \n[3820,] \"India\" \"\"  \n[3821,] \"India\" \"\"  \n[3822,] \"India\" \"\"  \n[3823,] \"India\" \"\"  \n[3824,] \"India\" \"\"  \n[3825,] \"India\" \"\"  \n[3826,] \"India\" \"\"  \n[3827,] \"India\" \"\"  \n[3828,] \"India\" \"\"  \n[3829,] \"India\" \"\"  \n[3830,] \"India\" \"\"  \n[3831,] \"India\" \"\"  \n[3832,] \"India\" \"\"  \n[3833,] \"India\" \"\"  \n[3834,] \"India\" \"\"  \n[3835,] \"India\" \"\"  \n[3836,] \"India\" \"\"  \n[3837,] \"India\" \"\"  \n[3838,] \"India\" \"\"  \n[3839,] \"India\" \"\"  \n[3840,] \"India\" \"\"  \n[3841,] \"India\" \"\"  \n[3842,] \"India\" \"\"  \n[3843,] \"India\" \"\"  \n[3844,] \"India\" \"\"  \n[3845,] \"India\" \"\"  \n[3846,] \"India\" \"\"  \n[3847,] \"India\" \"\"  \n[3848,] \"India\" \"\"  \n[3849,] \"India\" \"\"  \n[3850,] \"India\" \"\"  \n[3851,] \"India\" \"\"  \n[3852,] \"India\" \"\"  \n[3853,] \"India\" \"\"  \n[3854,] \"India\" \"\"  \n[3855,] \"India\" \"\"  \n[3856,] \"India\" \"\"  \n[3857,] \"India\" \"\"  \n[3858,] \"India\" \"\"  \n[3859,] \"India\" \"\"  \n[3860,] \"India\" \"\"  \n[3861,] \"India\" \"\"  \n[3862,] \"India\" \"\"  \n[3863,] \"India\" \"\"  \n[3864,] \"India\" \"\"  \n[3865,] \"India\" \"\"  \n[3866,] \"India\" \"\"  \n[3867,] \"India\" \"\"  \n[3868,] \"India\" \"\"  \n[3869,] \"India\" \"\"  \n[3870,] \"India\" \"\"  \n[3871,] \"India\" \"\"  \n[3872,] \"India\" \"\"  \n[3873,] \"India\" \"\"  \n[3874,] \"India\" \"\"  \n[3875,] \"India\" \"\"  \n[3876,] \"India\" \"\"  \n[3877,] \"India\" \"\"  \n[3878,] \"India\" \"\"  \n[3879,] \"India\" \"\"  \n[3880,] \"India\" \"\"  \n[3881,] \"India\" \"\"  \n[3882,] \"India\" \"\"  \n[3883,] \"India\" \"\"  \n[3884,] \"India\" \"\"  \n[3885,] \"India\" \"\"  \n[3886,] \"India\" \"\"  \n[3887,] \"India\" \"\"  \n[3888,] \"India\" \"\"  \n[3889,] \"India\" \"\"  \n[3890,] \"India\" \"\"  \n[3891,] \"India\" \"\"  \n[3892,] \"India\" \"\"  \n[3893,] \"India\" \"\"  \n[3894,] \"India\" \"\"  \n[3895,] \"India\" \"\"  \n[3896,] \"India\" \"\"  \n[3897,] \"India\" \"\"  \n[3898,] \"India\" \"\"  \n[3899,] \"India\" \"\"  \n[3900,] \"India\" \"\"  \n[3901,] \"India\" \"\"  \n[3902,] \"India\" \"\"  \n[3903,] \"India\" \"\"  \n[3904,] \"India\" \"\"  \n[3905,] \"India\" \"\"  \n[3906,] \"India\" \"\"  \n[3907,] \"India\" \"\"  \n[3908,] \"India\" \"\"  \n[3909,] \"India\" \"\"  \n[3910,] \"India\" \"\"  \n[3911,] \"India\" \"\"  \n[3912,] \"India\" \"\"  \n[3913,] \"India\" \"\"  \n[3914,] \"India\" \"\"  \n[3915,] \"India\" \"\"  \n[3916,] \"India\" \"\"  \n[3917,] \"India\" \"\"  \n[3918,] \"India\" \"\"  \n[3919,] \"India\" \"\"  \n[3920,] \"India\" \"\"  \n[3921,] \"India\" \"\"  \n[3922,] \"India\" \"\"  \n[3923,] \"India\" \"\"  \n[3924,] \"India\" \"\"  \n[3925,] \"India\" \"\"  \n[3926,] \"India\" \"\"  \n[3927,] \"India\" \"\"  \n[3928,] \"India\" \"\"  \n[3929,] \"India\" \"\"  \n[3930,] \"India\" \"\"  \n[3931,] \"India\" \"\"  \n[3932,] \"India\" \"\"  \n[3933,] \"India\" \"\"  \n[3934,] \"India\" \"\"  \n[3935,] \"India\" \"\"  \n[3936,] \"India\" \"\"  \n[3937,] \"India\" \"\"  \n[3938,] \"India\" \"\"  \n[3939,] \"India\" \"\"  \n[3940,] \"India\" \"\"  \n[3941,] \"India\" \"\"  \n[3942,] \"India\" \"\"  \n[3943,] \"India\" \"\"  \n[3944,] \"India\" \"\"  \n[3945,] \"India\" \"\"  \n[3946,] \"India\" \"\"  \n[3947,] \"India\" \"\"  \n[3948,] \"India\" \"\"  \n[3949,] \"India\" \"\"  \n[3950,] \"India\" \"\"  \n[3951,] \"India\" \"\"  \n[3952,] \"India\" \"\"  \n[3953,] \"India\" \"\"  \n[3954,] \"India\" \"\"  \n[3955,] \"India\" \"\"  \n[3956,] \"India\" \"\"  \n[3957,] \"India\" \"\"  \n[3958,] \"India\" \"\"  \n[3959,] \"India\" \"\"  \n[3960,] \"India\" \"\"  \n[3961,] \"India\" \"\"  \n[3962,] \"India\" \"\"  \n[3963,] \"India\" \"\"  \n[3964,] \"India\" \"\"  \n[3965,] \"India\" \"\"  \n[3966,] \"India\" \"\"  \n[3967,] \"India\" \"\"  \n[3968,] \"India\" \"\"  \n[3969,] \"India\" \"\"  \n[3970,] \"India\" \"\"  \n[3971,] \"India\" \"\"  \n[3972,] \"India\" \"\"  \n[3973,] \"India\" \"\"  \n[3974,] \"India\" \"\"  \n[3975,] \"India\" \"\"  \n[3976,] \"India\" \"\"  \n[3977,] \"India\" \"\"  \n[3978,] \"India\" \"\"  \n[3979,] \"India\" \"\"  \n[3980,] \"India\" \"\"  \n[3981,] \"India\" \"\"  \n[3982,] \"India\" \"\"  \n[3983,] \"India\" \"\"  \n[3984,] \"India\" \"\"  \n[3985,] \"India\" \"\"  \n[3986,] \"India\" \"\"  \n[3987,] \"India\" \"\"  \n[3988,] \"India\" \"\"  \n[3989,] \"India\" \"\"  \n[3990,] \"India\" \"\"  \n[3991,] \"India\" \"\"  \n[3992,] \"India\" \"\"  \n[3993,] \"India\" \"\"  \n[3994,] \"India\" \"\"  \n[3995,] \"India\" \"\"  \n[3996,] \"India\" \"\"  \n[3997,] \"India\" \"\"  \n[3998,] \"India\" \"\"  \n[3999,] \"India\" \"\"  \n[4000,] \"India\" \"\"  \n[4001,] \"India\" \"\"  \n[4002,] \"India\" \"\"  \n[4003,] \"India\" \"\"  \n[4004,] \"India\" \"\"  \n[4005,] \"India\" \"\"  \n[4006,] \"India\" \"\"  \n[4007,] \"India\" \"\"  \n[4008,] \"India\" \"\"  \n[4009,] \"India\" \"\"  \n[4010,] \"India\" \"\"  \n[4011,] \"India\" \"\"  \n[4012,] \"India\" \"\"  \n[4013,] \"India\" \"\"  \n[4014,] \"India\" \"\"  \n[4015,] \"India\" \"\"  \n[4016,] \"India\" \"\"  \n[4017,] \"India\" \"\"  \n[4018,] \"India\" \"\"  \n[4019,] \"India\" \"\"  \n[4020,] \"India\" \"\"  \n[4021,] \"India\" \"\"  \n[4022,] \"India\" \"\"  \n[4023,] \"India\" \"\"  \n[4024,] \"India\" \"\"  \n[4025,] \"India\" \"\"  \n[4026,] \"India\" \"\"  \n[4027,] \"India\" \"\"  \n[4028,] \"India\" \"\"  \n[4029,] \"India\" \"\"  \n[4030,] \"India\" \"\"  \n[4031,] \"India\" \"\"  \n[4032,] \"India\" \"\"  \n[4033,] \"India\" \"\"  \n[4034,] \"India\" \"\"  \n[4035,] \"India\" \"\"  \n[4036,] \"India\" \"\"  \n[4037,] \"India\" \"\"  \n[4038,] \"India\" \"\"  \n[4039,] \"India\" \"\"  \n[4040,] \"India\" \"\"  \n[4041,] \"India\" \"\"  \n[4042,] \"India\" \"\"  \n[4043,] \"India\" \"\"  \n[4044,] \"India\" \"\"  \n[4045,] \"India\" \"\"  \n[4046,] \"India\" \"\"  \n[4047,] \"India\" \"\"  \n[4048,] \"India\" \"\"  \n[4049,] \"India\" \"\"  \n[4050,] \"India\" \"\"  \n[4051,] \"India\" \"\"  \n[4052,] \"India\" \"\"  \n[4053,] \"India\" \"\"  \n[4054,] \"India\" \"\"  \n[4055,] \"India\" \"\"  \n[4056,] \"India\" \"\"  \n[4057,] \"India\" \"\"  \n[4058,] \"India\" \"\"  \n[4059,] \"India\" \"\"  \n[4060,] \"India\" \"\"  \n[4061,] \"India\" \"\"  \n[4062,] \"India\" \"\"  \n[4063,] \"India\" \"\"  \n[4064,] \"India\" \"\"  \n[4065,] \"India\" \"\"  \n[4066,] \"India\" \"\"  \n[4067,] \"India\" \"\"  \n[4068,] \"India\" \"\"  \n[4069,] \"India\" \"\"  \n[4070,] \"India\" \"\"  \n[4071,] \"India\" \"\"  \n[4072,] \"India\" \"\"  \n[4073,] \"India\" \"\"  \n[4074,] \"India\" \"\"  \n[4075,] \"India\" \"\"  \n[4076,] \"India\" \"\"  \n[4077,] \"India\" \"\"  \n[4078,] \"India\" \"\"  \n[4079,] \"India\" \"\"  \n[4080,] \"India\" \"\"  \n[4081,] \"India\" \"\"  \n[4082,] \"India\" \"\"  \n[4083,] \"India\" \"\"  \n[4084,] \"India\" \"\"  \n[4085,] \"India\" \"\"  \n[4086,] \"India\" \"\"  \n[4087,] \"India\" \"\"  \n[4088,] \"India\" \"\"  \n[4089,] \"India\" \"\"  \n[4090,] \"India\" \"\"  \n[4091,] \"India\" \"\"  \n[4092,] \"India\" \"\"  \n[4093,] \"India\" \"\"  \n[4094,] \"India\" \"\"  \n[4095,] \"India\" \"\"  \n[4096,] \"India\" \"\"  \n[4097,] \"India\" \"\"  \n[4098,] \"India\" \"\"  \n[4099,] \"India\" \"\"  \n[4100,] \"India\" \"\"  \n[4101,] \"India\" \"\"  \n[4102,] \"India\" \"\"  \n[4103,] \"India\" \"\"  \n[4104,] \"India\" \"\"  \n[4105,] \"India\" \"\"  \n[4106,] \"India\" \"\"  \n[4107,] \"India\" \"\"  \n[4108,] \"India\" \"\"  \n[4109,] \"India\" \"\"  \n[4110,] \"India\" \"\"  \n[4111,] \"India\" \"\"  \n[4112,] \"India\" \"\"  \n[4113,] \"India\" \"\"  \n[4114,] \"India\" \"\"  \n[4115,] \"India\" \"\"  \n[4116,] \"India\" \"\"  \n[4117,] \"India\" \"\"  \n[4118,] \"India\" \"\"  \n[4119,] \"India\" \"\"  \n[4120,] \"India\" \"\"  \n[4121,] \"India\" \"\"  \n[4122,] \"India\" \"\"  \n[4123,] \"India\" \"\"  \n[4124,] \"India\" \"\"  \n[4125,] \"India\" \"\"  \n[4126,] \"India\" \"\"  \n[4127,] \"India\" \"\"  \n[4128,] \"India\" \"\"  \n[4129,] \"India\" \"\"  \n[4130,] \"India\" \"\"  \n[4131,] \"India\" \"\"  \n[4132,] \"India\" \"\"  \n[4133,] \"India\" \"\"  \n[4134,] \"India\" \"\"  \n[4135,] \"India\" \"\"  \n[4136,] \"India\" \"\"  \n[4137,] \"India\" \"\"  \n[4138,] \"India\" \"\"  \n[4139,] \"India\" \"\"  \n[4140,] \"India\" \"\"  \n[4141,] \"India\" \"\"  \n[4142,] \"India\" \"\"  \n[4143,] \"India\" \"\"  \n[4144,] \"India\" \"\"  \n[4145,] \"India\" \"\"  \n[4146,] \"India\" \"\"  \n[4147,] \"India\" \"\"  \n[4148,] \"India\" \"\"  \n[4149,] \"India\" \"\"  \n[4150,] \"India\" \"\"  \n[4151,] \"India\" \"\"  \n[4152,] \"India\" \"\"  \n[4153,] \"India\" \"\"  \n[4154,] \"India\" \"\"  \n[4155,] \"India\" \"\"  \n[4156,] \"India\" \"\"  \n[4157,] \"India\" \"\"  \n[4158,] \"India\" \"\"  \n[4159,] \"India\" \"\"  \n[4160,] \"India\" \"\"  \n[4161,] \"India\" \"\"  \n[4162,] \"India\" \"\"  \n[4163,] \"India\" \"\"  \n[4164,] \"India\" \"\"  \n[4165,] \"India\" \"\"  \n[4166,] \"India\" \"\"  \n[4167,] \"India\" \"\"  \n[4168,] \"India\" \"\"  \n[4169,] \"India\" \"\"  \n[4170,] \"India\" \"\"  \n[4171,] \"India\" \"\"  \n[4172,] \"India\" \"\"  \n[4173,] \"India\" \"\"  \n[4174,] \"India\" \"\"  \n[4175,] \"India\" \"\"  \n[4176,] \"India\" \"\"  \n[4177,] \"India\" \"\"  \n[4178,] \"India\" \"\"  \n[4179,] \"India\" \"\"  \n[4180,] \"India\" \"\"  \n[4181,] \"India\" \"\"  \n[4182,] \"India\" \"\"  \n[4183,] \"India\" \"\"  \n[4184,] \"India\" \"\"  \n[4185,] \"India\" \"\"  \n[4186,] \"India\" \"\"  \n[4187,] \"India\" \"\"  \n[4188,] \"India\" \"\"  \n[4189,] \"India\" \"\"  \n[4190,] \"India\" \"\"  \n[4191,] \"India\" \"\"  \n[4192,] \"India\" \"\"  \n[4193,] \"India\" \"\"  \n[4194,] \"India\" \"\"  \n[4195,] \"India\" \"\"  \n[4196,] \"India\" \"\"  \n[4197,] \"India\" \"\"  \n[4198,] \"India\" \"\"  \n[4199,] \"India\" \"\"  \n[4200,] \"India\" \"\"  \n[4201,] \"India\" \"\"  \n[4202,] \"India\" \"\"  \n[4203,] \"India\" \"\"  \n[4204,] \"India\" \"\"  \n[4205,] \"India\" \"\"  \n[4206,] \"India\" \"\"  \n[4207,] \"India\" \"\"  \n[4208,] \"India\" \"\"  \n[4209,] \"India\" \"\"  \n[4210,] \"India\" \"\"  \n[4211,] \"India\" \"\"  \n[4212,] \"India\" \"\"  \n[4213,] \"India\" \"\"  \n[4214,] \"India\" \"\"  \n[4215,] \"India\" \"\"  \n[4216,] \"India\" \"\"  \n[4217,] \"India\" \"\"  \n[4218,] \"India\" \"\"  \n[4219,] \"India\" \"\"  \n[4220,] \"India\" \"\"  \n[4221,] \"India\" \"\"  \n[4222,] \"India\" \"\"  \n[4223,] \"India\" \"\"  \n[4224,] \"India\" \"\"  \n[4225,] \"India\" \"\"  \n[4226,] \"India\" \"\"  \n[4227,] \"India\" \"\"  \n[4228,] \"India\" \"\"  \n[4229,] \"India\" \"\"  \n[4230,] \"India\" \"\"  \n[4231,] \"India\" \"\"  \n[4232,] \"India\" \"\"  \n[4233,] \"India\" \"\"  \n[4234,] \"India\" \"\"  \n[4235,] \"India\" \"\"  \n[4236,] \"India\" \"\"  \n[4237,] \"India\" \"\"  \n[4238,] \"India\" \"\"  \n[4239,] \"India\" \"\"  \n[4240,] \"India\" \"\"  \n[4241,] \"India\" \"\"  \n[4242,] \"India\" \"\"  \n[4243,] \"India\" \"\"  \n[4244,] \"India\" \"\"  \n[4245,] \"India\" \"\"  \n[4246,] \"India\" \"\"  \n[4247,] \"India\" \"\"  \n[4248,] \"India\" \"\"  \n[4249,] \"India\" \"\"  \n[4250,] \"India\" \"\"  \n[4251,] \"India\" \"\"  \n[4252,] \"India\" \"\"  \n[4253,] \"India\" \"\"  \n[4254,] \"India\" \"\"  \n[4255,] \"India\" \"\"  \n[4256,] \"India\" \"\"  \n[4257,] \"India\" \"\"  \n[4258,] \"India\" \"\"  \n[4259,] \"India\" \"\"  \n[4260,] \"India\" \"\"  \n[4261,] \"India\" \"\"  \n[4262,] \"India\" \"\"  \n[4263,] \"India\" \"\"  \n[4264,] \"India\" \"\"  \n[4265,] \"India\" \"\"  \n[4266,] \"India\" \"\"  \n[4267,] \"India\" \"\"  \n[4268,] \"India\" \"\"  \n[4269,] \"India\" \"\"  \n[4270,] \"India\" \"\"  \n[4271,] \"India\" \"\"  \n[4272,] \"India\" \"\"  \n[4273,] \"India\" \"\"  \n[4274,] \"India\" \"\"  \n[4275,] \"India\" \"\"  \n[4276,] \"India\" \"\"  \n[4277,] \"India\" \"\"  \n[4278,] \"India\" \"\"  \n[4279,] \"India\" \"\"  \n[4280,] \"India\" \"\"  \n[4281,] \"India\" \"\"  \n[4282,] \"India\" \"\"  \n[4283,] \"India\" \"\"  \n[4284,] \"India\" \"\"  \n[4285,] \"India\" \"\"  \n[4286,] \"India\" \"\"  \n[4287,] \"India\" \"\"  \n[4288,] \"India\" \"\"  \n[4289,] \"India\" \"\"  \n[4290,] \"India\" \"\"  \n[4291,] \"India\" \"\"  \n[4292,] \"India\" \"\"  \n[4293,] \"India\" \"\"  \n[4294,] \"India\" \"\"  \n[4295,] \"India\" \"\"  \n[4296,] \"India\" \"\"  \n[4297,] \"India\" \"\"  \n[4298,] \"India\" \"\"  \n[4299,] \"India\" \"\"  \n[4300,] \"India\" \"\"  \n[4301,] \"India\" \"\"  \n[4302,] \"India\" \"\"  \n[4303,] \"India\" \"\"  \n[4304,] \"India\" \"\"  \n[4305,] \"India\" \"\"  \n[4306,] \"India\" \"\"  \n[4307,] \"India\" \"\"  \n[4308,] \"India\" \"\"  \n[4309,] \"India\" \"\"  \n[4310,] \"India\" \"\"  \n[4311,] \"India\" \"\"  \n[4312,] \"India\" \"\"  \n[4313,] \"India\" \"\"  \n[4314,] \"India\" \"\"  \n[4315,] \"India\" \"\"  \n[4316,] \"India\" \"\"  \n[4317,] \"India\" \"\"  \n[4318,] \"India\" \"\"  \n[4319,] \"India\" \"\"  \n[4320,] \"India\" \"\"  \n[4321,] \"India\" \"\"  \n[4322,] \"India\" \"\"  \n[4323,] \"India\" \"\"  \n[4324,] \"India\" \"\"  \n[4325,] \"India\" \"\"  \n[4326,] \"India\" \"\"  \n[4327,] \"India\" \"\"  \n[4328,] \"India\" \"\"  \n[4329,] \"India\" \"\"  \n[4330,] \"India\" \"\"  \n[4331,] \"India\" \"\"  \n[4332,] \"India\" \"\"  \n[4333,] \"India\" \"\"  \n[4334,] \"India\" \"\"  \n[4335,] \"India\" \"\"  \n[4336,] \"India\" \"\"  \n[4337,] \"India\" \"\"  \n[4338,] \"India\" \"\"  \n[4339,] \"India\" \"\"  \n[4340,] \"India\" \"\"  \n[4341,] \"India\" \"\"  \n[4342,] \"India\" \"\"  \n[4343,] \"India\" \"\"  \n[4344,] \"India\" \"\"  \n[4345,] \"India\" \"\"  \n[4346,] \"India\" \"\"  \n[4347,] \"India\" \"\"  \n[4348,] \"India\" \"\"  \n[4349,] \"India\" \"\"  \n[4350,] \"India\" \"\"  \n[4351,] \"India\" \"\"  \n[4352,] \"India\" \"\"  \n[4353,] \"India\" \"\"  \n[4354,] \"India\" \"\"  \n[4355,] \"India\" \"\"  \n[4356,] \"India\" \"\"  \n[4357,] \"India\" \"\"  \n[4358,] \"India\" \"\"  \n[4359,] \"India\" \"\"  \n[4360,] \"India\" \"\"  \n[4361,] \"India\" \"\"  \n[4362,] \"India\" \"\"  \n[4363,] \"India\" \"\"  \n[4364,] \"India\" \"\"  \n[4365,] \"India\" \"\"  \n[4366,] \"India\" \"\"  \n[4367,] \"India\" \"\"  \n[4368,] \"India\" \"\"  \n[4369,] \"India\" \"\"  \n[4370,] \"India\" \"\"  \n[4371,] \"India\" \"\"  \n[4372,] \"India\" \"\"  \n[4373,] \"India\" \"\"  \n[4374,] \"India\" \"\"  \n[4375,] \"India\" \"\"  \n[4376,] \"India\" \"\"  \n[4377,] \"India\" \"\"  \n[4378,] \"India\" \"\"  \n[4379,] \"India\" \"\"  \n[4380,] \"India\" \"\"  \n[4381,] \"India\" \"\"  \n[4382,] \"India\" \"\"  \n[4383,] \"India\" \"\"  \n[4384,] \"India\" \"\"  \n[4385,] \"India\" \"\"  \n[4386,] \"India\" \"\"  \n[4387,] \"India\" \"\"  \n[4388,] \"India\" \"\"  \n[4389,] \"India\" \"\"  \n[4390,] \"India\" \"\"  \n[4391,] \"India\" \"\"  \n[4392,] \"India\" \"\"  \n[4393,] \"India\" \"\"  \n[4394,] \"India\" \"\"  \n[4395,] \"India\" \"\"  \n[4396,] \"India\" \"\"  \n[4397,] \"India\" \"\"  \n[4398,] \"India\" \"\"  \n[4399,] \"India\" \"\"  \n[4400,] \"India\" \"\"  \n[4401,] \"India\" \"\"  \n[4402,] \"India\" \"\"  \n[4403,] \"India\" \"\"  \n[4404,] \"India\" \"\"  \n[4405,] \"India\" \"\"  \n[4406,] \"India\" \"\"  \n[4407,] \"India\" \"\"  \n[4408,] \"India\" \"\"  \n[4409,] \"India\" \"\"  \n[4410,] \"India\" \"\"  \n[4411,] \"India\" \"\"  \n[4412,] \"India\" \"\"  \n[4413,] \"India\" \"\"  \n[4414,] \"India\" \"\"  \n[4415,] \"India\" \"\"  \n[4416,] \"India\" \"\"  \n[4417,] \"India\" \"\"  \n[4418,] \"India\" \"\"  \n[4419,] \"India\" \"\"  \n[4420,] \"India\" \"\"  \n[4421,] \"India\" \"\"  \n[4422,] \"India\" \"\"  \n[4423,] \"India\" \"\"  \n[4424,] \"India\" \"\"  \n[4425,] \"India\" \"\"  \n[4426,] \"India\" \"\"  \n[4427,] \"India\" \"\"  \n[4428,] \"India\" \"\"  \n[4429,] \"India\" \"\"  \n[4430,] \"India\" \"\"  \n[4431,] \"India\" \"\"  \n[4432,] \"India\" \"\"  \n[4433,] \"India\" \"\"  \n[4434,] \"India\" \"\"  \n[4435,] \"India\" \"\"  \n[4436,] \"India\" \"\"  \n[4437,] \"India\" \"\"  \n[4438,] \"India\" \"\"  \n[4439,] \"India\" \"\"  \n[4440,] \"India\" \"\"  \n[4441,] \"India\" \"\"  \n[4442,] \"India\" \"\"  \n[4443,] \"India\" \"\"  \n[4444,] \"India\" \"\"  \n[4445,] \"India\" \"\"  \n[4446,] \"India\" \"\"  \n[4447,] \"India\" \"\"  \n[4448,] \"India\" \"\"  \n[4449,] \"India\" \"\"  \n[4450,] \"India\" \"\"  \n[4451,] \"India\" \"\"  \n[4452,] \"India\" \"\"  \n[4453,] \"India\" \"\"  \n[4454,] \"India\" \"\"  \n[4455,] \"India\" \"\"  \n[4456,] \"India\" \"\"  \n[4457,] \"India\" \"\"  \n[4458,] \"India\" \"\"  \n[4459,] \"India\" \"\"  \n[4460,] \"India\" \"\"  \n[4461,] \"India\" \"\"  \n[4462,] \"India\" \"\"  \n[4463,] \"India\" \"\"  \n[4464,] \"India\" \"\"  \n[4465,] \"India\" \"\"  \n[4466,] \"India\" \"\"  \n[4467,] \"India\" \"\"  \n[4468,] \"India\" \"\"  \n[4469,] \"India\" \"\"  \n[4470,] \"India\" \"\"  \n[4471,] \"India\" \"\"  \n[4472,] \"India\" \"\"  \n[4473,] \"India\" \"\"  \n[4474,] \"India\" \"\"  \n[4475,] \"India\" \"\"  \n[4476,] \"India\" \"\"  \n[4477,] \"India\" \"\"  \n[4478,] \"India\" \"\"  \n[4479,] \"India\" \"\"  \n[4480,] \"India\" \"\"  \n[4481,] \"India\" \"\"  \n[4482,] \"India\" \"\"  \n[4483,] \"India\" \"\"  \n[4484,] \"India\" \"\"  \n[4485,] \"India\" \"\"  \n[4486,] \"India\" \"\"  \n[4487,] \"India\" \"\"  \n[4488,] \"India\" \"\"  \n[4489,] \"India\" \"\"  \n[4490,] \"India\" \"\"  \n[4491,] \"India\" \"\"  \n[4492,] \"India\" \"\"  \n[4493,] \"India\" \"\"  \n[4494,] \"India\" \"\"  \n[4495,] \"India\" \"\"  \n[4496,] \"India\" \"\"  \n[4497,] \"India\" \"\"  \n[4498,] \"India\" \"\"  \n[4499,] \"India\" \"\"  \n[4500,] \"India\" \"\"  \n[4501,] \"India\" \"\"  \n[4502,] \"India\" \"\"  \n[4503,] \"India\" \"\"  \n[4504,] \"India\" \"\"  \n[4505,] \"India\" \"\"  \n[4506,] \"India\" \"\"  \n[4507,] \"India\" \"\"  \n[4508,] \"India\" \"\"  \n[4509,] \"India\" \"\"  \n[4510,] \"India\" \"\"  \n[4511,] \"India\" \"\"  \n[4512,] \"India\" \"\"  \n[4513,] \"India\" \"\"  \n[4514,] \"India\" \"\"  \n[4515,] \"India\" \"\"  \n[4516,] \"India\" \"\"  \n[4517,] \"India\" \"\"  \n[4518,] \"India\" \"\"  \n[4519,] \"India\" \"\"  \n[4520,] \"India\" \"\"  \n[4521,] \"India\" \"\"  \n[4522,] \"India\" \"\"  \n[4523,] \"India\" \"\"  \n[4524,] \"India\" \"\"  \n[4525,] \"India\" \"\"  \n[4526,] \"India\" \"\"  \n[4527,] \"India\" \"\"  \n[4528,] \"India\" \"\"  \n[4529,] \"India\" \"\"  \n[4530,] \"India\" \"\"  \n[4531,] \"India\" \"\"  \n[4532,] \"India\" \"\"  \n[4533,] \"India\" \"\"  \n[4534,] \"India\" \"\"  \n[4535,] \"India\" \"\"  \n[4536,] \"India\" \"\"  \n[4537,] \"India\" \"\"  \n[4538,] \"India\" \"\"  \n[4539,] \"India\" \"\"  \n[4540,] \"India\" \"\"  \n[4541,] \"India\" \"\"  \n[4542,] \"India\" \"\"  \n[4543,] \"India\" \"\"  \n[4544,] \"India\" \"\"  \n[4545,] \"India\" \"\"  \n[4546,] \"India\" \"\"  \n[4547,] \"India\" \"\"  \n[4548,] \"India\" \"\"  \n[4549,] \"India\" \"\"  \n[4550,] \"India\" \"\"  \n[4551,] \"India\" \"\"  \n[4552,] \"India\" \"\"  \n[4553,] \"India\" \"\"  \n[4554,] \"India\" \"\"  \n[4555,] \"India\" \"\"  \n[4556,] \"India\" \"\"  \n[4557,] \"India\" \"\"  \n[4558,] \"India\" \"\"  \n[4559,] \"India\" \"\"  \n[4560,] \"India\" \"\"  \n[4561,] \"India\" \"\"  \n[4562,] \"India\" \"\"  \n[4563,] \"India\" \"\"  \n[4564,] \"India\" \"\"  \n[4565,] \"India\" \"\"  \n[4566,] \"India\" \"\"  \n[4567,] \"India\" \"\"  \n[4568,] \"India\" \"\"  \n[4569,] \"India\" \"\"  \n[4570,] \"India\" \"\"  \n[4571,] \"India\" \"\"  \n[4572,] \"India\" \"\"  \n[4573,] \"India\" \"\"  \n[4574,] \"India\" \"\"  \n[4575,] \"India\" \"\"  \n[4576,] \"India\" \"\"  \n[4577,] \"India\" \"\"  \n[4578,] \"India\" \"\"  \n[4579,] \"India\" \"\"  \n[4580,] \"India\" \"\"  \n[4581,] \"India\" \"\"  \n[4582,] \"India\" \"\"  \n[4583,] \"India\" \"\"  \n[4584,] \"India\" \"\"  \n[4585,] \"India\" \"\"  \n[4586,] \"India\" \"\"  \n[4587,] \"India\" \"\"  \n[4588,] \"India\" \"\"  \n[4589,] \"India\" \"\"  \n[4590,] \"India\" \"\"  \n[4591,] \"India\" \"\"  \n[4592,] \"India\" \"\"  \n[4593,] \"India\" \"\"  \n[4594,] \"India\" \"\"  \n[4595,] \"India\" \"\"  \n[4596,] \"India\" \"\"  \n[4597,] \"India\" \"\"  \n[4598,] \"India\" \"\"  \n[4599,] \"India\" \"\"  \n[4600,] \"India\" \"\"  \n[4601,] \"India\" \"\"  \n[4602,] \"India\" \"\"  \n[4603,] \"India\" \"\"  \n[4604,] \"India\" \"\"  \n[4605,] \"India\" \"\"  \n[4606,] \"India\" \"\"  \n[4607,] \"India\" \"\"  \n[4608,] \"India\" \"\"  \n[4609,] \"India\" \"\"  \n[4610,] \"India\" \"\"  \n[4611,] \"India\" \"\"  \n[4612,] \"India\" \"\"  \n[4613,] \"India\" \"\"  \n[4614,] \"India\" \"\"  \n[4615,] \"India\" \"\"  \n[4616,] \"India\" \"\"  \n[4617,] \"India\" \"\"  \n[4618,] \"India\" \"\"  \n[4619,] \"India\" \"\"  \n[4620,] \"India\" \"\"  \n[4621,] \"India\" \"\"  \n[4622,] \"India\" \"\"  \n[4623,] \"India\" \"\"  \n[4624,] \"India\" \"\"  \n[4625,] \"India\" \"\"  \n[4626,] \"India\" \"\"  \n[4627,] \"India\" \"\"  \n[4628,] \"India\" \"\"  \n[4629,] \"India\" \"\"  \n[4630,] \"India\" \"\"  \n[4631,] \"India\" \"\"  \n[4632,] \"India\" \"\"  \n[4633,] \"India\" \"\"  \n[4634,] \"India\" \"\"  \n[4635,] \"India\" \"\"  \n[4636,] \"India\" \"\"  \n[4637,] \"India\" \"\"  \n[4638,] \"India\" \"\"  \n[4639,] \"India\" \"\"  \n[4640,] \"India\" \"\"  \n[4641,] \"India\" \"\"  \n[4642,] \"India\" \"\"  \n[4643,] \"India\" \"\"  \n[4644,] \"India\" \"\"  \n[4645,] \"India\" \"\"  \n[4646,] \"India\" \"\"  \n[4647,] \"India\" \"\"  \n[4648,] \"India\" \"\"  \n[4649,] \"India\" \"\"  \n[4650,] \"India\" \"\"  \n[4651,] \"India\" \"\"  \n[4652,] \"India\" \"\"  \n[4653,] \"India\" \"\"  \n[4654,] \"India\" \"\"  \n[4655,] \"India\" \"\"  \n[4656,] \"India\" \"\"  \n[4657,] \"India\" \"\"  \n[4658,] \"India\" \"\"  \n[4659,] \"India\" \"\"  \n[4660,] \"India\" \"\"  \n[4661,] \"India\" \"\"  \n[4662,] \"India\" \"\"  \n[4663,] \"India\" \"\"  \n[4664,] \"India\" \"\"  \n[4665,] \"India\" \"\"  \n[4666,] \"India\" \"\"  \n[4667,] \"India\" \"\"  \n[4668,] \"India\" \"\"  \n[4669,] \"India\" \"\"  \n[4670,] \"India\" \"\"  \n[4671,] \"India\" \"\"  \n[4672,] \"India\" \"\"  \n[4673,] \"India\" \"\"  \n[4674,] \"India\" \"\"  \n[4675,] \"India\" \"\"  \n[4676,] \"India\" \"\"  \n[4677,] \"India\" \"\"  \n[4678,] \"India\" \"\"  \n[4679,] \"India\" \"\"  \n[4680,] \"India\" \"\"  \n[4681,] \"India\" \"\"  \n[4682,] \"India\" \"\"  \n[4683,] \"India\" \"\"  \n[4684,] \"India\" \"\"  \n[4685,] \"India\" \"\"  \n[4686,] \"India\" \"\"  \n[4687,] \"India\" \"\"  \n[4688,] \"India\" \"\"  \n[4689,] \"India\" \"\"  \n[4690,] \"India\" \"\"  \n[4691,] \"India\" \"\"  \n[4692,] \"India\" \"\"  \n[4693,] \"India\" \"\"  \n[4694,] \"India\" \"\"  \n[4695,] \"India\" \"\"  \n[4696,] \"India\" \"\"  \n[4697,] \"India\" \"\"  \n[4698,] \"India\" \"\"  \n[4699,] \"India\" \"\"  \n[4700,] \"India\" \"\"  \n[4701,] \"India\" \"\"  \n```\n:::\n:::\n\n\nBased on the provided results, let's interpret the measures of popularity/status and role/power for the identified prominent nodes:\n\n1.  In-degree centrality:\n\n    -   Maximum in-degree: 12659\n\n    -   Minimum in-degree: 0\n\n    -   High in-degree nodes: No nodes identified\n\n    -   Low in-degree nodes: India, China, Taiwan, Brazil, USA, Mexico, Indonesia, Pakistan, United Kingdom, South Korea, France, Turkey, Egypt, Nigeria, Spain, Bangladesh, Japan, Colombia, Russia, Canada\n\nInterpretation: The maximum in-degree indicates that there is a node with the highest number of incoming connections. The minimum in-degree of 0 suggests that some nodes in the network do not have any incoming connections. The identified low in-degree nodes represent countries or concepts with relatively fewer incoming connections.\n\n2.  Out-degree centrality:\n\n    -   Maximum out-degree: 8792\n\n    -   Minimum out-degree: 0\n\n    -   High out-degree nodes: India\n\n    -   Low out-degree nodes: Linear or Logistic Regression\n\nInterpretation: The maximum out-degree suggests that India has the highest number of outgoing connections. The minimum out-degree indicates that some nodes do not have any outgoing connections. The identified low out-degree node, \"Linear or Logistic Regression,\" may represent a concept or skill that is less frequently mentioned in the dataset.\n\n3.  Bonachich power:\n\n    -   Maximum Bonachich power: 3.914278\n\n    -   Minimum Bonachich power: 0\n\n    -   High Bonachich power nodes: India\n\n    -   Low Bonachich power nodes: Linear or Logistic Regression\n\nInterpretation: The Bonachich power measures the power or influence of a node in the network. The maximum Bonachich power indicates that India has the highest power or influence in the network. The identified low Bonachich power node, \"Linear or Logistic Regression,\" may represent a concept or skill that has relatively less power or influence in the network.\n\n4.  Eigenvector centrality:\n\n    -   Maximum eigenvector centrality: 1\n\n    -   Minimum eigenvector centrality: 0.02743026\n\n    -   High eigenvector centrality nodes: India\n\n    -   Low eigenvector centrality nodes: Taiwan\n\nInterpretation: Eigenvector centrality measures the influence of a node based on both its direct connections and the influence of its neighbors. The maximum eigenvector centrality indicates that India has the highest influence in the network. The identified low eigenvector centrality node, Taiwan, may have relatively less influence compared to other nodes.\n\n5.  Derived centrality:\n\n    -   Maximum derived centrality: 6329.5\n\n    -   Minimum derived centrality: 121\n\n    -   High derived centrality nodes: No nodes identified\n\n    -   Low derived centrality nodes: Taiwan\n\nInterpretation: Derived centrality is calculated as the average of in-degree and out-degree centrality. The maximum derived centrality suggests the presence of a node with the highest average degree centrality. The minimum derived centrality indicates the presence of nodes with relatively lower average degree centrality. The identified low derived centrality node, Taiwan, has a lower average degree centrality compared to other nodes.\n\n6.  Constraint:\n\n    -   Maximum constraint: 0.5489773\n\n    -   Minimum constraint: 0.201266\n\n    -   High constraint nodes: France\n\n    -   Low constraint nodes: Linear or Logistic Regression\n\nInterpretation: Constraint measures the extent to which a node is constrained by its connections. The maximum constraint suggests that France has the highest level of constraint, indicating its position in the network. The identified low constraint node, \"Linear or Logistic Regression,\" may represent a concept or skill.\n\n#### 5. Community Detection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# Function to detect communities using Louvain method\ndetectCommunities <- function(g) {\n  # Convert graph to undirected\n  G_undirected <- as.undirected(g, mode = \"collapse\")\n  \n  # Apply Louvain method for community detection\n  communities <- cluster_louvain(G_undirected)\n  return(communities)\n}\n\n# Detect communities\ncommunities <- detectCommunities(g)\n\n# Print community membership for each node\nprint(membership(communities))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                           NA                         India \n                            1                             1 \n                        China                        Taiwan \n                            1                             1 \n                       Brazil                           USA \n                            1                             1 \n                       Mexico                     Indonesia \n                            1                             1 \n                     Pakistan                United Kingdom \n                            1                             1 \n                  South Korea                        France \n                            1                             1 \n                       Turkey                         Egypt \n                            1                             1 \n                      Nigeria                         Spain \n                            1                             1 \n                   Bangladesh                         Japan \n                            1                             1 \n                     Colombia                        Russia \n                            1                             1 \n                       Canada Linear or Logistic Regression \n                            1                             1 \n                              \n                            1 \n```\n:::\n:::\n\n\n-   Nodes: India, China, Taiwan, Brazil, USA, Mexico, Indonesia, Pakistan, United Kingdom, South Korea, France, Turkey, Egypt, Nigeria, Spain, Bangladesh, Japan, Colombia, Russia, Canada, Linear or Logistic Regression\n\n-   Interpretation: All of these nodes belong to the same community, indicating a cohesive group or core in the network. These nodes are densely connected within themselves and share common characteristics or interactions.\n\nThe presence of a single community suggests a strong interconnectedness and shared characteristics among these nodes. The behavioral implications may include strong collaboration, information exchange, and potentially shared goals or interests among these countries and concepts represented by the nodes. The influential nodes in this community, such as India, China, and the USA, may play central roles in shaping the dynamics and interactions within the community.\n\nIt's worth noting that the interpretation is based on the assumption that the Louvain method successfully captured the underlying community structure in the network. However, it's important to consider the context and specific characteristics of the network, as well as validate the community structure using additional methods or techniques.\n\nHypothesis Testing:\n\nIn section -3 of this code book answers our main research question or the hypothesis that, Countries with higher number of Master's degrees doesn't directly imply their strong Machine Learning skills network.\n\nBut according to the community detection results of the graph, it is clear that the nodes in the graph are equally distributed or they follow a linear/logistic regression. Hence it won't be possible to identify a closed group of nodes or countries in the graph at this stage of the project.\n\nHowever, I would continue to work on the data to define more functions to plot the similarity distribution of skills of these countries.\n\n#### Challenges & Conclusion:\n\n-   The first challenge is with understanding the raw data of the survey with 23998 rows and and 296 columns manipulating it according to the needs of my project where each question in the skills section has atleast 5 parts to it.\n\n-   Second challenge is with respect to the creation of similarity matrix and graph generation for ML skill-related environment between nations. The graph is not an accurate result of what I've imagined it to be and as the node degree is same for all the nodes, it became quite impossible to prove which group of countries are closely related in the skill distribution.\n\n-   This study requires further deep analysis by defining specific functions to accurately create the similarity between the nodes & edges.\n\n-   However, despite of all these challenges, I am quite happy about the follwing results I got to find through this study.\n\n-   The top 22 highest Master's degree producing countries are India, USA, Brazil, Nigeria, Pakistan, China, Japan, France, Mexico, Canada, Spain, Russia, Turkey, Columbia, Indonesia, United Kingdom, Taiwan, Bangladesh, Turkey, South Korea, Japan, Egypt.\n\n-   Data Scientist and Data Analyst are the most prominent roles in the ML & Data Science Master's community.\n\n-   Male proportion is roughly 3 times higher than women proportion in the ML & Data Science Master's community.\n\n#### References:\n\n-   2022 Kaggle Machine Learning & Data Science Survey <https://www.kaggle.com/competitions/kaggle-survey-2022/overview>\n\n-   <https://www.urban.org/sites/default/files/publication/99501/the_rise_of_masters_degrees_1.pdf>\n",
    "supporting": [
      "FinalProject_NiharikaPola_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}