{
  "hash": "52edefd7be6351358e1ab695032932c6",
  "result": {
    "markdown": "---\ntitle: \"Final Project\"\nauthor: \"Jerin Jacob\"\ndescription: \"\"\ndate: \"02/22/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n# editor: visual\ncategories: \n  - final_project\n#   output:\n# pdf_document: default\n---\n\n\n\n\n# Reading the Data\nWe are living in a world that produces a huge volume of waste everyday. It is estimated that by 2050, the global waste produced will be more than 3.4 billion tons every year. Certain industries produce large volume of waste while some other industries are considered to be cleaner than others. The world has already moved towards recycling as a part of reducing waste dumped in overall. Waste materials produced by certain industries can be used as raw material for certain other industries.\nThis project is an attempt to study the input-output data of materials between industries and the categories of wastes each industries produce. The dataset is from the 'Waste Input Output Analysis' by Nakamura, S. and Kondo, Yasushi. It is a data from Japan and therefore the economic flow is given in 1 million Japanese yen. The analysis will help us to find which all industries serve how many other industries with the goods they produce and compare it with the waste emission by each of those industires. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_2011 <- read_xlsx(\"_data/Project_data/WIO_2011.xlsx\", sheet = \"WIOdata\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nNew names:\n• `` -> `...1`\n```\n:::\n\n```{.r .cell-code}\nhead(data_2011)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 103\n  ...1      `Crop cultivation` Livestock Agricultural service…¹ Forestry Fishery\n  <chr>                  <dbl>     <dbl>                  <dbl>    <dbl>   <dbl>\n1 Crop cul…             183568    305684                   7436     2481       0\n2 Livestock              47771    238628                  14235       11       0\n3 Agricult…             337249    176157                      0       20       0\n4 Forestry                1321         0                      0    86929     216\n5 Fishery                    0         0                      0        0   54905\n6 Metallic…                  0         0                      0        0       0\n# ℹ abbreviated name: ¹​`Agricultural services`\n# ℹ 97 more variables: `Metallic ores` <dbl>, `Coal mining etc.` <dbl>,\n#   `Non-metallic ores` <dbl>, Foods <dbl>, Beverage <dbl>,\n#   `Feeds & organic fertilizer` <dbl>, Tobacco <dbl>,\n#   `Textile products` <dbl>, `Wearing apparel etc.` <dbl>,\n#   `Lumber and wood products` <dbl>, `Furniture & fixtures` <dbl>,\n#   `Pulp & paper` <dbl>, `Paper products` <dbl>, `Printing etc.` <dbl>, …\n```\n:::\n\n```{.r .cell-code}\n#data_2011\ndim(data_2011)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 294 103\n```\n:::\n:::\n\nThe dataset has 294 rows and 103 columns. We are interested in only the output flow between industries and the waste flow from industries to different waste management processes. Therefore, we can trim the data as a subset which is in the form we want.  \n## Cleaning Data\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data_2011[1:81, 1:92]\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 92\n  ...1      `Crop cultivation` Livestock Agricultural service…¹ Forestry Fishery\n  <chr>                  <dbl>     <dbl>                  <dbl>    <dbl>   <dbl>\n1 Crop cul…             183568    305684                   7436     2481       0\n2 Livestock              47771    238628                  14235       11       0\n3 Agricult…             337249    176157                      0       20       0\n4 Forestry                1321         0                      0    86929     216\n5 Fishery                    0         0                      0        0   54905\n6 Metallic…                  0         0                      0        0       0\n# ℹ abbreviated name: ¹​`Agricultural services`\n# ℹ 86 more variables: `Metallic ores` <dbl>, `Coal mining etc.` <dbl>,\n#   `Non-metallic ores` <dbl>, Foods <dbl>, Beverage <dbl>,\n#   `Feeds & organic fertilizer` <dbl>, Tobacco <dbl>,\n#   `Textile products` <dbl>, `Wearing apparel etc.` <dbl>,\n#   `Lumber and wood products` <dbl>, `Furniture & fixtures` <dbl>,\n#   `Pulp & paper` <dbl>, `Paper products` <dbl>, `Printing etc.` <dbl>, …\n```\n:::\n\n```{.r .cell-code}\nindustry_io <- data_2011[1:81, 1:82]\nwaste_io <- data_2011[1:81, c(1, 83:92)]\nhead(waste_io)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 11\n  ...1    Incineration Dehydration Concentration Shredding Filtration Composting\n  <chr>          <dbl>       <dbl>         <dbl>     <dbl>      <dbl>      <dbl>\n1 Crop c…            0           0             0         0          0          0\n2 Livest…            0           0             0         0          0          0\n3 Agricu…            0           0             0         0          0          0\n4 Forest…            0           0             0         0          0          0\n5 Fishery            0           0             0         0          0          0\n6 Metall…            0           0             0         0          0          0\n# ℹ 4 more variables: `Feed conversion` <dbl>, Gasification <dbl>,\n#   `Refuse derived fuel` <dbl>, Landfill <dbl>\n```\n:::\n:::\n\n# Creating Network\nAfter cleaning the dataset, next step is to create network data out of it. \n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- industry_io\n# Transform the data to long format\ndf_long <- melt(df, id.vars = \"...1\", variable.name = \"to\", value.name = \"weight\", variable.factor = FALSE)\n\n# Rename the \"Industries\" column to \"From\"\ncolnames(df_long)[colnames(df_long) == \"...1\"] <- \"from\"\n\n# Drop rows with weight 0\ndf_long <- df_long[df_long$weight != 0, ]\n\ndf_long <- df_long |>\n  mutate(waste_process = ifelse(to %in% c(\"Incineration\", \"Dehydration\", \"Concentration\", \"Shredding\", \"Filtration\", \"Composting\",\n                                  \"Feed conversion\", \"Gasification\", \"Refuse derived fuel\", \"Landfill\"), 1, 0))\nhead(df_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                         from               to weight waste_process\n1            Crop cultivation Crop cultivation 183568             0\n2                   Livestock Crop cultivation  47771             0\n3       Agricultural services Crop cultivation 337249             0\n4                    Forestry Crop cultivation   1321             0\n11 Feeds & organic fertilizer Crop cultivation  46056             0\n13           Textile products Crop cultivation    829             0\n```\n:::\n\n```{.r .cell-code}\ndim(df_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3822    4\n```\n:::\n:::\n\nThere are negative values in the 'weight' column. When the value is negative in directed network, it could be probably because the transaction was done in the reverse direction. So, assuming likewise, we can swap the from and to where weight is negative and then get the absolute values for weight so that we don't want to deal with anymore negative values! \n\n::: {.cell}\n\n```{.r .cell-code}\nstr(df_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t3822 obs. of  4 variables:\n $ from         : chr  \"Crop cultivation\" \"Livestock\" \"Agricultural services\" \"Forestry\" ...\n $ to           : Factor w/ 81 levels \"Crop cultivation\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ weight       : num  183568 47771 337249 1321 46056 ...\n $ waste_process: num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n\n```{.r .cell-code}\ndf_long$to <- as.character(df_long$to)\n\n\ndf_long <- df_long %>%\n  mutate(new_from = ifelse(weight < 0, to, from),\n         new_to = ifelse(weight < 0, from, to)) %>%\n  select(-c(from, to)) %>%\n  mutate(weight = abs(weight)) %>%\n  rename(from = new_from, to = new_to)\ndf_long <- df_long[, c(\"from\", \"to\", \"weight\", \"waste_process\")]\n\n\ndf_long |>\n  filter(waste_process == 1) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] from          to            weight        waste_process\n<0 rows> (or 0-length row.names)\n```\n:::\n:::\n\n\n## Creating the network\n\n::: {.cell}\n\n```{.r .cell-code}\ng_df <- graph_from_data_frame(df_long)\n# Extract the weighted vertex attribute values from the dataframe\n#vertex_attributes <- df[, 82:92]\nE(g_df)$weight <- df_long$weight\n#E(g_df)$waste_process <- df_long$waste_process\n\nprocess_names <- c(\"Incineration\", \"Dehydration\", \"Concentration\", \"Shredding\", \"Filtration\", \"Composting\",\n                   \"Feed conversion\", \"Gasification\", \"Refuse derived fuel\", \"Landfill\")\n\n# Create an empty vector to store the attribute values\nvertex_attribute <- rep(\"industry\", vcount(g_df))\n\n# Find the vertices with names in the list and assign attribute value of \"waste processing\"\nmatching_vertices <- which(V(g_df)$name %in% process_names)\nvertex_attribute[matching_vertices] <- \"waste processing\"\n\n# Add the vertex attribute to the graph\nV(g_df)$process <- vertex_attribute\n\n\n#V(g_df)$process\n\nls(df_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"from\"          \"to\"            \"waste_process\" \"weight\"       \n```\n:::\n\n```{.r .cell-code}\n#plot(g_df)\n```\n:::\n\n\n# Describing the Network Data\n\n::: {.cell}\n\n```{.r .cell-code}\nvcount(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81\n```\n:::\n\n```{.r .cell-code}\necount(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3822\n```\n:::\n\n```{.r .cell-code}\nis_bipartite(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n\n```{.r .cell-code}\nis_directed(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\nis_weighted(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\nThere are 81 nodes in the network and 3822 edges. It is a directed network and also weighted.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(E(g_df)$weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n       1      789     6908   119694    43739 11899111 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvertex_attr_names(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"name\"    \"process\"\n```\n:::\n\n```{.r .cell-code}\nedge_attr_names(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"weight\"        \"waste_process\"\n```\n:::\n:::\n\n\n## Dyad & Triad Census\n\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::dyad.census(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$mut\n[1] 1064\n\n$asym\n[1] 1606\n\n$null\n[1] 570\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::triad_census(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  2352  5654  1415 11037  1134  1891   663  7550  9814   188  1561  2147\n[13] 16767  2396 12177  8574\n```\n:::\n\n```{.r .cell-code}\nsum(igraph::triad_census(g_df))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 85320\n```\n:::\n\n```{.r .cell-code}\n(81*80*79)/(3*2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 85320\n```\n:::\n:::\n\n## Transitivity/ Global Clustering\nLet us look at the clustering pattern in a global level of network\n\n::: {.cell}\n\n```{.r .cell-code}\ntransitivity(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8675962\n```\n:::\n:::\n\nThe network has a high level of transitivity. It means, when two nodes are connected to a neighbouring node, it is highly likely that all three of them are connected to each other. \n\n## Local Transitivity / Clustering\nNow let us look at the Local transitivity. Since the number of vertices are fairly high, we will look on the average clustering coefficient rather than local clustering coefficient.\n\n::: {.cell}\n\n```{.r .cell-code}\ntransitivity(g_df, type = \"average\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8892353\n```\n:::\n:::\n\nThe average clustering coefficient of 0.889 suggests that the network is highly clustered. This means that the network has tightly connected sub groups/clusters. \n\n## Path Length and Geodesic\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage.path.length(g_df, directed = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 23.14815\n```\n:::\n:::\n\n\n# Component Structure and Membership\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(igraph::components(g_df)) # Elements of components\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"membership\" \"csize\"      \"no\"        \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::components(g_df)$no\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::components(g_df)$csize\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#igraph::components(g_df)$membership\n```\n:::\n\n\nThe component structure shows that there is only one big component with 81 members. In other words, there is no sub component or isolates in this network.\n\n# Density of Network\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngraph.density(g_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5898148\n```\n:::\n:::\n\nThe network has a 0.5898 density which means 0.5898 proportion of all possible ties are present in this network. \n\n\n\n## Creating a Dataframe with the Vertex Degree values\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree <- data.frame(name = V(g_df)$name, degree = igraph::degree(g_df))\nhead(df_degree)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                 name degree\nCrop cultivation                     Crop cultivation     75\nLivestock                                   Livestock     53\nAgricultural services           Agricultural services     48\nForestry                                     Forestry     73\nFeeds & organic fertilizer Feeds & organic fertilizer     54\nTextile products                     Textile products    112\n```\n:::\n:::\n\n\n\n## In degree and out degree\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree <- df_degree |>\n  mutate(indegree = igraph::degree(g_df, mode = \"in\"), \n         \n         outdegree = igraph::degree(g_df, mode = \"out\"))\ndf_degree |>\n  arrange(desc(outdegree)) |>\n  slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                     name degree indegree\nCommerce                                         Commerce    126       43\nMiscellaneous metal products Miscellaneous metal products    136       54\nMisc. manufacturing products Misc. manufacturing products    143       61\nWearing apparel etc.                 Wearing apparel etc.    123       42\nFinal chemical products           Final chemical products    135       54\n                             outdegree\nCommerce                            83\nMiscellaneous metal products        82\nMisc. manufacturing products        82\nWearing apparel etc.                81\nFinal chemical products             81\n```\n:::\n\n```{.r .cell-code}\ndf_degree |>\n  arrange(desc(indegree)) |>\n  slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                     name degree indegree\nPig iron & crude steel             Pig iron & crude steel     76       66\nPublic administration               Public administration     66       65\nMisc. manufacturing products Misc. manufacturing products    143       61\nTransport & post service         Transport & post service    142       61\nPersonal services                       Personal services    141       61\n                             outdegree\nPig iron & crude steel              10\nPublic administration                1\nMisc. manufacturing products        82\nTransport & post service            81\nPersonal services                   80\n```\n:::\n:::\n\n## Summary statistics of Network Degree\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(df_degree)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     name               degree          indegree       outdegree    \n Length:81          Min.   : 42.00   Min.   :17.00   Min.   : 0.00  \n Class :character   1st Qu.: 66.00   1st Qu.:42.00   1st Qu.:18.00  \n Mode  :character   Median : 91.00   Median :48.00   Median :46.00  \n                    Mean   : 94.37   Mean   :47.19   Mean   :47.19  \n                    3rd Qu.:121.00   3rd Qu.:52.00   3rd Qu.:78.00  \n                    Max.   :143.00   Max.   :66.00   Max.   :83.00  \n```\n:::\n:::\n\n## Network Degree Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree %>% melt %>% filter(variable != 'output' & variable != 'eigen.centrality') %>% \n  ggplot(aes(x = value, fill = variable, color = variable)) + geom_density(alpha = .2, bw = 5) +\n  ggtitle('Degree Distribution')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nUsing name as id variables\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: attributes are not identical across measure variables; they will be\ndropped\n```\n:::\n\n::: {.cell-output-display}\n![](final_project_jerinjacob_final_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\n## Network Degree Centralization\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentr_degree(g_df, mode = \"in\")$centralization\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2351852\n```\n:::\n\n```{.r .cell-code}\ncentr_degree(g_df, mode = \"out\")$centralization\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4476852\n```\n:::\n:::\n\n\n# Eigen Vector\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_eigen <- centr_eigen(g_df, directed = T)\nnames(temp_eigen)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"vector\"          \"value\"           \"options\"         \"centralization\" \n[5] \"theoretical_max\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(temp_eigen$vector)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_eigen$vector\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 0.5953827 0.5120362 0.6280237 0.6805738 0.5954991 0.6824618 0.6057831\n [8] 0.8187135 0.7071076 0.6528368 0.6034703 0.6478165 0.7163664 0.7881786\n[15] 0.5418807 0.7574951 0.6661287 0.6401862 0.6576396 0.7781058 0.6086314\n[22] 0.7930444 0.7667579 0.7641407 0.7718081 0.8899521 0.7727183 0.5146864\n[29] 0.5145222 0.6882062 0.6419725 0.5519556 0.5175506 0.9087712 0.7717444\n[36] 0.7442549 0.5454263 0.8646528 0.9102065 0.2697866 0.7511301 0.7086050\n[43] 0.6025945 0.6784769 0.6992363 0.7370351 0.7233416 0.7887455 0.7168331\n[50] 0.6934170 0.7050182 0.7535558 0.8082977 0.8390455 0.6841809 0.7379447\n[57] 0.7483575 0.7978797 0.7380666 0.5369580 0.5485777 0.5782104 0.4740734\n[64] 0.5273760 0.6535068 0.5117106 0.5468021 1.0000000 0.7119895 0.7187400\n[71] 0.7131842 0.7267811 0.7680584 0.7145214 0.6885328 0.8205471 0.8157092\n[78] 0.7580999 0.9623841 0.6121869 0.8306890\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_eigen$centralization\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.309789\n```\n:::\n:::\n\n\n## Adding Eigen Vector to node level measures dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree$eigen <- centr_eigen(g_df, directed = T)$vector\n#df_degree\narrange(df_degree, desc(eigen)) |> slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                     name degree indegree\nPig iron & crude steel             Pig iron & crude steel     76       66\nPublic administration               Public administration     66       65\nPersonal services                       Personal services    141       61\nTransport & post service         Transport & post service    142       61\nMisc. manufacturing products Misc. manufacturing products    143       61\n                             outdegree     eigen\nPig iron & crude steel              10 1.0000000\nPublic administration                1 0.9623841\nPersonal services                   80 0.9102065\nTransport & post service            81 0.9087712\nMisc. manufacturing products        82 0.8899521\n```\n:::\n:::\n\n\n## Bonacich Power Centrality to the dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree$bonpow <- power_centrality(g_df)\n\ndf_degree |>\n  arrange(desc(bonpow)) |>\n  slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                                     name\nSteel products                                             Steel products\nFeeds & organic fertilizer                     Feeds & organic fertilizer\nFishery                                                           Fishery\nMisc. ceramic, stone & clay products Misc. ceramic, stone & clay products\nElectrical devices & parts                     Electrical devices & parts\n                                     degree indegree outdegree     eigen\nSteel products                           91       41        50 0.6086314\nFeeds & organic fertilizer               54       41        13 0.5954991\nFishery                                  57       46        11 0.6841809\nMisc. ceramic, stone & clay products    129       54        75 0.7781058\nElectrical devices & parts               89       50        39 0.7370351\n                                       bonpow\nSteel products                       3.001614\nFeeds & organic fertilizer           2.372176\nFishery                              1.768329\nMisc. ceramic, stone & clay products 1.412379\nElectrical devices & parts           1.381722\n```\n:::\n:::\n\n\n## Derived and Reflected Centrality\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix_df_degree <- as.matrix(as_adjacency_matrix(g_df, attr = \"weight\"))\n# Square the adjacency matrix\nmatrix_df_degree_sq <- t(matrix_df_degree) %*% matrix_df_degree\n# Calculate the proportion of reflected centrality\ndf_degree$rc <- diag(matrix_df_degree_sq)/rowSums(matrix_df_degree_sq)\n\n# Replace missing values with 0\ndf_degree$rc <- ifelse(is.nan(df_degree$rc), 0, df_degree$rc)\n\n# Calculate received eigen value centrality\n\ndf_degree$eigen.rc <- df_degree$eigen * df_degree$rc\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate the proportion of derived centrality\ndf_degree$dc <- 1-diag(matrix_df_degree_sq)/rowSums(matrix_df_degree_sq)\n\n# Replace missing values with 0\ndf_degree$dc <- ifelse(is.nan(df_degree$dc), 0, df_degree$dc)\n\n# Calculate derived eigen value centrality\n\ndf_degree$eigen.dc <- df_degree$eigen * df_degree$dc\n```\n:::\n\n\n## Centrality Score Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree |>\n  select(-name) |>\n  gather() |>\n  ggplot(aes(value)) +\n  geom_histogram() +\n  facet_wrap(~key, scales = \"free\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: attributes are not identical across measure variables; they will be\ndropped\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](final_project_jerinjacob_final_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n## Centrality Measure Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- df_degree |>\n  select(degree, indegree, outdegree, eigen, eigen.rc, eigen.dc, bonpow) |>\n  correlate() |>\n  rearrange() \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nCorrelation computed with\n• Method: 'pearson'\n• Missing treated using: 'pairwise.complete.obs'\n```\n:::\n\n```{.r .cell-code}\nfashion(temp) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       term outdegree degree eigen.rc bonpow indegree eigen eigen.dc\n1 outdegree              .96      .01   -.25     -.07  -.08     -.09\n2    degree       .96             .07   -.22      .20   .19      .15\n3  eigen.rc       .01    .07             .04      .20   .22     -.29\n4    bonpow      -.25   -.22      .04             .08   .08      .06\n5  indegree      -.07    .20      .20    .08           1.00      .88\n6     eigen      -.08    .19      .22    .08     1.00            .87\n7  eigen.dc      -.09    .15     -.29    .06      .88   .87         \n```\n:::\n\n```{.r .cell-code}\nrplot(temp)\n```\n\n::: {.cell-output-display}\n![](final_project_jerinjacob_final_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n## Closeness Centrality\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree$close <- igraph::closeness(g_df)\n\ndf_degree |>\n  arrange(desc(close)) |>\n  slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                           name degree indegree\nMisc. electronic components         Misc. electronic components    115       51\nHousehold electronics equipment Household electronics equipment    128       52\nMedical service etc.                       Medical service etc.     82       54\nForestry                                               Forestry     73       46\nGlass & glass products                   Glass & glass products    107       48\n                                outdegree     eigen     bonpow          rc\nMisc. electronic components            64 0.7483575 -0.6396733 0.058544496\nHousehold electronics equipment        76 0.7718081 -1.2355812 0.036473660\nMedical service etc.                   28 0.7887455 -1.4600141 0.188048532\nForestry                               27 0.6805738  0.9696416 0.002645690\nGlass & glass products                 59 0.6934170 -2.6402940 0.004047831\n                                   eigen.rc        dc  eigen.dc        close\nMisc. electronic components     0.043812214 0.9414555 0.7045453 0.0004385965\nHousehold electronics equipment 0.028150667 0.9635263 0.7436575 0.0003711952\nMedical service etc.            0.148322436 0.8119515 0.6404231 0.0003303601\nForestry                        0.001800587 0.9973543 0.6787732 0.0003267974\nGlass & glass products          0.002806835 0.9959522 0.6906102 0.0003169572\n```\n:::\n:::\n\n\n## Betweenness Centrality\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree$between <- igraph::betweenness(g_df)\n\ndf_degree |>\n  arrange(desc(between)) |>\n  slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                     name degree indegree\nGlass & glass products             Glass & glass products    107       48\nPottery, china & earthenware Pottery, china & earthenware     90       45\nForestry                                         Forestry     73       46\nChemical fertilizer                   Chemical fertilizer     86       45\nMetallic ores                               Metallic ores     45       36\n                             outdegree     eigen     bonpow           rc\nGlass & glass products              59 0.6934170 -2.6402940 4.047831e-03\nPottery, china & earthenware        45 0.6576396 -1.8381676 1.457466e-03\nForestry                            27 0.6805738  0.9696416 2.645690e-03\nChemical fertilizer                 41 0.6478165  0.8723078 2.335198e-03\nMetallic ores                        9 0.5468021 -0.1219666 6.807622e-05\n                                 eigen.rc        dc  eigen.dc        close\nGlass & glass products       2.806835e-03 0.9959522 0.6906102 0.0003169572\nPottery, china & earthenware 9.584871e-04 0.9985425 0.6566811 0.0003127932\nForestry                     1.800587e-03 0.9973543 0.6787732 0.0003267974\nChemical fertilizer          1.512780e-03 0.9976648 0.6463037 0.0003127932\nMetallic ores                3.722422e-05 0.9999319 0.5467649 0.0001832509\n                              between\nGlass & glass products       2375.500\nPottery, china & earthenware 1919.000\nForestry                     1809.667\nChemical fertilizer          1755.000\nMetallic ores                1057.500\n```\n:::\n:::\n\nWe can calculate the network level score of betweenness centralization\n\n::: {.cell}\n\n```{.r .cell-code}\ncentr_betw(g_df)$centralization\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0276675\n```\n:::\n:::\n\n\n## Network Constraint\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree$constraint <- constraint(g_df)\n\ndf_degree |> arrange(constraint) |> slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                                     name\nMisc. ceramic, stone & clay products Misc. ceramic, stone & clay products\nGlass & glass products                             Glass & glass products\nIndustrial inorganic chemicals             Industrial inorganic chemicals\nMiscellaneous metal products                 Miscellaneous metal products\nPlastic products                                         Plastic products\n                                     degree indegree outdegree     eigen\nMisc. ceramic, stone & clay products    129       54        75 0.7781058\nGlass & glass products                  107       48        59 0.6934170\nIndustrial inorganic chemicals          124       49        75 0.7163664\nMiscellaneous metal products            136       54        82 0.7930444\nPlastic products                        129       52        77 0.7574951\n                                         bonpow          rc    eigen.rc\nMisc. ceramic, stone & clay products  1.4123794 0.003363506 0.002617164\nGlass & glass products               -2.6402940 0.004047831 0.002806835\nIndustrial inorganic chemicals        0.3463899 0.012085212 0.008657440\nMiscellaneous metal products         -0.3559538 0.034739948 0.027550320\nPlastic products                      0.7816329 0.102727058 0.077815246\n                                            dc  eigen.dc        close between\nMisc. ceramic, stone & clay products 0.9966365 0.7754887 0.0001986492   284.0\nGlass & glass products               0.9959522 0.6906102 0.0003169572  2375.5\nIndustrial inorganic chemicals       0.9879148 0.7077089 0.0001761184   108.0\nMiscellaneous metal products         0.9652601 0.7654940 0.0002575992    76.0\nPlastic products                     0.8972729 0.6796799 0.0001980983    11.5\n                                     constraint\nMisc. ceramic, stone & clay products  0.1081568\nGlass & glass products                0.1141318\nIndustrial inorganic chemicals        0.1165003\nMiscellaneous metal products          0.1242632\nPlastic products                      0.1294422\n```\n:::\n\n```{.r .cell-code}\ndf_degree |> arrange(desc(constraint)) |> slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                 name degree indegree outdegree\nFeeds & organic fertilizer Feeds & organic fertilizer     54       41        13\nMetallic ores                           Metallic ores     45       36         9\nMedicaments                               Medicaments     65       48        17\nLivestock                                   Livestock     53       35        18\nCoal mining etc.                     Coal mining etc.     80       36        44\n                               eigen     bonpow           rc     eigen.rc\nFeeds & organic fertilizer 0.5954991  2.3721763 2.256731e-02 1.343881e-02\nMetallic ores              0.5468021 -0.1219666 6.807622e-05 3.722422e-05\nMedicaments                0.6992363  1.1187649 3.466513e-02 2.423912e-02\nLivestock                  0.5120362  0.3828945 5.694910e-02 2.916000e-02\nCoal mining etc.           0.5369580 -0.1315835 3.650808e-04 1.960331e-04\n                                  dc  eigen.dc        close between constraint\nFeeds & organic fertilizer 0.9774327 0.5820603 2.407318e-04  1013.0  0.5747241\nMetallic ores              0.9999319 0.5467649 1.832509e-04  1057.5  0.5452660\nMedicaments                0.9653349 0.6749972 5.409499e-05    55.0  0.4932262\nLivestock                  0.9430509 0.4828762 3.045067e-04   478.5  0.4914524\nCoal mining etc.           0.9996349 0.5367619 1.932741e-04   125.5  0.4894916\n```\n:::\n:::\n\n\n\nFeeds & organic fertilizer, Metallic ores and Medicaments are the most reduntant industries while Misc. ceramic, stone & clay products, Glass & glass products and Industrial inorganic chemicals industries are the least reduntant ones.\n\n\n\n\n\n## Centrality Measure Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot :: corrplot(cor(df_degree[ , -1]), title = 'Correlation Plot')\n```\n\n::: {.cell-output-display}\n![](final_project_jerinjacob_final_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable1 <- kableExtra :: kable(apply(df_degree[ , -1], 2, function (x) df_degree$name[order(x, decreasing = TRUE)][1 : 10]))\ntable1\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> degree </th>\n   <th style=\"text-align:left;\"> indegree </th>\n   <th style=\"text-align:left;\"> outdegree </th>\n   <th style=\"text-align:left;\"> eigen </th>\n   <th style=\"text-align:left;\"> bonpow </th>\n   <th style=\"text-align:left;\"> rc </th>\n   <th style=\"text-align:left;\"> eigen.rc </th>\n   <th style=\"text-align:left;\"> dc </th>\n   <th style=\"text-align:left;\"> eigen.dc </th>\n   <th style=\"text-align:left;\"> close </th>\n   <th style=\"text-align:left;\"> between </th>\n   <th style=\"text-align:left;\"> constraint </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Misc. manufacturing products </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n   <td style=\"text-align:left;\"> Commerce </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n   <td style=\"text-align:left;\"> Steel products </td>\n   <td style=\"text-align:left;\"> Petroleum refinery products </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n   <td style=\"text-align:left;\"> Metallic ores </td>\n   <td style=\"text-align:left;\"> Public administration </td>\n   <td style=\"text-align:left;\"> Misc. electronic components </td>\n   <td style=\"text-align:left;\"> Glass &amp; glass products </td>\n   <td style=\"text-align:left;\"> Feeds &amp; organic fertilizer </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Public administration </td>\n   <td style=\"text-align:left;\"> Miscellaneous metal products </td>\n   <td style=\"text-align:left;\"> Public administration </td>\n   <td style=\"text-align:left;\"> Feeds &amp; organic fertilizer </td>\n   <td style=\"text-align:left;\"> Steel products </td>\n   <td style=\"text-align:left;\"> Petroleum refinery products </td>\n   <td style=\"text-align:left;\"> Coal mining etc. </td>\n   <td style=\"text-align:left;\"> Misc. manufacturing products </td>\n   <td style=\"text-align:left;\"> Household electronics equipment </td>\n   <td style=\"text-align:left;\"> Pottery, china &amp; earthenware </td>\n   <td style=\"text-align:left;\"> Metallic ores </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Personal services </td>\n   <td style=\"text-align:left;\"> Misc. manufacturing products </td>\n   <td style=\"text-align:left;\"> Misc. manufacturing products </td>\n   <td style=\"text-align:left;\"> Personal services </td>\n   <td style=\"text-align:left;\"> Fishery </td>\n   <td style=\"text-align:left;\"> Motor vehicle parts &amp; accessories </td>\n   <td style=\"text-align:left;\"> Motor vehicle parts &amp; accessories </td>\n   <td style=\"text-align:left;\"> Agricultural services </td>\n   <td style=\"text-align:left;\"> Lumber and wood products </td>\n   <td style=\"text-align:left;\"> Medical service etc. </td>\n   <td style=\"text-align:left;\"> Forestry </td>\n   <td style=\"text-align:left;\"> Medicaments </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Business services </td>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Wearing apparel etc. </td>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Misc. ceramic, stone &amp; clay products </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n   <td style=\"text-align:left;\"> Steel products </td>\n   <td style=\"text-align:left;\"> Pottery, china &amp; earthenware </td>\n   <td style=\"text-align:left;\"> Personal services </td>\n   <td style=\"text-align:left;\"> Forestry </td>\n   <td style=\"text-align:left;\"> Chemical fertilizer </td>\n   <td style=\"text-align:left;\"> Livestock </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Miscellaneous metal products </td>\n   <td style=\"text-align:left;\"> Personal services </td>\n   <td style=\"text-align:left;\"> Final chemical products </td>\n   <td style=\"text-align:left;\"> Misc. manufacturing products </td>\n   <td style=\"text-align:left;\"> Electrical devices &amp; parts </td>\n   <td style=\"text-align:left;\"> Passenger motor cars </td>\n   <td style=\"text-align:left;\"> Passenger motor cars </td>\n   <td style=\"text-align:left;\"> Leather etc. </td>\n   <td style=\"text-align:left;\"> Public construction </td>\n   <td style=\"text-align:left;\"> Glass &amp; glass products </td>\n   <td style=\"text-align:left;\"> Metallic ores </td>\n   <td style=\"text-align:left;\"> Coal mining etc. </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Final chemical products </td>\n   <td style=\"text-align:left;\"> Business services </td>\n   <td style=\"text-align:left;\"> Petroleum refinery products </td>\n   <td style=\"text-align:left;\"> Business services </td>\n   <td style=\"text-align:left;\"> Miscellaneous electrical machinery </td>\n   <td style=\"text-align:left;\"> Medical service etc. </td>\n   <td style=\"text-align:left;\"> Medical service etc. </td>\n   <td style=\"text-align:left;\"> Tobacco </td>\n   <td style=\"text-align:left;\"> Misc. transportation equipment  &amp; repair </td>\n   <td style=\"text-align:left;\"> Steel products </td>\n   <td style=\"text-align:left;\"> Coal products </td>\n   <td style=\"text-align:left;\"> Miscellaneous cars </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Repair of construction </td>\n   <td style=\"text-align:left;\"> Production machinery </td>\n   <td style=\"text-align:left;\"> Electricity </td>\n   <td style=\"text-align:left;\"> Production machinery </td>\n   <td style=\"text-align:left;\"> Coal products </td>\n   <td style=\"text-align:left;\"> Foods </td>\n   <td style=\"text-align:left;\"> Foods </td>\n   <td style=\"text-align:left;\"> Chemical fertilizer </td>\n   <td style=\"text-align:left;\"> Production machinery </td>\n   <td style=\"text-align:left;\"> Chemical fertilizer </td>\n   <td style=\"text-align:left;\"> Feeds &amp; organic fertilizer </td>\n   <td style=\"text-align:left;\"> Passenger motor cars </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Communications &amp; broadcasting </td>\n   <td style=\"text-align:left;\"> Lumber and wood products </td>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Building construction </td>\n   <td style=\"text-align:left;\"> Foods </td>\n   <td style=\"text-align:left;\"> Non-ferrous metal products </td>\n   <td style=\"text-align:left;\"> Non-ferrous metal products </td>\n   <td style=\"text-align:left;\"> Forestry </td>\n   <td style=\"text-align:left;\"> Building construction </td>\n   <td style=\"text-align:left;\"> Pottery, china &amp; earthenware </td>\n   <td style=\"text-align:left;\"> Textile products </td>\n   <td style=\"text-align:left;\"> Petrochemical basic products </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Activities not elsewhere classified </td>\n   <td style=\"text-align:left;\"> Building construction </td>\n   <td style=\"text-align:left;\"> Printing etc. </td>\n   <td style=\"text-align:left;\"> Misc. transportation equipment  &amp; repair </td>\n   <td style=\"text-align:left;\"> Medicaments </td>\n   <td style=\"text-align:left;\"> Real estate services </td>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Misc. ceramic, stone &amp; clay products </td>\n   <td style=\"text-align:left;\"> Transport &amp; post service </td>\n   <td style=\"text-align:left;\"> Rubber products </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n   <td style=\"text-align:left;\"> Fishery </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> Lumber and wood products </td>\n   <td style=\"text-align:left;\"> General-purpose machinery </td>\n   <td style=\"text-align:left;\"> Repair of construction </td>\n   <td style=\"text-align:left;\"> Lumber and wood products </td>\n   <td style=\"text-align:left;\"> Business oriented machinery </td>\n   <td style=\"text-align:left;\"> Communications &amp; broadcasting </td>\n   <td style=\"text-align:left;\"> Communications &amp; broadcasting </td>\n   <td style=\"text-align:left;\"> Glass &amp; glass products </td>\n   <td style=\"text-align:left;\"> Ships &amp; repair of ships </td>\n   <td style=\"text-align:left;\"> Livestock </td>\n   <td style=\"text-align:left;\"> Leather etc. </td>\n   <td style=\"text-align:left;\"> Pig iron &amp; crude steel </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\nindustry_io.node <-data.frame(apply(df_degree[ , -1], 2, function (x) df_degree$name[order(x, decreasing = TRUE)][1 : 10]))\nindustry_io.node\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                degree                     indegree\n1         Misc. manufacturing products       Pig iron & crude steel\n2             Transport & post service        Public administration\n3                    Personal services Misc. manufacturing products\n4                    Business services     Transport & post service\n5         Miscellaneous metal products            Personal services\n6              Final chemical products            Business services\n7               Repair of construction         Production machinery\n8        Communications & broadcasting     Lumber and wood products\n9  Activities not elsewhere classified        Building construction\n10            Lumber and wood products    General-purpose machinery\n                      outdegree                                    eigen\n1                      Commerce                   Pig iron & crude steel\n2  Miscellaneous metal products                    Public administration\n3  Misc. manufacturing products                        Personal services\n4          Wearing apparel etc.                 Transport & post service\n5       Final chemical products             Misc. manufacturing products\n6   Petroleum refinery products                        Business services\n7                   Electricity                     Production machinery\n8      Transport & post service                    Building construction\n9                 Printing etc. Misc. transportation equipment  & repair\n10       Repair of construction                 Lumber and wood products\n                                 bonpow                                rc\n1                        Steel products       Petroleum refinery products\n2            Feeds & organic fertilizer                    Steel products\n3                               Fishery Motor vehicle parts & accessories\n4  Misc. ceramic, stone & clay products            Pig iron & crude steel\n5            Electrical devices & parts              Passenger motor cars\n6    Miscellaneous electrical machinery              Medical service etc.\n7                         Coal products                             Foods\n8                                 Foods        Non-ferrous metal products\n9                           Medicaments              Real estate services\n10          Business oriented machinery     Communications & broadcasting\n                            eigen.rc                                   dc\n1             Pig iron & crude steel                        Metallic ores\n2        Petroleum refinery products                     Coal mining etc.\n3  Motor vehicle parts & accessories                Agricultural services\n4                     Steel products         Pottery, china & earthenware\n5               Passenger motor cars                         Leather etc.\n6               Medical service etc.                              Tobacco\n7                              Foods                  Chemical fertilizer\n8         Non-ferrous metal products                             Forestry\n9           Transport & post service Misc. ceramic, stone & clay products\n10     Communications & broadcasting               Glass & glass products\n                                   eigen.dc                           close\n1                     Public administration     Misc. electronic components\n2              Misc. manufacturing products Household electronics equipment\n3                  Lumber and wood products            Medical service etc.\n4                         Personal services                        Forestry\n5                       Public construction          Glass & glass products\n6  Misc. transportation equipment  & repair                  Steel products\n7                      Production machinery             Chemical fertilizer\n8                     Building construction    Pottery, china & earthenware\n9                  Transport & post service                 Rubber products\n10                  Ships & repair of ships                       Livestock\n                        between                   constraint\n1        Glass & glass products   Feeds & organic fertilizer\n2  Pottery, china & earthenware                Metallic ores\n3                      Forestry                  Medicaments\n4           Chemical fertilizer                    Livestock\n5                 Metallic ores             Coal mining etc.\n6                 Coal products           Miscellaneous cars\n7    Feeds & organic fertilizer         Passenger motor cars\n8              Textile products Petrochemical basic products\n9        Pig iron & crude steel                      Fishery\n10                 Leather etc.       Pig iron & crude steel\n```\n:::\n:::\n\n\nThese are the industries having the highest of centrality measures for the industries network.\n\nLet us look at the waste output from those industries having the highest Eigen Centrality and Bonacich Power Centrality since they are the most influential industries.  \n\n\n# How much waste does the most influential and least influential industries contribute?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_degree \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                                             name\nCrop cultivation                                                 Crop cultivation\nLivestock                                                               Livestock\nAgricultural services                                       Agricultural services\nForestry                                                                 Forestry\nFeeds & organic fertilizer                             Feeds & organic fertilizer\nTextile products                                                 Textile products\nWearing apparel etc.                                         Wearing apparel etc.\nLumber and wood products                                 Lumber and wood products\nPulp & paper                                                         Pulp & paper\nPaper products                                                     Paper products\nPrinting etc.                                                       Printing etc.\nChemical fertilizer                                           Chemical fertilizer\nIndustrial inorganic chemicals                     Industrial inorganic chemicals\nFinal chemical products                                   Final chemical products\nPetroleum refinery products                           Petroleum refinery products\nPlastic products                                                 Plastic products\nRubber products                                                   Rubber products\nLeather etc.                                                         Leather etc.\nPottery, china & earthenware                         Pottery, china & earthenware\nMisc. ceramic, stone & clay products         Misc. ceramic, stone & clay products\nSteel products                                                     Steel products\nMiscellaneous metal products                         Miscellaneous metal products\nBusiness oriented machinery                           Business oriented machinery\nMiscellaneous electrical machinery             Miscellaneous electrical machinery\nHousehold electronics equipment                   Household electronics equipment\nMisc. manufacturing products                         Misc. manufacturing products\nRepair of construction                                     Repair of construction\nElectricity                                                           Electricity\nGas & heat supply                                               Gas & heat supply\nWater supply                                                         Water supply\nCommerce                                                                 Commerce\nFinance & insurance                                           Finance & insurance\nReal estate services                                         Real estate services\nTransport & post service                                 Transport & post service\nCommunications & broadcasting                       Communications & broadcasting\nEducation & research                                         Education & research\nOther public services                                       Other public services\nBusiness services                                               Business services\nPersonal services                                               Personal services\nOffice supplies                                                   Office supplies\nActivities not elsewhere classified           Activities not elsewhere classified\nFoods                                                                       Foods\nBeverage                                                                 Beverage\nOrganic chemical products                               Organic chemical products\nMedicaments                                                           Medicaments\nElectrical devices & parts                             Electrical devices & parts\nFurniture & fixtures                                         Furniture & fixtures\nMedical service etc.                                         Medical service etc.\nNon-metallic ores                                               Non-metallic ores\nGlass & glass products                                     Glass & glass products\nCement & cement products                                 Cement & cement products\nMetal products for construction                   Metal products for construction\nGeneral-purpose machinery                               General-purpose machinery\nProduction machinery                                         Production machinery\nFishery                                                                   Fishery\nCast & forged steel products                         Cast & forged steel products\nMisc. electronic components                           Misc. electronic components\nShips & repair of ships                                   Ships & repair of ships\nNon-ferrous metal products                             Non-ferrous metal products\nCoal mining etc.                                                 Coal mining etc.\nCoal products                                                       Coal products\nSynthetic resins                                                 Synthetic resins\nPetrochemical basic products                         Petrochemical basic products\nSynthetic fibers                                                 Synthetic fibers\nNon-ferrous metals                                             Non-ferrous metals\nMiscellaneous iron or steel products         Miscellaneous iron or steel products\nMetallic ores                                                       Metallic ores\nPig iron & crude steel                                     Pig iron & crude steel\nHousehold electric appliances                       Household electric appliances\nElectronic devices                                             Electronic devices\nApplied electronic equipment etc.               Applied electronic equipment etc.\nElectronic computing equipment etc.           Electronic computing equipment etc.\nMotor vehicle parts & accessories               Motor vehicle parts & accessories\nPassenger motor cars                                         Passenger motor cars\nMiscellaneous cars                                             Miscellaneous cars\nMisc. transportation equipment  & repair Misc. transportation equipment  & repair\nPublic construction                                           Public construction\nCivil engineering                                               Civil engineering\nPublic administration                                       Public administration\nTobacco                                                                   Tobacco\nBuilding construction                                       Building construction\n                                         degree indegree outdegree     eigen\nCrop cultivation                             75       41        34 0.5953827\nLivestock                                    53       35        18 0.5120362\nAgricultural services                        48       43         5 0.6280237\nForestry                                     73       46        27 0.6805738\nFeeds & organic fertilizer                   54       41        13 0.5954991\nTextile products                            112       48        64 0.6824618\nWearing apparel etc.                        123       42        81 0.6057831\nLumber and wood products                    130       56        74 0.8187135\nPulp & paper                                114       49        65 0.7071076\nPaper products                              115       45        70 0.6528368\nPrinting etc.                               121       41        80 0.6034703\nChemical fertilizer                          86       45        41 0.6478165\nIndustrial inorganic chemicals              124       49        75 0.7163664\nFinal chemical products                     135       54        81 0.7881786\nPetroleum refinery products                 118       37        81 0.5418807\nPlastic products                            129       52        77 0.7574951\nRubber products                             123       46        77 0.6661287\nLeather etc.                                121       44        77 0.6401862\nPottery, china & earthenware                 90       45        45 0.6576396\nMisc. ceramic, stone & clay products        129       54        75 0.7781058\nSteel products                               91       41        50 0.6086314\nMiscellaneous metal products                136       54        82 0.7930444\nBusiness oriented machinery                  87       52        35 0.7667579\nMiscellaneous electrical machinery          106       52        54 0.7641407\nHousehold electronics equipment             128       52        76 0.7718081\nMisc. manufacturing products                143       61        82 0.8899521\nRepair of construction                      132       52        80 0.7727183\nElectricity                                 116       35        81 0.5146864\nGas & heat supply                           112       35        77 0.5145222\nWater supply                                126       46        80 0.6882062\nCommerce                                    126       43        83 0.6419725\nFinance & insurance                         117       37        80 0.5519556\nReal estate services                        114       35        79 0.5175506\nTransport & post service                    142       61        81 0.9087712\nCommunications & broadcasting               132       52        80 0.7717444\nEducation & research                        130       51        79 0.7442549\nOther public services                       115       37        78 0.5454263\nBusiness services                           138       58        80 0.8646528\nPersonal services                           141       61        80 0.9102065\nOffice supplies                              97       17        80 0.2697866\nActivities not elsewhere classified         131       51        80 0.7511301\nFoods                                        84       49        35 0.7086050\nBeverage                                     57       41        16 0.6025945\nOrganic chemical products                   116       47        69 0.6784769\nMedicaments                                  65       48        17 0.6992363\nElectrical devices & parts                   89       50        39 0.7370351\nFurniture & fixtures                        128       49        79 0.7233416\nMedical service etc.                         82       54        28 0.7887455\nNon-metallic ores                            83       48        35 0.7168331\nGlass & glass products                      107       48        59 0.6934170\nCement & cement products                     75       48        27 0.7050182\nMetal products for construction              78       51        27 0.7535558\nGeneral-purpose machinery                   101       55        46 0.8082977\nProduction machinery                        108       57        51 0.8390455\nFishery                                      57       46        11 0.6841809\nCast & forged steel products                 91       50        41 0.7379447\nMisc. electronic components                 115       51        64 0.7483575\nShips & repair of ships                      63       54         9 0.7978797\nNon-ferrous metal products                  115       50        65 0.7380666\nCoal mining etc.                             80       36        44 0.5369580\nCoal products                                87       38        49 0.5485777\nSynthetic resins                             79       40        39 0.5782104\nPetrochemical basic products                 64       33        31 0.4740734\nSynthetic fibers                             55       37        18 0.5273760\nNon-ferrous metals                           86       45        41 0.6535068\nMiscellaneous iron or steel products         76       35        41 0.5117106\nMetallic ores                                45       36         9 0.5468021\nPig iron & crude steel                       76       66        10 1.0000000\nHousehold electric appliances                61       48        13 0.7119895\nElectronic devices                           67       49        18 0.7187400\nApplied electronic equipment etc.            71       48        23 0.7131842\nElectronic computing equipment etc.          55       49         6 0.7267811\nMotor vehicle parts & accessories            60       52         8 0.7680584\nPassenger motor cars                         49       48         1 0.7145214\nMiscellaneous cars                           51       46         5 0.6885328\nMisc. transportation equipment  & repair     61       55         6 0.8205471\nPublic construction                          57       55         2 0.8157092\nCivil engineering                            53       51         2 0.7580999\nPublic administration                        66       65         1 0.9623841\nTobacco                                      42       42         0 0.6121869\nBuilding construction                        56       56         0 0.8306890\n                                              bonpow           rc     eigen.rc\nCrop cultivation                         -0.45146664 1.637191e-02 9.747553e-03\nLivestock                                 0.38289445 5.694910e-02 2.916000e-02\nAgricultural services                     0.54005548 1.216859e-03 7.642161e-04\nForestry                                  0.96964160 2.645690e-03 1.800587e-03\nFeeds & organic fertilizer                2.37217634 2.256731e-02 1.343881e-02\nTextile products                         -0.82476966 1.298756e-02 8.863512e-03\nWearing apparel etc.                     -0.71928868 2.091706e-02 1.267120e-02\nLumber and wood products                  0.42627794 1.636446e-02 1.339780e-02\nPulp & paper                             -0.33322046 5.554882e-02 3.927899e-02\nPaper products                           -0.07095362 3.818486e-02 2.492848e-02\nPrinting etc.                            -0.90083573 2.247675e-02 1.356405e-02\nChemical fertilizer                       0.87230783 2.335198e-03 1.512780e-03\nIndustrial inorganic chemicals            0.34638992 1.208521e-02 8.657440e-03\nFinal chemical products                  -0.71928868 3.047071e-02 2.401636e-02\nPetroleum refinery products              -0.46836472 5.184964e-01 2.809632e-01\nPlastic products                          0.78163286 1.027271e-01 7.781525e-02\nRubber products                           0.18770857 1.490049e-02 9.925642e-03\nLeather etc.                             -0.42431758 1.616228e-03 1.034687e-03\nPottery, china & earthenware             -1.83816759 1.457466e-03 9.584871e-04\nMisc. ceramic, stone & clay products      1.41237938 3.363506e-03 2.617164e-03\nSteel products                            3.00161364 3.598741e-01 2.190307e-01\nMiscellaneous metal products             -0.35595377 3.473995e-02 2.755032e-02\nBusiness oriented machinery               1.05825318 2.518162e-02 1.930820e-02\nMiscellaneous electrical machinery        1.29252428 1.140601e-02 8.715793e-03\nHousehold electronics equipment          -1.23558118 3.647366e-02 2.815067e-02\nMisc. manufacturing products             -0.35595377 9.118457e-03 8.114991e-03\nRepair of construction                    0.26761077 3.115299e-02 2.407249e-02\nElectricity                              -0.46836472 1.218214e-01 6.269981e-02\nGas & heat supply                        -1.16637735 5.180065e-02 2.665259e-02\nWater supply                             -0.40750641 1.355996e-02 9.332047e-03\nCommerce                                 -0.15369208 1.289454e-01 8.277941e-02\nFinance & insurance                      -0.40750641 6.257226e-02 3.453711e-02\nReal estate services                     -0.64681571 1.600004e-01 8.280831e-02\nTransport & post service                 -0.71928868 1.395405e-01 1.268104e-01\nCommunications & broadcasting            -0.40750641 1.455250e-01 1.123081e-01\nEducation & research                     -0.13196063 3.237998e-02 2.409896e-02\nOther public services                    -0.64681571 9.357777e-03 5.103978e-03\nBusiness services                        -0.40750641 1.242500e-01 1.074331e-01\nPersonal services                        -0.70767402 1.184374e-01 1.078025e-01\nOffice supplies                          -0.71928868 2.069674e-02 5.583703e-03\nActivities not elsewhere classified      -0.71928868 3.627871e-02 2.725003e-02\nFoods                                     1.13910371 1.867125e-01 1.323054e-01\nBeverage                                 -0.99314758 1.758446e-02 1.059630e-02\nOrganic chemical products                -1.46033419 1.148314e-01 7.791044e-02\nMedicaments                               1.11876493 3.466513e-02 2.423912e-02\nElectrical devices & parts                1.38172155 2.961807e-02 2.182955e-02\nFurniture & fixtures                     -0.10560955 6.527267e-03 4.721444e-03\nMedical service etc.                     -1.46001410 1.880485e-01 1.483224e-01\nNon-metallic ores                        -0.21744076 4.109170e-03 2.945589e-03\nGlass & glass products                   -2.64029396 4.047831e-03 2.806835e-03\nCement & cement products                  0.17001523 7.435039e-03 5.241838e-03\nMetal products for construction          -0.67455454 2.153869e-02 1.623061e-02\nGeneral-purpose machinery                -1.09886055 4.270602e-02 3.451918e-02\nProduction machinery                      1.04879133 6.043324e-02 5.070624e-02\nFishery                                   1.76832949 4.510132e-03 3.085746e-03\nCast & forged steel products             -0.24797604 9.693480e-03 7.153252e-03\nMisc. electronic components              -0.63967332 5.854450e-02 4.381221e-02\nShips & repair of ships                   0.35763327 2.214848e-02 1.767182e-02\nNon-ferrous metal products               -1.83921482 1.765695e-01 1.303201e-01\nCoal mining etc.                         -0.13158347 3.650808e-04 1.960331e-04\nCoal products                             1.27296538 4.449600e-02 2.440951e-02\nSynthetic resins                          0.66670380 7.847691e-02 4.537616e-02\nPetrochemical basic products             -3.02296295 1.276594e-01 6.051990e-02\nSynthetic fibers                         -0.05073276 5.494500e-03 2.897667e-03\nNon-ferrous metals                       -0.60376419 9.611980e-02 6.281494e-02\nMiscellaneous iron or steel products     -1.02963818 5.499840e-02 2.814327e-02\nMetallic ores                            -0.12196661 6.807622e-05 3.722422e-05\nPig iron & crude steel                    0.63094568 2.886971e-01 2.886971e-01\nHousehold electric appliances            -0.35853529 1.059602e-02 7.544256e-03\nElectronic devices                        0.86351133 3.285408e-02 2.361355e-02\nApplied electronic equipment etc.         1.01870710 2.289161e-02 1.632593e-02\nElectronic computing equipment etc.       0.10776372 2.114018e-02 1.536429e-02\nMotor vehicle parts & accessories        -0.01977941 3.010170e-01 2.311986e-01\nPassenger motor cars                      0.72666982 2.226240e-01 1.590696e-01\nMiscellaneous cars                       -0.62099289 7.674234e-02 5.283963e-02\nMisc. transportation equipment  & repair -1.34846726 3.817555e-02 3.132484e-02\nPublic construction                       0.21862977 3.070318e-02 2.504487e-02\nCivil engineering                         0.21862977 1.476531e-02 1.119358e-02\nPublic administration                    -0.62356454 5.117200e-02 4.924712e-02\nTobacco                                   0.00000000 1.968011e-03 1.204790e-03\nBuilding construction                     0.00000000 5.610320e-02 4.660431e-02\n                                                dc  eigen.dc        close\nCrop cultivation                         0.9836281 0.5856351 1.288328e-04\nLivestock                                0.9430509 0.4828762 3.045067e-04\nAgricultural services                    0.9987831 0.6272595 2.153316e-04\nForestry                                 0.9973543 0.6787732 3.267974e-04\nFeeds & organic fertilizer               0.9774327 0.5820603 2.407318e-04\nTextile products                         0.9870124 0.6735983 2.493144e-04\nWearing apparel etc.                     0.9790829 0.5931119 1.294163e-04\nLumber and wood products                 0.9836355 0.8053157 2.043318e-04\nPulp & paper                             0.9444512 0.6678286 2.730748e-04\nPaper products                           0.9618151 0.6279083 1.997204e-04\nPrinting etc.                            0.9775232 0.5899063 2.055921e-04\nChemical fertilizer                      0.9976648 0.6463037 3.127932e-04\nIndustrial inorganic chemicals           0.9879148 0.7077089 1.761184e-04\nFinal chemical products                  0.9695293 0.7641623 2.065689e-04\nPetroleum refinery products              0.4815036 0.2609175 3.182484e-05\nPlastic products                         0.8972729 0.6796799 1.980983e-04\nRubber products                          0.9850995 0.6562031 3.098853e-04\nLeather etc.                             0.9983838 0.6391516 2.562132e-04\nPottery, china & earthenware             0.9985425 0.6566811 3.127932e-04\nMisc. ceramic, stone & clay products     0.9966365 0.7754887 1.986492e-04\nSteel products                           0.6401259 0.3896008 3.140704e-04\nMiscellaneous metal products             0.9652601 0.7654940 2.575992e-04\nBusiness oriented machinery              0.9748184 0.7474497 2.241147e-04\nMiscellaneous electrical machinery       0.9885940 0.7554249 2.361275e-04\nHousehold electronics equipment          0.9635263 0.7436575 3.711952e-04\nMisc. manufacturing products             0.9908815 0.8818372 3.035823e-04\nRepair of construction                   0.9688470 0.7486459 5.021089e-05\nElectricity                              0.8781786 0.4519866 5.470759e-05\nGas & heat supply                        0.9481993 0.4878696 2.119542e-04\nWater supply                             0.9864400 0.6788742 5.613878e-05\nCommerce                                 0.8710546 0.5591931 2.890508e-05\nFinance & insurance                      0.9374277 0.5174185 3.142875e-05\nReal estate services                     0.8399996 0.4347423 3.866378e-05\nTransport & post service                 0.8604595 0.7819608 3.925124e-06\nCommunications & broadcasting            0.8544750 0.6594363 2.295842e-05\nEducation & research                     0.9676200 0.7201559 1.011429e-04\nOther public services                    0.9906422 0.5403223 1.154868e-04\nBusiness services                        0.8757500 0.7572196 5.670445e-06\nPersonal services                        0.8815626 0.8024040 1.660578e-04\nOffice supplies                          0.9793033 0.2642029 1.357220e-04\nActivities not elsewhere classified      0.9637213 0.7238801 9.634840e-05\nFoods                                    0.8132875 0.5762996 2.820079e-04\nBeverage                                 0.9824155 0.5919982 1.788269e-04\nOrganic chemical products                0.8851686 0.6005665 2.929115e-04\nMedicaments                              0.9653349 0.6749972 5.409499e-05\nElectrical devices & parts               0.9703819 0.7152056 1.636393e-04\nFurniture & fixtures                     0.9934727 0.7186202 2.260398e-04\nMedical service etc.                     0.8119515 0.6404231 3.303601e-04\nNon-metallic ores                        0.9958908 0.7138875 2.531646e-04\nGlass & glass products                   0.9959522 0.6906102 3.169572e-04\nCement & cement products                 0.9925650 0.6997764 2.134927e-04\nMetal products for construction          0.9784613 0.7373252 1.989258e-04\nGeneral-purpose machinery                0.9572940 0.7737786 3.022061e-04\nProduction machinery                     0.9395668 0.7883393 2.551671e-04\nFishery                                  0.9954899 0.6810951 2.547771e-04\nCast & forged steel products             0.9903065 0.7307915 2.069965e-04\nMisc. electronic components              0.9414555 0.7045453 4.385965e-04\nShips & repair of ships                  0.9778515 0.7802078 1.562744e-04\nNon-ferrous metal products               0.8234305 0.6077465 3.044140e-04\nCoal mining etc.                         0.9996349 0.5367619 1.932741e-04\nCoal products                            0.9555040 0.5241682 2.874389e-04\nSynthetic resins                         0.9215231 0.5328342 2.994012e-04\nPetrochemical basic products             0.8723406 0.4135535 2.560819e-04\nSynthetic fibers                         0.9945055 0.5244783 9.350164e-05\nNon-ferrous metals                       0.9038802 0.5906919 2.357934e-04\nMiscellaneous iron or steel products     0.9450016 0.4835673 2.438430e-04\nMetallic ores                            0.9999319 0.5467649 1.832509e-04\nPig iron & crude steel                   0.7113029 0.7113029 2.055921e-04\nHousehold electric appliances            0.9894040 0.7044453 2.495633e-04\nElectronic devices                       0.9671459 0.6951265 2.676874e-05\nApplied electronic equipment etc.        0.9771084 0.6968583 1.849454e-04\nElectronic computing equipment etc.      0.9788598 0.7114168 1.345714e-04\nMotor vehicle parts & accessories        0.6989830 0.5368598 2.614304e-06\nPassenger motor cars                     0.7773760 0.5554518 4.403948e-06\nMiscellaneous cars                       0.9232577 0.6356932 3.638785e-06\nMisc. transportation equipment  & repair 0.9618244 0.7892223 5.233054e-06\nPublic construction                      0.9692968 0.7906643 1.426330e-04\nCivil engineering                        0.9852347 0.7469063 1.121831e-04\nPublic administration                    0.9488280 0.9131370 1.099680e-08\nTobacco                                  0.9980320 0.6109821          NaN\nBuilding construction                    0.9438968 0.7840847          NaN\n                                            between constraint\nCrop cultivation                            0.50000  0.3205938\nLivestock                                 478.50000  0.4914524\nAgricultural services                     134.50000  0.3028473\nForestry                                 1809.66667  0.4272002\nFeeds & organic fertilizer               1013.00000  0.5747241\nTextile products                          968.00000  0.2438620\nWearing apparel etc.                       76.00000  0.1955590\nLumber and wood products                  703.50000  0.3114977\nPulp & paper                              442.00000  0.1915520\nPaper products                            105.00000  0.2038092\nPrinting etc.                               0.00000  0.2153851\nChemical fertilizer                      1755.00000  0.3652127\nIndustrial inorganic chemicals            108.00000  0.1165003\nFinal chemical products                   202.00000  0.1306160\nPetroleum refinery products                 0.00000  0.3554092\nPlastic products                           11.50000  0.1294422\nRubber products                           149.00000  0.1561429\nLeather etc.                              705.33333  0.1802013\nPottery, china & earthenware             1919.00000  0.2262136\nMisc. ceramic, stone & clay products      284.00000  0.1081568\nSteel products                             68.50000  0.2091610\nMiscellaneous metal products               76.00000  0.1242632\nBusiness oriented machinery                 0.00000  0.1579056\nMiscellaneous electrical machinery        196.33333  0.1468511\nHousehold electronics equipment             3.00000  0.1925047\nMisc. manufacturing products               44.00000  0.1559234\nRepair of construction                      0.00000  0.1772456\nElectricity                                 0.00000  0.2106597\nGas & heat supply                         143.00000  0.2702317\nWater supply                                0.00000  0.2064716\nCommerce                                    0.00000  0.1546499\nFinance & insurance                         0.00000  0.2828406\nReal estate services                        0.00000  0.2810388\nTransport & post service                   79.00000  0.1844128\nCommunications & broadcasting               0.00000  0.3034752\nEducation & research                       78.00000  0.1406254\nOther public services                       0.00000  0.2373658\nBusiness services                           0.00000  0.1605641\nPersonal services                          79.00000  0.2180852\nOffice supplies                             0.00000  0.2104526\nActivities not elsewhere classified        79.00000  0.2022155\nFoods                                      22.00000  0.2262387\nBeverage                                    1.00000  0.3430286\nOrganic chemical products                 578.00000  0.1973029\nMedicaments                                55.00000  0.4932262\nElectrical devices & parts                 77.00000  0.1548437\nFurniture & fixtures                        0.00000  0.1620324\nMedical service etc.                       88.00000  0.2498383\nNon-metallic ores                         385.00000  0.2122864\nGlass & glass products                   2375.50000  0.1141318\nCement & cement products                  108.50000  0.2414020\nMetal products for construction            58.00000  0.2170647\nGeneral-purpose machinery                 154.50000  0.1619621\nProduction machinery                        2.00000  0.1742834\nFishery                                   130.50000  0.4380732\nCast & forged steel products              415.66667  0.1910239\nMisc. electronic components               317.00000  0.1668877\nShips & repair of ships                     0.00000  0.1750264\nNon-ferrous metal products                531.00000  0.1722446\nCoal mining etc.                          125.50000  0.4894916\nCoal products                            1036.16667  0.3857319\nSynthetic resins                          700.66667  0.3253952\nPetrochemical basic products              211.00000  0.4483696\nSynthetic fibers                            0.00000  0.2434401\nNon-ferrous metals                        171.00000  0.3308661\nMiscellaneous iron or steel products      164.00000  0.2601309\nMetallic ores                            1057.50000  0.5452660\nPig iron & crude steel                    714.50000  0.4273430\nHousehold electric appliances              78.66667  0.1507978\nElectronic devices                          0.00000  0.1672784\nApplied electronic equipment etc.          77.00000  0.2513257\nElectronic computing equipment etc.         0.00000  0.2586440\nMotor vehicle parts & accessories           0.00000  0.2056411\nPassenger motor cars                        0.00000  0.4600919\nMiscellaneous cars                          0.00000  0.4829847\nMisc. transportation equipment  & repair    0.00000  0.2467625\nPublic construction                         6.50000  0.2262611\nCivil engineering                           0.00000  0.1699602\nPublic administration                       0.00000  0.2564144\nTobacco                                     0.00000  0.2540334\nBuilding construction                       0.00000  0.1741157\n```\n:::\n:::\n\n\n\n\n\n\n\n\n\n# Reference:\n1) Nakamura, S. (2020). Tracking the Product Origins of Waste for Treatment Using the WIO Data Developed by the Japanese Ministry of the Environment. Env. Sci. Technol. https://doi.org/10.1021/acs.est.0c06015\n\n2) \n\n",
    "supporting": [
      "final_project_jerinjacob_final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}