{
  "hash": "4017e6b2ab3d622b2ad21e22e9023c64",
  "result": {
    "markdown": "---\ntitle: \"A Network Analysis of Global Preferential Trade Agreements (PTAs)\"\nauthor: \"Cynthia Hester\"\ndescription: \"DACSS 697E Social Networks Analysis Final Project\"\ndate: \"05/20/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories: \n  - Cynthia Hester\n  - Final_Project\n  - Preferential Trade Agreements (PTAs)  \n  - Network of International Trade Agreements\n---\n\n\n\n\n\n\n# Research Question:\n\nHow does the network structure of Preferential Trade Agreements (PTAs) influence international trade patterns and economic integration among participating countries?\n\n\n\n## Hypothesis:\n\nH1: A more dense network structure in Preferential Trade Agreements (PTAs) leads to increased trade flow and economic integration among participating countries.\n\n\n## Introduction:\n\nIn our Social Network Analysis course, Professor Rolfe highlighted the breadth of applications and emphasized the flexibility to examine any scenario that involved interactive systems. Taking this into account, I chose to focus my project on an area that piqued my personal interest - the intersection of travel and global trade.[^1]\n\n\n**What is the source of the data?**\n\nThe data utilized for this project are derived from the Design of Trade Agreements (DESTA) database https://www.designoftradeagreements.org/project-description/, a comprehensive resource documenting numerous aspects of Preferential Trade Agreements (PTAs) globally, which was found via the World Trade Organization(WTO). With data spanning PTAs ratified since 1945, the DESTA database offers an examination of the various provisions and areas encompassed by these agreements. Utilizing this dataset was key in bringing the theories and methodologies of Social Network Analysis into practice in a real-world context.\n\n**What is being measured**\n\nThe **Preferential Trade Agreement** (PTA) data measures the bilateral agreements between countries that provide preferential access to certain products from the countries involved, reducing tariffs or duties below the level that each country charges other members of the World Trade Organization (WTO).\n\nThe data includes variables, such as the (nodes) countries/regions involved, the type of agreement (free trade agreement, customs union, etc.), the date the agreement came into effect, and trade parameters.\n*************************************************************************************\n\n**Data Format**\n\nIt is provided as a matrix, where countries are listed both in rows and columns, and each cell in the matrix indicates whether a trade agreement exists between the two countries. Alternatively, it could be provided as an edgelist, where each row represents an agreement with two columns for the two countries involved. Sometimes, it might also be in the form of an affiliation network, representing memberships of different countries in different agreements. For the purposes of this project it is presented as a matrix.\n\n\n## Data\n\nAs previously stated the data for this project was derived from the Design of Trade Agreements database (DESTA). The data utilized are a universe of cases.\n\n## Wrangling and Exploration\n\n#### Import DESTA data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#preferential trade agreement data (pta)\n#DESTA List of Treaties\n\nexcel_file <- \"C:/Users/Bud/Downloads/desta_list_of_treaties_02_01_dyads.xlsx\"\n\ndesta_list <- read_excel(excel_file, sheet = \"data\")\n\npta_data <- read_excel(path = excel_file, sheet = 2) \n\npta_data$regioncon <- as.factor(pta_data$regioncon)\n```\n:::\n\n*************************************************************************************\n## Inspect PTA trade agreement data/ Descriptive Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pta_data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#first few rows of the data\nhead(pta_data) #look at the structure of the data\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#inspect the data\nstr(pta_data) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_values <- sapply(pta_data, function(x) sum(is.na(x)))\nmissing_values\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove rows with missing values in country1 or country2 columns\npta_data <- pta_data[complete.cases(pta_data$country1, pta_data$country2), ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for missing values in country1 and country2 columns\nmissing_country1 <- sum(is.na(pta_data$country1))\nmissing_country2 <- sum(is.na(pta_data$country2))\n\n# Print the number of missing values\ncat(\"Number of missing values in country1 column:\", missing_country1, \"\\n\")\ncat(\"Number of missing values in country2 column:\", missing_country2, \"\\n\")\n```\n:::\n\n***********************************************************************************\n#### Adjacency Matrix for entire dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(pta_data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n  pta_data[1 : 16, 1 : 16]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#install and load the igraph package\nif (!require(igraph)) {\n    install.packages(\"igraph\")\n    library(igraph)\n}\n\n\ngraph <- graph_from_data_frame(d = pta_data, directed = FALSE)\n\n# extract the adjacency matrix\nadj_matrix <- as_adjacency_matrix(graph)\n\n# Print the adjacency matrix\nprint(adj_matrix)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n  [[ suppressing 204 column names 'Afghanistan', 'Algeria', 'Egypt' ... ]]\n```\n:::\n:::\n\n\n\nnodes(countries)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcount(graph)\n```\n:::\n\n\nedges(trade ties)\n\n\n::: {.cell}\n\n```{.r .cell-code}\necount(graph)\n```\n:::\n\n\nCalculating proportion of nodes \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the number of nodes\nnodes <- V(graph)\n\n# Calculate the proportion of non-zero entries\nprop_nonzero <- sum(adj_matrix[] > 0) / length(nodes) ^ 2\n\n# Print the proportion\nprint(prop_nonzero)\n```\n:::\n\n*******************************************************************************\n**Analysis**\n\nThe output value 0.3540465 indicates that, based on the **pta_data**, approximately 35.4% of all potential bilateral Preferential Trade Agreements (PTAs) among countries are in place. This shows a considerable degree of interconnectedness in global trade. It also suggests substantial room for more PTAs, as 64.6% of potential agreements are unexplored.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnodes <- data.frame(name = V(graph)$name,\n                    all.degree = igraph::degree(graph), \n                    out.degree = igraph::degree(graph, mode = 'out'),\n                    in.degree = igraph::degree(graph, mode = 'in'), \n                    total.degree = igraph::degree(graph, mode = 'total'),\n                    eigen.centrality = igraph::eigen_centrality(graph)$vector)\n\nhead(nodes)\n```\n:::\n\n**********************************************************************************\n**Distribution**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# histogram for all_degree\nggplot(nodes, aes(x=all.degree)) +\n  geom_histogram(binwidth=1, fill=\"steelblue\", color=\"black\") +\n  ggtitle(\"Distribution of All Degree\") +\n  xlab(\"All Degree\") +\n  ylab(\"Count\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# histogram for out_degree\nggplot(nodes, aes(x=out.degree)) +\n  geom_histogram(binwidth=1, fill=\"steelblue\", color=\"black\") +\n  ggtitle(\"Distribution of Out Degree\") +\n  xlab(\"Out Degree\") +\n  ylab(\"Count\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# histogram for in_degree\nggplot(nodes, aes(x=in.degree)) +\n  geom_histogram(binwidth=1, fill=\"steelblue\", color=\"black\") +\n  ggtitle(\"Distribution of In Degree\") +\n  xlab(\"In Degree\") +\n  ylab(\"Count\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-17-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# histogram for eigen_centrality\nggplot(nodes, aes(x=eigen.centrality)) +\n  geom_histogram(binwidth=0.1, fill=\"steelblue\", color=\"black\") +\n  ggtitle(\"Distribution of Eigen Centrality\") +\n  xlab(\"Eigen Centrality\") +\n  ylab(\"Count\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-17-4.png){width=672}\n:::\n:::\n\n\n\n**Analysis**\n\nThis distribution reveals how nations in the PTA network interact. High degree centrality indicates a country's extensive trade relationships. High out-degree signifies proactive trade agreement initiation, while high in-degree suggests a country's attractiveness as a trade partner. Lastly, elevated eigenvector centrality reveals a nation's importance within major trade blocs or networks.\n\n\n*************************************************************************************\n\n## Dyad and Triad Census\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndyad.census(nodes)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in intcalc(dat): NAs introduced by coercion\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntriad.census(nodes)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in triad.census(nodes): NAs introduced by coercion\n```\n:::\n:::\n\n\n\n\n## Data Exploration\n\nThis is a large dataset so I will focus on two variables; **year and region**. To better understand the data I will visualize it using the ggplot package from the tidyverse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# counts the frequency of ties between any two countries formed by year and region.\n\npta_data_count <- pta_data %>% group_by(year, regioncon) %>% count(name) \npta_data_count <- pta_data_count %>% arrange(desc(n))\nkable(head(pta_data_count), col.names = c(\"Year\", \"Region\", \"Agreement name\", \"Number of Ties\"),\n      caption = \"Frequency of Ties Table\")\n```\n:::\n\n\n*******************************************************************************\n## Centrality\n\n\nIntercontinental Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\npta_intercon <- pta_data %>% filter(regioncon == \"Intercontinental\")\npta_intercon_net <- graph_from_edgelist(cbind(pta_intercon$country1, pta_intercon$country2), directed = F)\n```\n:::\n\n\n\n\n\n\n **Degree Centrality Intercontinental Region**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n\n\n# Create a graph from the pta_data\npta_net <- graph_from_data_frame(d = pta_data_count, directed = TRUE)\n\n# Calculate the degree centrality\ndegree_centrality <- igraph::degree(pta_net, mode = \"all\")\n\n# Print the degree centrality values\nprint(degree_centrality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            1991             2000             1988             2018 \n              21               26               10               22 \n            1989             2003             1984             1979 \n               9               55               12                6 \n            1975             2008             2007             2015 \n               9               25               20               15 \n            1994             1982             1993             1981 \n              59                5               28                7 \n            2016             2012             2005             1997 \n               8               10               41               36 \n            2019             1971             1963             1969 \n              30                3                4                8 \n            2009             2001             1992             2011 \n              26               34               43               39 \n            1973             1986             1968             1980 \n              11               14                4                5 \n            1996             2004             2020             1983 \n              38               34               20               11 \n            1998             2006             2013             2014 \n              30               35               17               13 \n            2017             2010             1953             1959 \n              14               10                2                2 \n            1960             1966             1972             1985 \n               6                5               12               31 \n            2002             1951             1957             1961 \n              33                2                4                7 \n            1962             1995             1999             1976 \n               5               46               24               10 \n            1958             1964             1967             1977 \n               4                3                5                6 \n            1987             1970             1990             1965 \n               4                5                7                5 \n            2021             1948             1949             1954 \n               9                1                1                2 \n            1955             1974             1978           Africa \n               2                5                1               91 \nIntercontinental           Europe         Americas             Asia \n             382              260              231              140 \n         Oceania \n              12 \n```\n:::\n:::\n\n\n**Degree Centrality Analysis**\n\nIn the context of degree centrality, the nodes with the highest degree centrality values can be considered the most important or influential nodes in the network. These nodes have a large number of connections (edges) with other nodes in the network. \n\nNodes(regions) with the highest degree centrality values are:\n\n- Europe: 260\n- Americas: 231\n- Asia: 140\n- Intercontinental: 382\n\nThese nodes represent regions or continents and have the highest number of connections with other nodes in the network. Therefore, they can be considered the most significant or influential  network connectivity.\n\n\n**Betweenness Centrality**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(igraph)\n\n# graph from the pta_data_count\npta_net <- graph_from_data_frame(d = pta_data_count, directed = F)\n\n# betweenness centrality\nbetweenness_centrality <- igraph::betweenness(pta_net, directed = F)\n\n# Print the betweenness centrality values\nprint(betweenness_centrality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            1991             2000             1988             2018 \n    7.494461e+00     4.716374e+00     3.692614e+00     6.556118e+00 \n            1989             2003             1984             1979 \n    1.198995e+00     1.883398e+01     1.444299e+00     5.948588e-02 \n            1975             2008             2007             2015 \n    9.325719e-01     9.906810e+00     4.108716e+00     2.540474e+00 \n            1994             1982             1993             1981 \n    2.672258e+01     4.095292e-01     1.105058e+01     7.440072e-01 \n            2016             2012             2005             1997 \n    1.192980e-01     7.843512e-01     1.716253e+01     1.852355e+01 \n            2019             1971             1963             1969 \n    6.054483e+00     8.100132e-02     2.444396e-01     6.984590e-01 \n            2009             2001             1992             2011 \n    8.044566e+00     1.631060e+01     1.282501e+01     7.360925e+00 \n            1973             1986             1968             1980 \n    1.822063e+00     1.438660e+00     5.112771e-02     4.165937e-01 \n            1996             2004             2020             1983 \n    2.640890e+01     1.486621e+01     9.292370e-01     3.903573e+00 \n            1998             2006             2013             2014 \n    1.979985e+01     1.038072e+01     1.763910e+00     6.035179e-01 \n            2017             2010             1953             1959 \n    1.266956e+00     1.994557e-01     2.624046e-02     0.000000e+00 \n            1960             1966             1972             1985 \n    1.257798e-01     5.312405e-01     5.051379e-01     5.197904e+00 \n            2002             1951             1957             1961 \n    1.581869e+01     1.023883e-02     9.589339e-02     8.118623e-01 \n            1962             1995             1999             1976 \n    5.798910e-01     2.751133e+01     7.211283e+00     3.790315e+00 \n            1958             1964             1967             1977 \n    5.754305e-02     0.000000e+00     4.638906e-01     2.099237e-01 \n            1987             1970             1990             1965 \n    0.000000e+00     8.100096e-02     9.855898e-01     9.423750e-01 \n            2021             1948             1949             1954 \n    4.846182e-01     0.000000e+00     0.000000e+00     0.000000e+00 \n            1955             1974             1978           Africa \n    2.624046e-02     6.143295e-02     0.000000e+00     3.292609e+02 \nIntercontinental           Europe         Americas             Asia \n    1.071777e+03     3.835651e+02     6.806068e+02     3.412115e+02 \n         Oceania \n    1.578892e+00 \n```\n:::\n:::\n\n\n\n\n**Betweenness Analysis**\n\nEgypt, Jordan, and Morocco are identified as nodes with high betweenness centrality. These countries serve as key intermediaries in facilitating trade relationships and information exchange between other countries within the network.\n\nOn the other hand, nodes with lower betweenness centrality values, such as Albania or Armenia, have less influence in connecting different parts of the network. While they still contribute to the network structure, their impact on information flow and communication may be comparatively lower.\n\n\n*******************************************************************************\n\n\n**Summary of Preferential Trade Agreement data**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(summary(pta_data_count), col.names = c(\"Year\", \"Region\", \"Agreement name\", \"Number of Ties\"), \n      caption = \"A Summary of the Frequency of Ties Data\") #summary() provide a summary of the data\n```\n:::\n\n\n##  Overview\n\nAn overview of the data reveals six distinct categories: Africa, Americas, Asia, Europe, Oceania, and Intercontinental. Interestingly, most PTAs are Intercontinental, tallying 382 agreements, while Oceania, given the limited number of nations in the region, has only  12 intra-regional agreements.\n\nThe next stage of my exploration will involve identifying patterns of multilateral and bilateral PTA formation among different countries.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#filter the new data: which countries tend to form multilateral PTAs and which countries tend to form bilateral PTAs\n\npta_data_count <- pta_data_count %>% mutate(bilat = ifelse(n == 1, \"bilateral\", \"multilateral\")) #creating a new variable to see if a tie belongs to a bilateral or multilateral treaty\n\n#png(filename = \"network1.png\") # save as png\npta_data_count$bilat <- as.factor(pta_data_count$bilat)\nregion_count <- pta_data_count %>% group_by(regioncon, bilat) %>% count(regioncon)\nggplot(region_count, aes(x= regioncon, y = n, color = bilat, fill = bilat)) +\n  geom_col()\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\nIt's observed that African nations exhibit a preference for multilateral **PTAs** as opposed to bilateral ones. Conversely, countries in the Americas and Asia predominantly lean towards bilateral **PTAs**. Europe and Oceania display an almost equal inclination towards both bilateral and multilateral **PTAs**. Of note when it comes to inter-regional PTAs, there appears to be no clear preference between bilateral and multilateral arrangements.\n\n\n*******************************************************************************\n\n\nCreating a plot to visualize the number of ties formed annually by region reinforces indicates thats Africa is particularly prominent in terms of the number of ties established, as well as in forming intra-regional PTAs, with Europe following closely. Meanwhile, Asia, the Americas, and Oceania demonstrate a preference for forming bilateral agreements.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Visualizing ties formed annually by global region\n#png(filename = \"network2.png\") # save as png\nggplot(pta_data_count, aes(x = year, y = n, color = regioncon, fill = regioncon)) +\n  geom_col() + facet_wrap(~regioncon)\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nIndegree/ Outdegree of PTAs Intercontinental Region\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# indegree and outdegree\nindegree <- colSums(as.matrix(as_adjacency_matrix(pta_intercon_net)))\noutdegree <- rowSums(as.matrix(as_adjacency_matrix(pta_intercon_net)))\n\n# data frame with indegree and outdegree values\ndegree_df <- data.frame(country = V(pta_intercon_net)$name, indegree = indegree, outdegree = outdegree)\n\n# Print the degree information\nprint(degree_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                          country indegree\nEgypt                                                       Egypt      174\nJordan                                                     Jordan      109\nMorocco                                                   Morocco      145\nTunisia                                                   Tunisia      159\nAlbania                                                   Albania        1\nTurkey                                                     Turkey      109\nAlgeria                                                   Algeria      128\nBelgium                                                   Belgium      435\nDenmark                                                   Denmark      388\nFrance                                                     France      436\nGermany                                                   Germany      435\nIreland                                                   Ireland      388\nItaly                                                       Italy      435\nLuxembourg                                             Luxembourg      435\nNetherlands                                           Netherlands      435\nUnited Kingdom                                     United Kingdom      448\nPortugal                                                 Portugal      218\nSpain                                                       Spain      233\nAustria                                                   Austria      151\nFinland                                                   Finland      151\nSweden                                                     Sweden      152\nGreece                                                     Greece      290\nCyprus                                                     Cyprus      142\nCzechia                                                   Czechia      144\nEstonia                                                   Estonia      144\nHungary                                                   Hungary      144\nLatvia                                                     Latvia      143\nLithuania                                               Lithuania      143\nMalta                                                       Malta      142\nPoland                                                     Poland      144\nSlovakia                                                 Slovakia      144\nSlovenia                                                 Slovenia      144\nBulgaria                                                 Bulgaria      144\nRomania                                                   Romania      191\nCroatia                                                   Croatia      120\nIraq                                                         Iraq       99\nSyria                                                       Syria       91\nLibya                                                       Libya       90\nArmenia                                                   Armenia       59\nBelarus                                                   Belarus       49\nMoldova                                                   Moldova       30\nRussia                                                     Russia       52\nUkraine                                                   Ukraine       64\nKenya                                                       Kenya       81\nTanzania                                                 Tanzania      127\nUganda                                                     Uganda       80\nAustralia                                               Australia       78\nBrunei                                                     Brunei       31\nCambodia                                                 Cambodia        7\nIndonesia                                               Indonesia       68\nLaos                                                         Laos        8\nMalaysia                                                 Malaysia       85\nMyanmar (Burma)                                   Myanmar (Burma)        7\nPhilippines                                           Philippines       73\nSingapore                                               Singapore      148\nThailand                                                 Thailand       58\nVietnam                                                   Vietnam      137\nNew Zealand                                           New Zealand       62\nCanada                                                     Canada       63\nChile                                                       Chile      131\nUnited States                                       United States       21\nAzerbaijan                                             Azerbaijan       18\nBahrain                                                   Bahrain       42\nKazakhstan                                             Kazakhstan       78\nKyrgyzstan                                             Kyrgyzstan       43\nTajikistan                                             Tajikistan       36\nBosnia & Herzegovina                         Bosnia & Herzegovina        2\nIsrael                                                     Israel       90\nIceland                                                   Iceland       34\nLiechtenstein                                       Liechtenstein       33\nNorway                                                     Norway       33\nSwitzerland                                           Switzerland       35\nAntigua & Barbuda                               Antigua & Barbuda       78\nBahamas                                                   Bahamas       96\nBarbados                                                 Barbados       96\nBelize                                                     Belize       78\nDominica                                                 Dominica       87\nDominican Republic                             Dominican Republic       68\nGrenada                                                   Grenada       96\nGuyana                                                     Guyana      143\nHaiti                                                       Haiti      115\nJamaica                                                   Jamaica       96\nSt. Kitts & Nevis                               St. Kitts & Nevis       78\nSt. Lucia                                               St. Lucia       87\nSt. Vincent & Grenadines                 St. Vincent & Grenadines       78\nSuriname                                                 Suriname       88\nTrinidad & Tobago                               Trinidad & Tobago      143\nChina                                                       China       20\nIndia                                                       India       70\nJapan                                                       Japan       65\nSouth Korea                                           South Korea      118\nPeru                                                         Peru      124\nColombia                                                 Colombia       84\nGeorgia                                                   Georgia       60\nTurkmenistan                                         Turkmenistan       14\nUzbekistan                                             Uzbekistan       28\nCôte d’Ivoire                                       Côte d’Ivoire      108\nAngola                                                     Angola       87\nBenin                                                       Benin      127\nBotswana                                                 Botswana      110\nBurkina Faso                                         Burkina Faso       80\nBurundi                                                   Burundi       80\nCameroon                                                 Cameroon      128\nCape Verde                                             Cape Verde       59\nCentral African Republic                 Central African Republic       80\nChad                                                         Chad       80\nComoros                                                   Comoros       87\nCongo - Brazzaville                           Congo - Brazzaville       80\nCongo - Kinshasa                                 Congo - Kinshasa      127\nCook Islands                                         Cook Islands       39\nDjibouti                                                 Djibouti       78\nEquatorial Guinea                               Equatorial Guinea       68\nEritrea                                                   Eritrea       28\nEswatini                                                 Eswatini      110\nEthiopia                                                 Ethiopia       68\nFiji                                                         Fiji      111\nGabon                                                       Gabon       80\nGambia                                                     Gambia       68\nGhana                                                       Ghana      116\nGuinea                                                     Guinea      115\nGuinea-Bissau                                       Guinea-Bissau       68\nKiribati                                                 Kiribati       70\nLesotho                                                   Lesotho      110\nLiberia                                                   Liberia       68\nMadagascar                                             Madagascar      109\nMalawi                                                     Malawi       68\nMali                                                         Mali       80\nMarshall Islands                                 Marshall Islands       29\nMauritania                                             Mauritania       99\nMauritius                                               Mauritius      100\nMicronesia (Federated States of) Micronesia (Federated States of)       29\nMozambique                                             Mozambique      126\nNamibia                                                   Namibia       70\nNauru                                                       Nauru       29\nNiger                                                       Niger       80\nNigeria                                                   Nigeria      122\nNiue                                                         Niue       39\nPalau                                                       Palau       29\nPapua New Guinea                                 Papua New Guinea      103\nRwanda                                                     Rwanda       80\nSamoa                                                       Samoa      114\nSão Tomé & Príncipe                           São Tomé & Príncipe       59\nSenegal                                                   Senegal       80\nSeychelles                                             Seychelles       88\nSierra Leone                                         Sierra Leone       68\nSolomon Islands                                   Solomon Islands      105\nSouth Africa                                         South Africa       98\nSudan                                                       Sudan      157\nTogo                                                         Togo       80\nTonga                                                       Tonga       79\nTuvalu                                                     Tuvalu       70\nVanuatu                                                   Vanuatu       51\nZambia                                                     Zambia       69\nZimbabwe                                                 Zimbabwe      126\nTimor-Leste                                           Timor-Leste       28\nSomalia                                                   Somalia      117\nBangladesh                                             Bangladesh       54\nIran                                                         Iran       59\nPakistan                                                 Pakistan       70\nLebanon                                                   Lebanon      101\nMexico                                                     Mexico      118\nKuwait                                                     Kuwait       48\nOman                                                         Oman       42\nQatar                                                       Qatar       88\nSaudi Arabia                                         Saudi Arabia       50\nUnited Arab Emirates                         United Arab Emirates       42\nPalestinian Territories                   Palestinian Territories       38\nEl Salvador                                           El Salvador       31\nHonduras                                                 Honduras       31\nTaiwan                                                     Taiwan        6\nArgentina                                               Argentina       60\nBolivia                                                   Bolivia       47\nBrazil                                                     Brazil       75\nCuba                                                         Cuba       47\nEcuador                                                   Ecuador       82\nNicaragua                                               Nicaragua       76\nNorth Korea                                           North Korea       47\nSerbia                                                     Serbia       71\nSri Lanka                                               Sri Lanka       48\nUruguay                                                   Uruguay       75\nVenezuela                                               Venezuela       53\nYemen                                                       Yemen       37\nGuatemala                                               Guatemala       33\nParaguay                                                 Paraguay       14\nNorth Macedonia                                   North Macedonia        1\nMontenegro                                             Montenegro        1\nPanama                                                     Panama       36\nGreenland                                               Greenland        1\nCosta Rica                                             Costa Rica       35\nHong Kong SAR China                           Hong Kong SAR China        6\nKosovo                                                     Kosovo        1\n                                 outdegree\nEgypt                                  174\nJordan                                 109\nMorocco                                145\nTunisia                                159\nAlbania                                  1\nTurkey                                 109\nAlgeria                                128\nBelgium                                435\nDenmark                                388\nFrance                                 436\nGermany                                435\nIreland                                388\nItaly                                  435\nLuxembourg                             435\nNetherlands                            435\nUnited Kingdom                         448\nPortugal                               218\nSpain                                  233\nAustria                                151\nFinland                                151\nSweden                                 152\nGreece                                 290\nCyprus                                 142\nCzechia                                144\nEstonia                                144\nHungary                                144\nLatvia                                 143\nLithuania                              143\nMalta                                  142\nPoland                                 144\nSlovakia                               144\nSlovenia                               144\nBulgaria                               144\nRomania                                191\nCroatia                                120\nIraq                                    99\nSyria                                   91\nLibya                                   90\nArmenia                                 59\nBelarus                                 49\nMoldova                                 30\nRussia                                  52\nUkraine                                 64\nKenya                                   81\nTanzania                               127\nUganda                                  80\nAustralia                               78\nBrunei                                  31\nCambodia                                 7\nIndonesia                               68\nLaos                                     8\nMalaysia                                85\nMyanmar (Burma)                          7\nPhilippines                             73\nSingapore                              148\nThailand                                58\nVietnam                                137\nNew Zealand                             62\nCanada                                  63\nChile                                  131\nUnited States                           21\nAzerbaijan                              18\nBahrain                                 42\nKazakhstan                              78\nKyrgyzstan                              43\nTajikistan                              36\nBosnia & Herzegovina                     2\nIsrael                                  90\nIceland                                 34\nLiechtenstein                           33\nNorway                                  33\nSwitzerland                             35\nAntigua & Barbuda                       78\nBahamas                                 96\nBarbados                                96\nBelize                                  78\nDominica                                87\nDominican Republic                      68\nGrenada                                 96\nGuyana                                 143\nHaiti                                  115\nJamaica                                 96\nSt. Kitts & Nevis                       78\nSt. Lucia                               87\nSt. Vincent & Grenadines                78\nSuriname                                88\nTrinidad & Tobago                      143\nChina                                   20\nIndia                                   70\nJapan                                   65\nSouth Korea                            118\nPeru                                   124\nColombia                                84\nGeorgia                                 60\nTurkmenistan                            14\nUzbekistan                              28\nCôte d’Ivoire                          108\nAngola                                  87\nBenin                                  127\nBotswana                               110\nBurkina Faso                            80\nBurundi                                 80\nCameroon                               128\nCape Verde                              59\nCentral African Republic                80\nChad                                    80\nComoros                                 87\nCongo - Brazzaville                     80\nCongo - Kinshasa                       127\nCook Islands                            39\nDjibouti                                78\nEquatorial Guinea                       68\nEritrea                                 28\nEswatini                               110\nEthiopia                                68\nFiji                                   111\nGabon                                   80\nGambia                                  68\nGhana                                  116\nGuinea                                 115\nGuinea-Bissau                           68\nKiribati                                70\nLesotho                                110\nLiberia                                 68\nMadagascar                             109\nMalawi                                  68\nMali                                    80\nMarshall Islands                        29\nMauritania                              99\nMauritius                              100\nMicronesia (Federated States of)        29\nMozambique                             126\nNamibia                                 70\nNauru                                   29\nNiger                                   80\nNigeria                                122\nNiue                                    39\nPalau                                   29\nPapua New Guinea                       103\nRwanda                                  80\nSamoa                                  114\nSão Tomé & Príncipe                     59\nSenegal                                 80\nSeychelles                              88\nSierra Leone                            68\nSolomon Islands                        105\nSouth Africa                            98\nSudan                                  157\nTogo                                    80\nTonga                                   79\nTuvalu                                  70\nVanuatu                                 51\nZambia                                  69\nZimbabwe                               126\nTimor-Leste                             28\nSomalia                                117\nBangladesh                              54\nIran                                    59\nPakistan                                70\nLebanon                                101\nMexico                                 118\nKuwait                                  48\nOman                                    42\nQatar                                   88\nSaudi Arabia                            50\nUnited Arab Emirates                    42\nPalestinian Territories                 38\nEl Salvador                             31\nHonduras                                31\nTaiwan                                   6\nArgentina                               60\nBolivia                                 47\nBrazil                                  75\nCuba                                    47\nEcuador                                 82\nNicaragua                               76\nNorth Korea                             47\nSerbia                                  71\nSri Lanka                               48\nUruguay                                 75\nVenezuela                               53\nYemen                                   37\nGuatemala                               33\nParaguay                                14\nNorth Macedonia                          1\nMontenegro                               1\nPanama                                  36\nGreenland                                1\nCosta Rica                              35\nHong Kong SAR China                      6\nKosovo                                   1\n```\n:::\n:::\n\n\n**Analysis**\n\nWe see that countries like Egypt, Jordan, Morocco, and Tunisia have relatively high indegree values, indicating that they receive a substantial number of connections from other countries.\n\nOn the other hand, outdegree represents the number of outgoing connections or links originating from a particular country. Higher outdegree values suggest that the country has more connections with other countries in the network. Countries like Belgium, Denmark, France, and Turkey have notable outdegree values, indicating that they have numerous connections with other countries.\n\n\n\n*******************************************************************************\n\n\n## Creating a Network of Intercontinental Regions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# rechecking the first 6 rows of the data\nhead(pta_data)\n```\n:::\n\n\n\nWe create a network using an edgelist as the data structure, allowing us to visualize the connections between global regions and the formation of PTAs. This approach enables us to analyze the structural patterns within the global PTA landscape.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_graph <- graph_from_edgelist(cbind(head(pta_data$country1), head(pta_data$country2)), directed = F)\nget.adjacency(temp_graph)\n```\n:::\n\n\n\n**Edgelist**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(head(pta_data$country1), head(pta_data$country2))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# using the igraph package to create an edgelist\n\nedge_net <- graph_from_edgelist(cbind(head(pta_data$country1), head(pta_data$country2)),\ndirected = FALSE) \n\n#png(filename = \"network3.png\") # save as png\n\nset.seed(123) #randomizes the configuration of the plot\n\n\nplot.igraph(edge_net)\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n**Subset of Adjacency matrix**\n\nThe adjacency matrix of the Preferential Trade Agreement (PTA) dataset provides a  representation of the bilateral trade relationships between countries participating in trade agreements. Each entry in the matrix indicates whether a specific pair of countries has established a preferential trade agreement or not. This binary representation allows us to identify the specific countries that are directly connected through these agreements.\n\nBy examining the adjacency matrix, we can observe the clustering and groupings of countries that have formed preferential trade agreements. These clusters indicate the presence of regional trade blocs or alliances, where countries within each cluster have established closer trade ties among themselves. Conversely, countries that are not connected in the adjacency matrix may have limited or no preferential trade agreements with other countries in the dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget.adjacency(edge_net)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmatrix_net <- graph_from_adjacency_matrix(get.adjacency(edge_net), mode = \"undirected\")\nset.seed(123) \nplot.igraph(matrix_net)\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nHere we see that both graphs appear identical. This is attributed to the edge list and adjacency matrix representing an undirected network. In an undirected network, the connections between nodes are symmetric and bidirectional.\n\nNetwork representation of countries based on their inter-regional Preferential Trade Agreements (PTAs)\n\n*********************************************************************************\n\n\n\n\n\nThis code enhances the Preferential Trade Agreement(PTA) network graph by attributing each trade agreement with its respective name and the year it was established.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#The edges of the network are referred to as E$agt_name, representing the names of the PTAs, and E$year, representing the respective years of these PTAs.\n\nE(pta_intercon_net)$agt_name <- pta_intercon$name\nE(pta_intercon_net)$year <- pta_intercon$year\n```\n:::\n\n\n**Analysis**\n\nOf note, there may be duplicate edges between pairs of countries, indicating multiple PTAs formed between them. To address this, I assign a weight to each pair based on the number of shared PTAs. To simplify the network by removing loops and consolidating duplicate edges, I utilize the simplify() function from the igraph package. This process entails aggregating the weights of duplicate edges, ensuring a streamlined representation of the network.\n\n**Weights**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assigning weight 1 to all edges\nE(pta_intercon_net)$weight <- 1\n\n\npta_intercon_simp <- graph.strength(pta_intercon_net, mode = \"all\", loops = FALSE)\n```\n:::\n\n\n\n**Weights Discussion**\n\nI first normalize the relationships within the Preferential Trade Agreement (PTA) interconnection network. I do this by assigning a uniform weight of 1 to all edges, effectively treating all connections as equal. Following this, I calculate the strength, or degree, of each node in the network, which gives me the number of connections each node, or country, has within this network. In this calculation, I treat the network as undirected and exclude any loops. The resulting data offers a straightforward view of the interconnectedness of each country within the PTA network, under the assumption that all trade agreements hold the same importance or weight.\n\n\n\n\n#### Vertices and Edges\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(V(pta_intercon_net)$name)\n```\n:::\n\n\n**Vertices and Edges**\n\nnumber of vertices,and edges in the network\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(pta_intercon_net)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(vcount(pta_intercon_net))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 191\n```\n:::\n:::\n\n\n\n\nThe summary indicates the number of **vertices(nodes or countries)** **(191)** and edges **(9316)** in the graph. The following line presents a list of attributes categorized by their kind (g for graph, v for vertex, and e for edge).\n\n********************************************************************************\n\n## Network Visualizations\n\nWe will generate two separate plots: one depicting the Inter-regional PTA network consisting exclusively of Inter-regional PTAs, and another illustrating the Bilateral PTA network that includes Bilateral agreements regardless of whether they are Inter-regional or regional in nature.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npta_bilat <- pta_data %>% filter(typememb == 1)\npta_bilat_net <- graph_from_data_frame(d = pta_bilat, directed = FALSE)\n\nE(pta_bilat_net)$agt_name <- pta_bilat$name\nE(pta_bilat_net)$year <- pta_bilat$year\n\nE(pta_bilat_net)$weight <- 1\npta_bilat_simp <- simplify(pta_bilat_net)\n```\n:::\n\n\n\nNetwork depiction of Inter-regional Preferential Trade Agreements (PTA)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nplot.igraph(pta_intercon_net,\n            vertex.size = 5,\n            vertex.color = \"red\",\n            vertex.label = V(pta_intercon_net)$name,\n            vertex.label.cex = .5,\n            vertex.frame.color = NA,\n            layout = layout.fruchterman.reingold,\n            main = \"Network of Inter-regional Preferential Trade Agreements(PTA)\"\n            )\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\nUsing all of the data depicts a \"hairball\" I will therefore use a subset of the data for more comprehensible data representation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE(pta_bilat_simp)$color <- ifelse(E(pta_bilat_simp)$weight > 1,'blue', 'grey')\nplot.igraph(pta_bilat_simp,\n            vertex.size = 5,\n            vertex.color = \"red\",\n            vekrtex.label = V(pta_bilat_simp)$name,\n            vertex.label.cex = .5,\n            vertex.frame.color = NA,\n            layout = layout.fruchterman.reingold,\n            edge.width = E(pta_bilat_simp)$weight,\n            main = \"Network of Bilateral Preferential Trade Agreements(PTA)\"\n            )\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bar plot of Bilateral network\n\nE(pta_intercon_net)$bilateral <- ifelse(pta_intercon$typememb == 1, 1,0)\nbilateral_var <- as.data.frame(E(pta_intercon_net)$bilateral)\nggplot(bilateral_var, aes(x =E(pta_intercon_net)$bilateral)) +\n  geom_bar(fill = \"blue\", color = \"green\") +\n  theme_minimal() +\n  labs(x = \"Bilateral/Multilateral Inter-Regional Preferential Trade Agreements (PTA)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#png(filename = \"network4.png\") # save as png\n```\n:::\n\n\nThe bar plot shows the distribution and relative importance of bilateral and multilateral Preferential Trade Agreements (PTAs) within the framework of social network analysis applied to inter-regional trade relationships. Notably, the left bar exhibits a considerably higher frequency of PTAs compared to the right bar, indicating a distinct prevalence of bilateral PTAs in the network.\nConversely,the lower frequency of multilateral PTAs on the right bar signifies a relatively reduced presence of agreements involving multiple nations in the network. Multilateral PTAs typically require more extensive negotiations and coordination among a larger number of countries. The scarcity of such agreements suggests a less pronounced emphasis on broader inter-regional collaboration within the analyzed trade network.\n\n******************************************************************************\n\n::: {.cell}\n\n```{.r .cell-code}\n#bilateral inter-regional PTAs\npta_intercon_bilat <- subgraph.edges(pta_intercon_net,which(E(pta_intercon_net)$bilateral == 1))\nplot(pta_intercon_bilat,\n     vertex.size = 5,\n     vertex.color = \"red\",\n     vertex.label = V(pta_intercon_bilat)$name,\n     vertex.label.cex = .5,\n     vertex.frame.color = NA,\n     layout = layout.fruchterman.reingold,\n     main = \"Network of Bilateral Inter-regional PTAs\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#(filename = \"network5.png\") # save as png\n```\n:::\n\n\n\n\n\n**Eigen Centrality Intercontinental Region**\n\nI plot an Eigen centrality for the intercontinetal region which quantifies a country's influence by factoring both the quantity and quality of its trade agreements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# eigen centrality \nV(pta_intercon_bilat)$eigen_cen <- eigen_centrality(pta_intercon_bilat)$vector\n\nprint((V(pta_intercon_bilat)))\n\n\neigen_cen <- eigen_centrality(pta_intercon_bilat)$vector\n\n# bar plot\n\nbarplot(eigen_cen, names.arg = V(pta_intercon_bilat)$name, xlab = \"Country\", ylab = \"Eigen Centrality\", col = \"blue\")\n\ntitle(main = \"Eigen Centrality of Countries in PTA Intercontinental Bilateral Network\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#png(filename = \"network8.png\") # save as png\n```\n:::\n\n\n**Analysis**\n\nThis bar plot represents the eigen centrality values of countries in the PTA Intercontinental Bilateral network. This visualization helps to analyze and interpret the relative importance of countries based on their connections within the network. Countries with higher eigen centrality scores are considered more influential and have stronger trade relationships, while those with lower scores have less impact. This helps identify key players and the distribution of power within the PTA network.\n\n\n\n********************************************************************************\n\n\n::: {.cell}\n\n```{.r .cell-code}\nE(pta_intercon_bilat)$weight <- 1\npta_intercon_bilat_sim <- pta_intercon_bilat %>% simplify(edge.attr.comb = list(weight = \"sum\"))\nplot(pta_intercon_bilat_sim,\n     vertex.size = 5,\n     vertex.color = \"blue\",\n     vertex.label = V(pta_intercon_bilat_sim)$name,\n     vertex.label.cex = .5,\n     vertex.frame.color = NA,\n     edge.width = E(pta_intercon_bilat_sim)$weight,\n     layout = layout.fruchterman.reingold,\n     main = \"Network of Bilateral Inter-regional Preferential Trade Agreements(PTAs)\n     \")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#png(filename = \"network6.png\") # save as png\n```\n:::\n\n\n\n*******************************************************************************\n\n## Density and Transitivity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbilat_density <- edge_density(pta_intercon_bilat)\nbilat_transitivity <- transitivity(pta_intercon_bilat)\n\n#density\npta_density <- edge_density(pta_intercon_net)\npta_transitivity <- transitivity(pta_intercon_net)\n\nbilat_density\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npta_bilat_2 <-  subgraph.edges(pta_bilat_simp,which(E(pta_bilat_simp)$weight > 1))\nplot.igraph(pta_bilat_2,\n            vertex.size = 5,\n            vertex.color = \"green\",\n            vekrtex.label = V(pta_bilat_2)$name,\n            vertex.label.cex = .5,\n            vertex.frame.color = NA,\n            layout = layout.fruchterman.reingold,\n            edge.width = E(pta_bilat_2)$weight,\n            main = \"Countries with more than One Bilateral PTAs\"\n            )\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n```{.r .cell-code}\npng(filename = \"network11.png\") # save as png\n```\n:::\n\n\n********************************************************************************\n## Community\n\n**Walktrap Algorithim**\n\nFor this project examining the Preferential Trade Agreement (PTA) network, I use the Walktrap algorithm, we examined in the 7th tutorial. This approach seeks to find communities within this complex trade network by employing random walks. The guiding principle behind this method is that shorter, random walks will likely stay within the confines of a single community. By applying the Walktrap algorithm to the PTA network, I aim to discern the community structures present within this global trade landscape, thereby shedding light on the intricate dynamics and patterns that shape international trade agreements.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercon_bilat_walktrap <- cluster_walktrap(pta_intercon_bilat_sim)\nmembership(intercon_bilat_walktrap)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#bilateral walktrap\nsizes(intercon_bilat_walktrap)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# walktrap algorithim output data is in a vector named \"output\"\noutput <- c(11, 14, 18, 4, 2, 20, 3, 12, 2)\n\n# data frame\noutput_df <- data.frame(\n  \"Community\" = paste0(\"Community_\", 1:length(output)),\n  \"Size\" = output\n)\n\n# Print the data frame\nprint(output_df)\n```\n:::\n\n\n\n**Preferential Trade Agreement(PTA) Walktrap Analysis**\n\nThe Walktrap algorithm's output portrays the distribution of nodes across various communities in the Preferential Trade Agreement (PTA) network. Each community number is paired with a value that signifies the count of nodes (or countries) within that specific community.\n\nHere is what we can infer:\n\n- Community 1 consists of 11 nodes.\n- Community 2 has 14 nodes.\n- Community 3 comprises 18 nodes.\n- Community 4 includes 4 nodes.\n- Community 5 houses 2 nodes.\n- Community 6 holds 20 nodes.\n- Community 7 encapsulates 3 nodes.\n- Community 8 encompasses 12 nodes.\n- Community 9 shelters 2 nodes.\n\nThis distribution provides a snapshot of the diverse interconnectedness among global trade relationships in the PTA network. Communities with larger node counts might represent robustly interconnected trading partnerships, while smaller communities may indicate more specific or self-contained trade relationships.\n\n## Density \n\n**PTA Bilateral Density Analysis**\n\nThe value 0.04924761 represents the bilateral density in the context of the Preferential Trade Agreement (PTA) dataset. Network density measures the actual connections in a network relative to the total possible connections. \n\nHere, a density of 0.04924761 suggests that nearly 4.92% of all potential bilateral trade agreements among countries are realized. This means, on an average, a country in the network has a trade agreement with approximately 4.92% of all other potential trading partners. Given that this value is relatively low, it indicates that the bilateral trade network is sparsely connected, suggesting the potential for many more trade agreements to be formed.\n\n## Transitivity\n\n**PTA Bilateral Transitivity**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbilat_transitivity\n```\n:::\n\n**Analysis**\n\nIn the context of the Preferential Trade Agreement (PTA) dataset, a bilateral transitivity of 0.1098987 signifies that about 11% of the potential triangular trade relationships among countries are realized. This implies that if two countries both have a PTA with a third one, there is an approximately 11% probability that these two countries will also have a trade agreement directly with each other.\n\nThis relatively low transitivity index suggests that the formation of PTAs is not extensively based on the principle of transitivity. Rather, it underscores that the establishment of PTAs among countries may be influenced by a multitude of factors, including geographical proximity and political or economic dynamics.\n\n\n## Dendrogram\n\n**Dendrogram**\n\nIn the context of the Preferential Trade Agreement (PTA) dataset focusing on the variables, the dendrogram emerged as an influential graphical representation. It conveys the nested arrangement of relationships among countries or corresponding trade agreements, an arrangement that is guided by specified attributes or significant performance indicators. This hierarchical classification reveals nuanced patterns in international trade interactions, which contributes to a better understanding of intricate PTAs. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_matrix <- dist(pta_data) \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in dist(pta_data): NAs introduced by coercion\n```\n:::\n\n```{.r .cell-code}\n# Hierarchical clustering using complete linkage\nhc <- hclust(dist_matrix, method = \"complete\")\n\n# Plot dendrogram\nplot(hc, hang = -1, cex = 0.6, main = \"Dendrogram for PTA Data\")\n```\n\n::: {.cell-output-display}\n![](CynthiaHester_Final_Project_Social_Networks_Spring_23_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#png(filename = \"network9.png\") # save as png\n```\n:::\n\n\n\n********************************************************************************\n\n\n## Discussion\n\nThe Preferential Trade Agreement (PTA) dataset, spanning from 1958 to 2021, offers a comprehensive view into the evolution of global trade relationships. Delving into this dataset  has afforded me a richer understanding of social network analysis in the context of international trade. This journey, albeit marked by a steep learning curve, has been an enlightening one.\n\nThe dominance of bilateral PTAs suggests that countries in the network tend to engage in preferential trade arrangements on a bilateral basis, forming direct connections with specific trading partners. This finding underscores the significance of bilateral relationships in shaping the overall structure of the inter-regional trade network. Bilateral PTAs are often favored due to their simplicity in negotiation and implementation, enabling countries to establish tailored agreements that cater to their specific needs and preferences.[^4] These agreements facilitate focused interactions between pairs of countries, fostering closer economic ties and potentially enhancing trade efficiency and cooperation.\n\n*************************************************************************************\n\n\n## Conclusion/Reflection\n\n\nPrior to this project, the critical role that variable selection plays in shaping network interpretation was an aspect I hadn't fully appreciated. Now, I understand that even with the PTA dataset, or for any social network analysis, significant effort can be poured into understanding the relationships between just a couple of variables to derive meaningful insights. Upon reflection, the prospect of analyzing data from more recent years to assess how key features like **node centrality,transitivity,density** and community structure have evolved in the midst of global challenges like the COVID-19 pandemic would merit future study, especially considering recent challenges in global trade and supply chain restrictions.\n\nDespite the hurdles encountered, the process of dissecting this dataset has been rewarding. Every decision made echoed in the analysis outcomes, underscoring the potential for subtle shifts to lead to major interpretation changes. I plan to continue my exploration of the PTA data and branch out to related projects to enhance my understanding of Social Network Analysis. \n\n\n**********************************************************************************\n\n## References/Resources\n\n[^1]: https://www.designoftradeagreements.org/project-description/\n[^2]: Wasserman, S., & Faust, K. (1994). Social network analysis: Methods and \n      applications. Cambridge University Press.\n[^3]: Newman, M. E. J. (2018). Networks. Oxford University Press.     \n[^4]: https://www.wto.org/\n[^5]: Robins, G., Pattison, P., Kalish, Y., & Lusher, D. (2007). An Introduction to Exponential Random Graph (p*) Models for Social Networks. Social Networks, 29, 172-191. \n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "CynthiaHester_Final_Project_Social_Networks_Spring_23_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}