<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rahul Gundeti">
<meta name="dcterms.date" content="2023-05-07">

<title>Unveiling the Hidden Network: Exploring the Intricacies of the U.S. Air Transportation System</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<meta name="twitter:title" content="Unveiling the Hidden Network: Exploring the Intricacies of the U.S. Air Transportation System">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://dacss.github.io/Social_Networks_Spring_2023/posts/FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-4-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="true"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/Social_Networks_Spring_2023/" rel="" target="">
 <span class="menu-text">Spring 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/Social_Networks_Spring_2023/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#acquisition-and-visualization-of-the-us-air-transportation-network" id="toc-acquisition-and-visualization-of-the-us-air-transportation-network" class="nav-link" data-scroll-target="#acquisition-and-visualization-of-the-us-air-transportation-network">Acquisition and visualization of the US air transportation network</a></li>
  <li><a href="#degree-and-betweenness-centrality-relationship-in-the-u.s.-airports-network" id="toc-degree-and-betweenness-centrality-relationship-in-the-u.s.-airports-network" class="nav-link" data-scroll-target="#degree-and-betweenness-centrality-relationship-in-the-u.s.-airports-network">Degree and Betweenness Centrality Relationship in the U.S. Airports Network</a></li>
  <li><a href="#community-detection-in-the-u.s.-air-transportation-network" id="toc-community-detection-in-the-u.s.-air-transportation-network" class="nav-link" data-scroll-target="#community-detection-in-the-u.s.-air-transportation-network">Community detection in the U.S. air transportation network</a></li>
  <li><a href="#challenges" id="toc-challenges" class="nav-link" data-scroll-target="#challenges">Challenges</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Unveiling the Hidden Network: Exploring the Intricacies of the U.S. Air Transportation System</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">final project</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rahul Gundeti </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Considering a data analyst in the airline industry, I’ve been diving deep into the fascinating world of air transportation networks. Picture this: airports across the globe, each a bustling hub of activity, connected by a vast web of airline routes. This is our playing field, a prime example of a spatial network.</p>
<p>A few years back, a groundbreaking study by Guimerà and colleagues (2005) took a close look at this network. They explored the importance of each airport (or ‘node’) in the network, and how different measures can provide unique insights. They even proposed alternative ways of assessing the position of a node, shedding light on the diverse roles airports play in this complex network.</p>
<p>Now, imagine we’re conducting a ‘virtual knockout experiment’. It’s a bit like a game of Jenga, but instead of wooden blocks, we’re dealing with airports. We carefully remove one node at a time, observing the effects on the network. This isn’t just a game, though. These experiments are crucial for understanding how resilient our network is to disruptions.</p>
<p>Think about it. If an airport suddenly goes offline - due to a natural disaster, for instance - how does that impact the rest of the network? Can flights be rerouted efficiently? Do other airports become overloaded? These are the kinds of questions we’re seeking to answer.</p>
<p>And it’s not just the airline industry that benefits from this kind of analysis. Similar methods are used to study everything from power grids to social networks, and even the spatial networks of organisms. By understanding the potential impacts of node failure, we can make our networks more robust and resilient.</p>
<p>So, as we navigate the ever-changing landscape of the airline industry, we’re not just looking at numbers and routes. We’re telling the story of our network, understanding its strengths and weaknesses, and preparing for whatever the future may hold.</p>
</section>
<section id="acquisition-and-visualization-of-the-us-air-transportation-network" class="level2">
<h2 class="anchored" data-anchor-id="acquisition-and-visualization-of-the-us-air-transportation-network">Acquisition and visualization of the US air transportation network</h2>
<p>As a data analyst in the airline industry, I’ve been exploring the intricate tapestry of the US domestic air transportation network. Picture this: a bustling network of airports, each a hub of activity, connected by the invisible threads of flights. These threads, each representing a flight that took place in December 2010, weave together to form a complex and dynamic pattern.</p>
<p>This pattern, our network, is more than just a collection of airports and flights. It’s a snapshot of our industry’s heartbeat during that month. Each node, an airport, pulsates with life, sending out flights that ripple across the network. Each edge, a flight, is a connection, a link that ties our network together.</p>
<p>This dataset is our playground. It allows us to delve into the connectivity and dynamics of our air transportation system during that period. We can probe its structure, examine its function, and uncover the hidden patterns that lie beneath the surface.</p>
<p>So, as we navigate through this network, we’re not just looking at airports and flights. We’re embarking on a journey, a journey that takes us deep into the heart of our industry. We’re exploring the story of our network, a story that is woven with flights and etched in the hustle and bustle of airports. And as we unravel this story, we gain insights that help us understand our industry better and prepare for the future.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'igraph' was built under R version 4.1.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'igraph'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    decompose, spectrum</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:base':

    union</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraphdata) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'igraphdata' was built under R version 4.1.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(USairports) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>USairports</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH bf6202d DN-- 755 23473 -- US airports
+ attr: name (g/c), name (v/c), City (v/c), Position (v/c), Carrier
| (e/c), Departures (e/n), Seats (e/n), Passengers (e/n), Aircraft
| (e/n), Distance (e/n)
+ edges from bf6202d (vertex names):
 [1] BGR-&gt;JFK BGR-&gt;JFK BOS-&gt;EWR ANC-&gt;JFK JFK-&gt;ANC LAS-&gt;LAX MIA-&gt;JFK EWR-&gt;ANC
 [9] BJC-&gt;MIA MIA-&gt;BJC TEB-&gt;ANC JFK-&gt;LAX LAX-&gt;JFK LAX-&gt;SFO AEX-&gt;LAS BFI-&gt;SBA
[17] ELM-&gt;PIT GEG-&gt;SUN ICT-&gt;PBI LAS-&gt;LAX LAS-&gt;PBI LAS-&gt;SFO LAX-&gt;LAS PBI-&gt;AEX
[25] PBI-&gt;ICT PIT-&gt;VCT SFO-&gt;LAX VCT-&gt;DWH IAD-&gt;JFK ABE-&gt;CLT ABE-&gt;HPN AGS-&gt;CLT
[33] AGS-&gt;CLT AVL-&gt;CLT AVL-&gt;CLT AVP-&gt;CLT AVP-&gt;PHL BDL-&gt;CLT BHM-&gt;CLT BHM-&gt;CLT
[41] BNA-&gt;CLT BNA-&gt;CLT BNA-&gt;DCA BNA-&gt;PHL BTR-&gt;CLT BUF-&gt;CLT BUF-&gt;DCA BUF-&gt;PHL
+ ... omitted several edges</code></pre>
</div>
</div>
<p>I’ve been working with the US domestic air transportation network dataset, a vibrant tapestry of airports and flights. Each airport, a bustling node in our network, has a “Position” attribute, a set of coordinates that pinpoints its location on the globe. But, like any good story, there’s a twist. Some of these positions might not be entirely accurate due to minor discrepancies in airport codes and coordinates.</p>
<p>So, I turned to the Open Flights project, a treasure trove of comprehensive airport location data. Picture me, a data detective, downloading this dataset directly from the web, ready to cross-verify our airport locations. This isn’t just about dotting the i’s and crossing the t’s. It’s about ensuring the story we tell with our data is as accurate and reliable as possible.</p>
<p>By integrating this external dataset, we’re not just enhancing the precision of our airport locations. We’re adding another layer of depth to our analysis, enabling us to paint a more accurate picture of our network. This way, we can conduct a more precise spatial analysis and visualization, bringing the story of our network to life in the most authentic way possible.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>airports<span class="ot">=</span><span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat'</span>, <span class="at">header=</span>F)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airports)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  V1                                          V2           V3               V4
1  1                              Goroka Airport       Goroka Papua New Guinea
2  2                              Madang Airport       Madang Papua New Guinea
3  3                Mount Hagen Kagamuga Airport  Mount Hagen Papua New Guinea
4  4                              Nadzab Airport       Nadzab Papua New Guinea
5  5 Port Moresby Jacksons International Airport Port Moresby Papua New Guinea
6  6                 Wewak International Airport        Wewak Papua New Guinea
   V5   V6        V7      V8   V9 V10 V11                  V12     V13
1 GKA AYGA -6.081690 145.392 5282  10   U Pacific/Port_Moresby airport
2 MAG AYMD -5.207080 145.789   20  10   U Pacific/Port_Moresby airport
3 HGU AYMH -5.826790 144.296 5388  10   U Pacific/Port_Moresby airport
4 LAE AYNZ -6.569803 146.726  239  10   U Pacific/Port_Moresby airport
5 POM AYPY -9.443380 147.220  146  10   U Pacific/Port_Moresby airport
6 WWK AYWK -3.583830 143.669   19  10   U Pacific/Port_Moresby airport
          V14
1 OurAirports
2 OurAirports
3 OurAirports
4 OurAirports
5 OurAirports
6 OurAirports</code></pre>
</div>
</div>
<p>I’ve been on a mission to bring our US air transportation network to life. And now, with the Open Flights project’s airport location data in hand, we’re ready to take the next step.</p>
<p>Imagine each airport as a character in our story. Each one has its own unique set of coordinates - its latitude and longitude - that tells us exactly where it’s located in the world. These coordinates, tucked away in columns 7 and 8 of our dataset, are about to take center stage.</p>
<p>We’re going to import this data and assign each airport its rightful place on the map. This isn’t just about getting the details right. It’s about ensuring that our story - the story of our network - is as accurate and authentic as possible.</p>
<p>With the correct latitude and longitude values associated with each airport, we can conduct a more precise spatial analysis and visualization of our network. This means our analyses and visualizations will truly reflect the real-world locations of our airports, enhancing the credibility and impact of our findings. It’s another step forward in our journey to understand and tell the story of our network.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(USairports)<span class="sc">$</span>lat<span class="ot">=</span>airports[<span class="fu">match</span>(<span class="fu">V</span>(USairports)<span class="sc">$</span>name, airports[,<span class="dv">5</span>]), <span class="dv">7</span>] </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(USairports)<span class="sc">$</span>long<span class="ot">=</span>airports[<span class="fu">match</span>(<span class="fu">V</span>(USairports)<span class="sc">$</span>name, airports[,<span class="dv">5</span>]), <span class="dv">8</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>I’ve been preparing our US air transportation network for its moment in the spotlight. But before it’s ready for its debut, we need to make sure it’s looking its best. That’s where our data cleanup steps come in.</p>
<p>First, we’re going to simplify the network. Think of it as decluttering a room. We’re removing any loops and converting the network into an undirected format. This will make our network easier to understand and eliminate any unnecessary complexities.</p>
<p>Next, we’re going to address any mismatched nodes. These are like the odd socks in a drawer - airport codes that don’t match up with the Open Flights database. By removing these, we’re ensuring the accuracy and consistency of our data.</p>
<p>Then, we’re going to zoom in on the main stage by excluding US territories in the Eastern and Southern Hemispheres. This will allow us to focus on the heart of the US domestic air transportation network, making our analysis clearer and more focused.</p>
<p>Finally, we’re going to spotlight the star of the show - the largest connected component, also known as the ‘giant component’. This is the most interconnected subset of our network, and by focusing on this, we can derive meaningful insights and simplify our analysis.</p>
<p>Once these steps are complete, we’ll be left with a refined network representation, which we’ll call “usair”. This will be our star performer, ready to take center stage in our subsequent analysis and visualization tasks. It’s through this refined lens that we’ll gain a deeper understanding of the intricate dance that is the US air transportation network.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove loops and make undirected</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">as.undirected</span>(<span class="fu">simplify</span>(USairports))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#remove airports whose codes didn't match the OpenFlights database (and hence returned "NA" for latitude)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">is.na</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>lat)<span class="sc">==</span><span class="cn">TRUE</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">#remove nodes in the Eastern and Southern Hemispheres (US territories). This will make the plot easier to see.</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>lat<span class="sc">&lt;</span><span class="dv">0</span>))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>long<span class="sc">&gt;</span><span class="dv">0</span>))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#keep only the largest connected component of the network ("giant component"). this also makes the network easier to see.</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>decomp<span class="ot">=</span><span class="fu">decompose.graph</span>(usair)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span>decomp[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>I’ve been working on a masterpiece: a refined representation of the US domestic air transportation network, affectionately named “usair”. This isn’t just a collection of airports and flights. It’s a story waiting to be told.</p>
<p>Imagine each airport as a character in our narrative, each flight a connection, a relationship. As we delve into the analysis of this network, we’re not just crunching numbers. We’re exploring the intricate web of relationships between our characters, uncovering the key patterns and dynamics that drive the story forward.</p>
<p>Through the lens of visualization, we can see the grand dance of air traffic across the US, the ebb and flow of flights between airports, the intricate choreography of our network. This is more than just a dance, though. It’s a window into the heart of our industry, a way to understand the complexities of our air transportation system.</p>
<p>As we continue our journey, we’ll delve deeper into the story, exploring the importance of each character, the resilience of our network, and other key metrics. Each step brings us closer to understanding the narrative of our network, the story of the US air transportation system.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>l<span class="ot">=</span><span class="fu">layout_nicely</span>(usair)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>l, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.size=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="degree-and-betweenness-centrality-relationship-in-the-u.s.-airports-network" class="level2">
<h2 class="anchored" data-anchor-id="degree-and-betweenness-centrality-relationship-in-the-u.s.-airports-network">Degree and Betweenness Centrality Relationship in the U.S. Airports Network</h2>
<p>I’ve been using two trusty tools: degree centrality and betweenness centrality.</p>
<p>Imagine degree centrality as a measure of popularity. It tells us how many direct flights an airport has, reflecting its connectivity and accessibility. It’s like counting how many friends a character has in our story.</p>
<p>Betweenness centrality, on the other hand, is a measure of influence. It tells us how often an airport acts as a bridge between other airports, a crucial transfer hub in the network. It’s like tracking how many plotlines a character is involved in.</p>
<p>But, like any good story, there’s a twist. Our analysis uses a simplified network that only considers unique flight routes. It doesn’t take into account factors like the frequency of flights, replicated routes, or the size of aircraft. It’s a bit like focusing on the main plot and leaving out some of the subplots.</p>
<p>By examining these two measures, we can identify the key players in our network, understand the flow of air traffic, and assess the importance of each airport in connecting different regions of the country. It’s through this exploration that we can truly understand the narrative of our network and the roles each character plays in our story.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">degree</span>(usair), <span class="fu">betweenness</span>(usair), <span class="at">pch=</span><span class="dv">10</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Imagine degree and betweenness centrality as two characters in our narrative, usually seen together, reflecting an airport’s popularity and influence. But there are a few airports, the mavericks of our story, that break this mold.</p>
<p>In the bustling world of U.S. domestic flights, one airport stands out. It doesn’t have the highest degree - it’s not the most popular character in our story. But it has a remarkably high betweenness centrality. This airport is like the unsung hero of our tale, quietly playing a critical role as a transfer hub, ensuring passengers move efficiently between different regions of the country.</p>
<p>This unique character in our network story highlights the fascinating complexities and unexpected dynamics within the U.S. air transportation system.</p>
<p>To examine notable points, let’s begin by exploring the top 10 airports based on their node degree.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(usair)<span class="sc">$</span>name[<span class="fu">order</span>(<span class="fu">degree</span>(usair), <span class="at">decreasing=</span>T)][<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#order() gives us the element number in order of ranking.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ATL" "DEN" "ORD" "MSP" "DFW" "DTW" "LAS" "IAH" "CLT" "LAX"</code></pre>
</div>
</div>
<p>The analysis reveals that the majority of the top 10 airports, based on node degree, are prominent hubs situated within the interior of the lower 48 states. It is important to note that international flights are not considered in this network. Consequently, the list includes well-known airports such as Atlanta (ATL), Denver (DEN), O’Hare (ORD), Minneapolis (MSP), Dallas-Ft. Worth (DFW), and others.</p>
<p>Top 10 Airports Based on Node Betweenness in the U.S. Airports Network</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(usair)<span class="sc">$</span>name[<span class="fu">order</span>(<span class="fu">betweenness</span>(usair), <span class="at">decreasing=</span>T)][<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#order() gives us the element number in order of ranking.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ANC" "SEA" "DEN" "MSP" "ORD" "FAI" "DTW" "ATL" "BET" "LAX"</code></pre>
</div>
</div>
<p>Among the top 10 airports with the highest betweenness centrality, several are already familiar from the analysis of node degree: Denver (DEN), Minneapolis (MSP), Chicago O’Hare (ORD), Detroit (DTW), Atlanta (ATL), and LAX. However, there are some unexpected inclusions: Anchorage (ANC) emerges as the airport with the highest betweenness centrality by a significant margin. Seattle (SEA), although a major airport, did not feature in the top 10 for node degree but ranks second in terms of betweenness centrality. Notably, two other airports from Alaska, Fairbanks (FAI) and Bethel (BET), also make the list. The presence of Bethel, located in a town with a population of approximately 6,000, is particularly intriguing.</p>
<p>The disparity between the top 10 nodes based on degree and betweenness centrality becomes evident when visualizing the network in geographical space using the downloaded coordinates data. By plotting the network, we can gain a better understanding of the underlying reasons behind this discrepancy.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>longlat<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>long, <span class="fu">V</span>(usair)<span class="sc">$</span>lat), <span class="at">ncol=</span><span class="dv">2</span>) <span class="co">#set up layout matrix </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>longlat, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.size=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A constellation of airports scattered across Alaska, each a beacon in the vast wilderness, a testament to the state’s reliance on air transportation due to its limited road infrastructure.</p>
<p>In our network story, these Alaskan airports might not be the most popular characters, with fewer direct flight connections than their counterparts in the lower 48. But there are a couple of key players, Anchorage in Alaska and Seattle in the contiguous U.S., that act as crucial bridges, connecting Alaska to the rest of the country.</p>
<p>These airports, with their high betweenness centrality, are like the unsung heroes of our tale. They may not have the most connections, but they play a disproportionate role in facilitating travel between Alaska and the rest of the U.S. Their story underscores the unique dynamics and critical roles within our U.S. air transportation network.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.1.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggraph' was built under R version 4.1.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'usair' is your graph</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame of node attributes</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>node_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>name, <span class="at">lat =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>lat, <span class="at">long =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>long)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame of edge attributes</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">get.data.frame</span>(usair, <span class="at">what =</span> <span class="st">"edges"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge node attributes into edge data</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(edge_data, node_data, <span class="at">by.x =</span> <span class="st">"from"</span>, <span class="at">by.y =</span> <span class="st">"id"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(edge_data, node_data, <span class="at">by.x =</span> <span class="st">"to"</span>, <span class="at">by.y =</span> <span class="st">"id"</span>, <span class="at">suffixes =</span> <span class="fu">c</span>(<span class="st">".from"</span>, <span class="st">".to"</span>))</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a ggplot object with the base map</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">borders</span>(<span class="st">"state"</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_quickmap</span>()</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add edges to the plot</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_segment</span>(<span class="at">data =</span> edge_data, <span class="fu">aes</span>(<span class="at">x =</span> long.from, <span class="at">y =</span> lat.from, <span class="at">xend =</span> long.to, <span class="at">yend =</span> lat.to), <span class="at">colour =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Add nodes to the plot</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> node_data, <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat), <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">"tomato"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_point(data = node_data, aes(x = long, y = lat), linewidth = 1, :
Ignoring unknown parameters: `linewidth`</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the plot</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="community-detection-in-the-u.s.-air-transportation-network" class="level2">
<h2 class="anchored" data-anchor-id="community-detection-in-the-u.s.-air-transportation-network">Community detection in the U.S. air transportation network</h2>
<p>I’ve been delving into the chapters of our U.S. airports network story, inspired by the work of Guimerà and colleagues (2005). They discovered that the global airport network is like a community, with distinct regions tightly knit together, like close-knit neighborhoods in a bustling city.</p>
<p>Now, we’re about to embark on a similar journey with our U.S. domestic air transportation network. We’re going to use a tool called the fast greedy method, a community detection algorithm that’s like a speed-reader, quickly identifying clusters within our network. It’s a bit more efficient than the simulated annealing algorithm used in the original study, like choosing a fast-paced thriller over a slow-burning novel.</p>
<p>By applying this approach, we’re not just identifying clusters in our network. We’re uncovering the neighborhoods in our city, the communities within our story. This exploration will help us understand the underlying structure of our network, adding another layer of depth to our narrative.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fg<span class="ot">=</span><span class="fu">fastgreedy.community</span>(usair) </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(fg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modularity</span>(fg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3644685</code></pre>
</div>
</div>
<p>To visualize the community structure in the U.S. air transportation network, we will assign different colors to the nodes based on their community membership. By utilizing the RColorBrewer package, we can generate a palette of 12 distinct colors, representing the maximum number of communities detected. However, the last two communities will be displayed as white to ensure visibility and clarity in the plot. This visualization will provide an intuitive representation of the network’s clustering patterns and the interplay between different communities.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'RColorBrewer' was built under R version 4.1.3</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fgmembership<span class="ot">=</span><span class="fu">membership</span>(fg)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>colors.fg<span class="ot">=</span><span class="fu">c</span>(<span class="fu">brewer.pal</span>(<span class="dv">12</span>, <span class="at">name=</span><span class="st">"Paired"</span>), <span class="fu">rep</span>(<span class="st">"white"</span>,<span class="dv">2</span>)) <span class="co">#first 12 colors from RColorBrewer, last 2 communities are white</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>longlat, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.color=</span>colors.fg[fgmembership], <span class="at">vertex.size=</span><span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Our network is a vibrant tapestry of communities, each with its own unique patterns and characteristics. Some align with geographical regions like Alaska, the West Coast, and the Eastern seaboard, while others form smaller local subnetworks. There are even a few clusters that break the mold, representing private airports or Air Force bases.</p>
<p>In this network narrative, each airport plays a role, and to understand these roles, we turn to two measures introduced by Guimerà and colleagues (2005): the Within-Community Degree (z) and the Participation Coefficient (P).</p>
<p>Imagine the Within-Community Degree as a measure of a character’s popularity within their own community. It’s like calculating a z-score for each airport’s degree within its community, giving us a sense of its relative importance.</p>
<p>The Participation Coefficient, on the other hand, is a measure of a character’s connections across different communities. It tells us how evenly an airport’s links are distributed across the network, with values close to one indicating a well-traveled character and values close to zero indicating a homebody.</p>
<p>By examining these measures, we can understand the roles each airport plays in our network story, shedding light on their importance within and across communities. It’s through this exploration that we can truly understand the intricate dynamics of our U.S. air transportation network.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">##calculate within-module degree, z</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>z<span class="ot">=</span><span class="fu">list</span>()</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">max</span>(fgmembership)){ </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  newg<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(fgmembership<span class="sc">!=</span>i)) </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>wideg<span class="ot">=</span><span class="fu">degree</span>(newg) </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>z[[i]]<span class="ot">=</span>(wideg<span class="sc">-</span><span class="fu">mean</span>(wideg))<span class="sc">/</span><span class="fu">sd</span>(wideg)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>z<span class="ot">=</span><span class="fu">unlist</span>(z)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate participation coefficient</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>p<span class="ot">=</span><span class="fu">vector</span>(<span class="at">length=</span><span class="fu">vcount</span>(usair))</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">vcount</span>(usair)){</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>nei<span class="ot">=</span><span class="fu">neighbors</span>(usair, i) <span class="co">#get all neighbors of node i </span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>tab<span class="ot">=</span><span class="fu">table</span>(fgmembership[<span class="at">names=</span>nei]) <span class="co">#get table of community membership for neighbors </span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>p[i]<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">sum</span>((tab<span class="sc">/</span><span class="fu">sum</span>(tab))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="co">#create dataframe with airport name, z and p</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">V</span>(usair)<span class="sc">$</span>name, <span class="at">z=</span>z[<span class="fu">match</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>name,<span class="fu">names</span>(z))], <span class="at">p=</span>p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s plot the z-P phase-space</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>p, dat<span class="sc">$</span>z, <span class="at">pch=</span><span class="dv">10</span>, <span class="at">ylab=</span><span class="st">"Within-Community Degree (z)"</span>, <span class="at">xlab=</span><span class="st">"Participation Coefficient (p)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="FinalProject_RahulGundeti_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the igraph library</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'usair' and 'USairports' are your igraph network objects</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the edge lists for each graph</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>edge_list1 <span class="ot">&lt;-</span> <span class="fu">get.edgelist</span>(usair)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>edge_list2 <span class="ot">&lt;-</span> <span class="fu">get.edgelist</span>(USairports)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the edge lists to character vectors</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>edge_vector1 <span class="ot">&lt;-</span> <span class="fu">apply</span>(edge_list1, <span class="dv">1</span>, paste, <span class="at">collapse =</span> <span class="st">"-"</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>edge_vector2 <span class="ot">&lt;-</span> <span class="fu">apply</span>(edge_list2, <span class="dv">1</span>, paste, <span class="at">collapse =</span> <span class="st">"-"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the Jaccard similarity between the two edge lists</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>intersection <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">intersect</span>(edge_vector1, edge_vector2))</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>union <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">union</span>(edge_vector1, edge_vector2))</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>jaccard_similarity <span class="ot">&lt;-</span> intersection <span class="sc">/</span> union</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Jaccard similarity</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(jaccard_similarity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.441536</code></pre>
</div>
</div>
<p>I’ve been using a tool called the Jaccard similarity coefficient to compare two characters in our network story: ‘usair’ and ‘USairports’. This tool is like a magnifying glass, allowing us to examine the similarities and differences between these two graphs.</p>
<p>Imagine each graph as a bustling city, and each edge as a road connecting two locations. We convert these roads into a list and then transform them into a string of characters, like naming each road after the two locations it connects.</p>
<p>Next, we find the common roads between our two cities - the intersection - and all the roads in both cities - the union. The Jaccard similarity coefficient is then calculated as the ratio of the common roads to all roads.</p>
<p>In our case, the Jaccard similarity coefficient is 0.441536. This means that around 44.15% of all roads in both cities are common. It’s like finding out that almost half of the roads in one city can also be found in the other.</p>
<p>The significance of this value is like a plot twist in our story. If our cities are supposed to be identical, a value of 0.441536 might suggest significant differences. But if they’re meant to be different, this value could indicate a surprising level of similarity. It’s through this lens that we can truly understand the relationship between ‘usair’ and ‘USairports’ in our network narrative.</p>
</section>
<section id="challenges" class="level2">
<h2 class="anchored" data-anchor-id="challenges">Challenges</h2>
<p>Let’s reflect on the challenges we faced and the insights we gained.</p>
<p>Our first challenge was to simplify and clean up our network, removing any inconsistencies and focusing on the main stage. This process, while necessary, required careful attention to detail to ensure accuracy.</p>
<p>Next, we delved into the roles of airports in our network, using degree and betweenness centrality. Unraveling these roles was like peeling back layers, revealing the intricate dynamics within our network. However, interpreting these measures required a deep understanding of network theory.</p>
<p>We also faced the challenge of identifying and understanding the communities within our network. Using the fast greedy method, we discovered distinct clusters that aligned with geographical regions. But understanding these clusters and their significance required a keen eye and a deep understanding of the U.S. air transportation system.</p>
<p>Finally, we compared our network, ‘usair’, with another, ‘USairports’, using the Jaccard similarity coefficient. This comparison revealed surprising similarities and differences, but interpreting these findings required a nuanced understanding of the measure and the context.</p>
<p>Despite these challenges, our journey through the U.S. air transportation network has been enlightening. We’ve seen the network from different perspectives, uncovered its communities, and understood the roles of its airports. We’ve compared it with another network and discovered surprising similarities and differences.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>As we conclude our exploration of the U.S. air transportation network, we find ourselves standing at the intersection of data, technology, and the complex dynamics of air travel. This journey has taken us through the intricate web of connections that make up our network, revealing the hidden patterns and structures that underpin the bustling activity of airports and flights across the country.</p>
<p>Our analysis has shed light on the roles of individual airports, the communities they form, and the importance of their connections. We’ve seen how some airports act as crucial hubs, connecting disparate regions and facilitating the efficient movement of passengers. We’ve also discovered that our network is not a homogeneous entity but a tapestry of interconnected communities, each with its own unique characteristics and dynamics.</p>
<p>Comparing our network with another has revealed surprising similarities and differences, underscoring the importance of context and interpretation in network analysis. This comparison has not only deepened our understanding of our own network but also highlighted the value of comparative analysis in uncovering new insights and perspectives.</p>
<p>However, this journey is far from over. The ever-evolving landscape of the airline industry presents new challenges and opportunities for network analysis. As routes change, airports expand, and passenger behavior evolves, our network will continue to transform. Staying abreast of these changes and continuously refining our analysis will be crucial in maintaining a clear and up-to-date understanding of our network.</p>
<p>In conclusion, our exploration of the U.S. air transportation network has been a fascinating journey, revealing the complex structures and dynamics that underpin the world of air travel. The insights we’ve gained will serve as a valuable guide as we navigate the future of the airline industry, helping us to make informed decisions, identify opportunities, and anticipate challenges. As we look to the future, we are excited to continue our journey, exploring new territories and uncovering new insights in the ever-evolving world of air transportation.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/Social_Networks_Spring_2023" data-repo-id="R_kgDOI9d_OA" data-category="Announcements" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb39" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Unveiling the Hidden Network: Exploring the Intricacies of the U.S. Air Transportation System"</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Rahul Gundeti"</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "A spatial analysis on US air network transoprt system"</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "05/07/2023"</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - final project</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="co">  - Social networks</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>Considering a data analyst in the airline industry, I've been diving deep into the fascinating world of air transportation networks. Picture this: airports across the globe, each a bustling hub of activity, connected by a vast web of airline routes. This is our playing field, a prime example of a spatial network.</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>A few years back, a groundbreaking study by Guimerà and colleagues (2005) took a close look at this network. They explored the importance of each airport (or 'node') in the network, and how different measures can provide unique insights. They even proposed alternative ways of assessing the position of a node, shedding light on the diverse roles airports play in this complex network.</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>Now, imagine we're conducting a 'virtual knockout experiment'. It's a bit like a game of Jenga, but instead of wooden blocks, we're dealing with airports. We carefully remove one node at a time, observing the effects on the network. This isn't just a game, though. These experiments are crucial for understanding how resilient our network is to disruptions.</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>Think about it. If an airport suddenly goes offline - due to a natural disaster, for instance - how does that impact the rest of the network? Can flights be rerouted efficiently? Do other airports become overloaded? These are the kinds of questions we're seeking to answer.</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>And it's not just the airline industry that benefits from this kind of analysis. Similar methods are used to study everything from power grids to social networks, and even the spatial networks of organisms. By understanding the potential impacts of node failure, we can make our networks more robust and resilient.</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>So, as we navigate the ever-changing landscape of the airline industry, we're not just looking at numbers and routes. We're telling the story of our network, understanding its strengths and weaknesses, and preparing for whatever the future may hold.</span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Acquisition and visualization of the US air transportation network</span></span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>As a data analyst in the airline industry, I've been exploring the intricate tapestry of the US domestic air transportation network. Picture this: a bustling network of airports, each a hub of activity, connected by the invisible threads of flights. These threads, each representing a flight that took place in December 2010, weave together to form a complex and dynamic pattern.</span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a>This pattern, our network, is more than just a collection of airports and flights. It's a snapshot of our industry's heartbeat during that month. Each node, an airport, pulsates with life, sending out flights that ripple across the network. Each edge, a flight, is a connection, a link that ties our network together.</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a>This dataset is our playground. It allows us to delve into the connectivity and dynamics of our air transportation system during that period. We can probe its structure, examine its function, and uncover the hidden patterns that lie beneath the surface.</span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a>So, as we navigate through this network, we're not just looking at airports and flights. We're embarking on a journey, a journey that takes us deep into the heart of our industry. We're exploring the story of our network, a story that is woven with flights and etched in the hustle and bustle of airports. And as we unravel this story, we gain insights that help us understand our industry better and prepare for the future.</span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{r Loading required libraries}</span></span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph) </span>
<span id="cb39-43"><a href="#cb39-43" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraphdata) </span>
<span id="cb39-44"><a href="#cb39-44" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(USairports) </span>
<span id="cb39-45"><a href="#cb39-45" aria-hidden="true" tabindex="-1"></a>USairports</span>
<span id="cb39-46"><a href="#cb39-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-47"><a href="#cb39-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-48"><a href="#cb39-48" aria-hidden="true" tabindex="-1"></a>I've been working with the US domestic air transportation network dataset, a vibrant tapestry of airports and flights. Each airport, a bustling node in our network, has a "Position" attribute, a set of coordinates that pinpoints its location on the globe. But, like any good story, there's a twist. Some of these positions might not be entirely accurate due to minor discrepancies in airport codes and coordinates.</span>
<span id="cb39-49"><a href="#cb39-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-50"><a href="#cb39-50" aria-hidden="true" tabindex="-1"></a>So, I turned to the Open Flights project, a treasure trove of comprehensive airport location data. Picture me, a data detective, downloading this dataset directly from the web, ready to cross-verify our airport locations. This isn't just about dotting the i's and crossing the t's. It's about ensuring the story we tell with our data is as accurate and reliable as possible.</span>
<span id="cb39-51"><a href="#cb39-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-52"><a href="#cb39-52" aria-hidden="true" tabindex="-1"></a>By integrating this external dataset, we're not just enhancing the precision of our airport locations. We're adding another layer of depth to our analysis, enabling us to paint a more accurate picture of our network. This way, we can conduct a more precise spatial analysis and visualization, bringing the story of our network to life in the most authentic way possible.</span>
<span id="cb39-53"><a href="#cb39-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-56"><a href="#cb39-56" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-57"><a href="#cb39-57" aria-hidden="true" tabindex="-1"></a>airports<span class="ot">=</span><span class="fu">read.csv</span>(<span class="st">'https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat'</span>, <span class="at">header=</span>F)</span>
<span id="cb39-58"><a href="#cb39-58" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airports)</span>
<span id="cb39-59"><a href="#cb39-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-60"><a href="#cb39-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-61"><a href="#cb39-61" aria-hidden="true" tabindex="-1"></a>I've been on a mission to bring our US air transportation network to life. And now, with the Open Flights project's airport location data in hand, we're ready to take the next step.</span>
<span id="cb39-62"><a href="#cb39-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-63"><a href="#cb39-63" aria-hidden="true" tabindex="-1"></a>Imagine each airport as a character in our story. Each one has its own unique set of coordinates - its latitude and longitude - that tells us exactly where it's located in the world. These coordinates, tucked away in columns 7 and 8 of our dataset, are about to take center stage.</span>
<span id="cb39-64"><a href="#cb39-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-65"><a href="#cb39-65" aria-hidden="true" tabindex="-1"></a>We're going to import this data and assign each airport its rightful place on the map. This isn't just about getting the details right. It's about ensuring that our story - the story of our network - is as accurate and authentic as possible.</span>
<span id="cb39-66"><a href="#cb39-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-67"><a href="#cb39-67" aria-hidden="true" tabindex="-1"></a>With the correct latitude and longitude values associated with each airport, we can conduct a more precise spatial analysis and visualization of our network. This means our analyses and visualizations will truly reflect the real-world locations of our airports, enhancing the credibility and impact of our findings. It's another step forward in our journey to understand and tell the story of our network.</span>
<span id="cb39-68"><a href="#cb39-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-71"><a href="#cb39-71" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-72"><a href="#cb39-72" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(USairports)<span class="sc">$</span>lat<span class="ot">=</span>airports[<span class="fu">match</span>(<span class="fu">V</span>(USairports)<span class="sc">$</span>name, airports[,<span class="dv">5</span>]), <span class="dv">7</span>] </span>
<span id="cb39-73"><a href="#cb39-73" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(USairports)<span class="sc">$</span>long<span class="ot">=</span>airports[<span class="fu">match</span>(<span class="fu">V</span>(USairports)<span class="sc">$</span>name, airports[,<span class="dv">5</span>]), <span class="dv">8</span>]</span>
<span id="cb39-74"><a href="#cb39-74" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-75"><a href="#cb39-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-76"><a href="#cb39-76" aria-hidden="true" tabindex="-1"></a>I've been preparing our US air transportation network for its moment in the spotlight. But before it's ready for its debut, we need to make sure it's looking its best. That's where our data cleanup steps come in.</span>
<span id="cb39-77"><a href="#cb39-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-78"><a href="#cb39-78" aria-hidden="true" tabindex="-1"></a>First, we're going to simplify the network. Think of it as decluttering a room. We're removing any loops and converting the network into an undirected format. This will make our network easier to understand and eliminate any unnecessary complexities.</span>
<span id="cb39-79"><a href="#cb39-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-80"><a href="#cb39-80" aria-hidden="true" tabindex="-1"></a>Next, we're going to address any mismatched nodes. These are like the odd socks in a drawer - airport codes that don't match up with the Open Flights database. By removing these, we're ensuring the accuracy and consistency of our data.</span>
<span id="cb39-81"><a href="#cb39-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-82"><a href="#cb39-82" aria-hidden="true" tabindex="-1"></a>Then, we're going to zoom in on the main stage by excluding US territories in the Eastern and Southern Hemispheres. This will allow us to focus on the heart of the US domestic air transportation network, making our analysis clearer and more focused.</span>
<span id="cb39-83"><a href="#cb39-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-84"><a href="#cb39-84" aria-hidden="true" tabindex="-1"></a>Finally, we're going to spotlight the star of the show - the largest connected component, also known as the 'giant component'. This is the most interconnected subset of our network, and by focusing on this, we can derive meaningful insights and simplify our analysis.</span>
<span id="cb39-85"><a href="#cb39-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-86"><a href="#cb39-86" aria-hidden="true" tabindex="-1"></a>Once these steps are complete, we'll be left with a refined network representation, which we'll call "usair". This will be our star performer, ready to take center stage in our subsequent analysis and visualization tasks. It's through this refined lens that we'll gain a deeper understanding of the intricate dance that is the US air transportation network.</span>
<span id="cb39-87"><a href="#cb39-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-90"><a href="#cb39-90" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-91"><a href="#cb39-91" aria-hidden="true" tabindex="-1"></a><span class="co">#remove loops and make undirected</span></span>
<span id="cb39-92"><a href="#cb39-92" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">as.undirected</span>(<span class="fu">simplify</span>(USairports))</span>
<span id="cb39-93"><a href="#cb39-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-94"><a href="#cb39-94" aria-hidden="true" tabindex="-1"></a><span class="co">#remove airports whose codes didn't match the OpenFlights database (and hence returned "NA" for latitude)</span></span>
<span id="cb39-95"><a href="#cb39-95" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">is.na</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>lat)<span class="sc">==</span><span class="cn">TRUE</span>))</span>
<span id="cb39-96"><a href="#cb39-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-97"><a href="#cb39-97" aria-hidden="true" tabindex="-1"></a><span class="co">#remove nodes in the Eastern and Southern Hemispheres (US territories). This will make the plot easier to see.</span></span>
<span id="cb39-98"><a href="#cb39-98" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>lat<span class="sc">&lt;</span><span class="dv">0</span>))</span>
<span id="cb39-99"><a href="#cb39-99" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>long<span class="sc">&gt;</span><span class="dv">0</span>))</span>
<span id="cb39-100"><a href="#cb39-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-101"><a href="#cb39-101" aria-hidden="true" tabindex="-1"></a><span class="co">#keep only the largest connected component of the network ("giant component"). this also makes the network easier to see.</span></span>
<span id="cb39-102"><a href="#cb39-102" aria-hidden="true" tabindex="-1"></a>decomp<span class="ot">=</span><span class="fu">decompose.graph</span>(usair)</span>
<span id="cb39-103"><a href="#cb39-103" aria-hidden="true" tabindex="-1"></a>usair<span class="ot">=</span>decomp[[<span class="dv">1</span>]]</span>
<span id="cb39-104"><a href="#cb39-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-105"><a href="#cb39-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-106"><a href="#cb39-106" aria-hidden="true" tabindex="-1"></a>I've been working on a masterpiece: a refined representation of the US domestic air transportation network, affectionately named "usair". This isn't just a collection of airports and flights. It's a story waiting to be told.</span>
<span id="cb39-107"><a href="#cb39-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-108"><a href="#cb39-108" aria-hidden="true" tabindex="-1"></a>Imagine each airport as a character in our narrative, each flight a connection, a relationship. As we delve into the analysis of this network, we're not just crunching numbers. We're exploring the intricate web of relationships between our characters, uncovering the key patterns and dynamics that drive the story forward.</span>
<span id="cb39-109"><a href="#cb39-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-110"><a href="#cb39-110" aria-hidden="true" tabindex="-1"></a>Through the lens of visualization, we can see the grand dance of air traffic across the US, the ebb and flow of flights between airports, the intricate choreography of our network. This is more than just a dance, though. It's a window into the heart of our industry, a way to understand the complexities of our air transportation system.</span>
<span id="cb39-111"><a href="#cb39-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-112"><a href="#cb39-112" aria-hidden="true" tabindex="-1"></a>As we continue our journey, we'll delve deeper into the story, exploring the importance of each character, the resilience of our network, and other key metrics. Each step brings us closer to understanding the narrative of our network, the story of the US air transportation system.</span>
<span id="cb39-113"><a href="#cb39-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-116"><a href="#cb39-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-117"><a href="#cb39-117" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb39-118"><a href="#cb39-118" aria-hidden="true" tabindex="-1"></a>l<span class="ot">=</span><span class="fu">layout_nicely</span>(usair)</span>
<span id="cb39-119"><a href="#cb39-119" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb39-120"><a href="#cb39-120" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>l, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.size=</span><span class="dv">4</span>)</span>
<span id="cb39-121"><a href="#cb39-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-122"><a href="#cb39-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-123"><a href="#cb39-123" aria-hidden="true" tabindex="-1"></a><span class="fu">## Degree and Betweenness Centrality Relationship in the U.S. Airports Network</span></span>
<span id="cb39-124"><a href="#cb39-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-125"><a href="#cb39-125" aria-hidden="true" tabindex="-1"></a>I've been using two trusty tools: degree centrality and betweenness centrality.</span>
<span id="cb39-126"><a href="#cb39-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-127"><a href="#cb39-127" aria-hidden="true" tabindex="-1"></a>Imagine degree centrality as a measure of popularity. It tells us how many direct flights an airport has, reflecting its connectivity and accessibility. It's like counting how many friends a character has in our story.</span>
<span id="cb39-128"><a href="#cb39-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-129"><a href="#cb39-129" aria-hidden="true" tabindex="-1"></a>Betweenness centrality, on the other hand, is a measure of influence. It tells us how often an airport acts as a bridge between other airports, a crucial transfer hub in the network. It's like tracking how many plotlines a character is involved in.</span>
<span id="cb39-130"><a href="#cb39-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-131"><a href="#cb39-131" aria-hidden="true" tabindex="-1"></a>But, like any good story, there's a twist. Our analysis uses a simplified network that only considers unique flight routes. It doesn't take into account factors like the frequency of flights, replicated routes, or the size of aircraft. It's a bit like focusing on the main plot and leaving out some of the subplots.</span>
<span id="cb39-132"><a href="#cb39-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-133"><a href="#cb39-133" aria-hidden="true" tabindex="-1"></a>By examining these two measures, we can identify the key players in our network, understand the flow of air traffic, and assess the importance of each airport in connecting different regions of the country. It's through this exploration that we can truly understand the narrative of our network and the roles each character plays in our story.</span>
<span id="cb39-134"><a href="#cb39-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-137"><a href="#cb39-137" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-138"><a href="#cb39-138" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">degree</span>(usair), <span class="fu">betweenness</span>(usair), <span class="at">pch=</span><span class="dv">10</span>) </span>
<span id="cb39-139"><a href="#cb39-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-140"><a href="#cb39-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-141"><a href="#cb39-141" aria-hidden="true" tabindex="-1"></a>Imagine degree and betweenness centrality as two characters in our narrative, usually seen together, reflecting an airport's popularity and influence. But there are a few airports, the mavericks of our story, that break this mold.</span>
<span id="cb39-142"><a href="#cb39-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-143"><a href="#cb39-143" aria-hidden="true" tabindex="-1"></a>In the bustling world of U.S. domestic flights, one airport stands out. It doesn't have the highest degree - it's not the most popular character in our story. But it has a remarkably high betweenness centrality. This airport is like the unsung hero of our tale, quietly playing a critical role as a transfer hub, ensuring passengers move efficiently between different regions of the country.</span>
<span id="cb39-144"><a href="#cb39-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-145"><a href="#cb39-145" aria-hidden="true" tabindex="-1"></a>This unique character in our network story highlights the fascinating complexities and unexpected dynamics within the U.S. air transportation system.</span>
<span id="cb39-146"><a href="#cb39-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-147"><a href="#cb39-147" aria-hidden="true" tabindex="-1"></a>To examine notable points, let's begin by exploring the top 10 airports based on their node degree.</span>
<span id="cb39-148"><a href="#cb39-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-151"><a href="#cb39-151" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-152"><a href="#cb39-152" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(usair)<span class="sc">$</span>name[<span class="fu">order</span>(<span class="fu">degree</span>(usair), <span class="at">decreasing=</span>T)][<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#order() gives us the element number in order of ranking.</span></span>
<span id="cb39-153"><a href="#cb39-153" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-154"><a href="#cb39-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-155"><a href="#cb39-155" aria-hidden="true" tabindex="-1"></a>The analysis reveals that the majority of the top 10 airports, based on node degree, are prominent hubs situated within the interior of the lower 48 states. It is important to note that international flights are not considered in this network. Consequently, the list includes well-known airports such as Atlanta (ATL), Denver (DEN), O'Hare (ORD), Minneapolis (MSP), Dallas-Ft. Worth (DFW), and others.</span>
<span id="cb39-156"><a href="#cb39-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-157"><a href="#cb39-157" aria-hidden="true" tabindex="-1"></a>Top 10 Airports Based on Node Betweenness in the U.S. Airports Network</span>
<span id="cb39-158"><a href="#cb39-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-161"><a href="#cb39-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-162"><a href="#cb39-162" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(usair)<span class="sc">$</span>name[<span class="fu">order</span>(<span class="fu">betweenness</span>(usair), <span class="at">decreasing=</span>T)][<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co">#order() gives us the element number in order of ranking.</span></span>
<span id="cb39-163"><a href="#cb39-163" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-164"><a href="#cb39-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-165"><a href="#cb39-165" aria-hidden="true" tabindex="-1"></a>Among the top 10 airports with the highest betweenness centrality, several are already familiar from the analysis of node degree: Denver (DEN), Minneapolis (MSP), Chicago O'Hare (ORD), Detroit (DTW), Atlanta (ATL), and LAX. However, there are some unexpected inclusions: Anchorage (ANC) emerges as the airport with the highest betweenness centrality by a significant margin. Seattle (SEA), although a major airport, did not feature in the top 10 for node degree but ranks second in terms of betweenness centrality. Notably, two other airports from Alaska, Fairbanks (FAI) and Bethel (BET), also make the list. The presence of Bethel, located in a town with a population of approximately 6,000, is particularly intriguing.</span>
<span id="cb39-166"><a href="#cb39-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-167"><a href="#cb39-167" aria-hidden="true" tabindex="-1"></a>The disparity between the top 10 nodes based on degree and betweenness centrality becomes evident when visualizing the network in geographical space using the downloaded coordinates data. By plotting the network, we can gain a better understanding of the underlying reasons behind this discrepancy.</span>
<span id="cb39-168"><a href="#cb39-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-171"><a href="#cb39-171" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-172"><a href="#cb39-172" aria-hidden="true" tabindex="-1"></a>longlat<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>long, <span class="fu">V</span>(usair)<span class="sc">$</span>lat), <span class="at">ncol=</span><span class="dv">2</span>) <span class="co">#set up layout matrix </span></span>
<span id="cb39-173"><a href="#cb39-173" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb39-174"><a href="#cb39-174" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>longlat, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.size=</span><span class="dv">3</span>)</span>
<span id="cb39-175"><a href="#cb39-175" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-176"><a href="#cb39-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-177"><a href="#cb39-177" aria-hidden="true" tabindex="-1"></a>A constellation of airports scattered across Alaska, each a beacon in the vast wilderness, a testament to the state's reliance on air transportation due to its limited road infrastructure.</span>
<span id="cb39-178"><a href="#cb39-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-179"><a href="#cb39-179" aria-hidden="true" tabindex="-1"></a>In our network story, these Alaskan airports might not be the most popular characters, with fewer direct flight connections than their counterparts in the lower 48. But there are a couple of key players, Anchorage in Alaska and Seattle in the contiguous U.S., that act as crucial bridges, connecting Alaska to the rest of the country.</span>
<span id="cb39-180"><a href="#cb39-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-181"><a href="#cb39-181" aria-hidden="true" tabindex="-1"></a>These airports, with their high betweenness centrality, are like the unsung heroes of our tale. They may not have the most connections, but they play a disproportionate role in facilitating travel between Alaska and the rest of the U.S. Their story underscores the unique dynamics and critical roles within our U.S. air transportation network.</span>
<span id="cb39-182"><a href="#cb39-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-185"><a href="#cb39-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-186"><a href="#cb39-186" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the necessary libraries</span></span>
<span id="cb39-187"><a href="#cb39-187" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb39-188"><a href="#cb39-188" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb39-189"><a href="#cb39-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-190"><a href="#cb39-190" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'usair' is your graph</span></span>
<span id="cb39-191"><a href="#cb39-191" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame of node attributes</span></span>
<span id="cb39-192"><a href="#cb39-192" aria-hidden="true" tabindex="-1"></a>node_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>name, <span class="at">lat =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>lat, <span class="at">long =</span> <span class="fu">V</span>(usair)<span class="sc">$</span>long)</span>
<span id="cb39-193"><a href="#cb39-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-194"><a href="#cb39-194" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame of edge attributes</span></span>
<span id="cb39-195"><a href="#cb39-195" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">get.data.frame</span>(usair, <span class="at">what =</span> <span class="st">"edges"</span>)</span>
<span id="cb39-196"><a href="#cb39-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-197"><a href="#cb39-197" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge node attributes into edge data</span></span>
<span id="cb39-198"><a href="#cb39-198" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(edge_data, node_data, <span class="at">by.x =</span> <span class="st">"from"</span>, <span class="at">by.y =</span> <span class="st">"id"</span>)</span>
<span id="cb39-199"><a href="#cb39-199" aria-hidden="true" tabindex="-1"></a>edge_data <span class="ot">&lt;-</span> <span class="fu">merge</span>(edge_data, node_data, <span class="at">by.x =</span> <span class="st">"to"</span>, <span class="at">by.y =</span> <span class="st">"id"</span>, <span class="at">suffixes =</span> <span class="fu">c</span>(<span class="st">".from"</span>, <span class="st">".to"</span>))</span>
<span id="cb39-200"><a href="#cb39-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-201"><a href="#cb39-201" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a ggplot object with the base map</span></span>
<span id="cb39-202"><a href="#cb39-202" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb39-203"><a href="#cb39-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">borders</span>(<span class="st">"state"</span>, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb39-204"><a href="#cb39-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_quickmap</span>()</span>
<span id="cb39-205"><a href="#cb39-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-206"><a href="#cb39-206" aria-hidden="true" tabindex="-1"></a><span class="co"># Add edges to the plot</span></span>
<span id="cb39-207"><a href="#cb39-207" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_segment</span>(<span class="at">data =</span> edge_data, <span class="fu">aes</span>(<span class="at">x =</span> long.from, <span class="at">y =</span> lat.from, <span class="at">xend =</span> long.to, <span class="at">yend =</span> lat.to), <span class="at">colour =</span> <span class="st">"gray"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>)</span>
<span id="cb39-208"><a href="#cb39-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-209"><a href="#cb39-209" aria-hidden="true" tabindex="-1"></a><span class="co"># Add nodes to the plot</span></span>
<span id="cb39-210"><a href="#cb39-210" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">data =</span> node_data, <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat), <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">"tomato"</span>)</span>
<span id="cb39-211"><a href="#cb39-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-212"><a href="#cb39-212" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the plot</span></span>
<span id="cb39-213"><a href="#cb39-213" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span>
<span id="cb39-214"><a href="#cb39-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-215"><a href="#cb39-215" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-216"><a href="#cb39-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-217"><a href="#cb39-217" aria-hidden="true" tabindex="-1"></a><span class="fu">## Community detection in the U.S. air transportation network</span></span>
<span id="cb39-218"><a href="#cb39-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-219"><a href="#cb39-219" aria-hidden="true" tabindex="-1"></a>I've been delving into the chapters of our U.S. airports network story, inspired by the work of Guimerà and colleagues (2005). They discovered that the global airport network is like a community, with distinct regions tightly knit together, like close-knit neighborhoods in a bustling city.</span>
<span id="cb39-220"><a href="#cb39-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-221"><a href="#cb39-221" aria-hidden="true" tabindex="-1"></a>Now, we're about to embark on a similar journey with our U.S. domestic air transportation network. We're going to use a tool called the fast greedy method, a community detection algorithm that's like a speed-reader, quickly identifying clusters within our network. It's a bit more efficient than the simulated annealing algorithm used in the original study, like choosing a fast-paced thriller over a slow-burning novel.</span>
<span id="cb39-222"><a href="#cb39-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-223"><a href="#cb39-223" aria-hidden="true" tabindex="-1"></a>By applying this approach, we're not just identifying clusters in our network. We're uncovering the neighborhoods in our city, the communities within our story. This exploration will help us understand the underlying structure of our network, adding another layer of depth to our narrative.</span>
<span id="cb39-224"><a href="#cb39-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-227"><a href="#cb39-227" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-228"><a href="#cb39-228" aria-hidden="true" tabindex="-1"></a>fg<span class="ot">=</span><span class="fu">fastgreedy.community</span>(usair) </span>
<span id="cb39-229"><a href="#cb39-229" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(fg)</span>
<span id="cb39-230"><a href="#cb39-230" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-231"><a href="#cb39-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-234"><a href="#cb39-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-235"><a href="#cb39-235" aria-hidden="true" tabindex="-1"></a><span class="fu">modularity</span>(fg)</span>
<span id="cb39-236"><a href="#cb39-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-237"><a href="#cb39-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-238"><a href="#cb39-238" aria-hidden="true" tabindex="-1"></a>To visualize the community structure in the U.S. air transportation network, we will assign different colors to the nodes based on their community membership. By utilizing the RColorBrewer package, we can generate a palette of 12 distinct colors, representing the maximum number of communities detected. However, the last two communities will be displayed as white to ensure visibility and clarity in the plot. This visualization will provide an intuitive representation of the network's clustering patterns and the interplay between different communities.</span>
<span id="cb39-239"><a href="#cb39-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-242"><a href="#cb39-242" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-243"><a href="#cb39-243" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer)</span>
<span id="cb39-244"><a href="#cb39-244" aria-hidden="true" tabindex="-1"></a>fgmembership<span class="ot">=</span><span class="fu">membership</span>(fg)</span>
<span id="cb39-245"><a href="#cb39-245" aria-hidden="true" tabindex="-1"></a>colors.fg<span class="ot">=</span><span class="fu">c</span>(<span class="fu">brewer.pal</span>(<span class="dv">12</span>, <span class="at">name=</span><span class="st">"Paired"</span>), <span class="fu">rep</span>(<span class="st">"white"</span>,<span class="dv">2</span>)) <span class="co">#first 12 colors from RColorBrewer, last 2 communities are white</span></span>
<span id="cb39-246"><a href="#cb39-246" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb39-247"><a href="#cb39-247" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(usair, <span class="at">layout=</span>longlat, <span class="at">vertex.label=</span><span class="st">""</span>, <span class="at">vertex.color=</span>colors.fg[fgmembership], <span class="at">vertex.size=</span><span class="dv">5</span>)</span>
<span id="cb39-248"><a href="#cb39-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-249"><a href="#cb39-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-250"><a href="#cb39-250" aria-hidden="true" tabindex="-1"></a>Our network is a vibrant tapestry of communities, each with its own unique patterns and characteristics. Some align with geographical regions like Alaska, the West Coast, and the Eastern seaboard, while others form smaller local subnetworks. There are even a few clusters that break the mold, representing private airports or Air Force bases.</span>
<span id="cb39-251"><a href="#cb39-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-252"><a href="#cb39-252" aria-hidden="true" tabindex="-1"></a>In this network narrative, each airport plays a role, and to understand these roles, we turn to two measures introduced by Guimerà and colleagues (2005): the Within-Community Degree (z) and the Participation Coefficient (P).</span>
<span id="cb39-253"><a href="#cb39-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-254"><a href="#cb39-254" aria-hidden="true" tabindex="-1"></a>Imagine the Within-Community Degree as a measure of a character's popularity within their own community. It's like calculating a z-score for each airport's degree within its community, giving us a sense of its relative importance.</span>
<span id="cb39-255"><a href="#cb39-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-256"><a href="#cb39-256" aria-hidden="true" tabindex="-1"></a>The Participation Coefficient, on the other hand, is a measure of a character's connections across different communities. It tells us how evenly an airport's links are distributed across the network, with values close to one indicating a well-traveled character and values close to zero indicating a homebody.</span>
<span id="cb39-257"><a href="#cb39-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-258"><a href="#cb39-258" aria-hidden="true" tabindex="-1"></a>By examining these measures, we can understand the roles each airport plays in our network story, shedding light on their importance within and across communities. It's through this exploration that we can truly understand the intricate dynamics of our U.S. air transportation network.</span>
<span id="cb39-259"><a href="#cb39-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-262"><a href="#cb39-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-263"><a href="#cb39-263" aria-hidden="true" tabindex="-1"></a><span class="do">##calculate within-module degree, z</span></span>
<span id="cb39-264"><a href="#cb39-264" aria-hidden="true" tabindex="-1"></a>z<span class="ot">=</span><span class="fu">list</span>()</span>
<span id="cb39-265"><a href="#cb39-265" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">max</span>(fgmembership)){ </span>
<span id="cb39-266"><a href="#cb39-266" aria-hidden="true" tabindex="-1"></a>  newg<span class="ot">=</span><span class="fu">delete.vertices</span>(usair, <span class="fu">which</span>(fgmembership<span class="sc">!=</span>i)) </span>
<span id="cb39-267"><a href="#cb39-267" aria-hidden="true" tabindex="-1"></a>wideg<span class="ot">=</span><span class="fu">degree</span>(newg) </span>
<span id="cb39-268"><a href="#cb39-268" aria-hidden="true" tabindex="-1"></a>z[[i]]<span class="ot">=</span>(wideg<span class="sc">-</span><span class="fu">mean</span>(wideg))<span class="sc">/</span><span class="fu">sd</span>(wideg)</span>
<span id="cb39-269"><a href="#cb39-269" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-270"><a href="#cb39-270" aria-hidden="true" tabindex="-1"></a>z<span class="ot">=</span><span class="fu">unlist</span>(z)</span>
<span id="cb39-271"><a href="#cb39-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-272"><a href="#cb39-272" aria-hidden="true" tabindex="-1"></a><span class="do">## calculate participation coefficient</span></span>
<span id="cb39-273"><a href="#cb39-273" aria-hidden="true" tabindex="-1"></a>p<span class="ot">=</span><span class="fu">vector</span>(<span class="at">length=</span><span class="fu">vcount</span>(usair))</span>
<span id="cb39-274"><a href="#cb39-274" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">vcount</span>(usair)){</span>
<span id="cb39-275"><a href="#cb39-275" aria-hidden="true" tabindex="-1"></a>nei<span class="ot">=</span><span class="fu">neighbors</span>(usair, i) <span class="co">#get all neighbors of node i </span></span>
<span id="cb39-276"><a href="#cb39-276" aria-hidden="true" tabindex="-1"></a>tab<span class="ot">=</span><span class="fu">table</span>(fgmembership[<span class="at">names=</span>nei]) <span class="co">#get table of community membership for neighbors </span></span>
<span id="cb39-277"><a href="#cb39-277" aria-hidden="true" tabindex="-1"></a>p[i]<span class="ot">=</span><span class="dv">1</span><span class="sc">-</span><span class="fu">sum</span>((tab<span class="sc">/</span><span class="fu">sum</span>(tab))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb39-278"><a href="#cb39-278" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-279"><a href="#cb39-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-280"><a href="#cb39-280" aria-hidden="true" tabindex="-1"></a><span class="co">#create dataframe with airport name, z and p</span></span>
<span id="cb39-281"><a href="#cb39-281" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">V</span>(usair)<span class="sc">$</span>name, <span class="at">z=</span>z[<span class="fu">match</span>(<span class="fu">V</span>(usair)<span class="sc">$</span>name,<span class="fu">names</span>(z))], <span class="at">p=</span>p)</span>
<span id="cb39-282"><a href="#cb39-282" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-283"><a href="#cb39-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-284"><a href="#cb39-284" aria-hidden="true" tabindex="-1"></a>Let's plot the z-P phase-space</span>
<span id="cb39-285"><a href="#cb39-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-288"><a href="#cb39-288" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-289"><a href="#cb39-289" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>p, dat<span class="sc">$</span>z, <span class="at">pch=</span><span class="dv">10</span>, <span class="at">ylab=</span><span class="st">"Within-Community Degree (z)"</span>, <span class="at">xlab=</span><span class="st">"Participation Coefficient (p)"</span>)</span>
<span id="cb39-290"><a href="#cb39-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-291"><a href="#cb39-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-294"><a href="#cb39-294" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-295"><a href="#cb39-295" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the igraph library</span></span>
<span id="cb39-296"><a href="#cb39-296" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb39-297"><a href="#cb39-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-298"><a href="#cb39-298" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming 'usair' and 'USairports' are your igraph network objects</span></span>
<span id="cb39-299"><a href="#cb39-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-300"><a href="#cb39-300" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the edge lists for each graph</span></span>
<span id="cb39-301"><a href="#cb39-301" aria-hidden="true" tabindex="-1"></a>edge_list1 <span class="ot">&lt;-</span> <span class="fu">get.edgelist</span>(usair)</span>
<span id="cb39-302"><a href="#cb39-302" aria-hidden="true" tabindex="-1"></a>edge_list2 <span class="ot">&lt;-</span> <span class="fu">get.edgelist</span>(USairports)</span>
<span id="cb39-303"><a href="#cb39-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-304"><a href="#cb39-304" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the edge lists to character vectors</span></span>
<span id="cb39-305"><a href="#cb39-305" aria-hidden="true" tabindex="-1"></a>edge_vector1 <span class="ot">&lt;-</span> <span class="fu">apply</span>(edge_list1, <span class="dv">1</span>, paste, <span class="at">collapse =</span> <span class="st">"-"</span>)</span>
<span id="cb39-306"><a href="#cb39-306" aria-hidden="true" tabindex="-1"></a>edge_vector2 <span class="ot">&lt;-</span> <span class="fu">apply</span>(edge_list2, <span class="dv">1</span>, paste, <span class="at">collapse =</span> <span class="st">"-"</span>)</span>
<span id="cb39-307"><a href="#cb39-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-308"><a href="#cb39-308" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the Jaccard similarity between the two edge lists</span></span>
<span id="cb39-309"><a href="#cb39-309" aria-hidden="true" tabindex="-1"></a>intersection <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">intersect</span>(edge_vector1, edge_vector2))</span>
<span id="cb39-310"><a href="#cb39-310" aria-hidden="true" tabindex="-1"></a>union <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">union</span>(edge_vector1, edge_vector2))</span>
<span id="cb39-311"><a href="#cb39-311" aria-hidden="true" tabindex="-1"></a>jaccard_similarity <span class="ot">&lt;-</span> intersection <span class="sc">/</span> union</span>
<span id="cb39-312"><a href="#cb39-312" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-313"><a href="#cb39-313" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Jaccard similarity</span></span>
<span id="cb39-314"><a href="#cb39-314" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(jaccard_similarity)</span>
<span id="cb39-315"><a href="#cb39-315" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-316"><a href="#cb39-316" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-317"><a href="#cb39-317" aria-hidden="true" tabindex="-1"></a>I've been using a tool called the Jaccard similarity coefficient to compare two characters in our network story: 'usair' and 'USairports'. This tool is like a magnifying glass, allowing us to examine the similarities and differences between these two graphs.</span>
<span id="cb39-318"><a href="#cb39-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-319"><a href="#cb39-319" aria-hidden="true" tabindex="-1"></a>Imagine each graph as a bustling city, and each edge as a road connecting two locations. We convert these roads into a list and then transform them into a string of characters, like naming each road after the two locations it connects.</span>
<span id="cb39-320"><a href="#cb39-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-321"><a href="#cb39-321" aria-hidden="true" tabindex="-1"></a>Next, we find the common roads between our two cities - the intersection - and all the roads in both cities - the union. The Jaccard similarity coefficient is then calculated as the ratio of the common roads to all roads.</span>
<span id="cb39-322"><a href="#cb39-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-323"><a href="#cb39-323" aria-hidden="true" tabindex="-1"></a>In our case, the Jaccard similarity coefficient is 0.441536. This means that around 44.15% of all roads in both cities are common. It's like finding out that almost half of the roads in one city can also be found in the other.</span>
<span id="cb39-324"><a href="#cb39-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-325"><a href="#cb39-325" aria-hidden="true" tabindex="-1"></a>The significance of this value is like a plot twist in our story. If our cities are supposed to be identical, a value of 0.441536 might suggest significant differences. But if they're meant to be different, this value could indicate a surprising level of similarity. It's through this lens that we can truly understand the relationship between 'usair' and 'USairports' in our network narrative.</span>
<span id="cb39-326"><a href="#cb39-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-327"><a href="#cb39-327" aria-hidden="true" tabindex="-1"></a><span class="fu">## Challenges</span></span>
<span id="cb39-328"><a href="#cb39-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-329"><a href="#cb39-329" aria-hidden="true" tabindex="-1"></a>Let's reflect on the challenges we faced and the insights we gained.</span>
<span id="cb39-330"><a href="#cb39-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-331"><a href="#cb39-331" aria-hidden="true" tabindex="-1"></a>Our first challenge was to simplify and clean up our network, removing any inconsistencies and focusing on the main stage. This process, while necessary, required careful attention to detail to ensure accuracy.</span>
<span id="cb39-332"><a href="#cb39-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-333"><a href="#cb39-333" aria-hidden="true" tabindex="-1"></a>Next, we delved into the roles of airports in our network, using degree and betweenness centrality. Unraveling these roles was like peeling back layers, revealing the intricate dynamics within our network. However, interpreting these measures required a deep understanding of network theory.</span>
<span id="cb39-334"><a href="#cb39-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-335"><a href="#cb39-335" aria-hidden="true" tabindex="-1"></a>We also faced the challenge of identifying and understanding the communities within our network. Using the fast greedy method, we discovered distinct clusters that aligned with geographical regions. But understanding these clusters and their significance required a keen eye and a deep understanding of the U.S. air transportation system.</span>
<span id="cb39-336"><a href="#cb39-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-337"><a href="#cb39-337" aria-hidden="true" tabindex="-1"></a>Finally, we compared our network, 'usair', with another, 'USairports', using the Jaccard similarity coefficient. This comparison revealed surprising similarities and differences, but interpreting these findings required a nuanced understanding of the measure and the context.</span>
<span id="cb39-338"><a href="#cb39-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-339"><a href="#cb39-339" aria-hidden="true" tabindex="-1"></a>Despite these challenges, our journey through the U.S. air transportation network has been enlightening. We've seen the network from different perspectives, uncovered its communities, and understood the roles of its airports. We've compared it with another network and discovered surprising similarities and differences.</span>
<span id="cb39-340"><a href="#cb39-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-341"><a href="#cb39-341" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb39-342"><a href="#cb39-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-343"><a href="#cb39-343" aria-hidden="true" tabindex="-1"></a>As we conclude our exploration of the U.S. air transportation network, we find ourselves standing at the intersection of data, technology, and the complex dynamics of air travel. This journey has taken us through the intricate web of connections that make up our network, revealing the hidden patterns and structures that underpin the bustling activity of airports and flights across the country.</span>
<span id="cb39-344"><a href="#cb39-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-345"><a href="#cb39-345" aria-hidden="true" tabindex="-1"></a>Our analysis has shed light on the roles of individual airports, the communities they form, and the importance of their connections. We've seen how some airports act as crucial hubs, connecting disparate regions and facilitating the efficient movement of passengers. We've also discovered that our network is not a homogeneous entity but a tapestry of interconnected communities, each with its own unique characteristics and dynamics.</span>
<span id="cb39-346"><a href="#cb39-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-347"><a href="#cb39-347" aria-hidden="true" tabindex="-1"></a>Comparing our network with another has revealed surprising similarities and differences, underscoring the importance of context and interpretation in network analysis. This comparison has not only deepened our understanding of our own network but also highlighted the value of comparative analysis in uncovering new insights and perspectives.</span>
<span id="cb39-348"><a href="#cb39-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-349"><a href="#cb39-349" aria-hidden="true" tabindex="-1"></a>However, this journey is far from over. The ever-evolving landscape of the airline industry presents new challenges and opportunities for network analysis. As routes change, airports expand, and passenger behavior evolves, our network will continue to transform. Staying abreast of these changes and continuously refining our analysis will be crucial in maintaining a clear and up-to-date understanding of our network.</span>
<span id="cb39-350"><a href="#cb39-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-351"><a href="#cb39-351" aria-hidden="true" tabindex="-1"></a>In conclusion, our exploration of the U.S. air transportation network has been a fascinating journey, revealing the complex structures and dynamics that underpin the world of air travel. The insights we've gained will serve as a valuable guide as we navigate the future of the airline industry, helping us to make informed decisions, identify opportunities, and anticipate challenges. As we look to the future, we are excited to continue our journey, exploring new territories and uncovering new insights in the ever-evolving world of air transportation.</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>